<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PersonaSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('persona')->insert([

            [
                'cod_per' => 'PER_0001',
                'nom_per' => 'Victor',
                'ape_pat_per' => 'Asturizaga',
                'ape_mat_per' => 'Plata',
                'ci_per' => '13381086',
                'com_per' => null,
                'exp_per' => 'LP',
                'fec_nac_per' => '2006-06-11',
                'gen_per' => 'M',
                'tel_per' => '75836807',
                'ema_per' => 'asturizagavictor@gmail.com',
                'dir_per' => 'Zona Bajo Tejar, La Paz',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0002',
                'nom_per' => 'María Fernanda',
                'ape_pat_per' => 'Choque',
                'ape_mat_per' => 'Condori',
                'ci_per' => '7458123',
                'com_per' => null,
                'exp_per' => 'LP',
                'fec_nac_per' => '2006-07-25',
                'gen_per' => 'F',
                'tel_per' => '76543210',
                'ema_per' => 'maria.choque@gmail.com',
                'dir_per' => 'Zona El Alto, Distrito 3',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0003',
                'nom_per' => 'Luis Fernando',
                'ape_pat_per' => 'Rojas',
                'ape_mat_per' => 'Gutierrez',
                'ci_per' => '5987412',
                'com_per' => null,
                'exp_per' => 'LP',
                'fec_nac_per' => '1985-11-08',
                'gen_per' => 'M',
                'tel_per' => '70123456',
                'ema_per' => 'luis.rojas@gmail.com',
                'dir_per' => 'Zona Sopocachi, La Paz',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0004',
                'nom_per' => 'Ana Lucía',
                'ape_pat_per' => 'Vargas',
                'ape_mat_per' => 'Torrez',
                'ci_per' => '6321457',
                'com_per' => null,
                'exp_per' => 'LP',
                'fec_nac_per' => '1990-05-19',
                'gen_per' => 'F',
                'tel_per' => '78965412',
                'ema_per' => 'ana.vargas@gmail.com',
                'dir_per' => 'Zona Miraflores, La Paz',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0005',
                'nom_per' => 'Jorge Andrés',
                'ape_pat_per' => 'Flores',
                'ape_mat_per' => 'Mendoza',
                'ci_per' => '6123789',
                'com_per' => null,
                'exp_per' => 'LP',
                'fec_nac_per' => '1978-09-03',
                'gen_per' => 'M',
                'tel_per' => '73456789',
                'ema_per' => 'jorge.flores@gmail.com',
                'dir_per' => 'Zona Achumani, La Paz',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0006',
                'nom_per' => 'Edgar',
                'ape_pat_per' => 'Rios',
                'ape_mat_per' => 'Chuquimia',
                'ci_per' => '6798859',
                'com_per' => null,
                'exp_per' => 'LP',
                'fec_nac_per' => '1978-09-03',
                'gen_per' => 'M',
                'tel_per' => '73456789',
                'ema_per' => 'edgar.rios@gmail.com',
                'dir_per' => 'Zona Achumani, La Paz',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0007',
                'nom_per' => 'Diego Alejandro',
                'ape_pat_per' => 'Huanca',
                'ape_mat_per' => 'Mendoza',
                'ci_per' => '7021458',
                'com_per' => null,
                'exp_per' => 'LP',
                'fec_nac_per' => '2008-04-15',
                'gen_per' => 'M',
                'tel_per' => '72145678',
                'ema_per' => 'diego.huanca@gmail.com',
                'dir_per' => 'Zona Villa Adela, El Alto',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0008',
                'nom_per' => 'Lucía Fernanda',
                'ape_pat_per' => 'Quispe',
                'ape_mat_per' => 'Choque',
                'ci_per' => '7156324',
                'com_per' => '1A',
                'exp_per' => 'LP',
                'fec_nac_per' => '2009-08-21',
                'gen_per' => 'F',
                'tel_per' => '73219845',
                'ema_per' => 'lucia.quispe@gmail.com',
                'dir_per' => 'Ciudad Satélite, El Alto',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0009',
                'nom_per' => 'Kevin Andrés',
                'ape_pat_per' => 'Callisaya',
                'ape_mat_per' => 'Rojas',
                'ci_per' => '7245631',
                'com_per' => null,
                'exp_per' => 'LP',
                'fec_nac_per' => '2007-11-02',
                'gen_per' => 'M',
                'tel_per' => '74125698',
                'ema_per' => 'kevin.callisaya@gmail.com',
                'dir_per' => 'Villa Fátima, La Paz',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0010',
                'nom_per' => 'Valeria Sofía',
                'ape_pat_per' => 'Mamani',
                'ape_mat_per' => 'Flores',
                'ci_per' => '7365412',
                'com_per' => '2B',
                'exp_per' => 'LP',
                'fec_nac_per' => '2010-01-30',
                'gen_per' => 'F',
                'tel_per' => '75632147',
                'ema_per' => 'valeria.mamani@gmail.com',
                'dir_per' => 'Miraflores, La Paz',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0011',
                'nom_per' => 'José Luis',
                'ape_pat_per' => 'Condori',
                'ape_mat_per' => 'Quispe',
                'ci_per' => '7489123',
                'com_per' => null,
                'exp_per' => 'LP',
                'fec_nac_per' => '2008-06-10',
                'gen_per' => 'M',
                'tel_per' => '76521478',
                'ema_per' => 'jose.condori@gmail.com',
                'dir_per' => 'Alto Lima, El Alto',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0012',
                'nom_per' => 'Camila Andrea',
                'ape_pat_per' => 'Vargas',
                'ape_mat_per' => 'Lopez',
                'ci_per' => '7598741',
                'com_per' => '1C',
                'exp_per' => 'LP',
                'fec_nac_per' => '2009-03-18',
                'gen_per' => 'F',
                'tel_per' => '71234598',
                'ema_per' => 'camila.vargas@gmail.com',
                'dir_per' => 'Achumani, La Paz',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0013',
                'nom_per' => 'Fernando David',
                'ape_pat_per' => 'Rojas',
                'ape_mat_per' => 'Mamani',
                'ci_per' => '7612345',
                'com_per' => null,
                'exp_per' => 'LP',
                'fec_nac_per' => '2007-09-27',
                'gen_per' => 'M',
                'tel_per' => '78965432',
                'ema_per' => 'fernando.rojas@gmail.com',
                'dir_per' => 'Villa Bolívar, El Alto',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0014',
                'nom_per' => 'Daniela Paola',
                'ape_pat_per' => 'Choque',
                'ape_mat_per' => 'Gutierrez',
                'ci_per' => '7721456',
                'com_per' => '3A',
                'exp_per' => 'LP',
                'fec_nac_per' => '2010-12-05',
                'gen_per' => 'F',
                'tel_per' => '73412569',
                'ema_per' => 'daniela.choque@gmail.com',
                'dir_per' => 'San Pedro, La Paz',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0015',
                'nom_per' => 'Miguel Ángel',
                'ape_pat_per' => 'Flores',
                'ape_mat_per' => 'Condori',
                'ci_per' => '7832145',
                'com_per' => null,
                'exp_per' => 'LP',
                'fec_nac_per' => '2008-02-14',
                'gen_per' => 'M',
                'tel_per' => '72198745',
                'ema_per' => 'miguel.flores@gmail.com',
                'dir_per' => 'Sopocachi, La Paz',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0016',
                'nom_per' => 'Paola Jimena',
                'ape_pat_per' => 'Lopez',
                'ape_mat_per' => 'Quispe',
                'ci_per' => '7945612',
                'com_per' => '2A',
                'exp_per' => 'LP',
                'fec_nac_per' => '2009-07-09',
                'gen_per' => 'F',
                'tel_per' => '76549812',
                'ema_per' => 'paola.lopez@gmail.com',
                'dir_per' => 'Villa Copacabana, La Paz',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0017',
                'nom_per' => 'Luis Eduardo',
                'ape_pat_per' => 'Mamani',
                'ape_mat_per' => 'Rojas',
                'ci_per' => '8054123',
                'com_per' => null,
                'exp_per' => 'LP',
                'fec_nac_per' => '2007-05-11',
                'gen_per' => 'M',
                'tel_per' => '71236985',
                'ema_per' => 'luis.mamani@gmail.com',
                'dir_per' => 'El Tejar, La Paz',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0018',
                'nom_per' => 'Gabriela Nicole',
                'ape_pat_per' => 'Condori',
                'ape_mat_per' => 'Flores',
                'ci_per' => '8165234',
                'com_per' => '1B',
                'exp_per' => 'LP',
                'fec_nac_per' => '2010-10-22',
                'gen_per' => 'F',
                'tel_per' => '74325698',
                'ema_per' => 'gabriela.condori@gmail.com',
                'dir_per' => 'Villa Esperanza, El Alto',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0019',
                'nom_per' => 'Andrés Felipe',
                'ape_pat_per' => 'Quispe',
                'ape_mat_per' => 'Lopez',
                'ci_per' => '8276541',
                'com_per' => null,
                'exp_per' => 'LP',
                'fec_nac_per' => '2008-01-05',
                'gen_per' => 'M',
                'tel_per' => '75412369',
                'ema_per' => 'andres.quispe@gmail.com',
                'dir_per' => 'Alto Obrajes, La Paz',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0020',
                'nom_per' => 'Natalia Belén',
                'ape_pat_per' => 'Flores',
                'ape_mat_per' => 'Mamani',
                'ci_per' => '8387452',
                'com_per' => '2C',
                'exp_per' => 'LP',
                'fec_nac_per' => '2009-06-16',
                'gen_per' => 'F',
                'tel_per' => '72145896',
                'ema_per' => 'natalia.flores@gmail.com',
                'dir_per' => 'Munaypata, La Paz',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'cod_per' => 'PER_0021',
                'nom_per' => 'Cristian Daniel',
                'ape_pat_per' => 'Rojas',
                'ape_mat_per' => 'Condori',
                'ci_per' => '8496123',
                'com_per' => null,
                'exp_per' => 'LP',
                'fec_nac_per' => '2007-12-28',
                'gen_per' => 'M',
                'tel_per' => '73658941',
                'ema_per' => 'cristian.rojas@gmail.com',
                'dir_per' => 'Villa Dolores, El Alto',
                'fot_per' => null,
                'est_per' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

        ]);
    }
}