@props(['modelo', 'identificador', 'nombre' => 'fecha', 'etiqueta' => 'Fecha', 'minimo', 'maximo', 'inicio' => null, 'requerido' => false, 'validacionLocal' => false])
<div class="ui-fecha" wire:key="fecha-{{ $identificador }}-{{ $minimo }}-{{ $maximo }}" x-data="calendarioInstitucional($wire.entangle('{{ $modelo }}').live, @js($maximo), @js($minimo), @js($inicio ?? $maximo))" x-on:keydown.escape="if(abierto){ $event.stopPropagation(); abierto=false; }">
    <label class="ui-label" for="{{ $identificador }}">{{ $etiqueta }}{{ $requerido ? " *" : "" }}</label>
    <div class="ui-fecha-entrada mt-2">
        <input id="{{ $identificador }}" x-ref="fecha" name="{{ $nombre }}" class="ui-input w-full" type="date" x-model="fecha" min="{{ $minimo }}" max="{{ $maximo }}" @required($requerido) @if($validacionLocal) :aria-invalid="!!(tocado['{{ $identificador }}'] && errores['{{ $identificador }}'])" @endif aria-describedby="{{ $identificador }}-ayuda" />
        <button type="button" class="ui-calendario-accion" aria-label="Abrir calendario: {{ $etiqueta }}" :aria-expanded="abierto" aria-controls="{{ $identificador }}-calendario" x-on:click="abrir()"><i class="ph-duotone ph-calendar-dots" aria-hidden="true"></i></button>
    </div>
    <p id="{{ $identificador }}-ayuda" class="ui-muted mt-2 text-xs" x-text="fechaVisible ? 'Fecha seleccionada: '+fechaVisible : 'Elige día, mes y año; también puedes escribir la fecha.'"></p>
    @if($validacionLocal)<p x-show="tocado['{{ $identificador }}'] && errores['{{ $identificador }}']" x-cloak x-text="errores['{{ $identificador }}']" class="ui-error mt-2"></p>@endif<x-input-error :for="$modelo" />
    <div id="{{ $identificador }}-calendario" x-show="abierto" x-cloak x-transition.opacity.duration.150ms x-on:click.outside="abierto=false" class="ui-calendario" role="dialog" aria-label="{{ $etiqueta }}">
        <div class="ui-calendario-titulo"><strong class="ui-title text-sm">{{ $etiqueta }}</strong><button type="button" class="ui-calendario-accion" aria-label="Cerrar calendario" x-on:click="abierto=false; $refs.fecha.focus()"><i class="ph-duotone ph-x" aria-hidden="true"></i></button></div>
        <div class="ui-calendario-selectores"><div x-ref="mes"><x-selector-institucional enlace="mes" :numerico="true" :identificador="$identificador.'-mes'" etiqueta="Mes" :opciones="collect(['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'])->map(fn($etiqueta,$valor)=>['valor'=>$valor,'etiqueta'=>$etiqueta])->all()" /></div><x-selector-institucional enlace="anio" :numerico="true" :identificador="$identificador.'-anio'" etiqueta="Año" :opciones="collect(range((int) substr($maximo,0,4),(int) substr($minimo,0,4)))->map(fn($valor)=>['valor'=>$valor,'etiqueta'=>(string)$valor])->all()" /></div>
        <div class="ui-calendario-navegacion"><button type="button" class="ui-calendario-accion" aria-label="Mes anterior" :disabled="!puedeMover(-1)" x-on:click="mover(-1)"><i class="ph-duotone ph-caret-left" aria-hidden="true"></i></button><span class="ui-muted text-xs" x-text="meses[mes]+' '+anio" aria-live="polite"></span><button type="button" class="ui-calendario-accion" aria-label="Mes siguiente" :disabled="!puedeMover(1)" x-on:click="mover(1)"><i class="ph-duotone ph-caret-right" aria-hidden="true"></i></button></div>
        <div class="ui-calendario-semana" aria-hidden="true">@foreach(['Lu','Ma','Mi','Ju','Vi','Sá','Do'] as $dia)<span>{{ $dia }}</span>@endforeach</div>
        <div class="ui-calendario-dias" x-ref="dias"><template x-for="(dia, indice) in dias" :key="anio+'-'+mes+'-'+indice"><div><template x-if="dia"><button type="button" :data-fecha="dia.fecha" :aria-label="dia.nombre" :aria-pressed="fecha === dia.fecha" :disabled="dia.bloqueado" :class="fecha === dia.fecha ? 'ui-dia-seleccionado' : ''" x-on:click="elegir(dia.fecha)" x-on:keydown="moverFoco($event, dia.fecha)" x-text="dia.numero"></button></template></div></template></div>
        <p class="ui-muted text-xs mt-3">Selecciona primero el año y el mes. Las fechas fuera del rango permitido no están disponibles.</p>
    </div>
</div>
