@props(['anio', 'periodos'=>[], 'eventos'=>[], 'prepararCaso'=>false])
<section class="pa-calendario" x-data="calendarioAcademico(@js($anio), @js($periodos), @js($eventos), @js(today()->toDateString()))" wire:key="calendario-academico-{{ $anio }}-{{ md5(json_encode([$periodos,$eventos])) }}" aria-label="Calendario de trimestres {{ $anio }}">
    <div class="pa-cal-toolbar"><button type="button" class="ui-btn ui-btn-secondary" :disabled="mes===0" x-on:click="mover(-1)" aria-label="Mes anterior"><i class="ph-duotone ph-caret-left" aria-hidden="true"></i></button><strong class="ui-title" x-text="meses[mes]+' '+anio" aria-live="polite"></strong><button type="button" class="ui-btn ui-btn-secondary" :disabled="mes===11" x-on:click="mover(1)" aria-label="Mes siguiente"><i class="ph-duotone ph-caret-right" aria-hidden="true"></i></button></div>
    <div class="pa-meses" aria-label="Mes de consulta"><template x-for="(nombre, indice) in meses" :key="indice"><button type="button" x-text="nombre.slice(0,3)" :aria-label="nombre" :aria-pressed="mes===indice" x-on:click="mes=indice;elegida=''"></button></template></div>
    <div class="pa-dias pa-semana" aria-hidden="true">@foreach(['Lu','Ma','Mi','Ju','Vi','Sá','Do'] as $dia)<span>{{ $dia }}</span>@endforeach</div>
    <div class="pa-dias" x-ref="dias"><template x-for="(dia, indice) in dias" :key="mes+'-'+indice"><div><template x-if="dia"><button type="button" :data-fecha="dia.fecha" :data-tono="tono(dia.fecha)" :aria-label="descripcion(dia.fecha)" :title="descripcion(dia.fecha)" :aria-pressed="elegida===dia.fecha" :aria-current="dia.fecha===hoy?'date':null" x-on:click="elegida=dia.fecha" x-on:keydown="teclado($event,dia.fecha)"><span x-text="dia.numero"></span><small x-show="eventosDia(dia.fecha).length" x-text="eventosDia(dia.fecha).length" aria-hidden="true"></small></button></template></div></template></div>
    <div class="pa-leyenda">@foreach($periodos as $p)<span data-tono="{{ $p['orden'] }}"><i aria-hidden="true"></i>{{ $p['nombre'] }}</span>@endforeach<span data-tono="fuera"><i aria-hidden="true"></i>Sin trimestre</span><span class="ga-texto-danger" x-show="dias.some(d=>d && tono(d.fecha)==='solapado')" x-cloak>Fechas superpuestas por revisar</span></div>
    <div class="pa-dia-detalle" x-show="elegida" x-cloak x-transition.opacity aria-live="polite"><strong class="ui-title" x-text="elegida.split('-').reverse().join('/')"></strong><p class="ui-muted text-xs" x-text="trimestres(elegida).map(p=>p.nombre).join(' · ') || 'Sin trimestre registrado para este día.'"></p><template x-for="evento in eventosDia(elegida)" :key="evento.id"><div class="pa-dia-evento"><strong x-text="evento.nombre"></strong><span x-text="evento.estado.replaceAll('_',' ')+' · '+evento.efecto.replaceAll('_',' ')"></span></div></template><p class="ui-muted text-xs" x-show="eventosDia(elegida).length===0">No hay eventos registrados en esta fecha.</p></div>
    @if($prepararCaso)<button type="button" class="ui-btn ui-btn-primary mt-3" x-show="elegida" x-cloak x-on:click="$wire.usarFechaImpacto(elegida)"><i class="ph-duotone ph-calendar-plus" aria-hidden="true"></i>Preparar un caso para este día</button>@endif
    <p class="ui-muted text-xs mt-3">Selecciona un día para ver su trimestre y sus eventos. Los colores representan rangos de fechas, no días efectivos de clase.</p>
</section>
