@props(['datos'=>[], 'anio'=>null])
@php
    $serie=collect($datos)->sortBy('anio')->values();
    $indicadores=['inscripciones'=>'Inscripciones','planes'=>'Planes de asignatura','planes_tecnicos'=>'Planes técnicos','docentes'=>'Docentes en planes','grupos'=>'Grupos académicos','horarios'=>'Horarios','eventos'=>'Eventos del calendario'];
    $gradiente='trayectoria-'.md5(json_encode([$datos,$anio]));
@endphp
<section class="pa-comparativa pa-trayectoria-viva" x-data="comparativaAcademica(@js($serie),@js((string)$anio))" wire:key="comparativa-academica-{{ $anio }}">
    <nav class="pa-vistas-comparativa" aria-label="Vista de la comparación"><button type="button" :aria-pressed="vista==='linea'" x-on:click="vista='linea'"><i class="ph-duotone ph-chart-line-up" aria-hidden="true"></i>Línea de tiempo</button><button type="button" :aria-pressed="vista==='radial'" x-on:click="vista='radial'"><i class="ph-duotone ph-hexagon" aria-hidden="true"></i>Perfil de gestiones</button><button type="button" :aria-pressed="vista==='resumen'" x-on:click="vista='resumen'"><i class="ph-duotone ph-arrows-left-right" aria-hidden="true"></i>Cambios por indicador</button></nav>
    <x-plegable-institucional class="mb-4" etiqueta="Personalizar gestiones e indicadores" descripcion="Elige los años y los datos que quieres contrastar." icono="ph-sliders-horizontal">
        <x-slot:contador><span x-text="pareja.length+' elegidas'"></span></x-slot:contador>
        <div class="mt-3"><x-selector-institucional enlace="gestionesElegidas" identificador="comparativa-gestiones-{{ $gradiente }}" etiqueta="Gestiones a comparar" :multiple="true" :opciones="$serie->map(fn($d)=>['valor'=>(string)$d['anio'],'etiqueta'=>'Gestión '.$d['anio']])->all()" /></div>
        <p class="ui-error text-xs mt-2" x-show="!parejaValida" x-cloak>Elige al menos dos gestiones diferentes.</p>
        <div class="pa-ejes-opciones mt-3" x-show="vista!=='linea'"><p class="ui-muted text-xs">Indicadores del perfil: elige al menos tres.</p>@foreach($indicadores as $clave=>$nombre)<button type="button" :aria-pressed="ejes.includes(@js($clave))" x-on:click="alternarEje(@js($clave))">{{ $nombre }}</button>@endforeach</div>
        <div class="pa-escalas mt-3" x-show="vista==='linea'" role="group" aria-label="Años de la línea"><button type="button" :aria-pressed="modo==='todas'" x-on:click="modo='todas'">Todas las gestiones</button><button type="button" :aria-pressed="modo==='elegidas'" x-on:click="modo='elegidas'">Gestiones elegidas</button></div>
    </x-plegable-institucional>
    <div x-show="vista==='linea'" x-transition.opacity.duration.180ms>
    <div class="pa-comparativa-controles"><div class="pa-indicadores" role="group" aria-label="Indicador de comparación">@foreach($indicadores as $clave=>$nombre)<button type="button" class="ui-btn ui-btn-secondary" :aria-pressed="indicador===@js($clave)" x-on:click="indicador=@js($clave)">{{ $nombre }}</button>@endforeach</div><div class="pa-escalas" role="group" aria-label="Escala de la línea"><button type="button" :aria-pressed="escala==='detalle'" x-on:click="escala='detalle'">Ver variaciones</button><button type="button" :aria-pressed="escala==='general'" x-on:click="escala='general'">Desde cero</button></div></div>
    @if($serie->isNotEmpty())
        <div class="pa-trayectoria-cabecera" aria-live="polite"><div><p class="ui-kicker" x-text="'Gestión '+seleccion"></p><strong class="pa-trayectoria-valor" x-text="valorActual===null?'Sin dato':numero(valorActual)"></strong><span class="ui-muted text-sm" x-text="nombres[indicador]"></span></div><div class="pa-trayectoria-variacion"><span class="pa-trayectoria-flecha"><i class="ph-duotone" :class="variacion===null?'ph-minus':variacion>0?'ph-trend-up':variacion<0?'ph-trend-down':'ph-arrows-left-right'" aria-hidden="true"></i></span><div><strong x-text="variacion===null?'Sin año anterior':(variacion>0?'+':'')+numero(variacion)"></strong><p class="ui-muted text-xs" x-text="anterior?'respecto a '+anterior.anio:'Primer año disponible'"></p><small class="ui-muted" x-text="porcentaje===null?'':(porcentaje>0?'+':'')+porcentaje.toFixed(1)+' %'"></small></div></div><span class="ui-badge-info" x-text="actual?.estado || 'Por revisar'"></span></div>
        <div class="pa-comparativa-grafico" tabindex="0" aria-label="Línea de tiempo interactiva por gestión; puedes desplazarla en pantallas pequeñas">
            <svg class="pa-comparativa-svg" viewBox="0 0 800 265" role="group" aria-label="Evolución por año; selecciona un punto para consultar sus datos">
                <defs><linearGradient id="{{ $gradiente }}" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" class="pa-area-inicio" /><stop offset="100%" class="pa-area-final" /></linearGradient></defs>
                @for($i=0;$i<3;$i++)<g x-show="niveles[{{ $i }}]"><line x1="65" :y1="niveles[{{ $i }}]?.y" x2="750" :y2="niveles[{{ $i }}]?.y" class="ga-grafico-rejilla" /><text x="53" :y="niveles[{{ $i }}]?.y+4" text-anchor="end" class="ga-grafico-texto" x-text="numero(niveles[{{ $i }}]?.valor)"></text></g>@endfor
                @for($i=0;$i<$serie->count();$i++)<g x-show="segmentos[{{ $i }}]"><path :d="segmentos[{{ $i }}]?.area" fill="url(#{{ $gradiente }})" class="pa-trayectoria-area" /><path :d="segmentos[{{ $i }}]?.linea" class="ga-grafico-linea pa-trayectoria-linea" pathLength="1" /></g>@endfor
                <line x-show="puntoActual" :x1="puntoActual?.x || 0" :x2="puntoActual?.x || 0" y1="25" y2="218" class="pa-trayectoria-guia" />
                @for($i=0;$i<$serie->count();$i++)<g x-show="puntos[{{ $i }}]" role="button" :tabindex="seleccion===String(puntos[{{ $i }}]?.anio)?0:-1" :aria-label="'Consultar '+puntos[{{ $i }}]?.anio+': '+numero(puntos[{{ $i }}]?.valor || 0)+' '+nombres[indicador]" :aria-pressed="seleccion===String(puntos[{{ $i }}]?.anio)" x-on:click="seleccion=String(puntos[{{ $i }}]?.anio)" x-on:keydown.enter.prevent="seleccion=String(puntos[{{ $i }}]?.anio)" x-on:keydown.space.prevent="seleccion=String(puntos[{{ $i }}]?.anio)" x-on:keydown.arrow-left.prevent="mover(-1)" x-on:keydown.arrow-right.prevent="mover(1)" class="pa-trayectoria-punto"><circle :cx="puntos[{{ $i }}]?.x" :cy="puntos[{{ $i }}]?.y" r="20" class="pa-punto-zona" /><circle :cx="puntos[{{ $i }}]?.x" :cy="puntos[{{ $i }}]?.y" :r="seleccion===String(puntos[{{ $i }}]?.anio)?11:6" class="ga-grafico-punto" /><text :x="puntos[{{ $i }}]?.x" :y="(puntos[{{ $i }}]?.y || 0)-24" text-anchor="middle" class="ga-grafico-texto" x-text="numero(puntos[{{ $i }}]?.valor)"></text><text :x="puntos[{{ $i }}]?.x" y="251" text-anchor="middle" class="ga-grafico-texto" x-text="puntos[{{ $i }}]?.anio"></text></g>@endfor
            </svg>
        </div>
        <div class="pa-anios" role="group" aria-label="Consultar una gestión en el gráfico"><button type="button" class="pa-anio-anterior" aria-label="Gestión anterior en la línea" :disabled="indiceActual<=0" x-on:click="mover(-1)"><i class="ph-duotone ph-caret-left" aria-hidden="true"></i></button>@foreach($serie as $dato)<button type="button" x-show="modo==='todas' || gestionesElegidas.includes(@js((string)$dato['anio']))" :aria-pressed="seleccion===@js((string)$dato['anio'])" x-on:click="seleccion=@js((string)$dato['anio'])">{{ $dato['anio'] }}</button>@endforeach<button type="button" class="pa-anio-siguiente" aria-label="Gestión siguiente en la línea" :disabled="indiceActual>=datosVisibles.length-1" x-on:click="mover(1)"><i class="ph-duotone ph-caret-right" aria-hidden="true"></i></button></div>
        <p class="ui-muted text-xs pa-escala-nota" x-text="'Escala '+numero(limites.min)+'–'+numero(limites.max)+(escala==='detalle'?' para observar variaciones. Cambia a Desde cero para ver la magnitud completa.':'. Se conservan los valores reales.')"></p>
        <x-plegable-institucional class="pa-tabla-detalle" icono="ph-chart-bar"><x-slot:titulo>Consultar todos los valores</x-slot:titulo><div class="ga-tabla-contenedor"><table class="ga-tabla"><caption class="sr-only">Conteos reales por gestión</caption><thead><tr><th>Gestión</th><th>Inscripciones</th><th>Planes</th><th>Eventos</th></tr></thead><tbody>@foreach($serie as $d)<tr><th scope="row">{{ $d['anio'] }}</th><td>{{ $d['inscripciones']??'No disponible' }}</td><td>{{ $d['planes']??'No disponible' }}</td><td>{{ $d['eventos']??'No disponible' }}</td></tr>@endforeach</tbody></table></div></x-plegable-institucional>
    @else<p class="ui-muted text-sm">Aún no hay gestiones para comparar.</p>@endif
    </div>
    <div x-show="vista!=='linea' && parejaValida" x-cloak class="pa-perfil-distribucion" :class="{'pa-perfil-solo-datos':vista==='resumen'}">
        <section x-show="vista==='radial'" x-transition.opacity.duration.180ms class="pa-comparativa-radial" aria-label="Perfil de las gestiones elegidas">
            <div class="pa-radial-leyenda"><template x-for="(dato,i) in pareja" :key="dato.anio"><button type="button" :class="claseSerie(i)" @mouseenter="resaltada=String(dato.anio)" @mouseleave="resaltada=''" @focus="resaltada=String(dato.anio)" @blur="resaltada=''" :aria-label="'Resaltar gestión '+dato.anio"><i aria-hidden="true"></i><strong x-text="dato.anio"></strong></button></template></div>
            <svg viewBox="0 0 600 450" role="img" aria-label="Perfil de gestiones: proporción del máximo histórico por indicador">
                @foreach([1,.75,.5,.25] as $nivel)<polygon :points="poligono(143*{{ $nivel }})" class="pa-radial-rejilla" />@endforeach
                @for($i=0;$i<count($indicadores);$i++)<g x-show="ejesRadiales[{{ $i }}]"><line x1="300" y1="223" :x2="ejesRadiales[{{ $i }}]?.fin.x" :y2="ejesRadiales[{{ $i }}]?.fin.y" class="ga-grafico-rejilla" /><text :x="ejesRadiales[{{ $i }}]?.x" :y="ejesRadiales[{{ $i }}]?.y" text-anchor="middle" class="pa-radial-texto" x-text="ejesRadiales[{{ $i }}]?.nombre"></text></g>@endfor
                @for($i=0;$i<$serie->count();$i++)<polygon x-show="radiales[{{ $i }}]?.completa" :points="radiales[{{ $i }}]?.puntos || ''" class="pa-radial-poligono" :class="claseSerie({{ $i }})" :style="{opacity:!resaltada || resaltada===String(radiales[{{ $i }}]?.anio)?1:.15}" />@endfor
            </svg>
            <p class="ui-muted text-xs">Cada eje usa su máximo histórico. Un perfil sin datos completos no se dibuja; consulta sus valores a la derecha.</p>
        </section>
        <section class="pa-perfil-valores"><h3 class="ui-title font-semibold text-sm">Cantidades por gestión</h3><p class="ui-muted text-xs mt-1">La variación toma como referencia la primera gestión elegida.</p>
            <div class="ga-tabla-contenedor mt-3" tabindex="0" aria-label="Comparación de valores por gestión"><table class="ga-tabla pa-perfil-tabla"><caption class="sr-only">Comparación entre las gestiones seleccionadas</caption><thead><tr><th>Indicador</th><template x-for="(dato,i) in pareja" :key="dato.anio"><th :class="claseSerie(i)" x-text="dato.anio"></th></template></tr></thead><tbody><template x-for="clave in ejes" :key="clave"><tr><th scope="row" x-text="nombres[clave]"></th><template x-for="dato in pareja" :key="dato.anio"><td><strong x-text="valor(dato,clave)===null?'Sin dato':numero(valor(dato,clave))"></strong><small x-show="dato.anio!==pareja[0]?.anio" x-text="cambioDesdeBase(dato,clave)"></small></td></template></tr></template></tbody></table></div>
        </section>
    </div>
    <p class="ui-muted text-xs mt-3">Registros de cada gestión. El año en curso puede estar incompleto; estas variaciones no representan rendimiento académico.</p>
</section>
