@props(['modelo'=>null,'enlace'=>null,'numerico'=>false,'identificador','etiqueta','opciones'=>[], 'deshabilitado'=>false, 'requerido'=>false,'multiple'=>false])
<div class="ui-selector" x-data="selectorInstitucional({{ $modelo ? '$wire.entangle('.\Illuminate\Support\Js::from($modelo).').live' : 'null' }}, @js($opciones), @js($identificador), @js($numerico), @js($multiple))" x-modelable="valor" @if($enlace) x-model{{ $numerico ? '.number' : '' }}="{{ $enlace }}" @endif x-on:keydown="teclado($event)" wire:key="selector-{{ $identificador }}-{{ md5(json_encode($opciones)) }}">
    <label id="{{ $identificador }}-etiqueta" for="{{ $identificador }}" class="ui-label">{{ $etiqueta }}{{ $requerido ? ' *' : '' }}</label>
    <button id="{{ $identificador }}" x-ref="control" type="button" class="ui-selector-control ui-input mt-2" role="combobox" aria-haspopup="listbox" aria-controls="{{ $identificador }}-lista" aria-labelledby="{{ $identificador }}-etiqueta" :aria-expanded="abierto" :aria-activedescendant="abierto && filtradas.length ? identificador+'-opcion-'+indice : null" x-on:click="abrir()" @disabled($deshabilitado)><span x-text="seleccionada"></span><i class="ph-duotone ph-caret-down" :class="{'ui-selector-flecha-abierta':abierto}" aria-hidden="true"></i></button>
    <div x-ref="panel" popover="manual" x-show="abierto" x-cloak :style="posicion" class="ui-selector-panel" x-on:click.outside="if(!$refs.control.contains($event.target)) cerrar()" x-transition.opacity.duration.140ms>
        <div class="ui-selector-buscar"><i class="ph-duotone ph-magnifying-glass" aria-hidden="true"></i><input type="search" x-model="busqueda" x-on:input="indice=0" aria-label="Buscar opción: {{ $etiqueta }}" placeholder="Buscar opción…" autocomplete="off" /></div>
        <div id="{{ $identificador }}-lista" role="listbox" @if($multiple) aria-multiselectable="true" @endif aria-labelledby="{{ $identificador }}-etiqueta" class="ui-selector-lista"><template x-for="(opcion,i) in filtradas" :key="String(opcion.valor)"><button type="button" role="option" :id="identificador+'-opcion-'+i" :data-indice="i" :aria-selected="estaElegida(opcion)" :disabled="!!opcion.deshabilitada" :class="{'ui-selector-opcion-activa':indice===i}" x-on:mouseenter="indice=i" x-on:click="elegir(opcion)"><span x-text="opcion.etiqueta"></span><i class="ph-duotone ph-check" x-show="estaElegida(opcion)" aria-hidden="true"></i></button></template><p class="ui-muted p-3 text-sm" x-show="!filtradas.length">No hay opciones con esa búsqueda.</p></div>
    </div>
    @if($multiple)<div class="ui-seleccion-multiple" x-show="elegidas.length"><template x-for="opcion in elegidas" :key="String(opcion.valor)"><button type="button" class="ui-badge-info" :aria-label="'Quitar '+opcion.etiqueta" x-on:click="elegir(opcion)"><span x-text="opcion.etiqueta"></span><i class="ph-duotone ph-x" aria-hidden="true"></i></button></template></div>@endif
    @if($modelo)<x-input-error :for="$modelo" />@endif
</div>
