<div class="regencia-pagina space-y-5" x-data="{...paginacionInstitucional(),vista:'tarjetas',grafico:'estudiantes'}">
    @include('livewire.admin.regencia.estilos')
    @php
        $nombre = fn($p)=>trim(($p?->nom_per??'').' '.($p?->ape_pat_per??'').' '.($p?->ape_mat_per??''));
        $opRegentes=$regents->map(fn($r)=>['valor'=>$r->cod_vpe,'etiqueta'=>$nombre($r->personalInstitucional?->persona)])->all();
        $opYears=$years->map(fn($r)=>['valor'=>$r->cod_gea,'etiqueta'=>'Gestión '.$r->ani_gea])->all();
        $opCourses=$courses->map(fn($r)=>['valor'=>$r->cod_cur,'etiqueta'=>$r->nom_cur])->all();
    @endphp
    <header class="ui-card regencia-cabecera"><div><p class="ui-kicker">Organización y acompañamiento académico</p><h1 class="ui-title text-2xl font-bold mt-2">Asignaciones de Regencia</h1><p class="ui-muted text-sm mt-2">Regentes, grados, docentes y estudiantes a cargo. Hasta dos grados simultáneos por regente, con historia por gestión.</p></div><button type="button" class="ui-btn ui-btn-primary" wire:click="abrir" wire:loading.attr="disabled" @disabled(!$ready || $regents->isEmpty())><i class="ph-duotone ph-plus" aria-hidden="true"></i>Asignar grados</button></header>
    @if(session('status'))<p class="ui-alert-success" role="status">{{ session('status') }}</p>@endif
    @if(!$ready)<p class="ui-alert-warning" role="status">El esquema de asignaciones no está disponible. La operación permanece bloqueada.</p>@else
    @if($regents->isEmpty())<p class="ui-alert-warning" role="status">Faltan regentes habilitados: se necesitan cuenta con rol Regente, cargo y vínculo institucional activos. No se asignan grados solamente por el nombre.</p>@endif
    <div class="regencia-indicadores">
        @foreach(['regentes'=>'Regentes habilitados','grados'=>'Grados con regencia vigente','docentes'=>'Docentes relacionados hoy','asignaciones'=>'Asignaciones registradas'] as $clave=>$etiqueta)<article class="ui-card"><strong>{{ $metricas[$clave] }}</strong><span>{{ $etiqueta }}</span></article>@endforeach
    </div>
    @include('livewire.admin.regencia.estudiantes')
    <section class="ui-card p-5" aria-label="Distribución de responsabilidades">
        <div class="regencia-herramientas"><div><p class="ui-kicker">Panorama de la gestión consultada</p><h2 class="ui-title font-bold mt-2">Distribución de responsabilidades</h2><p class="ui-muted text-xs mt-2">Vigencia al {{ \Carbon\Carbon::parse($hoy)->format('d/m/Y') }}. Los docentes se cuentan una vez por regente desde planes vigentes, incluyendo especialidades.</p></div><div class="regencia-vistas"><button type="button" class="ui-btn ui-btn-secondary" @click="grafico='estudiantes'" :aria-pressed="grafico==='estudiantes'">Estudiantes</button><button type="button" class="ui-btn ui-btn-secondary" @click="grafico='grados'" :aria-pressed="grafico==='grados'">Grados</button><button type="button" class="ui-btn ui-btn-secondary" @click="grafico='docentes'" :aria-pressed="grafico==='docentes'">Docentes</button><button type="button" class="ui-btn ui-btn-secondary" @click="grafico='conexiones'" :aria-pressed="grafico==='conexiones'">Conexiones</button></div></div>
        <div class="regencia-grafico mt-5" x-show="grafico!=='conexiones'" x-transition.opacity>
            @forelse($panorama as $fila)
                <button type="button" class="regencia-barra" wire:click="$set('regente','{{ $fila['vinculo']->cod_vpe }}')"><span>{{ $nombre($fila['vinculo']->personalInstitucional?->persona) }}</span><strong x-text="grafico==='estudiantes'?{{ $fila['estudiantes'] }}:(grafico==='grados'?{{ $fila['grados']->count() }}:{{ $fila['docentes'] }})"></strong><span class="regencia-pista"><i :style="'transform:scaleX('+(grafico==='estudiantes'?{{ $fila['estudiantes']/max(1,$panorama->max('estudiantes')) }}:(grafico==='grados'?{{ min(1,$fila['grados']->count()/2) }}:{{ $fila['docentes']/max(1,$panorama->max('docentes')) }}))+')'"></i></span><small x-text="grafico==='estudiantes'?'{{ $fila['estudiantes'] }} estudiantes únicos a cargo':(grafico==='grados'?'{{ $fila['grados']->count() }} de 2 grados permitidos':'{{ $fila['docentes'] }} docentes con planes vigentes')"></small></button>
            @empty<div class="regencia-vacio"><i class="ph-duotone ph-tree-structure" aria-hidden="true"></i><strong>No hay regentes habilitados para representar</strong><p>El gráfico se completará con designaciones reales.</p></div>@endforelse
        </div>
        <div class="regencia-conexiones mt-5" x-show="grafico==='conexiones'" x-cloak x-transition.opacity>
            @forelse($panorama as $fila)<article class="ui-card-soft p-4"><h3 class="ui-title font-bold">{{ $nombre($fila['vinculo']->personalInstitucional?->persona) }}</h3><div class="regencia-enlaces mt-3">@forelse($fila['grados'] as $a)<span class="ui-badge-info">{{ $a->curso?->nom_cur }}</span>@empty<span class="ui-badge-warning">Sin grados vigentes</span>@endforelse</div><p class="ui-muted text-sm mt-3">{{ $fila['docentes'] }} docentes relacionados mediante la planificación académica.</p></article>@empty<p class="ui-muted">No hay conexiones institucionales registradas.</p>@endforelse
        </div>
    </section>
    @if($rotacion)
    <x-plegable-institucional etiqueta="Rotación prevista para la siguiente gestión" descripcion="Una designación de Dirección tiene prioridad" icono="ph-arrows-clockwise" :abierto="false"><div class="regencia-conexiones">@foreach($rotacion as $propuesta)<article class="ui-card-soft p-4"><h3 class="ui-title font-bold">{{ $nombre($propuesta['vinculo']?->personalInstitucional?->persona) }}</h3><p class="ui-muted text-sm mt-2">Gestión {{ $propuesta['gestion'] }} · {{ collect($propuesta['cursos'])->pluck('nom_cur')->join(' y ') }}</p></article>@endforeach</div><p class="ui-muted text-xs mt-3">Se aplica al iniciar una gestión activa, únicamente cuando no existe una designación para ese regente. Una asignación retirada también impide volver a asignarla automáticamente.</p></x-plegable-institucional>
    @endif
    <section class="ui-card p-5" aria-label="Filtros de regencia"><div class="regencia-filtros">
        <x-selector-institucional modelo="gestion" identificador="regencia-gestion" etiqueta="Consultar gestión" :opciones="array_merge([['valor'=>'','etiqueta'=>'Todas las gestiones']],$opYears)" />
        <x-selector-institucional modelo="regente" identificador="regencia-regente" etiqueta="Regente" :opciones="array_merge([['valor'=>'','etiqueta'=>'Todos los regentes habilitados']],$opRegentes)" />
        <x-selector-institucional modelo="grado" identificador="regencia-grado" etiqueta="Grado" :opciones="array_merge([['valor'=>'','etiqueta'=>'Todos los grados']],$opCourses)" />
        <x-selector-institucional modelo="estado" identificador="regencia-estado" etiqueta="Situación del intervalo" :opciones="collect([''=>'Todas las situaciones','Vigente'=>'Vigente','Programada'=>'Programada','Finalizada'=>'Finalizada','Retirada'=>'Retirada'])->map(fn($etiqueta,$valor)=>['valor'=>$valor,'etiqueta'=>$etiqueta])->values()->all()" />
    </div><button type="button" class="ui-btn ui-btn-secondary mt-3" wire:click="limpiarFiltros">Limpiar filtros</button></section>
    <section class="ui-card p-5" aria-label="Historial de asignaciones" x-ref="resultados">
        <div class="regencia-herramientas"><div><h2 class="ui-title font-bold">Responsabilidades por gestión</h2><p class="ui-muted text-xs mt-2">{{ $assignments->total() }} resultados. Cada rotación conserva el intervalo anterior.</p></div><div class="regencia-vistas">@foreach(['tarjetas'=>'Tarjetas','lista'=>'Lista','cronologia'=>'Cronología'] as $valor=>$etiqueta)<button type="button" class="ui-btn ui-btn-secondary" @click="vista='{{ $valor }}'" :aria-pressed="vista==='{{ $valor }}'">{{ $etiqueta }}</button>@endforeach</div></div>
        <div class="regencia-registros mt-4" :class="{'regencia-lista':vista==='lista','regencia-cronologia':vista==='cronologia'}">
            @forelse($assignments as $assignment)
                @php($situacion=\App\Livewire\Admin\AsignacionesRegencia::estadoTemporal($assignment,$hoy))
                @php($conteo=$situacion==='Vigente'?($porGrado[$assignment->cod_cur.'|'.$assignment->cod_gea]??null):null)
                <article class="regencia-tarjeta" wire:key="asignacion-{{ $assignment->cod_ras }}"><div class="regencia-herramientas"><h3 class="ui-title font-bold">{{ $nombre($assignment->vinculoPersonal?->personalInstitucional?->persona) }}</h3><span class="{{ $situacion==='Vigente'?'ui-badge-success':'ui-badge-info' }}">{{ $situacion }}</span></div><p class="ui-title mt-3">{{ $assignment->curso?->nom_cur }} · Gestión {{ $assignment->gestion?->ani_gea }}</p><p class="ui-muted text-sm mt-2">{{ $assignment->fii_ras->format('d/m/Y') }} — {{ $assignment->ffi_ras?->format('d/m/Y')??'Sin fin registrado' }}</p><div class="regencia-tarjeta-cifras mt-3">@if($conteo)<span><i class="ph-duotone ph-student" aria-hidden="true"></i><strong>{{ $conteo['estudiantes'] }}</strong> estudiantes a cargo hoy</span><span><strong>{{ $conteo['observados'] }}</strong> con notas de inscripción</span>@else<span class="ui-muted text-xs">Conteo actual disponible solo para responsabilidades vigentes.</span>@endif</div><p class="ui-muted text-sm mt-3">{{ $assignment->obs_ras ?: 'Registro histórico sin motivo documentado.' }}</p>@if($situacion==='Vigente')<button type="button" class="ui-btn ui-btn-secondary mt-4" wire:click="retirar('{{ $assignment->cod_ras }}')" wire:confirm="¿Retirar esta responsabilidad? La historia se conserva." wire:loading.attr="disabled">Retirar asignación</button>@endif</article>
            @empty<div class="regencia-vacio"><i class="ph-duotone ph-clipboard-text" aria-hidden="true"></i><strong>No hay asignaciones para esta consulta</strong><p>Selecciona otra gestión o limpia los filtros. No se muestran asignaciones inventadas.</p></div>@endforelse
        </div>
    </section>
    <x-paginacion-institucional :paginador="$assignments" :elementos="[$assignments->getUrlRange(1,$assignments->lastPage())]" :cantidad="$perPage" entidad="asignaciones" singular="asignación" />
    <x-plegable-institucional etiqueta="Cómo organizar una designación" descripcion="Ejemplos de uso y reglas de prevención" icono="ph-info" :abierto="false"><p class="ui-muted text-sm">Selecciona un regente habilitado, la gestión y un grado. Ejemplo: una responsabilidad sobre 1.º y 2.º se registra como dos asignaciones con fechas y motivo. Dirección puede ordenar una distribución distinta; nunca se sobrescribe la historia.</p><p class="ui-muted text-sm mt-3">La pertenencia docente se calcula desde los planes vigentes del grado. Un docente que imparte en varios grados aparece una sola vez en el total de su regente.</p></x-plegable-institucional>
    @endif
    @if($modal)
    @php($year=$years->firstWhere('cod_gea',$form['cod_gea']))
    <template x-teleport="body"><div class="personas-modal" role="dialog" aria-modal="true" aria-labelledby="regencia-modal-titulo" x-data="{}" x-trap.inert.noscroll="true"><div class="personas-modal-fondo" wire:click="cerrar"></div><section class="personas-modal-panel" style="max-width:58rem"><header class="personas-modal-cabecera"><div><p class="ui-kicker">Designación institucional</p><h2 id="regencia-modal-titulo" class="ui-title text-xl font-bold mt-2">Asignar responsabilidad de un grado</h2></div><button type="button" class="personas-accion" aria-label="Cerrar asignación" wire:click="cerrar"><i class="ph-duotone ph-x" aria-hidden="true"></i></button></header><div class="personas-modal-contenido regencia-formulario">
        <div class="space-y-4">
            <x-selector-institucional modelo="form.cod_vpe" identificador="regencia-form-regente" etiqueta="Regente habilitado" :requerido="true" :opciones="array_merge([['valor'=>'','etiqueta'=>'Elige el regente']],$opRegentes)" />
            <x-selector-institucional modelo="form.cod_gea" identificador="regencia-form-gestion" etiqueta="Gestión activa" :requerido="true" :opciones="array_merge([['valor'=>'','etiqueta'=>'Elige la gestión']],$years->where('est_gea','ACTIVO')->map(fn($r)=>['valor'=>$r->cod_gea,'etiqueta'=>'Gestión '.$r->ani_gea])->all())" />
            <x-selector-institucional modelo="form.cod_cur" identificador="regencia-form-grado" etiqueta="Grado a cargo" :requerido="true" :opciones="array_merge([['valor'=>'','etiqueta'=>'Elige el grado']],$opCourses)" />
            <div class="regencia-fechas"><x-calendario-institucional modelo="form.fii_ras" identificador="regencia-inicio" etiqueta="Inicio" :minimo="$year?->fii_gea?->toDateString()??$hoy" :maximo="$year?->ffi_gea?->toDateString()??$hoy" :requerido="true" /><x-calendario-institucional modelo="form.ffi_ras" identificador="regencia-fin" etiqueta="Fin" :minimo="$year?->fii_gea?->toDateString()??$hoy" :maximo="$year?->ffi_gea?->toDateString()??$hoy" :requerido="true" /></div>
            <div><label class="ui-label" for="regencia-motivo">Motivo y referencia de la designación *</label><textarea id="regencia-motivo" class="ui-textarea mt-2" wire:model.live.debounce.400ms="form.obs_ras" rows="4" maxlength="1000" placeholder="Ej.: Designación de Dirección para acompañar el primer grado durante la gestión; indica la referencia real de la instrucción."></textarea><x-input-error for="form.obs_ras" /></div>
        </div><aside class="ui-card-soft p-5"><p class="ui-kicker">Comprobación antes de guardar</p><h3 class="ui-title font-bold mt-2">Responsabilidad y vigencia</h3><p class="ui-muted text-sm mt-3">La selección asigna un grado y sus paralelos. No cambia especialidades, docentes ni sus planes.</p>@foreach($revision['errores']??[] as $campo=>$mensajes)<p class="ui-alert-warning mt-3">{{ implode(' ',$mensajes) }}</p>@endforeach @foreach($revision['advertencias']??[] as $advertencia)<p class="ui-alert-warning mt-3">{{ $advertencia }}</p>@endforeach @if($revision['puede_guardar']??false)<p class="ui-alert-success mt-3">Datos completos. Las fechas, el vínculo y el límite de grados se comprobarán nuevamente al guardar.</p>@endif<p class="ui-muted text-xs mt-4">Máximo dos grados simultáneos. El motivo y la operación se conservan en bitácora.</p></aside>
    </div><footer class="personas-modal-pie"><button type="button" class="ui-btn ui-btn-secondary" wire:click="cerrar">Cancelar</button><button type="button" class="ui-btn ui-btn-primary" wire:click="guardar" wire:loading.attr="disabled" @disabled(!($revision['puede_guardar']??false))>Guardar asignación</button></footer></section></div></template>
    @endif
</div>

