<div class="ga-pagina" x-data="{seccion:$wire.entangle('seccion').live,...borradorCalendario(@js($claveBorrador),@js($clavePlantillas))}" wire:key="calendario-casos-{{ $selectedGestionId }}" x-on:calendario-borrador-validado.window="guardar($event.detail.caso)">
    @php($formatDate=fn($fecha)=>$fecha?\Carbon\Carbon::parse($fecha)->format('d/m/Y'):'Por confirmar')
    <header class="ui-card ga-cabecera"><div class="ga-identidad"><div class="ga-emblema"><i class="ph-duotone ph-calendar-dots" aria-hidden="true"></i></div><div><p class="ui-kicker">Fechas y continuidad curricular</p><h1 class="ui-title">Calendario institucional</h1><p class="ui-muted">Revisa los feriados, las fuentes y el alcance de cada contingencia antes de decidir.</p></div></div><a class="ui-btn ui-btn-secondary" wire:navigate href="{{ route('admin.gestion-academica',['gestion'=>$selectedGestionId]) }}"><i class="ph-duotone ph-arrow-left" aria-hidden="true"></i>Volver a esta gestión</a></header>
    <section class="ui-card ga-contexto"><div><p class="ui-kicker">Alcance de consulta</p><h2 class="ui-title font-bold mt-1">Gestión {{ $gestionSeleccionada['anio'] ?? 'por seleccionar' }}</h2><p class="ui-muted text-xs mt-1">La consulta y la simulación conservan este expediente anual.</p></div><x-selector-institucional modelo="selectedGestionId" identificador="calendario-contexto" etiqueta="Gestión del calendario" :opciones="$opcionesGestion" /></section>
    <nav class="ui-card ga-cal-nav" aria-label="Vistas del calendario"><button type="button" x-on:click="seccion='agenda'" :aria-pressed="seccion==='agenda'"><i class="ph-duotone ph-calendar-dots" aria-hidden="true"></i>Agenda y fechas</button><button type="button" x-on:click="seccion='referencias'" :aria-pressed="seccion==='referencias'"><i class="ph-duotone ph-books" aria-hidden="true"></i>Referencias y disposiciones</button><button type="button" x-on:click="seccion='impacto'" :aria-pressed="seccion==='impacto'"><i class="ph-duotone ph-intersect" aria-hidden="true"></i>Analista de impacto</button></nav>
    @foreach($avisosSesion as $aviso)<div class="ga-aviso" data-nivel="{{ $aviso['nivel'] }}" role="alert"><div><h3 class="ui-title font-bold">{{ $aviso['titulo'] }}</h3><p>{{ $aviso['mensaje'] }}</p></div></div>@endforeach
    @include('livewire.admin.academica.calendario')

</div>
