@php($r=$detalle['registro'])
<div class="personas-modal" x-data x-trap.inert.noscroll="true" role="dialog" aria-modal="true" aria-labelledby="trayectoria-titulo" wire:click.self="cerrarDetalle" x-on:keydown.escape.window="$wire.cerrarDetalle()">
    <section class="personas-modal-panel docentes-horario-panel">
        <header class="personas-modal-cabecera"><div><p class="ui-kicker">Ficha de seguimiento · {{ $r->ani_gea }}</p><h2 id="trayectoria-titulo" class="font-black mt-2">{{ trim($r->nom_per.' '.$r->ape_pat_per.' '.$r->ape_mat_per) }}</h2><p class="ui-help">{{ $r->nom_cur }} · {{ $r->nom_par }}. Historial académico y estudios registrados.</p></div><button wire:click="cerrarDetalle" class="ui-btn-secondary" aria-label="Cerrar trayectoria"><i class="ph-duotone ph-x" aria-hidden="true"></i></button></header>
        <div class="personas-modal-contenido space-y-5">
            <section><p class="ui-kicker">Trayectoria por gestión y período</p>
                @forelse($detalle['notas']->groupBy(fn($n)=>$n->inscripcionEstudiante?->gestionAcademica?->ani_gea ?? 'Sin gestión') as $year=>$notas)
                <x-plegable-institucional :etiqueta="'Gestión '.$year" :descripcion="$notas->count().' notas vigentes o rectificadas'" icono="ph-chart-line" :abierto="(string)$year===(string)$r->ani_gea">
                    <div class="resultados-periodos">@foreach($notas->groupBy('cod_pev')->sortBy(fn($grupo)=>$grupo->first()->periodoEvaluacion?->ord_pev) as $periodo)<article class="ui-card-soft p-3"><strong class="text-sm">{{ $periodo->first()->periodoEvaluacion?->nom_pev ?? 'Período sin referencia' }}</strong><p class="mt-2 text-xl font-black">{{ number_format($periodo->avg('not_cal'),2) }}/100</p><div class="resultados-pista mt-2"><span class="resultados-barra" style="width:{{ min(100,max(0,$periodo->avg('not_cal'))) }}%"></span></div><p class="ui-help">{{ $periodo->count() }} notas · {{ $periodo->where('not_cal','<=',50)->count() }} de 50 o menos</p></article>@endforeach</div>
                    <?php
                        $grupos=$notas->groupBy('cod_pev')->sortBy(fn($grupo)=>$grupo->first()->periodoEvaluacion?->ord_pev);
                        $inicio=$grupos->first()->toBase()->filter(fn($n)=>$n->cod_pas || $n->cod_pes)->keyBy(fn($n)=>$n->cod_pas ?? $n->cod_pes);
                        $fin=$grupos->last()->toBase()->filter(fn($n)=>$n->cod_pas || $n->cod_pes)->keyBy(fn($n)=>$n->cod_pas ?? $n->cod_pes);
                        $comunes=$inicio->keys()->intersect($fin->keys());
                    ?>
                    @if($grupos->count()>1 && $comunes->isNotEmpty())
                    @php($cambio=$fin->only($comunes->all())->avg('not_cal')-$inicio->only($comunes->all())->avg('not_cal'))
                    <p class="ui-alert-info mt-4"><strong>Variación en las mismas materias: {{ $cambio>0 ? '+' : '' }}{{ number_format($cambio,2) }} puntos.</strong> {{ $grupos->first()->first()->periodoEvaluacion?->nom_pev }} → {{ $grupos->last()->first()->periodoEvaluacion?->nom_pev }} · {{ $comunes->count() }} asignaciones comparables. Es una diferencia observada, no una medida del efecto del aporte.</p>
                    @endif
                    <div class="overflow-x-auto mt-4"><table class="w-full resultados-tabla text-sm"><thead><tr><th>Materia / especialidad</th><th>Período</th><th>Nota / 100</th><th>Observación registrada</th></tr></thead><tbody>@foreach($notas as $n)<tr><td>{{ $n->asignatura?->nom_asi ?? $n->planEspecialidad?->especialidad?->nom_esp ?? 'Sin referencia curricular' }}</td><td>{{ $n->periodoEvaluacion?->nom_pev }}</td><td><strong style="color:var(--ui-{{ $n->not_cal<=50 ? 'danger':'primary' }})">{{ number_format($n->not_cal,2) }}</strong></td><td>{{ $n->obs_cal ?: 'Sin observación registrada' }}</td></tr>@endforeach</tbody></table></div>
                </x-plegable-institucional>
                @empty<p class="ui-alert-info mt-3">Este estudiante no tiene notas vigentes registradas.</p>@endforelse
            </section>
            <section><p class="ui-kicker">Intereses y resultados del aporte</p><p class="ui-help mt-2">Se conservan los intentos y fechas originales. Los intereses, la preparación académica y las recomendaciones se interpretan por separado.</p>
                @forelse($detalle['actividades'] as $actividad)
                <x-plegable-institucional :etiqueta="'RIASEC · gestión '.($actividad->gestionAcademica?->ani_gea ?? 'sin referencia').' · intento '.($actividad->int_oac ?? 1)" :descripcion="$actividad->estado.' · avance '.$actividad->avance.'%'" icono="ph-compass" :abierto="$loop->first">
                    <p class="ui-help">Finalizado: {{ $actividad->finalizado_at?->format('d/m/Y H:i') ?? 'pendiente' }} · Estudio: {{ $actividad->analysis_completed_at?->format('d/m/Y H:i') ?? 'sin estudio guardado' }}</p>
                    @if($actividad->resultado)<div class="ui-card-soft p-4 mt-3"><strong>{{ $actividad->resultado->perfil_predominante ?: 'Sin perfil predominante registrado' }}</strong><p class="text-sm mt-2">{{ $actividad->resultado->interpretacion }}</p><dl class="resultados-mini mt-3">@foreach(['rea_ors'=>'Realista','inv_ors'=>'Investigador','art_ors'=>'Artístico','soc_ors'=>'Social','emp_ors'=>'Emprendedor','con_ors'=>'Convencional'] as $campo=>$nombre)<div><dt>{{ $nombre }}</dt><dd>{{ $actividad->resultado->$campo ?? 'Sin puntuación' }}</dd></div>@endforeach</dl></div>@elseif($actividad->riasec_score)<div class="ui-card-soft p-4 mt-3"><strong>{{ data_get($actividad->riasec_score,'holland_code','Sin perfil registrado') }}</strong><dl class="resultados-mini mt-3">@foreach(['R'=>'Realista','I'=>'Investigador','A'=>'Artístico','S'=>'Social','E'=>'Emprendedor','C'=>'Convencional'] as $dimension=>$nombre)<div><dt>{{ $nombre }}</dt><dd>{{ data_get($actividad->riasec_score,'scores.'.$dimension,'Sin puntuación') }}</dd></div>@endforeach</dl><p class="ui-help mt-3">Puntuaciones guardadas por el servicio de orientación. Expresan intereses en la escala de su instrumento.</p></div>@else<p class="ui-alert-info mt-3">No hay resultado RIASEC consolidado para este intento.</p>@endif
                    @if($actividad->analysis_snapshot && $actividad->analysis_completed_at)
                    @php($estados=['AVAILABLE'=>'Evidencia disponible','PARTIAL'=>'Evidencia parcial','INSUFFICIENT'=>'Evidencia insuficiente','UNAVAILABLE'=>'Sin evidencia'])
                    <div class="ui-alert-info mt-3">Estudio del aporte guardado el {{ $actividad->analysis_completed_at->format('d/m/Y H:i') }}. Describe la evidencia disponible en esa fecha; las notas posteriores pueden requerir una nueva revisión.</div>
                    @foreach(collect(data_get($actividad->analysis_snapshot,'career_evidence_profiles',[])) as $carrera)
                    @php($estados=['AVAILABLE'=>'Evidencia disponible','PARTIAL'=>'Evidencia parcial','INSUFFICIENT'=>'Evidencia insuficiente','UNAVAILABLE'=>'Sin evidencia'])
                    <article class="ui-card-soft p-4 mt-3"><h3 class="font-black">{{ data_get($carrera,'career_name','Carrera sin nombre registrado') }}</h3><p class="ui-help">{{ data_get($carrera,'university','Sin universidad documentada') }}</p><dl class="resultados-mini mt-3"><div><dt>Relación de intereses</dt><dd>{{ $estados[data_get($carrera,'vocational_interest_relation.status')] ?? 'Sin evidencia' }}</dd></div><div><dt>Relaciones con notas observadas</dt><dd>{{ data_get($carrera,'preparation.relations_with_observed_academic_evidence','Sin evidencia') }}</dd></div></dl><p class="text-sm mt-3">{{ data_get($carrera,'preparation.interpretation') }}</p>@foreach(data_get($carrera,'preparation.reinforcement_areas',[]) as $area)<p class="ui-help mt-2"><strong>{{ data_get($area,'competency') }}:</strong> {{ data_get($area,'rationale') }}</p>@endforeach<p class="ui-help mt-3">{{ data_get($carrera,'evidence_quality.academic_record_count',0) }} notas · {{ data_get($carrera,'evidence_quality.distinct_subject_count',0) }} materias · {{ data_get($carrera,'evidence_quality.ordered_period_count',0) }} períodos respaldan esta revisión.</p>@foreach(data_get($carrera,'limitations',[]) as $limite)<p class="ui-help mt-2">{{ data_get($limite,'message') }}</p>@endforeach</article>
                    @endforeach
                    <x-plegable-institucional etiqueta="Respaldo y alcance del estudio" descripcion="Evidencia conservada en la fecha del análisis" icono="ph-file-text" :compacto="true"><dl class="resultados-mini">@foreach(['academic'=>'Calificaciones','attendance'=>'Asistencia','learning_activity'=>'Actividad de aprendizaje','historical'=>'Historial académico','technical'=>'Especialidad técnica','declared_interest'=>'Intereses declarados'] as $clave=>$titulo)<div><dt>{{ $titulo }}</dt><dd>{{ $estados[data_get($actividad->analysis_snapshot,'student_snapshot.'.$clave.'_evidence.status')] ?? 'Sin evidencia registrada' }}</dd></div>@endforeach</dl>@foreach(data_get($actividad->analysis_snapshot,'limitations',[]) as $limite)<p class="ui-help mt-3">{{ is_string($limite) ? $limite : data_get($limite,'message') }}</p>@endforeach</x-plegable-institucional>
                    @else<p class="ui-alert-warning mt-3">No existe un estudio del aporte guardado para este intento. No se asigna una carrera por inferencia.</p>@endif
                    @if($actividad->resultado?->carreras->isNotEmpty())<div class="mt-4"><h3 class="font-bold text-sm">Carreras sugeridas en el resultado RIASEC</h3>@foreach($actividad->resultado->carreras as $c)<article class="ui-card-soft p-3 mt-2"><strong class="text-sm">{{ $c->getRawOriginal('carrera') }}</strong><p class="ui-help">{{ $c->razon }}</p>@if($c->areas_a_fortalecer)<p class="ui-help">Áreas por fortalecer: {{ implode(' · ',array_filter($c->areas_a_fortalecer,'is_string')) }}</p>@endif</article>@endforeach</div>@endif
                    <x-plegable-institucional etiqueta="Respuestas del cuestionario" :descripcion="max($actividad->respuestas->count(),count(data_get($actividad->riasec_public,'responses',[]))).' respuestas conservadas · valor de la escala del instrumento'" icono="ph-list-checks" :compacto="true"><ol class="space-y-3">@forelse($actividad->respuestas as $respuesta)<li class="ui-card-soft p-3 text-sm"><p>{{ $respuesta->instrumentoPregunta?->orientacionPregunta?->texto ?? $respuesta->pregunta?->texto ?? 'Pregunta sin referencia disponible' }}</p><strong class="block mt-2">Respuesta registrada: {{ $respuesta->valor_likert }}</strong></li>@empty @forelse(data_get($actividad->riasec_public,"responses",[]) as $respuesta)<li class="ui-card-soft p-3 text-sm">Ítem {{ data_get($respuesta,"item_id","sin referencia") }} · respuesta registrada: <strong>{{ data_get($respuesta,"value","sin valor") }}</strong><p class="ui-help">El enunciado pertenece a la versión {{ data_get($actividad->riasec_public,"instrument_version","sin referencia") }} del instrumento público.</p></li>@empty<li class="ui-muted">Sin respuestas guardadas para este intento.</li>@endforelse @endforelse</ol></x-plegable-institucional>
                </x-plegable-institucional>
                @empty<p class="ui-alert-info mt-3">{{ $puedeVerOrientacion ? 'Todavía no hay actividad de orientación registrada para este estudiante.' : 'Tu cuenta no dispone del permiso para consultar orientación institucional.' }}</p>@endforelse
            </section>
            <section class="ui-card-soft p-4"><h3 class="font-black text-sm">Compromisos, responsabilidad y continuidad escolar</h3><p class="ui-help mt-2">Este panel no dispone de una evaluación consolidada de estos aspectos. Se muestran las observaciones académicas registradas; una calificación no permite diagnosticar responsabilidad ni confirmar deserción.</p></section>
        </div>
        <footer class="personas-modal-pie"><p class="ui-help">Consulta de evidencia institucional. La orientación no certifica admisión a una carrera.</p><button class="ui-btn-secondary" wire:click="cerrarDetalle">Cerrar</button></footer>
    </section>
</div>
