@php
    $r=$detalle['registro']; $actividad=$detalle['actividad']; $datos=$vistaPrevia ?? $detalle['estudio']['datos'];
    $estados=['AVAILABLE'=>'Disponible','PARTIAL'=>'Parcial','INSUFFICIENT'=>'Insuficiente','UNAVAILABLE'=>'Sin evidencia'];
@endphp
<section class="ui-card rendimiento-detalle" aria-labelledby="rendimiento-ficha-titulo" wire:key="rendimiento-detalle-{{ $r->cod_ins }}" x-data x-init="$nextTick(() => $el.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth'}))">
    <header class="rendimiento-detalle-cabecera"><div><p class="ui-kicker">Ficha académica · gestión {{ $r->ani_gea }}</p><h2 id="rendimiento-ficha-titulo">{{ trim($r->nom_per.' '.$r->ape_pat_per.' '.$r->ape_mat_per) }}</h2><p class="ui-help">{{ $r->cod_est }} · {{ $r->nom_cur }} · paralelo {{ $r->nom_par ?? 'sin referencia' }}</p></div><button type="button" class="ui-btn-secondary" wire:click="cerrarDetalle" aria-label="Cerrar ficha del estudiante"><i class="ph-duotone ph-x" aria-hidden="true"></i> Cerrar ficha</button></header>
    <x-plegable-institucional etiqueta="Notas que respaldan el rendimiento" :descripcion="$detalle['notas']->count().' registros vigentes o rectificados · período de las notas seleccionado'" icono="ph-exam" :abierto="true">
        <div class="rendimiento-notas-grafico">@forelse($detalle['notas']->groupBy(fn($n)=>$n->asignatura?->nom_asi ?? $n->planEspecialidad?->especialidad?->nom_esp ?? 'Sin referencia curricular') as $materia=>$notas)<article><div><h3>{{ $materia }}</h3><strong>{{ $notas->whereNotNull('not_cal')->isEmpty() ? 'Sin nota' : number_format($notas->avg('not_cal'),2).' / 100' }}</strong></div><svg viewBox="0 0 400 20" preserveAspectRatio="none" aria-hidden="true"><rect class="rendimiento-grafico-fondo" width="400" height="20" rx="7"/><rect class="rendimiento-grafico-primary" width="{{ 4*min(100,max(0,$notas->avg('not_cal') ?? 0)) }}" height="20" rx="7"/><line x1="200" x2="200" y1="0" y2="20" class="rendimiento-grafico-guia"/></svg><p class="ui-help">Promedio de {{ $notas->count() }} notas registradas · {{ $notas->pluck('periodoEvaluacion.nom_pev')->filter()->unique()->implode(' · ') }}</p></article>@empty<p class="ui-alert-info">No hay notas para esta inscripción y período.</p>@endforelse</div>
        <details class="rendimiento-respaldo"><summary>Ver registros de respaldo</summary><div class="rendimiento-tabla"><table><caption class="sr-only">Notas de la inscripción seleccionada</caption><thead><tr><th scope="col">Asignatura o especialidad</th><th scope="col">Período</th><th scope="col">Nota / 100</th><th scope="col">Fecha</th><th scope="col">Observación</th></tr></thead><tbody>@forelse($detalle['notas'] as $nota)<tr><td>{{ $nota->asignatura?->nom_asi ?? $nota->planEspecialidad?->especialidad?->nom_esp ?? 'Sin referencia curricular' }}</td><td>{{ $nota->periodoEvaluacion?->nom_pev ?? 'Sin período' }}</td><td><strong>{{ $nota->not_cal === null ? 'Sin nota' : number_format($nota->not_cal,2) }}</strong></td><td>{{ $nota->fea_cal?->format('d/m/Y') ?? 'Sin fecha' }}</td><td>{{ $nota->obs_cal ?: 'Sin observación' }}</td></tr>@empty<tr><td colspan="5">No hay notas para esta inscripción y período.</td></tr>@endforelse</tbody></table></div></details>
    </x-plegable-institucional>
    @if(!$puedeVerOrientacion)<p class="ui-alert-info">Tu cuenta no tiene permiso para consultar respuestas y estudios institucionales de orientación.</p>
    @elseif(!$actividad)<p class="ui-alert-info">Sin cuestionario ni análisis registrados en esta gestión. Las notas disponibles se muestran arriba.</p>
    @else
        <section class="ui-card-soft rendimiento-preparacion"><h3>Revisar la evidencia actual con el aporte</h3><p class="ui-help">La vista previa analiza las notas de esta gestión, el cuestionario oficial compatible y la evidencia disponible. El período elegido en la lista no recorta el perfil que se envía al análisis.</p><div class="rendimiento-vistas"><button type="button" class="ui-btn-secondary" wire:click="revisarPreparacion" wire:loading.attr="disabled">Revisar preparación</button><button type="button" class="ui-btn-primary" wire:click="analizarEvidencia" wire:loading.attr="disabled" @disabled(!($preparacion['ready'] ?? false))>Analizar evidencia actual</button></div>
            @if(!$preparacion)<p class="ui-help">Revisa primero la preparación para conocer los requisitos del análisis.</p>@else<dl class="rendimiento-requisitos">@foreach($preparacion['requirements'] as $requisito)<div><dt>{{ $requisito['label'] }}</dt><dd>{{ $requisito['type']==='NO_APLICA' ? 'No aplica' : ($requisito['complete'] ? 'Disponible' : ($requisito['type']==='OBLIGATORIO' ? 'Falta · obligatorio' : 'Sin evidencia · no bloquea')) }}</dd></div>@endforeach</dl>@if(!$preparacion['ready'])<p class="ui-alert-warning">El análisis está bloqueado hasta completar los requisitos obligatorios. Los cuestionarios locales o de otra versión se conservan; no se convierten automáticamente al instrumento público del aporte.</p>@endif @endif
            @if($mensajeAnalisis)<p class="ui-alert-info" role="status">{{ $mensajeAnalisis }}</p>@endif
            <p wire:loading wire:target="analizarEvidencia" class="ui-alert-info" role="status">El aporte está analizando la evidencia…</p>
        </section>
        <x-plegable-institucional etiqueta="Lo que respondió el estudiante" :descripcion="'Último intento de esta gestión · '.($actividad->finalizado_at ? 'finalizado el '.$actividad->finalizado_at->format('d/m/Y') : 'cuestionario pendiente')" icono="ph-list-checks" :abierto="true">
            @if($actividad->resultado)<p class="ui-badge-info">Perfil de intereses: {{ $actividad->resultado->perfil_predominante ?: 'sin perfil registrado' }}</p>
            @elseif($actividad->riasec_score)<p class="ui-badge-info">Perfil de intereses: {{ data_get($actividad->riasec_score,'holland_code','sin perfil registrado') }}</p>@endif
            <p class="ui-help">Las respuestas describen intereses. Su valor pertenece a la escala y versión del instrumento utilizado.</p>
            <ol class="rendimiento-respuestas">@forelse($actividad->respuestas as $respuesta)<li><p>{{ $respuesta->instrumentoPregunta?->orientacionPregunta?->texto ?? $respuesta->pregunta?->texto ?? 'Pregunta sin enunciado disponible' }}</p><strong>Respuesta guardada: {{ $respuesta->valor_likert }}</strong></li>@empty @forelse(data_get($actividad->riasec_public,'responses',[]) as $respuesta)<li><p>Ítem {{ data_get($respuesta,'item_id','sin referencia') }}</p><strong>Respuesta guardada: {{ data_get($respuesta,'value','sin valor') }}</strong><small class="ui-muted">Instrumento {{ data_get($actividad->riasec_public,'instrument_version','sin versión') }} · el enunciado no está conservado en este registro.</small></li>@empty<li>Sin respuestas guardadas en este intento.</li>@endforelse @endforelse</ol>
        </x-plegable-institucional>
        @if(!$datos)<p class="ui-alert-warning">{{ $detalle['estudio']['estado'] === 'requiere_revision' ? 'El resultado guardado requiere revisar su formato, referencia del estudiante o trazabilidad. Se conserva, pero no se presenta como un análisis interpretable.' : 'Este intento no tiene un análisis guardado. Completar el cuestionario y generar su estudio desde el espacio de orientación permitirá consultarlo aquí.' }}</p>
        @else
            <div class="ui-alert-info"><strong>{{ $vistaPrevia ? 'Vista previa · ' : '' }}{{ ['COMPLETE'=>'Análisis completo','PARTIAL'=>'Análisis parcial','INSUFFICIENT'=>'Evidencia insuficiente'][$datos['analysis_status']] }}.</strong> {{ $vistaPrevia ? 'Calculado con la evidencia actual; no guardado en el historial.' : 'Guardado el '.$actividad->analysis_completed_at->format('d/m/Y H:i').'.' }} Formato y vinculación comprobados. Este estudio describe la evidencia enviada al aporte.</div>
            @if(!$vistaPrevia && $detalle['notasPosteriores'])<p class="ui-alert-warning">Hay notas registradas o modificadas después del estudio. El análisis guardado puede necesitar actualización; las notas actuales no se incorporan automáticamente al resultado anterior.</p>@endif
            <x-plegable-institucional etiqueta="Evidencia que utilizó el aporte" descripcion="Calificaciones, asistencia, trayectoria y formación disponibles en la fecha del estudio" icono="ph-files" :abierto="true"><dl class="rendimiento-evidencias">@foreach(['academic'=>'Calificaciones','attendance'=>'Asistencia','learning_activity'=>'Actividad de aprendizaje','historical'=>'Trayectoria','technical'=>'Formación técnica','declared_interest'=>'Intereses declarados'] as $clave=>$titulo)<div><dt>{{ $titulo }}</dt><dd>{{ $estados[data_get($datos,'student_snapshot.'.$clave.'_evidence.status')] }}</dd></div>@endforeach</dl>
                @php($asistencia=data_get($datos,'student_snapshot.attendance_evidence'))
                @if(is_numeric(data_get($asistencia,'total_classes')) && data_get($asistencia,'total_classes') > 0 && is_numeric(data_get($asistencia,'attended_classes')))<p class="ui-help">Asistencia utilizada: {{ $asistencia['attended_classes'] }} clases asistidas de {{ $asistencia['total_classes'] }} registradas.</p>@endif
                @foreach(data_get($datos,'student_snapshot.academic_evidence.warnings',[]) as $aviso)<p class="ui-help">{{ $aviso }}</p>@endforeach
            </x-plegable-institucional>
            <section class="rendimiento-estudio-carreras"><p class="ui-kicker">Relaciones para explorar su futuro académico</p><h3>Opciones de formación y áreas por fortalecer</h3><p class="ui-help">La preparación observada, los intereses y las fuentes se interpretan por separado. El aporte orienta el acompañamiento; no determina qué llegará a ser el estudiante.</p>
                @forelse($datos['career_evidence_profiles'] as $carrera)<x-plegable-institucional :etiqueta="$carrera['career_name']" :descripcion="$carrera['university']" icono="ph-graduation-cap" :abierto="$loop->first"><p>{{ data_get($carrera,'preparation.interpretation') }}</p><dl class="rendimiento-medidas"><div><dt>Relación de intereses</dt><dd>{{ $estados[data_get($carrera,'vocational_interest_relation.status')] }}</dd></div><div><dt>Notas que respaldan la revisión</dt><dd>{{ data_get($carrera,'evidence_quality.academic_record_count') }}</dd></div></dl>
                    @foreach(data_get($carrera,'preparation.reinforcement_areas',[]) as $area)<article class="ui-card-soft rendimiento-refuerzo"><h4>{{ $area['competency'] }}</h4><p class="ui-help">{{ $area['rationale'] }}</p></article>@endforeach
                    @foreach(data_get($carrera,'limitations',[]) as $limite)<p class="ui-help">{{ $limite['message'] }}</p>@endforeach
                    <p class="ui-help">{{ data_get($carrera,'evidence_quality.distinct_subject_count') }} materias · {{ data_get($carrera,'evidence_quality.ordered_period_count') }} períodos con evidencia.</p>
                </x-plegable-institucional>@empty<p class="ui-alert-info">El análisis no incluye opciones de carrera con evidencia documentada.</p>@endforelse
            </section>
            <x-plegable-institucional etiqueta="Fuentes, límites y trazabilidad" descripcion="Respaldo del estudio conservado" icono="ph-file-text"><dl class="rendimiento-evidencias"><div><dt>Versión del motor</dt><dd>{{ data_get($datos,'traceability.engine_version','Sin referencia') }}</dd></div><div><dt>Versión de criterios</dt><dd>{{ data_get($datos,'traceability.criteria_version','Sin referencia') }}</dd></div><div><dt>Referencia de trazabilidad</dt><dd class="rendimiento-referencia">{{ $datos['trace_id'] }}</dd></div></dl><ul class="rendimiento-fuentes">@forelse($datos['sources_used'] as $fuente)<li><strong>{{ data_get($fuente,'title') ?: data_get($fuente,'source_id','Sin referencia') }}</strong><p class="ui-help">{{ data_get($fuente,'institution') }} · {{ data_get($fuente,'version','Sin versión indicada') }} · {{ data_get($fuente,'source_id') }}</p></li>@empty<li>No hay fuentes conservadas en este resultado.</li>@endforelse</ul>@foreach($datos['limitations'] as $limite)<p class="ui-alert-warning">{{ data_get($limite,'message') }}</p>@endforeach @foreach($datos['warnings'] as $aviso)<p class="ui-help">{{ $aviso }}</p>@endforeach</x-plegable-institucional>
        @endif
    @endif
</section>
