<section class="ui-card rendimiento-grupo" aria-labelledby="rendimiento-grupo-titulo">
    <p class="ui-kicker">De las respuestas al acompañamiento</p><h2 id="rendimiento-grupo-titulo">Qué evidencia tiene el grupo</h2>
    <p class="ui-help">Los filtros se aplican al grupo completo. Cada estudiante se cuenta con su último intento de la gestión seleccionada.</p>
    <div class="rendimiento-recorrido">@foreach([['evaluados','Con notas','primary'],['riasec','RIASEC finalizado','info'],['analisis','Estudio guardado','violet']] as [$campo,$titulo,$color])
        @php($cantidad=$campo!=='evaluados' && !$puedeVerOrientacion ? 0 : (int)$resumen->$campo)
        <article class="rendimiento-cobertura"><div class="rendimiento-anillo"><svg viewBox="0 0 120 120" aria-hidden="true"><circle class="rendimiento-anillo-fondo" cx="60" cy="60" r="50"/><circle cx="60" cy="60" r="50" pathLength="100" stroke-dasharray="{{ min(100,100*$cantidad/max(1,(int)$resumen->total)) }} 100" style="stroke:var(--ui-{{ $color }})" class="rendimiento-anillo-dato"/></svg><strong>{{ $campo!=='evaluados' && !$puedeVerOrientacion ? '—' : $cantidad }}<small>/ {{ (int)$resumen->total }}</small></strong></div><h3>{{ $titulo }}</h3><p class="ui-help">{{ $campo!=='evaluados' && !$puedeVerOrientacion ? 'Acceso restringido' : ($resumen->total ? round(100*$cantidad/$resumen->total,1).'% del grupo' : 'Sin estudiantes en la consulta') }}</p></article>
    @endforeach</div>
    <p class="ui-help">Estas coberturas son independientes. Finalizar el cuestionario no significa que el análisis académico esté completo.</p>
</section>
<div class="rendimiento-grupo-columnas">
    <section class="ui-card rendimiento-grupo"><p class="ui-kicker">Rendimiento observado</p><h2>Seguimiento por grado</h2><p class="ui-help">Promedio observado por grado. La línea marca 50 puntos; debajo se indican los estudiantes con alguna nota de 50 o menos.</p>
        @forelse($grados as $grado)<article class="rendimiento-grado"><div><strong>{{ $grado->nom_cur }}</strong><span>{{ $grado->promedio === null ? 'Sin notas' : number_format($grado->promedio,2).' / 100' }}</span></div><svg class="rendimiento-barra-svg" viewBox="0 0 400 22" preserveAspectRatio="none" role="img" aria-label="Promedio observado de {{ $grado->nom_cur }}: {{ $grado->promedio === null ? 'sin notas' : number_format($grado->promedio,2) }}"><rect class="rendimiento-grafico-fondo" width="400" height="22" rx="7"/><rect class="rendimiento-grafico-primary" width="{{ 4*min(100,max(0,$grado->promedio ?? 0)) }}" height="22" rx="7"/><line x1="200" x2="200" y1="0" y2="22" class="rendimiento-grafico-guia"/></svg><p class="ui-help">{{ (int)$grado->riesgo }} necesitan seguimiento · {{ (int)$grado->evaluados }} con notas / {{ (int)$grado->total }} inscritos.</p></article>@empty<p class="ui-help">No hay inscripciones para comparar.</p>@endforelse
    </section>
    <section class="ui-card rendimiento-grupo"><p class="ui-kicker">Resultados del aporte</p><h2>Alcance de los estudios</h2>
        @if(!$puedeVerOrientacion)<p class="ui-help">Tu cuenta no tiene permiso para consultar orientación institucional.</p>
        @else<dl class="rendimiento-alcance"><div><dt>Formato y vinculación comprobados</dt><dd>{{ $grupo['validos'] }}</dd></div>@foreach(['COMPLETE'=>'Análisis completo','PARTIAL'=>'Análisis parcial','INSUFFICIENT'=>'Evidencia insuficiente'] as $estado=>$etiqueta)<div><dt>{{ $etiqueta }}</dt><dd>{{ $grupo['estados'][$estado] }}</dd></div>@endforeach<div><dt>Requieren revisar formato o vinculación</dt><dd>{{ $grupo['revision'] }}</dd></div></dl>
            <p class="ui-help">Se comprueban el contrato del aporte, la referencia del estudiante y la trazabilidad. Esto no acredita predicciones de éxito académico ni validación psicométrica.</p>
            @if($grupo['ultima'])<p class="ui-help">Último estudio de este grupo: {{ \Carbon\Carbon::parse($grupo['ultima'])->format('d/m/Y H:i') }}.</p>@endif
        @endif
    </section>
</div>
@if($puedeVerOrientacion)
    <section class="ui-card rendimiento-grupo"><p class="ui-kicker">Qué pudo analizar el sistema</p><h2>Cobertura de la evidencia utilizada</h2>
        @if(!$grupo['validos'])<div class="rendimiento-vacio"><i class="ph-duotone ph-files" aria-hidden="true"></i><h3>No hay estudios interpretables en este grupo</h3><p class="ui-help">Los resultados aparecerán cuando exista un estudio guardado y vinculado al estudiante. Las respuestas y las notas existentes se conservan en su ficha.</p></div>
        @else<div class="rendimiento-evidencias">@foreach(['academic'=>'Calificaciones','attendance'=>'Asistencia','learning_activity'=>'Actividad de aprendizaje','historical'=>'Trayectoria','technical'=>'Formación técnica','declared_interest'=>'Intereses declarados'] as $tipo=>$titulo) @php($e=$grupo['evidencias'][$tipo])<article><h3>{{ $titulo }}</h3><strong>{{ $e['AVAILABLE'] }} <small>con evidencia disponible</small></strong><div class="rendimiento-evidencia-apilada" role="img" aria-label="{{ $titulo }}: {{ $e['AVAILABLE'] }} disponibles, {{ $e['PARTIAL'] }} parciales, {{ $e['INSUFFICIENT'] }} insuficientes, {{ $e['UNAVAILABLE'] }} sin evidencia">@foreach(['AVAILABLE'=>'primary','PARTIAL'=>'info','INSUFFICIENT'=>'warning','UNAVAILABLE'=>'muted'] as $estado=>$color)<span style="width:{{ 100*$e[$estado]/$grupo['validos'] }}%;background:var(--ui-{{ $color }})"></span>@endforeach</div><p class="ui-help">{{ $e['PARTIAL'] }} parciales · {{ $e['INSUFFICIENT'] }} insuficientes · {{ $e['UNAVAILABLE'] }} sin evidencia</p></article>@endforeach</div>@endif
    </section>
    <section class="ui-card rendimiento-grupo"><p class="ui-kicker">Estudiantes y posibilidades de formación</p><h2>Carreras conocidas y relaciones con el grupo</h2><p class="ui-help">Catálogo instalado del aporte · versión {{ $grupo['version_catalogo'] ?? 'no disponible' }}. Cada barra cuenta estudiantes con una relación respaldada en su estudio, respecto a los estudios interpretables del grupo. Selecciónala para ver quiénes son.</p>
        <div class="rendimiento-leyenda">@foreach(['academica'=>['Preparación observada','primary'],'tecnica'=>['Formación técnica relacionada','info'],'declarados'=>['Interés declarado relacionado','violet']] as $tipo=>[$etiqueta,$color])<span><i style="background:var(--ui-{{ $color }})"></i>{{ $etiqueta }}</span>@endforeach</div>
        @if(!$grupo['validos'])<p class="ui-alert-info">Los estudiantes de esta consulta todavía no tienen estudios interpretables. Se muestran todas las carreras del catálogo; sus relaciones quedan pendientes de análisis, sin asignar compatibilidad por suposición.</p>@endif
        <div class="rendimiento-carreras-graficos">@forelse($grupo['carreras'] as $carrera)<article class="ui-card-soft"><h3>{{ $carrera['nombre'] }}</h3><p class="ui-help">{{ $carrera['universidad'] }}</p>
            @if(!$carrera['elegible'])<p class="ui-badge-warning">Fuente externa · consulta informativa</p><p class="ui-help">Esta carrera queda fuera del cálculo de relaciones del aporte.</p>
            @else<div class="rendimiento-carrera-barras">@foreach(['academica'=>['Preparación observada','primary'],'tecnica'=>['Formación técnica','info'],'declarados'=>['Interés declarado','violet']] as $tipo=>[$etiqueta,$color])<button type="button" wire:click="verRelacionCarrera('{{ $carrera['id'] }}','{{ $tipo }}')" aria-label="Ver estudiantes con {{ mb_strtolower($etiqueta) }} para {{ $carrera['nombre'] }} en {{ $carrera['universidad'] }}"><span>{{ $etiqueta }}<strong>{{ $carrera['estudios'] ? $carrera[$tipo] : '—' }}</strong></span><svg viewBox="0 0 300 14" preserveAspectRatio="none" aria-hidden="true"><rect class="rendimiento-grafico-fondo" width="300" height="14" rx="5"/><rect width="{{ 300*$carrera[$tipo]/max(1,$grupo['validos']) }}" height="14" rx="5" style="fill:var(--ui-{{ $color }})"/></svg></button>@endforeach</div><p class="ui-help">{{ $carrera['estudios'] }} estudios revisan esta carrera · {{ max(0,(int)$resumen->total-$carrera['estudios']) }} estudiantes pendientes de revisión de esta opción.</p>@endif
        </article>@empty<p class="ui-alert-warning">El catálogo instalado no está disponible. Se conservan los resultados existentes; no se añaden carreras supuestas.</p>@endforelse</div>
        <p class="ui-help">El contrato actual no calcula un porcentaje global de compatibilidad. La relación de notas con contenidos universitarios, la formación técnica y los intereses declarados se consultan por separado; su presencia no garantiza admisión ni éxito futuro.</p>
        @if($grupo['carrera_seleccionada'])<section class="rendimiento-coincidencias" aria-labelledby="rendimiento-coincidencias-titulo" wire:key="carrera-{{ $carreraSeleccionada }}-{{ $tipoRelacion }}"><p class="ui-kicker">Quiénes respaldan la gráfica</p><h3 id="rendimiento-coincidencias-titulo">{{ $grupo['carrera_seleccionada']['nombre'] }}</h3><p class="ui-help">{{ $grupo['carrera_seleccionada']['universidad'] }} · {{ ['academica'=>'Preparación observada','tecnica'=>'Formación técnica relacionada','declarados'=>'Interés declarado relacionado'][$tipoRelacion] }}</p><div class="rendimiento-vinculados">@forelse($grupo['vinculados'] as $vinculado)<button type="button" class="ui-card-soft" wire:click="verEstudiante('{{ $vinculado['inscripcion'] }}')"><i class="ph-duotone ph-student" aria-hidden="true"></i><strong>{{ $vinculado['nombre'] }}</strong><small>{{ $vinculado['codigo'] }} · estudio {{ $vinculado['fecha'] }}</small><span>Ver la evidencia de su estudio <i class="ph-duotone ph-arrow-right" aria-hidden="true"></i></span></button>@empty<p class="ui-alert-info">{{ $grupo['validos'] ? 'No hay estudiantes con esta relación documentada en los estudios revisados.' : 'La relación con esta carrera está pendiente: todavía no hay estudios interpretables en el grupo.' }}</p>@endforelse</div></section>@endif
    </section>
@endif
