@php
    $puedeEditar=auth()->user()->can('roles-permisos.gestionar')&&auth()->user()->can('roles.permisos.asignar');
    $datosRoles=$roles->map(fn($r)=>['id'=>$r->id,'nombre'=>$r->name,'permisos'=>$r->permissions->pluck('name')->all()])->all();
    $miAdministracion=$permisosCuenta->where('espacio','administrativo')->count();$miAula=$permisosCuenta->where('espacio','aula')->count();$porcentajeAdmin=$cuenta['total']?$miAdministracion/$cuenta['total']*100:0; $totalPermisos=$catalogoCompleto->count(); $maxCuentas=max(1,$roles->max('users_count'));$maxPermisos=max(1,$roles->max('permissions_count'));
@endphp
<div class="roles-pagina" x-data="rolesInstitucionales(@js($permisos->all()),@js($datosRoles),$wire.entangle('selectedPermissions'),@js(['motivos'=>\App\Support\SupportRolesInstitucionales::MOTIVOS,'ambitos'=>\App\Support\SupportRolesInstitucionales::AMBITOS,'minimo'=>now()->setTimezone(config('seguridad-accesos.zona_horaria'))->toDateString(),'maximo'=>$gestionActiva?->ffi_gea?->toDateString()??'']),@js($ventanas),@js($catalogoCompleto->all()),@js(['permisos'=>$permisosCuenta->pluck('name')->all(),'roles'=>auth()->user()->roles->modelKeys()]),$wire.entangle('apartado'))" x-on:roles-acceso-guardado.window="avisoAcceso($event.detail)" wire:key="roles-panel-{{ md5(json_encode($datosRoles)) }}">
    <header class="ui-card roles-cabecera">
        <div><p class="roles-kicker">Seguridad institucional</p><h1>Roles y permisos</h1><p class="ui-muted text-sm">Organiza quién puede hacer cada tarea, con accesos claros y vigencias respaldadas.</p></div>
        <div class="roles-acciones">
            @if(auth()->user()->can('roles.solicitudes.crear'))<button class="ui-btn ui-btn-secondary" type="button" x-on:click="abrirSolicitud()" :disabled="!!proceso"><i class="ph-duotone ph-user-plus" aria-hidden="true"></i>Solicitar rol</button>@endif
            @if($puedePersonal)<button class="ui-btn ui-btn-secondary" type="button" x-on:click="apartado='usuarios'"><i class="ph-duotone ph-user-check" aria-hidden="true"></i>Asignar a usuario</button>@endif
            @if($puedeEditar)<button class="ui-btn ui-btn-primary" type="button" x-on:click="abrirAcceso()" :disabled="!!proceso"><i class="ph-duotone ph-calendar-plus" aria-hidden="true"></i>Programar acceso</button>@endif
        </div>
    </header>
    <section class="roles-graficos" aria-label="Resumen de permisos y cuentas por rol">
        <article class="ui-card roles-grafico"><p class="roles-kicker">Capacidad de cada rol</p><h2>Permisos asignados</h2><p class="ui-muted">Cada barra cuenta permisos realmente guardados.</p><div class="roles-barras">@foreach($roles as $r)<button type="button" class="roles-barra" x-on:click="seleccionarRol({{ $r->id }})" aria-label="Consultar {{ $r->name }}: {{ $r->permissions_count }} permisos"><span>{{ $r->name }}</span><span class="roles-barra-pista"><i style="--avance:{{ $r->permissions_count/$maxPermisos*100 }}%" aria-hidden="true"></i></span><strong>{{ $r->permissions_count }}</strong></button>@endforeach</div></article>
        <article class="ui-card roles-grafico roles-distribucion"><p class="roles-kicker">Tus tareas por espacio</p><h2>Administración y Aula virtual</h2><p class="ui-muted">Dónde se distribuyen los permisos de tu cuenta.</p><div class="roles-anillo" style="--porcentaje:{{ $porcentajeAdmin }}"><svg viewBox="0 0 120 120" aria-hidden="true"><circle class="roles-anillo-base" cx="60" cy="60" r="48" pathLength="100"/><circle class="roles-anillo-avance" cx="60" cy="60" r="48" pathLength="100" stroke-dasharray="{{ $porcentajeAdmin }} 100"/></svg><span><strong>{{ $cuenta['total'] }}</strong><small>permisos propios</small></span></div><div class="roles-distribucion-leyenda"><button type="button" x-on:click="cambiarEspacio('administrativo')"><i class="ph-duotone ph-buildings" aria-hidden="true"></i><span>Administración</span><strong>{{ $miAdministracion }}</strong></button><button type="button" x-on:click="cambiarEspacio('aula')"><i class="ph-duotone ph-chalkboard-teacher" aria-hidden="true"></i><span>Aula virtual</span><strong>{{ $miAula }}</strong></button></div></article>
        <article class="ui-card roles-grafico roles-cuenta"><div class="roles-cuenta-identidad"><img src="{{ auth()->user()->profile_photo_url }}" alt="" width="42" height="42"><div><p class="roles-kicker">Tu cuenta</p><strong>{{ auth()->user()->persona?->nom_per ?? 'Tu cuenta institucional' }}</strong></div></div><button type="button" class="roles-total-grafico" x-on:click="apartado='catalogo'" aria-label="Ver los {{ $totalPermisos }} permisos del sistema"><span class="roles-anillo roles-anillo-total"><svg viewBox="0 0 120 120" aria-hidden="true"><circle class="roles-total-base" cx="60" cy="60" r="48" pathLength="100"/><circle class="roles-anillo-avance" cx="60" cy="60" r="48" pathLength="100" stroke-dasharray="{{ $totalPermisos?min(100,$cuenta['total']/$totalPermisos*100):0 }} 100"/></svg><span><strong>{{ $totalPermisos }}</strong><small>permisos del sistema</small></span></span><span class="roles-total-leyenda"><span><i class="ph-duotone ph-check-circle" aria-hidden="true"></i>{{ $cuenta['total'] }} en tu cuenta</span><span><i class="ph-duotone ph-minus-circle" aria-hidden="true"></i>{{ max(0,$totalPermisos-$cuenta['total']) }} fuera de tu cuenta</span></span><small>Explorar catálogo completo <i class="ph-duotone ph-arrow-right" aria-hidden="true"></i></small></button><p class="ui-muted text-xs">{{ $cuenta['permanentes'] }} permanentes · {{ $cuenta['temporales'] }} temporales adicionales</p><p class="roles-catalogo-total">{{ $totalPermisos }} en el catálogo · {{ $roles->count() }} roles · {{ $cuentasConRol }} cuentas con rol</p></article>
    </section>
    <nav class="roles-navegacion" role="tablist" aria-label="Organización de accesos">
        @foreach(['roles'=>['ph-users-three','Roles y permisos'],'catalogo'=>['ph-stack','Catálogo completo · '.$totalPermisos],'cuenta'=>['ph-identification-card','Mi cuenta · '.$cuenta['total'].' permisos'],'vigencias'=>['ph-calendar-check','Accesos y vigencias'],'solicitudes'=>['ph-file-pdf','Solicitudes']] as $id=>[$icono,$nombre])<button type="button" role="tab" :aria-selected="apartado==='{{ $id }}'" x-on:click="apartado='{{ $id }}'"><i class="ph-duotone {{ $icono }}" aria-hidden="true"></i>{{ $nombre }}</button>@endforeach
        @if($puedePersonal)<button type="button" role="tab" :aria-selected="apartado==='usuarios'" x-on:click="apartado='usuarios'"><i class="ph-duotone ph-user-check" aria-hidden="true"></i>Por usuario</button>@endif
    </nav>
    <p role="status" class="roles-aviso" x-show="mensaje" x-text="mensaje" x-cloak></p>
    <div class="roles-zona" x-show="apartado==='roles'">
        <aside class="ui-card roles-lista" aria-label="Elegir un rol"><h2>¿Qué rol revisamos?</h2>@foreach($roles as $r)<button class="roles-elegir" type="button" x-on:click="seleccionarRol({{ $r->id }})" :disabled="!!proceso" aria-pressed="{{ $selectedRoleId===$r->id?'true':'false' }}"><i class="ph-duotone {{ $r->icono }}" aria-hidden="true"></i><span><strong>{{ $r->name }}</strong><small>{{ $r->permissions_count }} permisos · {{ $r->users_count }} cuentas</small></span></button>@endforeach</aside>
        <section class="ui-card roles-trabajo" :aria-busy="proceso==='rol'">
            <div class="roles-titulo"><i class="ph-duotone {{ $selectedRole?->icono }}" aria-hidden="true"></i><div><p class="roles-kicker">{{ in_array($selectedRole?->name,\App\Models\Oficial\Sistema\Role::INSTITUTIONAL,true)?'Rol institucional':'Rol complementario' }}</p><h2>{{ $selectedRole?->name }}</h2><p class="ui-muted">{{ $selectedRole?->descripcion }}</p></div><i x-show="proceso==='rol'" class="ph-duotone ph-spinner-gap roles-giro" aria-label="Consultando rol"></i>@include('livewire.admin.roles.modo-edicion')</div>

            @include('livewire.admin.roles.ventanas')
            <div class="roles-herramientas"><nav class="roles-vistas" aria-label="Vista de permisos">@foreach(['lectura'=>['ph-list-bullets','Lectura'],'matriz'=>['ph-table','Matriz'],'selectores'=>['ph-check-square','Selección']] as $v=>[$i,$n])<button type="button" :aria-pressed="vista==='{{ $v }}'" x-on:click="vista='{{ $v }}';pagina=1"><i class="ph-duotone {{ $i }}" aria-hidden="true"></i>{{ $n }}</button>@endforeach</nav>
            <nav class="roles-espacios" aria-label="Espacio de permisos"><button type="button" :aria-pressed="espacio==='administrativo'" x-on:click="cambiarEspacio('administrativo')"><i class="ph-duotone ph-buildings" aria-hidden="true"></i>Administración <span>{{ $permisos->where('espacio','administrativo')->count() }}</span></button><button type="button" :aria-pressed="espacio==='aula'" x-on:click="cambiarEspacio('aula')"><i class="ph-duotone ph-chalkboard-teacher" aria-hidden="true"></i>Aula virtual <span>{{ $permisos->where('espacio','aula')->count() }}</span></button></nav></div>
            @include('livewire.admin.roles.cambios-permisos',['origenEdicion'=>'roles'])
            <div class="roles-filtros"><label class="ui-label">Buscar una tarea<input class="ui-input" type="search" x-model.debounce.150ms="busqueda" x-on:input="pagina=1" placeholder="Consultar, registrar, aula…"></label><div x-show="espacio==='administrativo'"><x-selector-institucional enlace="dominio" identificador="roles-filtro-area" etiqueta="Área administrativa" :opciones="array_merge([['valor'=>'','etiqueta'=>'Todas las áreas']],$permisos->where('espacio','administrativo')->pluck('domain')->unique()->sort()->map(fn($d)=>['valor'=>$d,'etiqueta'=>$d])->values()->all())" /></div><div x-show="espacio==='aula'" x-cloak><x-selector-institucional enlace="tipoAula" identificador="roles-filtro-aula" etiqueta="Actividad del aula" :opciones="array_merge([['valor'=>'','etiqueta'=>'Todas las actividades']],$permisos->where('espacio','aula')->pluck('tipo_aula')->unique()->sort()->map(fn($d)=>['valor'=>$d,'etiqueta'=>$d])->values()->all())" /></div><x-selector-institucional enlace="estado" identificador="roles-filtro-permisos" etiqueta="Permisos del rol" :opciones="[['valor'=>'','etiqueta'=>'Todos'],['valor'=>'consulta','etiqueta'=>'Puede consultar'],['valor'=>'edicion','etiqueta'=>'Puede editar'],['valor'=>'entrada','etiqueta'=>'Entrada al módulo'],['valor'=>'operacion','etiqueta'=>'Otras operaciones'],['valor'=>'sin','etiqueta'=>'Sin permiso específico']]" /><button class="ui-btn ui-btn-secondary" type="button" x-on:click="limpiar()" aria-label="Limpiar filtros"><i class="ph-duotone ph-arrow-counter-clockwise" aria-hidden="true"></i></button></div>
            <div x-show="vista==='lectura'" class="roles-lectura">
                @foreach($dominios as $d)<x-plegable-institucional :etiqueta="$d" icono="ph-folder-open" :abierto="false" :data-area="$d" x-show="filtrados.some(p=>p.domain===$el.dataset.area)"><x-slot:contador><span x-text="filtrados.filter(p=>p.domain===@js($d)).length"></span> tareas · <span x-text="filtrados.filter(p=>p.domain===@js($d)&&seleccion.includes(p.name)).length"></span> asignadas</x-slot:contador><div class="roles-permisos"><template x-for="p in filtrados.filter(p=>p.domain===@js($d))" :key="p.name"><div class="roles-permiso"><input x-show="$wire.edicionPermisos&&!bloqueoAsignacion(p)" type="checkbox" :aria-label="'Asignar '+p.label+' · '+p.scope_label" :checked="seleccion.includes(p.name)" x-on:change="marcar(p.name)" :disabled="!$wire.edicionPermisos||!!proceso||!!bloqueoAsignacion(p)"><i x-show="!$wire.edicionPermisos||bloqueoAsignacion(p)" class="ph-duotone" :class="seleccion.includes(p.name)?'ph-check-circle':'ph-minus-circle'" aria-hidden="true"></i><div><button type="button" class="roles-detalle-enlace" x-on:click="permisoDetalle=p"><strong x-text="p.label"></strong><i class="ph-duotone ph-info" aria-hidden="true"></i><span class="sr-only">Ver detalles del permiso</span></button><small x-text="p.scope_label"></small><small x-text="nivelPermiso(p)"></small><small x-show="p.critical">Requiere autoridad elevada</small></div></div></template></div></x-plegable-institucional>@endforeach
            </div>
            <div x-show="vista==='matriz'" x-cloak><p class="ui-muted text-xs">Compara los permisos guardados de todos los roles. La selección pendiente del rol actual se marca antes de guardar.</p><div class="roles-matriz-contenedor"><table class="roles-matriz"><caption class="sr-only">Matriz de tareas y roles</caption><thead><tr><th scope="col">Tarea y alcance</th>@foreach($roles as $r)<th scope="col">{{ $r->name }}</th>@endforeach</tr></thead><tbody><template x-for="p in visibles" :key="p.name"><tr><th scope="row"><button type="button" class="roles-detalle-enlace" x-on:click="permisoDetalle=p"><span x-text="p.label"></span><i class="ph-duotone ph-info" aria-hidden="true"></i></button><small x-text="p.scope_label"></small></th>@foreach($roles as $r)<td><span :class="nivelPermiso(p,{{ $r->id }}).startsWith('Consulta')?'roles-consulta':nivelPermiso(p,{{ $r->id }})==='Sin permiso'?'roles-no':'roles-si'"><i class="ph-duotone" :class="nivelPermiso(p,{{ $r->id }}).startsWith('Consulta')?'ph-eye':nivelPermiso(p,{{ $r->id }})==='Edición'?'ph-pencil-simple':nivelPermiso(p,{{ $r->id }})==='Sin permiso'?'ph-minus':'ph-check-circle'" aria-hidden="true"></i><span class="roles-nivel" x-text="nivelPermiso(p,{{ $r->id }})"></span></span></td>@endforeach</tr></template></tbody></table></div></div>
            <div x-show="vista==='selectores'" x-cloak><p class="ui-muted text-xs mb-3">Selecciona las tareas necesarias. Activa Edición para modificar; Guardar aplica el cambio a las cuentas del rol.</p><div class="roles-permisos"><template x-for="p in visibles" :key="p.name"><label class="roles-permiso"><input x-show="$wire.edicionPermisos" x-cloak type="checkbox" :checked="seleccion.includes(p.name)" x-on:change="marcar(p.name)" :disabled="!$wire.edicionPermisos||!!proceso||@js(!$puedeEditar)"><span><strong x-text="p.label"></strong><small x-text="p.scope_label"></small><small x-show="p.critical">La autoridad elevada se valida al guardar.</small></span></label></template></div></div>
            <div class="roles-vacio" x-show="!filtrados.length" x-cloak><i class="ph-duotone ph-magnifying-glass" aria-hidden="true"></i>No encontramos tareas con estos filtros. Prueba otra palabra o limpia la búsqueda.</div>
            <div class="roles-paginacion" x-show="vista!=='lectura'&&filtrados.length"><p><span x-text="filtrados.length"></span> tareas · Página <span x-text="Math.min(pagina,paginas)"></span> de <span x-text="paginas"></span></p><div class="roles-acciones"><button type="button" class="ui-btn ui-btn-secondary" x-on:click="pagina=Math.max(1,pagina-1)" :disabled="pagina<=1">Anterior</button><button type="button" class="ui-btn ui-btn-secondary" x-on:click="pagina=Math.min(paginas,pagina+1)" :disabled="pagina>=paginas">Siguiente</button></div></div>
            @unless($puedeEditar)<p class="roles-aviso mt-4">Puedes consultar la matriz. Para cambiarla necesitas autorización de administración y asignación de permisos.</p>@endunless
            <x-plegable-institucional class="mt-4" compacto etiqueta="Cómo se interpreta este acceso" icono="ph-info" descripcion="Rol principal, consultas compatibles y límites de cada operación."><p class="ui-muted text-sm">Cada cuenta activa mantiene un único actor institucional. Los permisos habilitan tareas; el módulo comprueba también sus cursos, personas asignadas y ámbito de datos.</p>@if($legacyReadGrants->isNotEmpty())<p class="font-bold text-sm mt-3">Consultas que conserva este rol</p><ul class="roles-permisos mt-2">@foreach($legacyReadGrants as $p)<li class="roles-permiso text-xs"><i class="ph-duotone ph-eye" aria-hidden="true"></i>{{ \App\Support\PermissionLabel::describe($p)['label'] }}</li>@endforeach</ul>@endif</x-plegable-institucional>
        </section>
    </div>
    <section class="ui-card roles-trabajo" x-show="apartado==='vigencias'" x-cloak>@include('livewire.admin.roles.vigencias')</section>
    <section class="ui-card roles-trabajo" x-show="apartado==='cuenta'" x-cloak><div class="roles-titulo"><i class="ph-duotone ph-identification-card" aria-hidden="true"></i><div><p class="roles-kicker">Tu acceso personal</p><h2>{{ $cuenta['total'] }} permisos vigentes</h2><p class="ui-muted">Esta vista reúne los permisos de tus roles y los personales sin contarlos dos veces.</p></div></div>@foreach($permisosCuenta->groupBy('domain') as $area=>$tareas)<x-plegable-institucional class="mb-3" :etiqueta="$area" icono="ph-folder-open"><x-slot:contador>{{ $tareas->count() }} tareas</x-slot:contador><div class="roles-permisos">@foreach($tareas as $p)<div class="roles-permiso"><i class="ph-duotone ph-check-circle" aria-hidden="true"></i><span><strong>{{ $p['label'] }}</strong><small>{{ $p['scope_label'] }}</small></span></div>@endforeach</div></x-plegable-institucional>@endforeach</section>
    <section class="ui-card roles-trabajo" x-show="apartado==='solicitudes'" x-cloak>@include('livewire.admin.roles.solicitudes')</section>
    @if($puedePersonal)<section x-show="apartado==='usuarios'" x-cloak>@include('livewire.admin.roles.usuarios')</section>@endif
    @include('livewire.admin.roles.catalogo')
    @include('livewire.admin.roles.detalle-permiso')
    @include('livewire.admin.roles.solicitud')
    @include('livewire.admin.roles.acceso')
    @include('livewire.admin.roles.revision')
</div>
