<div class="roles-modal" x-show="accesoVisible" x-cloak x-transition.opacity.duration.150ms x-on:keydown.escape.window="if(accesoVisible)cerrarAcceso()" role="dialog" aria-modal="true" aria-labelledby="acceso-programado-titulo" x-trap.inert.noscroll="accesoVisible"><section class="roles-modal-panel roles-panel-acceso" x-show="accesoVisible" x-transition:enter="roles-transicion" x-transition:enter-start="roles-panel-oculto" x-transition:enter-end="roles-panel-visible" x-transition:leave="roles-transicion-salida" x-transition:leave-start="roles-panel-visible" x-transition:leave-end="roles-panel-oculto"><header class="roles-modal-cabecera"><div><p class="roles-kicker">Vigencia personal o de un grupo</p><h2 id="acceso-programado-titulo">Programar acceso</h2></div><button type="button" x-on:click="cerrarAcceso()" aria-label="Cerrar programación"><i class="ph-duotone ph-x" aria-hidden="true"></i></button></header><div class="roles-modal-cuerpo">@if($modalAcceso)
@unless($accesosDisponibles)<p class="roles-aviso">Puedes preparar los destinatarios y fechas. Guardar necesita la migración de gobernanza revisada.</p>@endunless
@if($analisisAcceso)
<section class="roles-resumen" aria-label="Revisión del acceso"><h3 class="font-bold">Revisa antes de autorizar</h3><strong>{{ $analisisAcceso['personas'] }} {{ $analisisAcceso['personas']===1?'cuenta':'cuentas' }} · {{ $analisisAcceso['permisos'] }} {{ $analisisAcceso['permisos']===1?'permiso':'permisos' }}</strong>
@foreach($analisisAcceso['destinatarios'] as $persona)<p>{{ $persona }}</p>@endforeach
@if($analisisAcceso['personas']>20)<p>Y {{ $analisisAcceso['personas']-20 }} cuentas más del grupo seleccionado.</p>@endif
@foreach($analisisAcceso['tareas'] as $tarea)<p class="roles-estado">{{ $tarea }}</p>@endforeach
<div class="roles-fechas-lectura"><p><i class="ph-duotone ph-door-open" aria-hidden="true"></i><span>Podrá empezar<strong>{{ $analisisAcceso['inicio'] }}</strong></span></p><p><i class="ph-duotone ph-clock-countdown" aria-hidden="true"></i><span>El acceso terminará<strong>{{ $analisisAcceso['fin'] }}</strong></span></p></div><p class="ui-muted text-sm">{{ $analisisAcceso['motivo'] }}</p>
@foreach($analisisAcceso['errores'] as $e)<p class="roles-error" role="alert">{{ $e }}</p>@endforeach @foreach($analisisAcceso['advertencias'] as $e)<p class="ui-muted">{{ $e }}</p>@endforeach
<p class="text-xs">{{ $analisisAcceso['valido']?'Al confirmar se guardará tu autorización y el aviso privado de cada destinatario. El acceso terminará automáticamente.':'Corrige los datos indicados antes de autorizar. La revisión conserva tus selecciones.' }}</p><button type="button" class="ui-btn ui-btn-secondary" x-on:click="editarRevisionAcceso=true" x-show="!editarRevisionAcceso&&$wire.analisisAcceso?.valido"><i class="ph-duotone ph-pencil-simple" aria-hidden="true"></i>Ajustar acceso</button></section>
@endif
<div class="roles-formulario" x-show="!$wire.analisisAcceso?.valido||editarRevisionAcceso"><div class="ancho"><h3 class="font-bold">1 · ¿Quién necesita el acceso?</h3><p class="ui-muted text-xs mt-1">Elige personas o incorpora las cuentas actuales de un rol. Las incorporaciones futuras no se incluyen automáticamente.</p></div>
<label class="ui-label ancho">Buscar personas<input type="search" class="ui-input" wire:model.live.debounce.400ms="buscarUsuario" placeholder="Escribe al menos dos letras del nombre"><span wire:loading wire:target="buscarUsuario" class="ui-muted text-xs">Buscando cuentas…</span></label>
<div class="ancho roles-permisos">@foreach($cuentas as $u)@php $nombre=trim(implode(' ',array_filter([$u->persona?->nom_per,$u->persona?->ape_pat_per,$u->persona?->ape_mat_per])))?:'Cuenta sin nombre registrado'; @endphp<label class="roles-permiso"><input type="checkbox" wire:model.live="usuariosAcceso" value="{{ $u->getKey() }}"><span><strong>{{ $nombre }}</strong><small>Cuenta activa</small></span></label>@endforeach</div>
@if($cuentas->count()===100)<p class="ui-muted text-xs ancho">Se muestran hasta 100 coincidencias. Afina la búsqueda para encontrar a una persona.</p>@endif
<x-selector-institucional modelo="rolDestinatarios" identificador="roles-grupo-destinatarios" etiqueta="Incorporar un grupo por rol" numerico :opciones="array_merge([['valor'=>null,'etiqueta'=>'Elegir un grupo']],$roles->map(fn($r)=>['valor'=>$r->id,'etiqueta'=>$r->name.' · '.$r->users_count.' cuentas'])->all())" /><button type="button" class="ui-btn ui-btn-secondary self-end" x-on:click="actuar('grupo',()=>$wire.agregarGrupo())" :disabled="!!proceso||!$wire.rolDestinatarios"><i class="ph-duotone ph-users-three" aria-hidden="true"></i>Incorporar cuentas del grupo</button>
<div class="ancho roles-resumen"><strong>{{ count($usuariosAcceso) }} {{ count($usuariosAcceso)===1?'cuenta seleccionada':'cuentas seleccionadas' }}</strong><button type="button" class="ui-btn ui-btn-secondary" wire:click="$set('usuariosAcceso',[])">Limpiar destinatarios</button></div>
<div class="ancho"><h3 class="font-bold">2 · ¿Qué podrán hacer?</h3><p class="ui-muted text-xs mt-1">Cada módulo conserva su ámbito de datos. La vigencia no reemplaza el rol institucional de la cuenta.</p></div>
<x-selector-institucional modelo="tipoAcceso" identificador="roles-tipo-acceso" etiqueta="Tipo de acceso" :opciones="[['valor'=>'PERMISOS','etiqueta'=>'Tareas concretas'],['valor'=>'ROL','etiqueta'=>'Rol complementario aprobado']]" />
@if($tipoAcceso==='ROL')<x-selector-institucional modelo="rolAcceso" identificador="roles-rol-complementario" etiqueta="Rol complementario" numerico :opciones="array_merge([['valor'=>null,'etiqueta'=>'Elegir rol aprobado']],$roles->reject(fn($r)=>in_array($r->name,\App\Models\Oficial\Sistema\Role::INSTITUTIONAL,true))->map(fn($r)=>['valor'=>$r->id,'etiqueta'=>$r->name])->values()->all())" />@else<div class="ancho" x-data="{busquedaPermiso:''}"><label class="ui-label">Buscar tareas<input class="ui-input" type="search" x-model="busquedaPermiso" placeholder="Permisos mínimos para el acceso temporal"></label><div class="roles-permisos mt-3">@foreach($permisos->filter(fn($p)=>($p['name']==='cursos.gestionar.global'||str_contains($p['name'],'.')&&!$p['critical']&&!str_ends_with($p['name'],'.global'))) as $p)<label class="roles-permiso" x-show="@js(mb_strtolower($p['label'])).includes(busquedaPermiso.toLowerCase())"><input type="checkbox" wire:model="permisosAcceso" value="{{ $p['name'] }}"><span><strong>{{ $p['label'] }}</strong><small>{{ $p['scope_label'] }}</small>@if($p['name']==='cursos.gestionar.global')<small>Solo Docentes · máximo 24 horas · no habilita otras ventanas administrativas.</small>@endif</span></label>@endforeach</div></div>@endif
<div class="ancho"><h3 class="font-bold">3 · ¿Durante cuánto tiempo?</h3><p class="ui-muted text-xs mt-1">El acceso se retirará al terminar el plazo. Los horarios corresponden a tu institución.</p><div class="roles-vistas mt-3" aria-label="Duración del acceso"><button type="button" x-on:click="vigenciaUnDia()" :aria-pressed="$wire.modoVigenciaAcceso==='DIA'" :disabled="!!proceso"><i class="ph-duotone ph-clock-countdown" aria-hidden="true"></i>Un día · 24 horas</button><button type="button" x-on:click="vigenciaPersonalizada()" :aria-pressed="$wire.modoVigenciaAcceso==='PERSONALIZADO'" :disabled="!!proceso"><i class="ph-duotone ph-calendar-dots" aria-hidden="true"></i>Personalizado</button></div></div>
<div class="ancho roles-resumen roles-plazo-fijo" x-show="$wire.modoVigenciaAcceso==='DIA'" x-transition.opacity.duration.180ms><strong><i class="ph-duotone ph-lock-simple" aria-hidden="true"></i>Un día completo · 24 horas</strong><div class="roles-fechas-lectura"><p><i class="ph-duotone ph-door-open" aria-hidden="true"></i><span>Podrá empezar<strong x-text="fechaVigencia('Inicio')"></strong></span></p><p><i class="ph-duotone ph-clock-countdown" aria-hidden="true"></i><span>El acceso terminará<strong x-text="fechaVigencia('Fin')"></strong></span></p></div><small class="ui-muted">Las fechas quedan fijas. Elige Personalizado si necesitas cambiarlas.</small></div>
<x-input-error for="modoVigenciaAcceso" />
@php
    $hoyAcceso=now()->setTimezone(config('seguridad-accesos.zona_horaria'))->toDateString();
    $minimoAcceso=max($hoyAcceso,$gestionActiva?->fii_gea?->toDateString()??$hoyAcceso);
    $maximoAcceso=$gestionActiva?->ffi_gea?->toDateString()??$hoyAcceso;
    $horasAcceso=collect(range(0,23))->map(fn($h)=>['valor'=>sprintf('%02d',$h),'etiqueta'=>sprintf('%02d h',$h)])->all();
    $minutosAcceso=collect(range(0,59))->map(fn($m)=>['valor'=>sprintf('%02d',$m),'etiqueta'=>sprintf('%02d min',$m)])->all();
@endphp
<div class="ancho roles-formulario" x-show="$wire.modoVigenciaAcceso==='PERSONALIZADO'" x-transition.opacity.duration.180ms>
@foreach(['Inicio'=>'Podrá empezar el','Fin'=>'El acceso terminará el'] as $extremo=>$etiqueta)
<div class="roles-vigencia-fecha">
    <x-calendario-institucional :modelo="'fecha'.$extremo.'Acceso'" :identificador="'roles-fecha-'.strtolower($extremo)" :etiqueta="$etiqueta" :minimo="$minimoAcceso" :maximo="$maximoAcceso" :inicio="$hoyAcceso" requerido />
    <div class="roles-hora"><x-selector-institucional :modelo="'hora'.$extremo.'Acceso'" :identificador="'roles-hora-'.strtolower($extremo)" etiqueta="Hora" :opciones="$horasAcceso" /><x-selector-institucional :modelo="'minuto'.$extremo.'Acceso'" :identificador="'roles-minuto-'.strtolower($extremo)" etiqueta="Minutos" :opciones="$minutosAcceso" /></div>
    <x-input-error :for="'hora'.$extremo.'Acceso'" /><x-input-error :for="'minuto'.$extremo.'Acceso'" /><x-input-error :for="strtolower($extremo)" />
</div>
@endforeach
</div>
<div class="ancho"><x-selector-institucional modelo="tipoMotivoAcceso" identificador="roles-motivo-acceso" etiqueta="Motivo de la autorización" :opciones="collect(\App\Support\SupportRolesInstitucionales::MOTIVOS['acceso'])->map(fn($texto,$valor)=>['valor'=>$valor,'etiqueta'=>$texto])->prepend(['valor'=>'','etiqueta'=>'Selecciona el motivo'])->values()->all()" /></div><label class="ui-label ancho" x-show="$wire.tipoMotivoAcceso==='OTRO'">Explica el otro motivo *<textarea class="ui-textarea" x-model="$wire.motivoAcceso" maxlength="2000" placeholder="Describe la necesidad concreta con palabras completas."></textarea></label><div class="roles-resumen ancho" role="status"><strong><i class="ph-duotone ph-shield-check" aria-hidden="true"></i> Support preventivo</strong><span x-text="errorAcceso||'Datos completos. Revisa la vigencia para comprobar disponibilidad y permisos.'"></span></div><x-input-error for="motivo" />
</div>
@foreach(['acceso','usuarios','permisos'] as $e)<x-input-error :for="$e" />@endforeach
@else<p role="status"><i class="ph-duotone ph-spinner-gap roles-giro" aria-hidden="true"></i>Preparando acceso…</p>@endif</div><footer class="roles-modal-pie"><button type="button" class="ui-btn ui-btn-secondary" x-on:click="cerrarAcceso()" :disabled="proceso==='guardar-acceso'">Cancelar</button><div class="roles-acciones"><button type="button" class="ui-btn ui-btn-secondary" x-on:click="revisarAcceso()" :disabled="!!proceso||!!errorAcceso"><i class="ph-duotone" :class="proceso==='analisis'?'ph-spinner-gap roles-giro':'ph-shield-check'" aria-hidden="true"></i><span x-text="proceso==='analisis'?'Revisando…':'Revisar vigencia'"></span></button><button type="button" class="ui-btn ui-btn-primary"  x-on:click="actuar('guardar-acceso',()=>$wire.guardarAcceso()).then(()=>{if(!$wire.modalAcceso)accesoVisible=false})" :disabled="!!proceso||@js(!$accesosDisponibles)||!$wire.analisisAcceso?.valido||editarRevisionAcceso||ultimaRevisionAcceso!==huellaAcceso||!!errorAcceso"><i class="ph-duotone" :class="proceso==='guardar-acceso'?'ph-spinner-gap roles-giro':'ph-calendar-check'" aria-hidden="true"></i><span x-text="proceso==='guardar-acceso'?'Programando…':'Confirmar acceso'"></span></button></div></footer></section></div>
