<section class="ui-card roles-trabajo" x-show="apartado==='catalogo'" x-cloak>
    <div class="roles-titulo"><i class="ph-duotone ph-stack" aria-hidden="true"></i><div><p class="roles-kicker">Base de datos · Catálogo completo</p><h2>{{ $catalogoCompleto->count() }} permisos registrados</h2><p class="ui-muted">Consulta ventanas y límites. Para cambiar asignaciones, elige un rol y activa Edición.</p></div>@include('livewire.admin.roles.modo-edicion')</div>
    <nav class="roles-catalogo-roles" aria-label="Rol para editar desde el catálogo">@foreach($roles as $r)<button type="button" class="roles-elegir" x-on:click="seleccionarRol({{ $r->id }})" :disabled="!!proceso" :aria-pressed="Number($wire.selectedRoleId)==={{ $r->id }}"><i class="ph-duotone {{ $r->icono }}" aria-hidden="true"></i><span><strong>{{ $r->name }}</strong><small>{{ $r->permissions_count }} permisos guardados</small></span></button>@endforeach</nav>
    <p class="roles-catalogo-contexto" role="status"><i class="ph-duotone" :class="$wire.edicionPermisos?'ph-lock-simple-open':'ph-eye'" aria-hidden="true"></i><span x-text="($wire.edicionPermisos?'Editando asignaciones de ':'Consultando asignaciones de ')+(rolActual?.nombre??'')"></span><strong><span x-text="seleccion.length"></span> seleccionados</strong></p>
    @include('livewire.admin.roles.cambios-permisos',['origenEdicion'=>'catalogo'])
    <div class="roles-filtros mt-4"><label class="ui-label">Buscar permiso o ventana<input type="search" class="ui-input" x-model.debounce.150ms="buscarCatalogo" placeholder="Nombre, identificador, rol o ruta…"></label>
        <x-selector-institucional enlace="rolCatalogo" identificador="catalogo-rol" etiqueta="Asignado al rol" :opciones="array_merge([['valor'=>'','etiqueta'=>'Todos los roles']],$roles->map(fn($r)=>['valor'=>$r->name,'etiqueta'=>$r->name])->all())" />
        <x-selector-institucional enlace="espacioCatalogo" identificador="catalogo-espacio" etiqueta="Espacio" :opciones="[['valor'=>'','etiqueta'=>'Toda la plataforma'],['valor'=>'administrativo','etiqueta'=>'Administración'],['valor'=>'aula','etiqueta'=>'Aula virtual']]" />
        <button type="button" class="ui-btn ui-btn-secondary" x-on:click="buscarCatalogo='';rolCatalogo='';espacioCatalogo=''" aria-label="Limpiar catálogo"><i class="ph-duotone ph-arrow-counter-clockwise" aria-hidden="true"></i></button>
    </div>
    <p class="ui-muted text-xs my-3"><span x-text="registrosCatalogo.length"></span> registros encontrados · Los cambios se aplican solo al guardar con un motivo.</p>
    <div class="roles-catalogo-lista"><template x-for="p in registrosCatalogo" :key="p.id"><article class="roles-catalogo-registro">
        <button type="button" class="roles-detalle-enlace" x-on:click="permisoDetalle=p"><i class="ph-duotone" :class="p.capacidad==='edicion'?'ph-pencil-simple':'ph-eye'" aria-hidden="true"></i><strong x-text="p.label"></strong><i class="ph-duotone ph-arrow-right" aria-hidden="true"></i></button>
        <code x-text="p.name"></code><small><span x-text="p.scope_label"></span> · Guard <span x-text="p.guard"></span> · Registro <span x-text="p.id"></span></small>
        <p class="ui-muted text-xs" x-text="p.roles.length?'Asignado a: '+p.roles.join(', '):'Sin asignación a roles'"></p>
        <label class="roles-catalogo-asignacion" :class="seleccion.includes(p.name)?'asignado':''"><input x-show="$wire.edicionPermisos&&!bloqueoAsignacion(p)" x-cloak type="checkbox" :aria-label="'Asignar '+p.label+' a '+rolActual?.nombre+' · '+p.name" :checked="seleccion.includes(p.name)" x-on:change="marcar(p.name)" :disabled="!$wire.edicionPermisos||!!proceso||!!bloqueoAsignacion(p)"><span x-text="seleccion.includes(p.name)?'Asignado a '+rolActual?.nombre:'Sin asignar a '+rolActual?.nombre"></span></label><small x-show="$wire.edicionPermisos&&bloqueoAsignacion(p)" x-text="bloqueoAsignacion(p)"></small>
        <template x-for="v in p.ventanas" :key="v.id"><div class="roles-ruta"><span><strong x-text="v.label+' · '+v.actor"></strong><code x-text="v.url"></code></span><template x-if="v.puede_ir"><a class="roles-ir" :href="v.url" target="_blank" rel="noopener" :aria-label="'Ir a '+v.label"><i class="ph-duotone ph-arrow-square-out" aria-hidden="true"></i>Ir</a></template></div></template>
        <small x-show="!p.ventanas.length" x-text="p.operaciones.length?'Operación dentro del módulo: revisa sus requisitos en Detalles.':'Sin entrada directa de menú vinculada.'"></small>
    </article></template></div><p class="roles-vacio" x-show="!registrosCatalogo.length">No hay registros con estos filtros.</p>
</section>
