<div class="roles-modal" x-show="solicitudVisible" x-cloak x-transition.opacity.duration.150ms x-on:keydown.escape.window="if(solicitudVisible)cerrarSolicitud()" role="dialog" aria-modal="true" aria-labelledby="solicitud-rol-titulo" x-trap.inert.noscroll="solicitudVisible">
<section class="roles-modal-panel"><header class="roles-modal-cabecera"><div><p class="roles-kicker">Autorización institucional</p><h2 id="solicitud-rol-titulo">Solicitar un rol complementario</h2></div><button type="button" x-on:click="cerrarSolicitud()" aria-label="Cerrar solicitud"><i class="ph-duotone ph-x" aria-hidden="true"></i></button></header>
<div class="roles-modal-cuerpo">@if($showRequestModal)
    <x-fases-institucionales :actual="$requestStep" :pasos="[1=>['titulo'=>'Necesidad','icono'=>'ph-users-three'],2=>['titulo'=>'Tareas','icono'=>'ph-list-checks'],3=>['titulo'=>'Carta y revisión','icono'=>'ph-file-pdf']]" />
    @unless($solicitudesDisponibles)<p class="roles-aviso">Puedes revisar y preparar los requisitos. Guardar se habilitará después de aplicar la migración de gobernanza.</p>@endunless
    @if($requestStep===1)<div class="roles-formulario">
        <label class="ui-label">Nombre del rol *<input class="ui-input" type="text" x-model="$wire.requestedName" maxlength="80" placeholder="Ej. Coordinación de informes" :aria-invalid="!!$wire.requestedName && !!errorTexto($wire.requestedName,4,true)"><p class="roles-error mt-2" role="status" x-show="$wire.requestedName" x-text="errorTexto($wire.requestedName,4,true)"></p><x-input-error for="requestedName" /></label>
        <x-selector-institucional modelo="requestedScope" identificador="roles-ambito-solicitud" etiqueta="Ámbito de trabajo" :opciones="collect(\App\Support\SupportRolesInstitucionales::AMBITOS)->map(fn($texto)=>['valor'=>$texto,'etiqueta'=>$texto])->prepend(['valor'=>'','etiqueta'=>'Selecciona el ámbito'])->values()->all()" />
        <div class="ancho"><x-selector-institucional modelo="tipoMotivoSolicitud" identificador="roles-motivo-solicitud" etiqueta="Motivo institucional" :opciones="collect(\App\Support\SupportRolesInstitucionales::MOTIVOS['solicitud'])->map(fn($texto,$valor)=>['valor'=>$valor,'etiqueta'=>$texto])->prepend(['valor'=>'','etiqueta'=>'Selecciona el motivo'])->values()->all()" /></div>
        <label class="ui-label ancho" x-show="$wire.tipoMotivoSolicitud==='OTRO'">Explica la otra necesidad *<textarea class="ui-textarea" x-model="$wire.institutionalReason" maxlength="2000" placeholder="Explica qué necesidad concreta no cubren los roles actuales."></textarea><p class="roles-error" x-show="$wire.institutionalReason" x-text="errorTexto($wire.institutionalReason,30)"></p><x-input-error for="institutionalReason" /></label>
        <div class="ancho"><x-selector-institucional modelo="responsabilidadesSolicitud" identificador="roles-responsabilidades-solicitud" etiqueta="Responsabilidades del rol" multiple :opciones="collect(\App\Support\SupportRolesInstitucionales::RESPONSABILIDADES)->map(fn($texto,$valor)=>['valor'=>$valor,'etiqueta'=>$texto])->values()->all()" /><x-input-error for="responsabilidades" /><p class="ui-muted text-xs mt-2">Puedes agregar o retirar responsabilidades; los permisos concretos se ajustan en la siguiente fase.</p></div>
        <div class="roles-resumen ancho" role="status"><strong><i class="ph-duotone ph-shield-check" aria-hidden="true"></i> Support preventivo</strong><span x-text="errorSolicitud?'Completa los campos indicados; avanzar se habilitará cuando estén correctos.':'Los datos están completos. Revisaremos compatibilidad y permisos en la siguiente fase.'"></span></div>
        <p class="ui-muted text-xs ancho">Un nuevo rol reúne tareas complementarias; la cuenta conserva su actor principal y el ámbito de sus datos.</p>
    </div>@elseif($requestStep===2)<div x-data="{buscarTarea:''}"><label class="ui-label">Buscar una tarea<input type="search" class="ui-input" x-model="buscarTarea" placeholder="Tareas mínimas para esta función"></label><div class="roles-permisos mt-3">@foreach($permisos as $p)<label class="roles-permiso" x-show="@js(mb_strtolower($p['label'])).includes(buscarTarea.toLowerCase())"><input type="checkbox" wire:model="requestedPermissions" value="{{ $p['name'] }}" @disabled($p['critical']||!str_contains($p['name'],'.')||str_ends_with($p['name'],'.global'))><span><strong>{{ $p['label'] }}</strong><small>{{ $p['scope_label'] }}</small>@if($p['critical']||!str_contains($p['name'],'.')||str_ends_with($p['name'],'.global'))<small>No delegable por este flujo</small>@endif</span></label>@endforeach</div><x-input-error for="requestedPermissions" /></div>
    @else<div class="roles-resumen"><strong>{{ $requestedName }}</strong><span>{{ count($requestedPermissions) }} tareas · {{ $requestedScope }}</span><span>{{ $justification }}</span></div>
        <p class="text-sm">La carta debe identificar el rol, autorizar su creación en la gestión activa e incluir la firma del Director vigente.</p>
        <p class="ui-muted text-sm">{{ $authority['status']==='ACTIVO'?'Director configurado: '.$authority['name']:$authority['message'] }}</p>
        <label class="ui-label">Carta firmada en PDF *<input type="file" wire:model="document" class="ui-input" accept="application/pdf,.pdf"><x-input-error for="document" /></label><p class="ui-muted text-xs">Hasta 8 MB y 60 páginas; texto legible, sin contraseña. Se conserva de forma privada.</p>
        <button type="button" class="ui-btn ui-btn-secondary" x-on:click="actuar('carta',()=>$wire.leerCarta())" :disabled="!!proceso"><i class="ph-duotone" :class="proceso==='carta'?'ph-spinner-gap roles-giro':'ph-scan'" aria-hidden="true"></i><span x-text="proceso==='carta'?'Leyendo carta…':'Revisar contenido del PDF'"></span></button>
        @if($lecturaDocumento)<div class="{{ $lecturaDocumento['coherente']?'ui-alert-success':'roles-aviso' }}"><strong>{{ $lecturaDocumento['coherente']?'Los datos del texto coinciden':'La carta necesita corrección' }}</strong>@foreach($lecturaDocumento['errores'] as $e)<p class="text-sm mt-2">{{ $e }}</p>@endforeach<p class="text-xs mt-3">La firma y autenticidad requieren revisión personal por otro administrador. Si el texto se rechaza al registrar, se conserva el intento con su evidencia.</p></div>@endif
        <label class="ui-label">Observaciones<textarea class="ui-textarea" wire:model="observations" maxlength="2000" placeholder="Información que ayudará a revisar la solicitud."></textarea></label>
    @endif
    @if($governanceResult&&$governanceResult['reasons'])<div role="alert" class="roles-aviso"><strong>Revisa la función y sus permisos</strong>@foreach($governanceResult['reasons'] as $e)<p class="mt-2">{{ $e }}</p>@endforeach</div>@endif
    <x-input-error for="role_request" />
@else<p role="status"><i class="ph-duotone ph-spinner-gap roles-giro" aria-hidden="true"></i>Preparando el formulario…</p>@endif</div>
<footer class="roles-modal-pie"><button type="button" class="ui-btn ui-btn-secondary" x-on:click="cerrarSolicitud()" :disabled="proceso==='guardar-solicitud'">Cancelar</button><div class="roles-acciones">@if($requestStep>1)<button type="button" class="ui-btn ui-btn-secondary" x-on:click="actuar('fase',()=>$wire.volverSolicitud())" :disabled="!!proceso">Volver</button>@endif @if($requestStep<3)<button type="button" class="ui-btn ui-btn-primary" x-on:click="actuar('fase',()=>$wire.nextRequestStep())" :disabled="!!proceso||($wire.requestStep===1?!!errorSolicitud:!$wire.requestedPermissions.length)"><i class="ph-duotone" :class="proceso==='fase'?'ph-spinner-gap roles-giro':'ph-arrow-right'" aria-hidden="true"></i><span x-text="proceso==='fase'?'Revisando…':'Continuar'"></span></button>@else<button type="button" class="ui-btn ui-btn-primary" x-on:click="actuar('guardar-solicitud',()=>$wire.submitRequest()).then(()=>{if(!$wire.showRequestModal)solicitudVisible=false})" :disabled="!!proceso||@js(!$solicitudesDisponibles)||!$wire.lecturaDocumento||!!errorSolicitud||!$wire.requestedPermissions.length"><i class="ph-duotone" :class="proceso==='guardar-solicitud'?'ph-spinner-gap roles-giro':'ph-paper-plane-tilt'" aria-hidden="true"></i><span x-text="proceso==='guardar-solicitud'?'Registrando…':'Registrar solicitud'"></span></button>@endif</div></footer></section></div>
