<div x-show="detalle" x-cloak class="personas-modal docentes-modal" role="dialog" aria-modal="true" aria-labelledby="asignatura-detalle-titulo" x-on:keydown.escape.window="if(detalle) cerrarDetalle()" x-trap.inert.noscroll="detalle">
    <div class="personas-modal-fondo" x-on:click="cerrarDetalle()" aria-hidden="true"></div>
    <section class="personas-modal-panel docentes-horario-panel" x-ref="detallePanel"><header class="personas-modal-cabecera"><div><p class="ui-kicker">Ficha de asignatura · Gestión {{ $gestion?->ani_gea }}</p><h2 class="ui-title text-xl font-bold mt-2" id="asignatura-detalle-titulo"><span x-show="procesando==='detalle'">Preparando la ficha</span><span x-show="procesando!=='detalle'">{{ $detalleAsignatura['nombre']??'Asignatura' }}</span></h2></div><button type="button" class="personas-accion" x-on:click="cerrarDetalle()" aria-label="Cerrar ficha de asignatura"><i class="ph-duotone ph-x" aria-hidden="true"></i></button></header>
    <div class="personas-modal-contenido"><div x-show="procesando==='detalle'" class="cursos-espera-revision" role="status"><i class="ph-duotone ph-spinner-gap cursos-giro" aria-hidden="true"></i><strong x-text="mensajeProceso"></strong></div><p x-show="errorProceso" class="ui-error" role="alert" x-text="errorProceso"></p>
        <div x-show="procesando!=='detalle'&&!errorProceso">
        @if($modalDetalle && $detalleAsignatura)
            @php $d=$detalleAsignatura; $campo=$d['campo']; @endphp
            <section class="ui-card-soft p-4 asignaturas-campo-{{ $campo['clave'] }}"><div class="asignaturas-herramientas"><span class="asignaturas-campo"><i class="ph-duotone {{ $campo['icono'] }}" aria-hidden="true"></i>{{ $campo['nombre'] }}</span><span class="{{ $d['estado']==='ACTIVO'?'ui-badge-success':'ui-badge-warning' }}">{{ $d['estado']==='ACTIVO'?'Vigente':'Retirada del catálogo' }}</span></div><p class="ui-title text-sm mt-3">{{ $d['sigla'] }} · {{ $d['horas'] }} horas académicas de referencia</p><p class="ui-muted text-sm mt-3">{{ $d['analisis']['descripcion']??'' }}</p></section>
            <section class="mt-5"><h3 class="ui-title font-bold">Docentes que la imparten en {{ $gestion?->ani_gea }}</h3><p class="ui-muted text-xs mt-2">Grados, paralelos y turnos según la planificación registrada.</p><div class="asignaturas-docentes mt-4">@forelse($d['docentes'] as $docente)<article class="ui-card-soft p-4"><h4><i class="ph-duotone ph-chalkboard-teacher" aria-hidden="true"></i>{{ $docente['nombre'] }}</h4><details class="mt-3"><summary class="ui-title text-sm cursor-pointer">{{ count($docente['grupos']) }} grupos · ver distribución</summary><ul>@foreach($docente['grupos'] as $grupo)<li><strong>{{ $grupo['curso'] }} · {{ $grupo['paralelo'] }}</strong><br>{{ $grupo['turno'] }} · {{ rtrim(rtrim(number_format($grupo['horas'],2,'.',''),'0'),'.') }} h académicas semanales</li>@endforeach</ul></details></article>@empty<div class="asignaturas-vacio"><i class="ph-duotone ph-chalkboard-teacher" aria-hidden="true"></i><strong>Sin docentes asignados en esta gestión</strong>La materia permanece en el catálogo para su planificación.</div>@endforelse</div></section>
            <x-plegable-institucional class="mt-5" etiqueta="Historial y motivos de cambio" descripcion="Consulta por qué se editó, retiró o recuperó esta materia." icono="ph-clock-counter-clockwise" :abierto="$d['estado']!=='ACTIVO'">
                <div class="asignaturas-cifras mt-0"><span><strong>{{ $d['uso']['planes'] }}</strong>planes históricos</span><span><strong>{{ $d['uso']['calificaciones'] }}</strong>notas conservadas</span><span><strong>{{ $d['uso']['horarios'] }}</strong>bloques históricos</span></div>
                <ol class="asignaturas-historial">@forelse($d['historial'] as $cambio)<li><strong class="ui-title text-sm">{{ match($cambio['accion']){'EDITAR_ASIGNATURA'=>'Edición','DESACTIVAR_ASIGNATURA'=>'Retiro del catálogo',default=>'Recuperación para planificación'} }}</strong><small class="block mt-1">{{ \Carbon\Carbon::parse($cambio['fecha'])->format('d/m/Y H:i') }}</small><p class="mt-2">{{ $cambio['motivo'] }}</p>@if(!$cambio['tiene_motivo'])<small>Registro anterior sin motivo detallado.</small>@endif</li>@empty<li><p>No hay cambios registrados en la bitácora para esta materia.</p></li>@endforelse</ol>
            </x-plegable-institucional>
            <p class="ui-muted text-xs mt-4">{{ $d['recomendacion'] }}</p>
        @endif
        </div>
    </div><footer class="personas-modal-pie"><p class="ui-muted text-xs">Las notas y la historia académica se conservan.</p><button type="button" class="ui-btn ui-btn-secondary" x-on:click="cerrarDetalle()">Cerrar</button></footer></section>
</div>
