<header class="ui-card asignaturas-cabecera">
    <div><p class="ui-kicker">Catálogo académico</p><h1 class="ui-title text-2xl font-bold mt-2">Gestión de Asignaturas</h1><p class="ui-muted text-sm mt-2">Consulta materias, docentes y su distribución por campo educativo.</p></div>
    <div class="asignaturas-acciones"><button type="button" class="ui-btn ui-btn-primary" x-on:click="abrir('crear',null,$event.currentTarget)" :disabled="!!procesando"><i class="ph-duotone ph-plus" aria-hidden="true"></i>Registrar asignatura</button><button type="button" class="ui-btn ui-btn-secondary" x-on:click="abrir('catalogo',null,$event.currentTarget)" :disabled="!!procesando"><i class="ph-duotone ph-books" aria-hidden="true"></i>Materias por incorporar <span class="ui-badge-info">{{ count($catalogoInteligente) }}</span></button></div>
</header>
<section class="ui-card p-5" aria-label="Indicadores de asignaturas">
    <div class="asignaturas-herramientas"><div><p class="ui-kicker">Panorama curricular</p><h2 class="ui-title font-bold mt-2">Así se distribuyen las materias</h2></div><div class="asignaturas-gestion"><x-selector-institucional modelo="gestionFiltro" identificador="asignaturas-gestion" etiqueta="Consultar gestión" :opciones="$gestiones->map(fn($g)=>['valor'=>$g->cod_gea,'etiqueta'=>'Gestión '.$g->ani_gea.($g->est_gea==='ACTIVO'?' · En curso':'')])->all()" /></div></div>
    <div class="asignaturas-graficos">
        <section><h3 class="ui-title text-sm font-bold">Campos educativos</h3><p class="ui-muted text-xs mt-2">Todo el catálogo. Selecciona un campo para filtrar.</p>
            <div x-data="{grafico:'barras'}"><div class="flex flex-wrap gap-2 mt-3" role="group" aria-label="Tipo de gráfico"><button type="button" class="ui-btn ui-btn-secondary" x-on:click="grafico='barras'" :aria-pressed="grafico==='barras'">Distribución</button><button type="button" class="ui-btn ui-btn-secondary" x-on:click="grafico='mapa'" :aria-pressed="grafico==='mapa'">Mapa curricular</button><button type="button" class="ui-btn ui-btn-secondary" x-on:click="grafico='anillo'" :aria-pressed="grafico==='anillo'">Anillo</button></div><div x-show="grafico==='barras'" class="especialidades-distribucion mt-4" x-transition.opacity>
@foreach($campos as $clave=>$campo)
@php $cantidad=$materias->filter(fn($m)=>$m->campo_educativo['clave']===$clave)->count(); @endphp
@if($cantidad)
<button type="button" class="especialidades-barra asignaturas-campo-{{ $clave }}" style="--grafico-color:var(--campo-color)" x-on:click="filtrarCampo(@js($clave))" aria-pressed="{{ $campoEducativo===$clave?'true':'false' }}"><span><i class="ph-duotone {{ $campo['icono'] }}" aria-hidden="true"></i> {{ $campo['nombre'] }}</span><strong>{{ $cantidad }}</strong><span class="especialidades-pista"><span style="--proporcion:{{ $cantidad/max(1,$materias->count()) }}"></span></span><small>{{ round($cantidad/max(1,$materias->count())*100) }}% del catálogo</small></button>
@endif
@endforeach
</div><div x-show="grafico==='mapa'" class="curricular-mapa mt-4">@foreach($campos as $clave=>$campo)@php $cantidadCampo=$materias->filter(fn($m)=>$m->campo_educativo['clave']===$clave)->count(); @endphp@if($cantidadCampo)<button type="button" class="ui-card-soft asignaturas-campo-{{ $clave }}" x-on:click="filtrarCampo(@js($clave))" aria-pressed="{{ $campoEducativo===$clave?'true':'false' }}"><i class="ph-duotone {{ $campo['icono'] }}" aria-hidden="true"></i><strong>{{ $cantidadCampo }}</strong><span>{{ $campo['nombre'] }}</span><small>{{ round($cantidadCampo/max(1,$materias->count())*100) }}% del catálogo</small></button>@endif @endforeach</div><div class="asignaturas-distribucion" x-show="grafico==='anillo'">
                @php $desfase=0; $total=max(1,$materias->count()); @endphp
                <svg class="asignaturas-anillo" viewBox="0 0 160 160" role="group" aria-label="Asignaturas por campo educativo">
                    <circle cx="80" cy="80" r="59" fill="none" stroke="var(--ui-border)" stroke-width="18" />
                    @foreach($campos as $clave=>$campo)
                        @php $n=$materias->filter(fn($m)=>$m->campo_educativo['clave']===$clave)->count(); $porcion=$n/$total*100; @endphp
                        @if($n)<circle class="asignaturas-campo-{{ $clave }}" cx="80" cy="80" r="59" pathLength="100" fill="none" stroke="var(--campo-color)" stroke-width="18" stroke-dasharray="{{ $porcion }} {{ 100-$porcion }}" stroke-dashoffset="{{ -$desfase }}" transform="rotate(-90 80 80)" role="button" tabindex="0" aria-label="{{ $campo['nombre'] }}: {{ $n }} asignaturas" aria-pressed="{{ $campoEducativo===$clave?'true':'false' }}" x-on:click="filtrarCampo(@js($clave))" x-on:keydown.enter.prevent="filtrarCampo(@js($clave))" x-on:keydown.space.prevent="filtrarCampo(@js($clave))"><title>{{ $campo['nombre'] }}: {{ $n }}</title></circle>@endif
                        @php $desfase+=$porcion; @endphp
                    @endforeach
                    <text x="80" y="77" text-anchor="middle" fill="var(--ui-text)" font-size="27" font-weight="700">{{ $resumen['total'] }}</text><text x="80" y="96" text-anchor="middle" fill="var(--ui-muted)" font-size="10">asignaturas</text>
                </svg>
                <div class="asignaturas-leyenda">@foreach($campos as $clave=>$campo)@php $n=$materias->filter(fn($m)=>$m->campo_educativo['clave']===$clave)->count(); @endphp @if($n)<button type="button" class="asignaturas-campo-{{ $clave }}" x-on:click="filtrarCampo(@js($clave))" aria-pressed="{{ $campoEducativo===$clave?'true':'false' }}" :disabled="!!procesando"><i class="ph-duotone {{ $campo['icono'] }}" aria-hidden="true"></i><span>{{ $campo['nombre'] }}</span><strong>{{ $n }}</strong></button>@endif @endforeach</div>
            </div></div>
        </section>
        <section x-data="{comparativa:'docentes'}"><div class="asignaturas-herramientas"><h3 class="ui-title text-sm font-bold">Presencia en gestión {{ $gestion?->ani_gea }}</h3><div class="personas-tipos-vista" role="group" aria-label="Indicador de comparación"><button type="button" x-on:click="comparativa='docentes'" :aria-pressed="comparativa==='docentes'">Docentes</button><button type="button" x-on:click="comparativa='cursos'" :aria-pressed="comparativa==='cursos'">Grados</button></div></div><p class="ui-muted text-xs mt-2">Asignaciones vigentes. Selecciona una materia para ver quién la imparte.</p>
            @foreach(['docentes'=>'docentes_actuales','cursos'=>'cursos_actuales'] as $vistaGrafico=>$atributo)
                @php $ranking=$materias->sortByDesc($atributo)->take(6); $maximo=max(1,$materias->max($atributo)); @endphp
                <div class="asignaturas-ranking" x-show="comparativa===@js($vistaGrafico)">@foreach($ranking as $m)<button type="button" class="asignaturas-campo-{{ $m->campo_educativo['clave'] }}" x-on:click="consultar(@js($m->cod_asi),$event.currentTarget)" :disabled="!!procesando" aria-label="Ver {{ $m->nom_asi }}, {{ $m->$atributo }} {{ $vistaGrafico==='docentes'?'docentes':'grados' }}"><span>{{ $m->nom_asi }}</span><strong>{{ $m->$atributo }}</strong><i style="width:{{ $m->$atributo/$maximo*100 }}%" aria-hidden="true"></i></button>@endforeach</div>
            @endforeach
            @if(!$materias->sum('planes_actuales'))<p class="ui-muted text-xs mt-3">Esta gestión aún no tiene asignaciones de materias.</p>@endif
        </section>
    </div>
    <div class="asignaturas-cifras"><span><strong>{{ $resumen['activas'] }}</strong>Vigentes</span><span><strong>{{ $resumen['inactivas'] }}</strong>Retiradas del catálogo</span><span><strong>{{ $resumen['con_uso'] }}</strong>Con planificación en {{ $gestion?->ani_gea }}</span><span><strong>{{ $resumen['sin_uso'] }}</strong>Sin planificación en {{ $gestion?->ani_gea }}</span><span><strong>{{ rtrim(rtrim(number_format((float)$resumen['horas'],2,'.',''),'0'),'.') }}</strong>Horas académicas del catálogo</span></div>
</section>
<section class="ui-card p-4" aria-label="Filtros del catálogo">
    <div class="asignaturas-filtros"><div><label class="ui-label" for="asignaturas-buscar">Buscar materia</label><input id="asignaturas-buscar" class="ui-input" wire:model.live.debounce.400ms="search" placeholder="Nombre o sigla de la asignatura"></div><x-selector-institucional modelo="campoEducativo" identificador="asignaturas-campo" etiqueta="Campo educativo" :opciones="array_merge([['valor'=>'','etiqueta'=>'Todos los campos']],collect($campos)->map(fn($c,$id)=>['valor'=>$id,'etiqueta'=>$c['nombre']])->values()->all())" /></div>
    <x-plegable-institucional class="mt-4" compacto etiqueta="Afinar la consulta" descripcion="Vigencia y planificación de la gestión seleccionada." icono="ph-sliders-horizontal"><div class="asignaturas-filtros-extra"><x-selector-institucional modelo="estado" identificador="asignaturas-vigencia" etiqueta="Vigencia del catálogo" :opciones="[['valor'=>'','etiqueta'=>'Todas las materias'],['valor'=>'ACTIVO','etiqueta'=>'Vigentes'],['valor'=>'INACTIVO','etiqueta'=>'Retiradas del catálogo']]" /><x-selector-institucional modelo="usoAcademico" identificador="asignaturas-planificacion" etiqueta="Planificación" :opciones="[['valor'=>'','etiqueta'=>'Todas'],['valor'=>'CON_USO','etiqueta'=>'Con planificación en esta gestión'],['valor'=>'SIN_USO','etiqueta'=>'Sin planificación en esta gestión'],['valor'=>'CON_CALIFICACIONES','etiqueta'=>'Con notas en su historial']]" /><x-selector-institucional modelo="filtroHoras" identificador="asignaturas-horas" etiqueta="Carga de referencia" :opciones="[['valor'=>'','etiqueta'=>'Todas'],['valor'=>'hasta2','etiqueta'=>'Hasta 2 períodos'],['valor'=>'3a4','etiqueta'=>'3 a 4 períodos'],['valor'=>'5mas','etiqueta'=>'5 períodos o más']]" /><x-selector-institucional modelo="filtroDocentes" identificador="asignaturas-docentes" etiqueta="Docentes en esta gestión" :opciones="[['valor'=>'','etiqueta'=>'Todos'],['valor'=>'ninguno','etiqueta'=>'Sin docentes'],['valor'=>'uno','etiqueta'=>'Un docente'],['valor'=>'varios','etiqueta'=>'Varios docentes']]" /><x-selector-institucional modelo="filtroClases" identificador="asignaturas-clases" etiqueta="Clases registradas" :opciones="[['valor'=>'','etiqueta'=>'Todas'],['valor'=>'con','etiqueta'=>'Con clases'],['valor'=>'sin','etiqueta'=>'Sin clases']]" /><button type="button" class="ui-btn ui-btn-secondary" wire:click="limpiarFiltros" wire:loading.attr="disabled"><i class="ph-duotone ph-arrow-counter-clockwise" aria-hidden="true"></i>Limpiar</button></div></x-plegable-institucional>
</section>
<section class="ui-card p-4" x-ref="resultados" aria-label="Catálogo de asignaturas">
    <div class="asignaturas-herramientas mb-4"><div><h2 class="ui-title font-bold">Materias del catálogo</h2><p class="ui-muted text-xs mt-2">Docentes y grados de gestión {{ $gestion?->ani_gea }}. El historial se conserva.</p></div><div class="personas-tipos-vista" role="group" aria-label="Vista de las asignaturas"><button type="button" x-on:click="vista='tabla'" :aria-pressed="vista==='tabla'&&!movil"><i class="ph-duotone ph-list-bullets" aria-hidden="true"></i>Lista</button><button type="button" x-on:click="vista='tarjetas'" :aria-pressed="vista==='tarjetas'||(movil&&vista==='tabla')"><i class="ph-duotone ph-squares-four" aria-hidden="true"></i>Tarjetas</button><button type="button" x-on:click="vista='campos'" :aria-pressed="vista==='campos'"><i class="ph-duotone ph-stack" aria-hidden="true"></i>Por campo</button></div></div>
    @if($asignaturas->isEmpty())<div class="asignaturas-vacio"><i class="ph-duotone ph-magnifying-glass" aria-hidden="true"></i><strong>No hay materias para esta consulta</strong><p>Prueba otro campo educativo o limpia los filtros.</p></div>@else
    <div class="asignaturas-tabla-wrap" x-show="vista==='tabla'&&!movil"><table class="asignaturas-tabla"><caption class="sr-only">Asignaturas y docentes en gestión {{ $gestion?->ani_gea }}</caption><thead><tr><th scope="col"><button type="button" wire:click="ordenarPor('nom_asi')" wire:loading.attr="disabled">Asignatura <i class="ph-duotone ph-arrows-down-up" aria-hidden="true"></i></button></th><th scope="col">En esta gestión</th><th scope="col">Consulta y cambios</th></tr></thead><tbody>@foreach($asignaturas as $m)<tr class="asignaturas-campo-{{ $m->campo_educativo['clave'] }}" wire:key="asignatura-lista-{{ $m->cod_asi }}"><th scope="row">@include('livewire.admin.asignaturas.identidad',['numero'=>$asignaturas->firstItem()+$loop->index])</th><td>@include('livewire.admin.asignaturas.datos')</td><td>@include('livewire.admin.asignaturas.acciones')</td></tr>@endforeach</tbody></table></div>
    <div class="asignaturas-tarjetas" x-show="vista==='tarjetas'||(movil&&vista==='tabla')">@foreach($asignaturas as $m)@include('livewire.admin.asignaturas.tarjeta',['numero'=>$asignaturas->firstItem()+$loop->index,'claveVista'=>'tarjetas'])@endforeach</div>
    <div class="asignaturas-grupos" x-show="vista==='campos'">@foreach(collect($asignaturas->items())->groupBy(fn($m)=>$m->campo_educativo['clave']) as $clave=>$grupo)<section class="asignaturas-campo-{{ $clave }}"><h3><i class="ph-duotone {{ $campos[$clave]['icono'] }}" aria-hidden="true"></i>{{ $campos[$clave]['nombre'] }} · {{ $grupo->count() }} en esta página</h3><div class="asignaturas-tarjetas">@foreach($grupo as $m)@include('livewire.admin.asignaturas.tarjeta',['numero'=>null,'claveVista'=>'campos'])@endforeach</div></section>@endforeach</div>
    @endif
</section>
<x-paginacion-institucional :paginador="$asignaturas" :elementos="[$asignaturas->getUrlRange(1,$asignaturas->lastPage())]" :cantidad="$perPage" entidad="asignaturas" singular="asignatura" />
