<section class="ui-card estudiantes-filtros" aria-label="Buscar y filtrar estudiantes">
    <div class="estudiantes-filtros-grid"><div><label for="estudiantes-buscar" class="ui-label">Buscar estudiante</label><input id="estudiantes-buscar" class="ui-input mt-2" type="search" wire:model.live.debounce.350ms="search" placeholder="Nombre, apellido, RUDE o CI" autocomplete="off" /></div>
    <x-selector-institucional modelo="filtroCurso" identificador="estudiantes-curso" etiqueta="Curso" :opciones="collect([['valor'=>'','etiqueta'=>'Todos los cursos']])->merge($cursos->map(fn($c)=>['valor'=>$c->cod_cur,'etiqueta'=>$c->nom_cur]))->all()" />
    <x-selector-institucional modelo="filtroParalelo" identificador="estudiantes-paralelo" etiqueta="Paralelo" :opciones="collect([['valor'=>'','etiqueta'=>'Todos los paralelos']])->merge($paralelos->map(fn($p)=>['valor'=>$p->cod_par,'etiqueta'=>$p->nom_par]))->all()" />
    <x-selector-institucional modelo="filtroEspecialidad" identificador="estudiantes-especialidad" etiqueta="Especialidad" :opciones="collect([['valor'=>'','etiqueta'=>'Todas las especialidades'],['valor'=>'SIN_ESPECIALIDAD','etiqueta'=>'Sin especialidad registrada']])->merge($especialidades->map(fn($e)=>['valor'=>$e->cod_esp,'etiqueta'=>$e->nom_esp]))->all()" /></div>
    <div x-show="masFiltros" x-cloak x-transition.opacity class="estudiantes-filtros-extra">
        <x-selector-institucional modelo="filtroInscripcion" identificador="estudiantes-inscripcion" etiqueta="Inscripción en la gestión" :opciones="[['valor'=>'','etiqueta'=>'Todas'],['valor'=>'INSCRITO','etiqueta'=>'Inscripción activa'],['valor'=>'SIN_INSCRIPCION','etiqueta'=>'Sin inscripción'],['valor'=>'PENDIENTE','etiqueta'=>'Otras situaciones de inscripción']]" />
        <x-selector-institucional modelo="filtroEstado" identificador="estudiantes-estado" etiqueta="Situación académica" :opciones="collect([['valor'=>'','etiqueta'=>'Todas las situaciones']])->merge(collect($estadosEstudiante)->map(fn($e)=>['valor'=>$e,'etiqueta'=>$this->estadoEstudianteLabel($e)]))->all()" />
        <x-selector-institucional modelo="filtroVinculacion" identificador="estudiantes-vinculacion" etiqueta="Vinculación" :opciones="collect([['valor'=>'','etiqueta'=>'Todas las vinculaciones']])->merge($tiposVinculacion->map(fn($t)=>['valor'=>$t->cod_tve,'etiqueta'=>$t->nom_tve]))->all()" />
        <x-selector-institucional modelo="filtroProcedencia" identificador="estudiantes-procedencia" etiqueta="Institución de procedencia" :opciones="collect([['valor'=>'','etiqueta'=>'Todas las procedencias']])->merge($institucionesProcedencia->map(fn($i)=>['valor'=>$i->cod_ipe,'etiqueta'=>mb_strtoupper($i->nom_ipe)]))->all()" />
        <x-selector-institucional modelo="orden" identificador="estudiantes-orden" etiqueta="Ordenar por" :opciones="[['valor'=>'nombre','etiqueta'=>'Apellidos · A → Z'],['valor'=>'nombre_desc','etiqueta'=>'Apellidos · Z → A'],['valor'=>'recientes','etiqueta'=>'Registros más recientes'],['valor'=>'rude','etiqueta'=>'RUDE']]" />
    </div>
    <div class="estudiantes-filtros-pie"><div class="personas-tipos-vista estudiantes-vistas" role="group" aria-label="Vistas de estudiantes">@foreach([['cursos','squares-four','Cursos'],['especialidades','graduation-cap','Especialidades'],['tarjetas','identification-card','Tarjetas'],['lista','list-bullets','Lista'],['todos','table','Tabla']] as [$valor,$icono,$etiqueta])<button type="button" x-on:click="vista=@js($valor)" :aria-pressed="vista===@js($valor)"><i class="ph-duotone ph-{{ $icono }}" aria-hidden="true"></i>{{ $etiqueta }}</button>@endforeach</div><div class="personas-acciones"><button type="button" class="ui-btn ui-btn-secondary" x-on:click="masFiltros=!masFiltros" :aria-expanded="masFiltros"><i class="ph-duotone ph-funnel" aria-hidden="true"></i>Más filtros y orden</button><button type="button" class="ui-btn ui-btn-secondary" wire:click="limpiarFiltros"><i class="ph-duotone ph-arrow-counter-clockwise" aria-hidden="true"></i>Limpiar</button></div></div>
    @if($search || $filtroCurso || $filtroParalelo || $filtroEspecialidad || $filtroEstado || $filtroInscripcion || $filtroVinculacion || $filtroProcedencia)<p class="ui-muted text-xs mt-3" role="status">Filtros aplicados. Las vistas y los indicadores muestran la misma selección.</p>@endif
</section>
