@php($cerrar=$modalEditar?'cerrarModalEditar':'cerrarModalRegistrar')
@php($personaSeleccionada=$modalEditar?$estudianteDetalle?->persona:$personasDisponibles->firstWhere('cod_per',$formEstudiante['cod_per']))
@teleport('body')
<div class="personas-modal" role="dialog" aria-modal="true" aria-labelledby="estudiante-form-titulo" x-data="{rud:$wire.entangle('formEstudiante.rud_est').live,tocado:false}" x-trap.inert.noscroll="true" x-on:keydown.escape.window="$wire.{{ $cerrar }}()"><div class="personas-modal-fondo" wire:click="{{ $cerrar }}" aria-hidden="true"></div><form wire:submit="{{ $modalEditar?'actualizarEstudiante':'guardarEstudiante' }}" class="personas-modal-panel estudiantes-modal-panel"><header class="personas-modal-cabecera"><div><p class="ui-kicker">Registro académico</p><h2 id="estudiante-form-titulo" class="ui-title text-xl font-bold mt-1">{{ $modalEditar?'Editar datos del estudiante':'Vincular una persona como estudiante' }}</h2></div><button class="personas-accion" type="button" wire:click="{{ $cerrar }}" aria-label="Cerrar formulario de estudiante"><i class="ph-duotone ph-x" aria-hidden="true"></i></button></header><div class="personas-modal-contenido"><p class="ui-muted text-sm mb-5">La identidad y el contacto pertenecen a Personas. Aquí se completa el registro académico; el curso y paralelo se asignan en la inscripción.</p><div class="estudiantes-form-layout"><div class="estudiantes-form-campos">
@if($modalEditar)<div class="ui-card-soft p-4"><p class="ui-label">Persona vinculada</p><strong class="ui-title block mt-2">{{ $this->nombreCompleto($personaSeleccionada) }}</strong></div>@else<x-selector-institucional modelo="formEstudiante.cod_per" identificador="estudiante-persona" etiqueta="Persona registrada" :requerido="true" :opciones="collect([['valor'=>'','etiqueta'=>'Selecciona una persona']])->merge($personasDisponibles->map(fn($p)=>['valor'=>$p->cod_per,'etiqueta'=>$this->nombreCompleto($p).' · '.$this->ciCompleto($p)]))->all()" />@if($personasDisponibles->isEmpty())<p class="ui-alert-warning">No hay personas disponibles para vincular. Registra primero la identidad en Personas.</p>@endif @endif
<div><label class="ui-label" for="estudiante-rude">RUDE *</label><input id="estudiante-rude" class="ui-input mt-2" x-model="rud" x-on:blur="tocado=true" maxlength="30" minlength="5" required autocomplete="off" :aria-invalid="tocado && (rud.trim().length<5 || rud.trim().length>30)" /><p class="ui-error text-xs mt-2" x-show="tocado && (rud.trim().length<5 || rud.trim().length>30)" x-cloak>El RUDE debe tener entre 5 y 30 caracteres.</p><x-input-error for="formEstudiante.rud_est" /></div>
<x-selector-institucional modelo="formEstudiante.cod_tve" identificador="estudiante-vinculacion" etiqueta="Tipo de vinculación" :requerido="true" :opciones="collect([['valor'=>'','etiqueta'=>'Selecciona la vinculación']])->merge($tiposVinculacion->map(fn($t)=>['valor'=>$t->cod_tve,'etiqueta'=>$t->nom_tve]))->all()" />
<x-selector-institucional modelo="formEstudiante.cod_ipe" identificador="estudiante-procedencia" etiqueta="Institución de procedencia" :requerido="true" :opciones="collect([['valor'=>'','etiqueta'=>'Selecciona la procedencia']])->merge($institucionesProcedencia->map(fn($i)=>['valor'=>$i->cod_ipe,'etiqueta'=>mb_strtoupper($i->nom_ipe)]))->all()" />@if($institucionesProcedencia->isEmpty())<p class="ui-alert-warning text-sm">No hay instituciones de procedencia registradas. Este campo obligatorio necesita una opción del catálogo antes de guardar.</p>@endif
<x-selector-institucional modelo="formEstudiante.cod_esp" identificador="estudiante-especialidad" etiqueta="Especialidad registrada" :opciones="collect([['valor'=>'','etiqueta'=>'Sin especialidad registrada']])->merge($especialidades->map(fn($e)=>['valor'=>$e->cod_esp,'etiqueta'=>$e->nom_esp]))->all()" />
<x-selector-institucional modelo="formEstudiante.est_est" identificador="estudiante-situacion" etiqueta="Situación académica" :requerido="true" :opciones="collect($estadosEstudiante)->map(fn($e)=>['valor'=>$e,'etiqueta'=>$this->estadoEstudianteLabel($e)])->all()" /></div><aside class="ui-card-soft estudiantes-preview"><p class="ui-kicker">Vista previa del registro</p><h3 class="ui-title font-bold mt-3">{{ $personaSeleccionada ? $this->nombreCompleto($personaSeleccionada) : 'Selecciona una persona' }}</h3><dl class="estudiantes-ficha-datos mt-4"><div><dt>RUDE</dt><dd x-text="rud || 'Pendiente'"></dd></div><div><dt>Especialidad</dt><dd>{{ $especialidades->firstWhere('cod_esp',$formEstudiante['cod_esp'])?->nom_esp ?: 'Sin especialidad registrada' }}</dd></div></dl><p class="ui-muted text-xs mt-4">Después podrás registrar su inscripción en la gestión, curso y paralelo correspondientes.</p></aside></div></div><footer class="personas-modal-pie"><p class="ui-muted text-xs w-full">@if(!$this->puedeGuardarEstudiante())Completa persona, RUDE válido, vinculación y procedencia para guardar.@elseRevisa el registro antes de confirmar.@endif</p><button type="button" class="ui-btn ui-btn-secondary" wire:click="{{ $cerrar }}">Cancelar</button><button type="submit" class="ui-btn ui-btn-primary" @disabled(!$this->puedeGuardarEstudiante()) wire:loading.attr="disabled" wire:target="guardarEstudiante,actualizarEstudiante">{{ $modalEditar?'Guardar cambios':'Registrar estudiante' }}</button></footer></form></div>
@endteleport
