<div class="estudiantes-pagina" wire:ignore.self x-data="estudiantesInstitucionalPage(@js($indicadoresEstudiantes),$wire.entangle('vistaActiva').live)" x-on:indicadores-estudiantes.window="datos=$event.detail.datos" x-on:success-general.window="avisar('success',$event.detail.mensaje)" x-on:error-general.window="avisar('warning',$event.detail.mensaje)">
    <header class="ui-card estudiantes-cabecera"><div class="estudiantes-cabecera-identidad"><span class="estudiantes-cabecera-icono"><i class="ph-duotone ph-student" aria-hidden="true"></i></span><div><p class="ui-kicker">Comunidad estudiantil · Gestión {{ $nombreGestionActual }}</p><h1 class="ui-title text-2xl font-extrabold mt-2">Estudiantes</h1><p class="ui-muted text-sm mt-2">Encuentra a cada estudiante por su curso, paralelo o especialidad. Consulta su ficha y trayectoria en un mismo lugar.</p></div></div><div class="personas-acciones"><button class="ui-btn ui-btn-secondary" type="button" x-on:click="indicadores=!indicadores" :aria-expanded="indicadores"><i class="ph-duotone ph-chart-pie-slice" aria-hidden="true"></i>Indicadores</button>@can('Inscripciones')<a href="{{ route($rutaInscripciones) }}" class="ui-btn ui-btn-primary"><i class="ph-duotone ph-user-circle-plus" aria-hidden="true"></i>Inscribir estudiante</a>@endcan</div></header>
    <section class="ui-card estudiantes-cifras" aria-label="Resumen de estudiantes en la institución">@foreach([['student',$totalEstudiantes,'Estudiantes registrados'],['check-circle',$inscritosGestionActual,'Inscritos en '.$nombreGestionActual],['user-circle-plus',$sinInscripcionGestionActual,'Sin inscripción en la gestión'],['graduation-cap',$totalEspecialidadesConEstudiantes,'Especialidades con estudiantes']] as [$icono,$valor,$etiqueta])<div><i class="ph-duotone ph-{{ $icono }}" aria-hidden="true"></i><strong>{{ $valor }}</strong><span>{{ $etiqueta }}</span></div>@endforeach</section>
    @include('livewire.admin.estudiantes.indicadores')
    @include('livewire.admin.estudiantes.filtros')
    <div x-ref="resultados" class="estudiantes-resultados"><x-estado-carga-institucional objetivo="search,filtroCurso,filtroParalelo,filtroEspecialidad,filtroEstado,filtroInscripcion,filtroVinculacion,filtroProcedencia,orden,perPage,gotoPage,limpiarFiltros,seleccionarCursoCarpeta,seleccionarEspecialidadCarpeta,filtrarCursoParalelo" mensaje="Actualizando estudiantes…" />
        @include('livewire.admin.estudiantes.grupos')
        <div class="estudiantes-resultados-titulo" :aria-busy="cargandoGrupo"><div><h2 class="ui-title font-bold" x-ref="tituloResultados" tabindex="-1">{{ $filtroCurso ? ($cursos->firstWhere('cod_cur',$filtroCurso)?->nom_cur ?? 'Curso seleccionado') : ($filtroEspecialidad ? ($filtroEspecialidad==='SIN_ESPECIALIDAD'?'Sin especialidad registrada':($especialidades->firstWhere('cod_esp',$filtroEspecialidad)?->nom_esp ?? 'Especialidad seleccionada')) : 'Directorio de estudiantes') }}{{ $filtroParalelo ? ' · Paralelo '.($paralelos->firstWhere('cod_par',$filtroParalelo)?->nom_par ?? '') : '' }}</h2><p class="ui-muted text-xs mt-1" role="status" aria-live="polite">{{ $estudiantes->total() }} estudiantes coinciden · Gestión {{ $nombreGestionActual }}</p></div></div>
        @include('livewire.admin.estudiantes.resultados')
    </div>
    {{ $estudiantes->onEachSide(1)->links('vendor.livewire.paginacion-institucional',['cantidad'=>$perPage,'entidad'=>'estudiantes','singular'=>'estudiante']) }}
    @if($panelDetalle && $estudianteDetalle)@include('livewire.admin.estudiantes.ficha')@endif
    @if($modalEditar)@include('livewire.admin.estudiantes.formulario')@endif
</div>
