<?php

declare(strict_types=1);

/** Contrato aditivo Universidades. Fuente: guía aprobada 2026-10-03; sin backfill ni retiro. */
return [
    [
        'tabla' => 'universidad',
        'creacion' => 'CREATE TABLE "universidad" (
 "cod_uni" VARCHAR(20) PRIMARY KEY,
 "nom_uni" VARCHAR(255) NOT NULL,
 "sig_uni" VARCHAR(50),
 "tip_uni" VARCHAR(80),
 "pai_uni" codigo_pais_iso2 NOT NULL DEFAULT \'BO\',
 "web_uni" url_http,
 "est_uni" VARCHAR(20) NOT NULL DEFAULT \'ACTIVA\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'nom_uni' => '"nom_uni" VARCHAR(255) NULL',
            'sig_uni' => '"sig_uni" VARCHAR(50) NULL',
            'tip_uni' => '"tip_uni" VARCHAR(80) NULL',
            'pai_uni' => '"pai_uni" codigo_pais_iso2 NULL',
            'web_uni' => '"web_uni" url_http NULL',
            'est_uni' => '"est_uni" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_uni',
        'columnas' => [
            'cod_uni' => 'VARCHAR(20) PRIMARY KEY',
            'nom_uni' => 'VARCHAR(255) NOT NULL',
            'sig_uni' => 'VARCHAR(50)',
            'tip_uni' => 'VARCHAR(80)',
            'pai_uni' => 'codigo_pais_iso2 NOT NULL DEFAULT \'BO\'',
            'web_uni' => 'url_http',
            'est_uni' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVA\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_uni IN (\'ACTIVA\',\'INACTIVA\',\'CERRADA\',\'ANULADA\')',
        ],
        'unicos' => [],
        'grupo' => 'Universidades',
        'existente' => false,
    ],
    [
        'tabla' => 'sede_universidad',
        'creacion' => 'CREATE TABLE "sede_universidad" (
 "cod_sed" VARCHAR(20) PRIMARY KEY,
 "cod_uni" VARCHAR(20) NOT NULL,
 "nom_sed" VARCHAR(220) NOT NULL,
 "dep_sed" VARCHAR(120),
 "ciu_sed" VARCHAR(120) NOT NULL,
 "dir_sed" TEXT,
 "tel_sed" telefono_e164,
 "web_sed" url_http,
 "lat_sed" NUMERIC(9,6),
 "lon_sed" NUMERIC(9,6),
 "fii_sed" DATE,
 "ffi_sed" DATE,
 "est_sed" VARCHAR(20) NOT NULL DEFAULT \'ACTIVA\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_uni' => '"cod_uni" VARCHAR(20) NULL',
            'nom_sed' => '"nom_sed" VARCHAR(220) NULL',
            'dep_sed' => '"dep_sed" VARCHAR(120) NULL',
            'ciu_sed' => '"ciu_sed" VARCHAR(120) NULL',
            'dir_sed' => '"dir_sed" TEXT NULL',
            'tel_sed' => '"tel_sed" telefono_e164 NULL',
            'web_sed' => '"web_sed" url_http NULL',
            'lat_sed' => '"lat_sed" NUMERIC(9,6) NULL',
            'lon_sed' => '"lon_sed" NUMERIC(9,6) NULL',
            'fii_sed' => '"fii_sed" DATE NULL',
            'ffi_sed' => '"ffi_sed" DATE NULL',
            'est_sed' => '"est_sed" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_sed',
        'columnas' => [
            'cod_sed' => 'VARCHAR(20) PRIMARY KEY',
            'cod_uni' => 'VARCHAR(20) NOT NULL',
            'nom_sed' => 'VARCHAR(220) NOT NULL',
            'dep_sed' => 'VARCHAR(120)',
            'ciu_sed' => 'VARCHAR(120) NOT NULL',
            'dir_sed' => 'TEXT',
            'tel_sed' => 'telefono_e164',
            'web_sed' => 'url_http',
            'lat_sed' => 'NUMERIC(9,6)',
            'lon_sed' => 'NUMERIC(9,6)',
            'fii_sed' => 'DATE',
            'ffi_sed' => 'DATE',
            'est_sed' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVA\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'lat_sed IS NULL OR lat_sed BETWEEN -90 AND 90',
            'lon_sed IS NULL OR lon_sed BETWEEN -180 AND 180',
            'est_sed IN (\'ACTIVA\',\'INACTIVA\',\'CERRADA\',\'ANULADA\')',
            'ffi_sed IS NULL OR fii_sed IS NULL OR ffi_sed>=fii_sed',
        ],
        'unicos' => [],
        'grupo' => 'Universidades',
        'existente' => false,
    ],
    [
        'tabla' => 'oferta_academica',
        'creacion' => 'CREATE TABLE "oferta_academica" (
 "cod_ofa" VARCHAR(20) PRIMARY KEY,
 "cod_sed" VARCHAR(20) NOT NULL,
 "cod_car" VARCHAR(20) NOT NULL,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_sed' => '"cod_sed" VARCHAR(20) NULL',
            'cod_car' => '"cod_car" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_ofa',
        'columnas' => [
            'cod_ofa' => 'VARCHAR(20) PRIMARY KEY',
            'cod_sed' => 'VARCHAR(20) NOT NULL',
            'cod_car' => 'VARCHAR(20) NOT NULL',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [],
        'unicos' => [
            [
                'cod_sed',
                'cod_car',
            ],
        ],
        'grupo' => 'Universidades',
        'existente' => false,
    ],
    [
        'tabla' => 'version_oferta_academica',
        'creacion' => 'CREATE TABLE "version_oferta_academica" (
 "cod_vof" VARCHAR(20) PRIMARY KEY,
 "cod_ofa" VARCHAR(20) NOT NULL,
 "nom_vof" VARCHAR(255),
 "mod_vof" VARCHAR(80),
 "dur_vof" NUMERIC(8,2),
 "uni_vof" VARCHAR(40),
 "tit_vof" VARCHAR(255),
 "req_vof" TEXT,
 "cos_vof" NUMERIC(14,2),
 "mon_vof" CHAR(3),
 "bec_vof" TEXT,
 "fii_vof" DATE NOT NULL,
 "ffi_vof" DATE,
 "est_vof" VARCHAR(30) NOT NULL DEFAULT \'ACTIVA\',
 "fec_vof" TIMESTAMPTZ,
 "dat_vof" JSONB,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_ofa' => '"cod_ofa" VARCHAR(20) NULL',
            'nom_vof' => '"nom_vof" VARCHAR(255) NULL',
            'mod_vof' => '"mod_vof" VARCHAR(80) NULL',
            'dur_vof' => '"dur_vof" NUMERIC(8,2) NULL',
            'uni_vof' => '"uni_vof" VARCHAR(40) NULL',
            'tit_vof' => '"tit_vof" VARCHAR(255) NULL',
            'req_vof' => '"req_vof" TEXT NULL',
            'cos_vof' => '"cos_vof" NUMERIC(14,2) NULL',
            'mon_vof' => '"mon_vof" CHAR(3) NULL',
            'bec_vof' => '"bec_vof" TEXT NULL',
            'fii_vof' => '"fii_vof" DATE NULL',
            'ffi_vof' => '"ffi_vof" DATE NULL',
            'est_vof' => '"est_vof" VARCHAR(30) NULL',
            'fec_vof' => '"fec_vof" TIMESTAMPTZ NULL',
            'dat_vof' => '"dat_vof" JSONB NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_vof',
        'columnas' => [
            'cod_vof' => 'VARCHAR(20) PRIMARY KEY',
            'cod_ofa' => 'VARCHAR(20) NOT NULL',
            'nom_vof' => 'VARCHAR(255)',
            'mod_vof' => 'VARCHAR(80)',
            'dur_vof' => 'NUMERIC(8,2)',
            'uni_vof' => 'VARCHAR(40)',
            'tit_vof' => 'VARCHAR(255)',
            'req_vof' => 'TEXT',
            'cos_vof' => 'NUMERIC(14,2)',
            'mon_vof' => 'CHAR(3)',
            'bec_vof' => 'TEXT',
            'fii_vof' => 'DATE NOT NULL',
            'ffi_vof' => 'DATE',
            'est_vof' => 'VARCHAR(30) NOT NULL DEFAULT \'ACTIVA\'',
            'fec_vof' => 'TIMESTAMPTZ',
            'dat_vof' => 'JSONB',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'dur_vof IS NULL OR dur_vof>0',
            'cos_vof IS NULL OR cos_vof>=0',
            'est_vof IN (\'ACTIVA\',\'SUSPENDIDA\',\'CERRADA\',\'SIN_ADMISION\',\'ANULADA\')',
            'ffi_vof IS NULL OR ffi_vof>=fii_vof',
            'dat_vof IS NULL OR jsonb_typeof(dat_vof)=\'object\'',
        ],
        'unicos' => [],
        'grupo' => 'Universidades',
        'existente' => false,
    ],
    [
        'tabla' => 'recurso_fuente',
        'creacion' => 'CREATE TABLE "recurso_fuente" (
 "cod_rfu" VARCHAR(20) PRIMARY KEY,
 "cod_uni" VARCHAR(20),
 "cod_sed" VARCHAR(20),
 "tip_rfu" VARCHAR(40) NOT NULL,
 "tit_rfu" VARCHAR(255),
 "url_rfu" url_http NOT NULL UNIQUE,
 "dom_rfu" VARCHAR(255),
 "con_rfu" VARCHAR(30) NOT NULL DEFAULT \'OFICIAL\',
 "est_rfu" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_uni' => '"cod_uni" VARCHAR(20) NULL',
            'cod_sed' => '"cod_sed" VARCHAR(20) NULL',
            'tip_rfu' => '"tip_rfu" VARCHAR(40) NULL',
            'tit_rfu' => '"tit_rfu" VARCHAR(255) NULL',
            'url_rfu' => '"url_rfu" url_http NULL',
            'dom_rfu' => '"dom_rfu" VARCHAR(255) NULL',
            'con_rfu' => '"con_rfu" VARCHAR(30) NULL',
            'est_rfu' => '"est_rfu" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_rfu',
        'columnas' => [
            'cod_rfu' => 'VARCHAR(20) PRIMARY KEY',
            'cod_uni' => 'VARCHAR(20)',
            'cod_sed' => 'VARCHAR(20)',
            'tip_rfu' => 'VARCHAR(40) NOT NULL',
            'tit_rfu' => 'VARCHAR(255)',
            'url_rfu' => 'url_http NOT NULL UNIQUE',
            'dom_rfu' => 'VARCHAR(255)',
            'con_rfu' => 'VARCHAR(30) NOT NULL DEFAULT \'OFICIAL\'',
            'est_rfu' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'tip_rfu IN (\'PAGINA_WEB\',\'PDF\',\'MALLA_CURRICULAR\',\'PLAN_ESTUDIOS\',\'RESOLUCION\',\'CONVOCATORIA\',\'DOCUMENTO\')',
            'con_rfu IN (\'OFICIAL\',\'INSTITUCIONAL\',\'SECUNDARIA\')',
            'est_rfu IN (\'ACTIVO\',\'INACTIVO\',\'NO_DISPONIBLE\',\'ANULADO\')',
        ],
        'unicos' => [
            [
                'url_rfu',
            ],
        ],
        'grupo' => 'Universidades',
        'existente' => false,
    ],
    [
        'tabla' => 'captura_fuente',
        'creacion' => 'CREATE TABLE "captura_fuente" (
 "cod_cfu" VARCHAR(20) PRIMARY KEY,
 "cod_rfu" VARCHAR(20) NOT NULL,
 "fec_cfu" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "url_cfu" url_http,
 "htt_cfu" INTEGER,
 "mim_cfu" VARCHAR(150),
 "eta_cfu" TEXT,
 "mod_cfu" TEXT,
 "cab_cfu" JSONB,
 "tam_cfu" BIGINT,
 "has_cfu" hash_sha256,
 "rut_cfu" TEXT,
 "tex_cfu" TEXT,
 "ori_cfu" VARCHAR(20) NOT NULL DEFAULT \'PYTHON\',
 "val_cfu" VARCHAR(20),
 "est_cfu" VARCHAR(30) NOT NULL DEFAULT \'CAPTURADA\',
 "err_cfu" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_rfu' => '"cod_rfu" VARCHAR(20) NULL',
            'fec_cfu' => '"fec_cfu" TIMESTAMPTZ NULL',
            'url_cfu' => '"url_cfu" url_http NULL',
            'htt_cfu' => '"htt_cfu" INTEGER NULL',
            'mim_cfu' => '"mim_cfu" VARCHAR(150) NULL',
            'eta_cfu' => '"eta_cfu" TEXT NULL',
            'mod_cfu' => '"mod_cfu" TEXT NULL',
            'cab_cfu' => '"cab_cfu" JSONB NULL',
            'tam_cfu' => '"tam_cfu" BIGINT NULL',
            'has_cfu' => '"has_cfu" hash_sha256 NULL',
            'rut_cfu' => '"rut_cfu" TEXT NULL',
            'tex_cfu' => '"tex_cfu" TEXT NULL',
            'ori_cfu' => '"ori_cfu" VARCHAR(20) NULL',
            'val_cfu' => '"val_cfu" VARCHAR(20) NULL',
            'est_cfu' => '"est_cfu" VARCHAR(30) NULL',
            'err_cfu' => '"err_cfu" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_cfu',
        'columnas' => [
            'cod_cfu' => 'VARCHAR(20) PRIMARY KEY',
            'cod_rfu' => 'VARCHAR(20) NOT NULL',
            'fec_cfu' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'url_cfu' => 'url_http',
            'htt_cfu' => 'INTEGER',
            'mim_cfu' => 'VARCHAR(150)',
            'eta_cfu' => 'TEXT',
            'mod_cfu' => 'TEXT',
            'cab_cfu' => 'JSONB',
            'tam_cfu' => 'BIGINT',
            'has_cfu' => 'hash_sha256',
            'rut_cfu' => 'TEXT',
            'tex_cfu' => 'TEXT',
            'ori_cfu' => 'VARCHAR(20) NOT NULL DEFAULT \'PYTHON\'',
            'val_cfu' => 'VARCHAR(20)',
            'est_cfu' => 'VARCHAR(30) NOT NULL DEFAULT \'CAPTURADA\'',
            'err_cfu' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'htt_cfu IS NULL OR htt_cfu BETWEEN 100 AND 599',
            'tam_cfu IS NULL OR tam_cfu>=0',
            'ori_cfu IN (\'PYTHON\',\'MANUAL\',\'IMPORTACION\')',
            'est_cfu IN (\'CAPTURADA\',\'VALIDADA\',\'OBSERVADA\',\'ERROR\',\'ANULADA\')',
            'cab_cfu IS NULL OR jsonb_typeof(cab_cfu)=\'object\'',
            'est_cfu=\'ERROR\' OR has_cfu IS NOT NULL OR rut_cfu IS NOT NULL OR tex_cfu IS NOT NULL',
        ],
        'unicos' => [],
        'grupo' => 'Universidades',
        'existente' => false,
    ],
    [
        'tabla' => 'evidencia_academica',
        'creacion' => 'CREATE TABLE "evidencia_academica" (
 "cod_eac" VARCHAR(20) PRIMARY KEY,
 "cod_vof" VARCHAR(20) NOT NULL,
 "cod_cfu" VARCHAR(20) NOT NULL,
 "tip_eac" VARCHAR(80),
 "cam_eac" VARCHAR(160),
 "con_eac" TEXT,
 "est_eac" VARCHAR(20) NOT NULL DEFAULT \'VALIDA\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_vof' => '"cod_vof" VARCHAR(20) NULL',
            'cod_cfu' => '"cod_cfu" VARCHAR(20) NULL',
            'tip_eac' => '"tip_eac" VARCHAR(80) NULL',
            'cam_eac' => '"cam_eac" VARCHAR(160) NULL',
            'con_eac' => '"con_eac" TEXT NULL',
            'est_eac' => '"est_eac" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_eac',
        'columnas' => [
            'cod_eac' => 'VARCHAR(20) PRIMARY KEY',
            'cod_vof' => 'VARCHAR(20) NOT NULL',
            'cod_cfu' => 'VARCHAR(20) NOT NULL',
            'tip_eac' => 'VARCHAR(80)',
            'cam_eac' => 'VARCHAR(160)',
            'con_eac' => 'TEXT',
            'est_eac' => 'VARCHAR(20) NOT NULL DEFAULT \'VALIDA\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_eac IN (\'VALIDA\',\'OBSERVADA\',\'DESCARTADA\',\'ANULADA\')',
        ],
        'unicos' => [
            [
                'cod_vof',
                'cod_cfu',
            ],
        ],
        'grupo' => 'Universidades',
        'existente' => false,
    ],
];
