@teleport('body')
<div class="personas-modal docentes-modal" x-data="{}" x-trap.inert.noscroll="true" role="dialog" aria-modal="true" aria-labelledby="docente-carga-titulo" x-on:keydown.escape.window="$wire.cerrarFicha()">
    <div class="personas-modal-fondo" wire:click="cerrarFicha" aria-hidden="true"></div><section class="personas-modal-panel docentes-carga-panel">
    <header class="personas-modal-cabecera"><div><p class="ui-kicker">Asignaciones académicas · Gestión {{ $nombreGestion }}</p><h2 class="ui-title text-xl font-bold mt-1" id="docente-carga-titulo">Carga docente</h2><p class="ui-muted text-sm mt-2">{{ $ficha['nombre'] }}</p></div><button type="button" class="personas-accion" wire:click="cerrarFicha" aria-label="Cerrar carga docente"><i class="ph-duotone ph-x" aria-hidden="true"></i></button></header>
    <div class="personas-modal-contenido"><div class="docentes-ficha-resumen"><div><strong>{{ $ficha['horas'] }} h</strong><span>Horas asignadas</span></div><div><strong>{{ count($ficha['activos']) }}</strong><span>Asignaciones activas</span></div><div><strong>{{ count($ficha['cursos']) }}</strong><span>Grupos atendidos</span></div></div>
    <div class="docentes-etiquetas mt-4"><span class="ui-badge-info">{{ $ficha['horas_materias'] }} h curriculares</span><span class="ui-badge-info">{{ $ficha['horas_tecnicas'] }} h técnicas</span></div>
    <div class="docentes-carga-areas mt-5">@forelse(collect($ficha['activos'])->groupBy('nombre') as $nombre=>$planes)<section class="docentes-carga-area"><header><h3 class="ui-title font-bold">{{ $nombre }}</h3><span class="ui-badge-info">{{ $planes->sum('horas') }} h</span></header><p class="ui-muted text-xs mt-2">{{ $planes->first()['tipo']==='materia'?'Materia curricular':'Especialidad técnica' }} · {{ $planes->pluck('grupo')->unique()->count() }} grupos</p><ol class="docentes-asignaciones mt-3">@foreach($planes as $plan)<li><span class="ui-title text-sm">{{ $plan['grupo'] }}</span><strong>{{ $plan['horas'] }} h</strong></li>@endforeach</ol></section>@empty<p class="ui-muted text-sm">No tiene carga activa registrada en esta gestión.</p>@endforelse</div>
    @php($anteriores=collect($ficha['planes'])->where('activo',false))
    @if($anteriores->isNotEmpty())<x-plegable-institucional class="docentes-materias mt-5" icono="ph-books" :compacto="true"><x-slot:titulo>Consultar asignaciones anteriores de esta gestión ({{ $anteriores->count() }})</x-slot:titulo><ol class="docentes-asignaciones mt-3">@foreach($anteriores as $plan)<li><div><strong class="ui-title text-sm">{{ $plan['nombre'] }}</strong><p class="ui-muted text-xs mt-2">{{ $plan['grupo'] }} · {{ ucfirst(mb_strtolower($plan['estado'] ?: 'Sin estado registrado')) }}</p></div><strong>{{ $plan['horas'] }} h</strong></li>@endforeach</ol></x-plegable-institucional>@endif
    </div><footer class="personas-modal-pie"><button type="button" class="ui-btn ui-btn-secondary" wire:click="cerrarFicha">Cerrar carga</button>@can('Personal_Institucional')<a href="{{ route('admin.personal-institucional') }}" class="ui-btn ui-btn-primary">Gestionar asignaciones</a>@endcan</footer>
    </section>
</div>
@endteleport
