@teleport('body')
<div class="personas-modal docentes-drawer" x-data="{seccion:@js($seccion)}" x-trap.inert.noscroll="true" role="dialog" aria-modal="true" aria-labelledby="docentes-ficha-titulo" x-on:keydown.escape.window="$wire.cerrarFicha()">
    <div class="personas-modal-fondo" wire:click="cerrarFicha" aria-hidden="true"></div><section class="personas-modal-panel docentes-drawer-panel">
        <header class="personas-modal-cabecera"><div class="docentes-identidad"><x-avatar-institucional :user="$docenteFicha->personalInstitucional?->persona?->usuario" :nombre="$ficha['nombre']" alternativa="iniciales" /><div><p class="ui-kicker">Ficha docente · Gestión {{ $nombreGestion }}</p><h2 class="ui-title text-lg font-bold mt-1" id="docentes-ficha-titulo">{{ $ficha['nombre'] }}</h2><p class="ui-muted text-xs mt-1">{{ $ficha['perfil'] }}</p></div></div><button type="button" class="personas-accion" wire:click="cerrarFicha" aria-label="Cerrar ficha docente"><i class="ph-duotone ph-x" aria-hidden="true"></i></button></header>
        <div class="personas-modal-contenido"><div class="docentes-ficha-resumen"><div><strong>{{ $ficha['horas'] }} h</strong><span>Carga académica</span></div><div><strong>{{ count($ficha['cursos']) }}</strong><span>Grupos atendidos</span></div><div><strong>{{ count($ficha['materias']) }}</strong><span>Áreas</span></div></div>
        <div class="personas-tipos-vista mt-5" role="group" aria-label="Secciones de la ficha docente">@foreach(['perfil'=>'Perfil y contacto','trayectoria'=>'Trayectoria'] as $valor=>$titulo)<button type="button" x-on:click="seccion='{{ $valor }}'" :aria-pressed="seccion==='{{ $valor }}'">{{ $titulo }}</button>@endforeach</div>
        <section x-show="seccion==='perfil'" x-transition.opacity.duration.140ms class="mt-5"><h3 class="ui-title font-bold">Perfil profesional y contacto</h3><dl class="docentes-ficha-datos mt-4"><div><dt>Especialidad profesional</dt><dd>{{ $ficha['perfil'] }}</dd></div><div><dt>Documento de identidad</dt><dd>{{ $ficha['ci'] }}</dd></div><div><dt>Correo personal</dt><dd>{{ $ficha['correo'] ?: 'Sin correo registrado' }}</dd></div><div><dt>Teléfono</dt><dd>{{ $ficha['telefono'] ?: 'Sin teléfono registrado' }}</dd></div><div><dt>Cuenta de acceso</dt><dd>{{ $ficha['cuenta'] ?: 'Sin cuenta vinculada' }}</dd></div><div><dt>Acceso al sistema</dt><dd>{{ ['ACTIVO'=>'Cuenta activa','INACTIVO'=>'Cuenta inactiva','SIN_CUENTA'=>'Pendiente de vinculación'][$ficha['acceso']] }}</dd></div><div><dt>Roles de la cuenta</dt><dd>{{ $ficha['roles'] ?: 'Sin roles registrados' }}</dd></div></dl><h3 class="ui-title font-bold mt-5">Cursos y paralelos atendidos</h3><div class="docentes-etiquetas mt-3">@forelse($ficha['cursos'] as $grupo)<span class="ui-badge-info">{{ $grupo }}</span>@empty<p class="ui-muted text-sm">Sin grupos asignados en esta gestión.</p>@endforelse</div></section>
        @include('livewire.admin.docentes.trayectoria')
        </div><footer class="personas-modal-pie"><button type="button" class="ui-btn ui-btn-secondary" wire:click="cerrarFicha">Cerrar</button>@can('Personal_Institucional')<a href="{{ route('admin.personal-institucional') }}" class="ui-btn ui-btn-primary">Gestionar perfil y carga</a>@endcan</footer>
    </section>
</div>
@endteleport
