<section class="ui-card docentes-filtros" aria-label="Buscar y filtrar docentes">
    <div class="docentes-filtros-principales"><div><label for="docentes-buscar" class="ui-label">Buscar docente</label><div class="docentes-busqueda"><i class="ph-duotone ph-magnifying-glass" aria-hidden="true"></i><input id="docentes-buscar" class="ui-input" type="search" maxlength="100" wire:model.live.debounce.350ms="search" placeholder="Nombre, documento o especialidad…" /></div><x-input-error for="search" /></div>
    <x-selector-institucional modelo="gestion" identificador="docentes-gestion" etiqueta="Gestión académica" :opciones="$gestiones->map(fn($g)=>['valor'=>$g->cod_gea,'etiqueta'=>(string)$g->ani_gea])->all()" />
    <x-selector-institucional modelo="materia" identificador="docentes-materia" etiqueta="Materia o especialidad técnica" :opciones="array_merge([['valor'=>'','etiqueta'=>'Todas las áreas']],$materias->map(fn($m)=>['valor'=>$m,'etiqueta'=>$m])->all())" />
    <x-selector-institucional modelo="curso" identificador="docentes-curso" etiqueta="Curso y paralelo" :opciones="array_merge([['valor'=>'','etiqueta'=>'Todos los grupos']],$cursos->map(fn($c)=>['valor'=>$c,'etiqueta'=>$c])->all())" />
    </div>
    <div class="docentes-herramientas"><div class="personas-tipos-vista" role="group" aria-label="Vistas de docentes">@foreach(['tarjetas'=>['squares-four','Tarjetas'],'lista'=>['list','Lista'],'tabla'=>['table','Tabla'],'cargas'=>['books','Cargas']] as $valor=>[$icono,$texto])<button type="button" x-on:click="vista='{{ $valor }}'" :aria-pressed="vista==='{{ $valor }}'"><i class="ph-duotone ph-{{ $icono }}" aria-hidden="true"></i>{{ $texto }}</button>@endforeach</div><div class="personas-acciones"><button type="button" class="ui-btn ui-btn-secondary" x-on:click="masFiltros=!masFiltros" :aria-expanded="masFiltros"><i class="ph-duotone ph-sliders-horizontal" aria-hidden="true"></i>Más filtros y orden</button><button type="button" class="ui-btn ui-btn-secondary" wire:click="limpiarFiltros">Limpiar</button></div></div>
    <div class="docentes-filtros-extra" x-show="masFiltros" x-cloak x-transition.opacity.duration.140ms>
    <x-selector-institucional modelo="carga" identificador="docentes-carga" etiqueta="Asignaciones académicas" :opciones="[['valor'=>'','etiqueta'=>'Cualquier carga'],['valor'=>'CON_CARGA','etiqueta'=>'Con horas asignadas'],['valor'=>'SIN_CARGA','etiqueta'=>'Sin horas asignadas'],['valor'=>'MATERIA','etiqueta'=>'Con materias curriculares'],['valor'=>'TECNICA','etiqueta'=>'Con especialidades técnicas']]" />
    <x-selector-institucional modelo="acceso" identificador="docentes-acceso" etiqueta="Cuenta vinculada" :opciones="[['valor'=>'','etiqueta'=>'Cualquier cuenta'],['valor'=>'ACTIVO','etiqueta'=>'Con acceso activo'],['valor'=>'INACTIVO','etiqueta'=>'Con acceso inactivo'],['valor'=>'SIN_CUENTA','etiqueta'=>'Sin cuenta vinculada']]" />
    <x-selector-institucional modelo="perfil" identificador="docentes-perfil" etiqueta="Perfil profesional" :opciones="[['valor'=>'','etiqueta'=>'Todos los perfiles'],['valor'=>'COMPLETO','etiqueta'=>'Especialidad registrada'],['valor'=>'PENDIENTE','etiqueta'=>'Especialidad por completar']]" />
    <x-selector-institucional modelo="orden" identificador="docentes-orden" etiqueta="Ordenar por" :opciones="[['valor'=>'nombre','etiqueta'=>'Nombre · A a Z'],['valor'=>'horas_desc','etiqueta'=>'Mayor carga horaria'],['valor'=>'horas_asc','etiqueta'=>'Menor carga horaria'],['valor'=>'perfil','etiqueta'=>'Especialidad profesional']]" />
    </div>
    @if($search || $materia || $curso || $carga || $acceso || $perfil)<p class="ui-muted text-xs mt-3">Los resultados y los gráficos corresponden a tus filtros. <button type="button" class="docentes-enlace" wire:click="limpiarFiltros">Ver todos los docentes</button></p>@endif
</section>
