@php($horasSeleccion=$indicadores['materias']+$indicadores['tecnicas'])
<section class="docentes-indicadores" x-show="indicadores" x-transition.opacity.duration.160ms aria-label="Distribución académica de docentes">
    <article class="ui-card docentes-grafico"><header><div><p class="ui-kicker">Horas por área · Gestión {{ $nombreGestion }}</p><h2 class="ui-title font-bold mt-1">Materias y especialidades</h2><p class="ui-muted text-xs mt-2">Compara las horas asignadas y selecciona un área para ver a sus docentes.</p></div><span class="ui-badge-info">{{ $indicadores['total'] }} {{ $indicadores['total']===1?'docente':'docentes' }} en la selección</span></header>
    <div class="personas-tipos-vista mt-4" role="group" aria-label="Tipo de gráfico por área"><button type="button" x-on:click="grafico='mosaico'" :aria-pressed="grafico==='mosaico'">Mosaico</button><button type="button" x-on:click="grafico='burbujas'" :aria-pressed="grafico==='burbujas'">Burbujas</button></div>
    <div x-show="grafico==='mosaico'" x-transition.opacity.duration.140ms><x-mosaico-institucional :datos="$grupos" modelo="materia" etiqueta="Horas académicas por materia o especialidad técnica" /><p class="ui-muted text-xs mt-3">Cada área ocupa una superficie proporcional a sus horas académicas.</p></div>
    <div class="docentes-burbujas" x-show="grafico==='burbujas'" x-cloak x-transition.opacity.duration.140ms>@forelse($grupos as $grupo)<button type="button" class="docentes-area" wire:key="area-{{ md5($grupo['nombre']) }}" wire:click="$set('materia', @js($grupo['nombre']))" aria-label="{{ $grupo['nombre'] }}: {{ $grupo['horas'] }} horas, {{ $grupo['docentes'] }} {{ $grupo['docentes']===1?'docente':'docentes' }} y {{ $grupo['grupos'] }} grupos"><span class="docentes-burbuja" style="--docente-diametro:{{ 5.2*sqrt($grupo['horas']/max(1,$grupos->max('horas'))) }}rem"><strong>{{ $grupo['horas'] }}</strong><small>horas</small></span><strong>{{ $grupo['nombre'] }}</strong><small>{{ $grupo['docentes'] }} {{ $grupo['docentes']===1?'docente':'docentes' }} · {{ $grupo['grupos'] }} grupos</small></button>@empty<p class="ui-muted text-sm p-4">No hay asignaciones activas para representar en esta selección.</p>@endforelse</div>
    </article>
    <article class="ui-card docentes-grafico"><p class="ui-kicker">Composición de la carga</p><h2 class="ui-title font-bold mt-1">Horas académicas asignadas</h2><div class="docentes-anillo {{ !$horasSeleccion ? 'docentes-anillo-vacio' : '' }}" style="--docente-porcentaje:{{ $horasSeleccion ? 100*$indicadores['materias']/$horasSeleccion : 0 }}%" role="img" aria-label="{{ $indicadores['materias'] }} horas curriculares y {{ $indicadores['tecnicas'] }} horas técnicas"><div><strong>{{ $horasSeleccion }}</strong><span>horas</span></div></div><dl class="docentes-leyenda"><div><dt><i class="docentes-punto"></i>Materias curriculares</dt><dd>{{ $indicadores['materias'] }} h</dd></div><div><dt><i class="docentes-punto docentes-punto-tecnico"></i>Especialidades técnicas</dt><dd>{{ $indicadores['tecnicas'] }} h</dd></div></dl><p class="ui-muted text-xs mt-4">{{ $indicadores['sin_carga'] }} docentes sin carga en esta selección. Las horas corresponden a las asignaciones, no a horas de reloj.</p></article>
    @include('livewire.admin.docentes.mapa-carga')
</section>
