@php
    $maxHoras=max(1,$mapaCarga->max('horas')??0);
    $maxGrupos=max(1,$mapaCarga->max('grupos')??0);
@endphp
<article class="ui-card docentes-grafico docentes-mapa-panel" x-data="{punto:null}" wire:key="mapa-carga-{{ md5(json_encode($mapaCarga)) }}"><div><p class="ui-kicker">Relación entre carga y grupos</p><h2 class="ui-title font-bold mt-1">Mapa de carga docente</h2><p class="ui-muted text-xs mt-2">A la derecha hay más horas; hacia arriba, más grupos. Selecciona un punto para conocer a sus docentes.</p></div>
    @if($mapaCarga->isNotEmpty())<div class="docentes-mapa"><span class="docentes-mapa-eje-y">Cursos y paralelos</span><div class="docentes-mapa-plano" role="group" aria-label="Docentes por horas y grupos atendidos"><span class="docentes-mapa-maximo">{{ $maxGrupos }} grupos</span>@foreach($mapaCarga as $punto)<button type="button" class="docentes-mapa-punto" style="left:{{ 6+88*$punto['horas']/$maxHoras }}%;bottom:{{ 8+84*$punto['grupos']/$maxGrupos }}%;--punto-tamano:{{ 1.2+.5*sqrt(count($punto['docentes'])) }}rem" x-on:click="punto=@js($punto)" :aria-pressed="punto?.horas===@js($punto['horas']) && punto?.grupos===@js($punto['grupos'])" aria-label="{{ count($punto['docentes']) }} {{ count($punto['docentes'])===1?'docente':'docentes' }} con {{ $punto['horas'] }} horas y {{ $punto['grupos'] }} grupos" title="{{ $punto['horas'] }} h · {{ $punto['grupos'] }} grupos · {{ count($punto['docentes']) }} docentes">{{ count($punto['docentes']) }}</button>@endforeach</div><div class="docentes-mapa-eje-x"><span>0 h</span><span>Horas académicas asignadas</span><span>{{ $maxHoras }} h</span></div></div>
    <div x-show="punto" x-cloak x-transition.opacity.duration.140ms class="docentes-mapa-seleccion"><p class="ui-title text-sm font-bold" x-text="punto ? punto.horas+' horas · '+punto.grupos+' grupos' : ''"></p><div class="docentes-etiquetas mt-3"><template x-for="docente in (punto?.docentes || [])" :key="docente.clave"><button type="button" class="ui-btn ui-btn-secondary" x-on:click="$wire.abrirFicha(docente.clave,'asignaciones')" x-text="docente.nombre"></button></template></div></div>
    @else<p class="ui-muted text-sm mt-4">No hay docentes en la selección para comparar sus cargas.</p>@endif
</article>
