@if($docentes->isEmpty())<div class="ui-card docentes-vacio"><i class="ph-duotone ph-magnifying-glass" aria-hidden="true"></i><h3 class="ui-title font-bold">No encontramos docentes con estos filtros</h3><p class="ui-muted text-sm mt-2">Prueba otra materia, curso o nombre para continuar.</p><button type="button" class="ui-btn ui-btn-secondary mt-4" wire:click="limpiarFiltros">Limpiar filtros</button></div>@else
    <div x-show="vista!=='tabla'" class="docentes-directorio" :class="{'docentes-lista':vista==='lista','docentes-cargas':vista==='cargas'}">
    @foreach($docentes as $docente)<article class="ui-card docentes-tarjeta" wire:key="docente-{{ $docente['clave'] }}"><div class="docentes-tarjeta-identidad"><x-avatar-institucional :user="$docente['usuario']" alternativa="iniciales" :nombre="$docente['nombre']" /><div><h3 class="ui-title font-bold">{{ $docente['nombre'] }}</h3><p class="ui-muted text-xs mt-1">{{ $docente['perfil'] }}</p></div></div>
    @if(!$docente['completo'])<p class="ui-alert-warning text-xs">Completa sus especialidades con el botón Especialidades, si tienes permiso para gestionar personal.</p>@endif
    <div class="docentes-tarjeta-datos"><div><strong>{{ $docente['horas'] }} <small>h</small></strong><span>Carga académica</span></div><div><strong>{{ count($docente['cursos']) }}</strong><span>Cursos y paralelos</span></div><div><strong>{{ count($docente['materias']) }}</strong><span>Áreas de enseñanza</span></div></div>
    <div class="docentes-etiquetas"><span class="ui-badge-info">{{ $docente['horas_materias'] }} h curriculares</span>@if($docente['horas_tecnicas'])<span class="ui-badge-info">{{ $docente['horas_tecnicas'] }} h técnicas</span>@endif</div>
    <x-plegable-institucional class="docentes-materias" icono="ph-books" :compacto="true"><x-slot:titulo>Materias y especialidades <span>{{ count($docente['materias']) }}</span></x-slot:titulo><p class="ui-muted text-xs mt-2">{{ implode(' · ',$docente['materias']) ?: 'Sin materias asignadas en esta gestión' }}</p></x-plegable-institucional>
    <div class="docentes-carga-detalle" x-show="vista==='cargas'" x-cloak><ol>@forelse($docente['activos'] as $plan)<li><div><strong class="ui-title text-xs">{{ $plan['nombre'] }}</strong><span>{{ $plan['grupo'] }}</span></div><b>{{ $plan['horas'] }} h</b></li>@empty<li class="ui-muted text-sm">Sin carga asignada.</li>@endforelse</ol></div>
    @include('livewire.admin.docentes.acciones')
    </article>@endforeach</div>
    <div x-show="vista==='tabla'" x-cloak class="ui-card docentes-tabla" tabindex="0" role="region" aria-label="Tabla de docentes"><table><thead><tr><th>Docente</th><th>Especialidad profesional</th><th>Horas</th><th>Grupos</th><th>Áreas</th><th>Acciones</th></tr></thead><tbody>@foreach($docentes as $docente)<tr><td><strong>{{ $docente['nombre'] }}</strong></td><td>{{ $docente['perfil'] }}</td><td>{{ $docente['horas'] }} h</td><td>{{ count($docente['cursos']) }}</td><td>{{ implode(' · ',$docente['materias']) ?: 'Sin asignaciones' }}</td><td>@include('livewire.admin.docentes.acciones')</td></tr>@endforeach</tbody></table></div>
@endif
