<?php

declare(strict_types=1);

/** Contrato aditivo Traslados. Fuente: guía aprobada 2026-10-03; sin backfill ni retiro. */
return [
    [
        'tabla' => 'institucion_procedencia',
        'creacion' => 'CREATE TABLE "institucion_procedencia" (
 "cod_ipe" VARCHAR(20) PRIMARY KEY,
 "nom_ipe" VARCHAR(255) NOT NULL,
 "tip_ipe" VARCHAR(80),
 "dep_ipe" VARCHAR(120),
 "ciu_ipe" VARCHAR(120),
 "dir_ipe" TEXT,
 "tel_ipe" telefono_e164,
 "web_ipe" url_http,
 "est_ipe" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'nom_ipe' => '"nom_ipe" VARCHAR(255) NULL',
            'tip_ipe' => '"tip_ipe" VARCHAR(80) NULL',
            'dep_ipe' => '"dep_ipe" VARCHAR(120) NULL',
            'ciu_ipe' => '"ciu_ipe" VARCHAR(120) NULL',
            'dir_ipe' => '"dir_ipe" TEXT NULL',
            'tel_ipe' => '"tel_ipe" telefono_e164 NULL',
            'web_ipe' => '"web_ipe" url_http NULL',
            'est_ipe' => '"est_ipe" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_ipe',
        'columnas' => [
            'cod_ipe' => 'VARCHAR(20) PRIMARY KEY',
            'nom_ipe' => 'VARCHAR(255) NOT NULL',
            'tip_ipe' => 'VARCHAR(80)',
            'dep_ipe' => 'VARCHAR(120)',
            'ciu_ipe' => 'VARCHAR(120)',
            'dir_ipe' => 'TEXT',
            'tel_ipe' => 'telefono_e164',
            'web_ipe' => 'url_http',
            'est_ipe' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_ipe IN (\'ACTIVO\',\'INACTIVO\')',
        ],
        'unicos' => [],
        'grupo' => 'Traslados',
        'existente' => true,
    ],
    [
        'tabla' => 'expediente_traslado',
        'creacion' => 'CREATE TABLE "expediente_traslado" (
 "cod_ext" VARCHAR(20) PRIMARY KEY,
 "cod_est" VARCHAR(20) NOT NULL,
 "cod_ipe" VARCHAR(20),
 "tip_ext" VARCHAR(40) NOT NULL,
 "ref_ext" VARCHAR(255),
 "fec_ext" DATE,
 "est_ext" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "obs_ext" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_est' => '"cod_est" VARCHAR(20) NULL',
            'cod_ipe' => '"cod_ipe" VARCHAR(20) NULL',
            'tip_ext' => '"tip_ext" VARCHAR(40) NULL',
            'ref_ext' => '"ref_ext" VARCHAR(255) NULL',
            'fec_ext' => '"fec_ext" DATE NULL',
            'est_ext' => '"est_ext" VARCHAR(20) NULL',
            'obs_ext' => '"obs_ext" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_ext',
        'columnas' => [
            'cod_ext' => 'VARCHAR(20) PRIMARY KEY',
            'cod_est' => 'VARCHAR(20) NOT NULL',
            'cod_ipe' => 'VARCHAR(20)',
            'tip_ext' => 'VARCHAR(40) NOT NULL',
            'ref_ext' => 'VARCHAR(255)',
            'fec_ext' => 'DATE',
            'est_ext' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'obs_ext' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'tip_ext IN (\'INGRESO\',\'SALIDA\')',
            'est_ext IN (\'ACTIVO\',\'CERRADO\',\'ANULADO\')',
        ],
        'unicos' => [],
        'grupo' => 'Traslados',
        'existente' => false,
    ],
    [
        'tabla' => 'documento_traslado',
        'creacion' => 'CREATE TABLE "documento_traslado" (
 "cod_dtr" VARCHAR(20) PRIMARY KEY,
 "cod_ext" VARCHAR(20) NOT NULL,
 "tip_dtr" VARCHAR(120) NOT NULL,
 "nom_dtr" VARCHAR(255) NOT NULL,
 "fec_dtr" DATE,
 "rut_dtr" TEXT NOT NULL,
 "mim_dtr" VARCHAR(150),
 "tam_dtr" BIGINT,
 "has_dtr" hash_sha256,
 "est_dtr" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "obs_dtr" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_ext' => '"cod_ext" VARCHAR(20) NULL',
            'tip_dtr' => '"tip_dtr" VARCHAR(120) NULL',
            'nom_dtr' => '"nom_dtr" VARCHAR(255) NULL',
            'fec_dtr' => '"fec_dtr" DATE NULL',
            'rut_dtr' => '"rut_dtr" TEXT NULL',
            'mim_dtr' => '"mim_dtr" VARCHAR(150) NULL',
            'tam_dtr' => '"tam_dtr" BIGINT NULL',
            'has_dtr' => '"has_dtr" hash_sha256 NULL',
            'est_dtr' => '"est_dtr" VARCHAR(20) NULL',
            'obs_dtr' => '"obs_dtr" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_dtr',
        'columnas' => [
            'cod_dtr' => 'VARCHAR(20) PRIMARY KEY',
            'cod_ext' => 'VARCHAR(20) NOT NULL',
            'tip_dtr' => 'VARCHAR(120) NOT NULL',
            'nom_dtr' => 'VARCHAR(255) NOT NULL',
            'fec_dtr' => 'DATE',
            'rut_dtr' => 'TEXT NOT NULL',
            'mim_dtr' => 'VARCHAR(150)',
            'tam_dtr' => 'BIGINT',
            'has_dtr' => 'hash_sha256',
            'est_dtr' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'obs_dtr' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'tam_dtr IS NULL OR tam_dtr>=0',
            'est_dtr IN (\'ACTIVO\',\'INACTIVO\',\'ANULADO\')',
        ],
        'unicos' => [],
        'grupo' => 'Traslados',
        'existente' => false,
    ],
    [
        'tabla' => 'nota_traslado',
        'creacion' => 'CREATE TABLE "nota_traslado" (
 "cod_ntr" VARCHAR(20) PRIMARY KEY,
 "cod_ext" VARCHAR(20) NOT NULL,
 "ani_ntr" INTEGER,
 "cur_ntr" VARCHAR(120) NOT NULL,
 "mat_ntr" VARCHAR(180) NOT NULL,
 "per_ntr" VARCHAR(120),
 "ori_ntr" VARCHAR(120) NOT NULL,
 "not_ntr" NUMERIC(8,2),
 "esc_ntr" VARCHAR(120),
 "cod_cur" VARCHAR(20),
 "cod_asi" VARCHAR(20),
 "cod_pev" VARCHAR(20),
 "obs_ntr" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_ext' => '"cod_ext" VARCHAR(20) NULL',
            'ani_ntr' => '"ani_ntr" INTEGER NULL',
            'cur_ntr' => '"cur_ntr" VARCHAR(120) NULL',
            'mat_ntr' => '"mat_ntr" VARCHAR(180) NULL',
            'per_ntr' => '"per_ntr" VARCHAR(120) NULL',
            'ori_ntr' => '"ori_ntr" VARCHAR(120) NULL',
            'not_ntr' => '"not_ntr" NUMERIC(8,2) NULL',
            'esc_ntr' => '"esc_ntr" VARCHAR(120) NULL',
            'cod_cur' => '"cod_cur" VARCHAR(20) NULL',
            'cod_asi' => '"cod_asi" VARCHAR(20) NULL',
            'cod_pev' => '"cod_pev" VARCHAR(20) NULL',
            'obs_ntr' => '"obs_ntr" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_ntr',
        'columnas' => [
            'cod_ntr' => 'VARCHAR(20) PRIMARY KEY',
            'cod_ext' => 'VARCHAR(20) NOT NULL',
            'ani_ntr' => 'INTEGER',
            'cur_ntr' => 'VARCHAR(120) NOT NULL',
            'mat_ntr' => 'VARCHAR(180) NOT NULL',
            'per_ntr' => 'VARCHAR(120)',
            'ori_ntr' => 'VARCHAR(120) NOT NULL',
            'not_ntr' => 'NUMERIC(8,2)',
            'esc_ntr' => 'VARCHAR(120)',
            'cod_cur' => 'VARCHAR(20)',
            'cod_asi' => 'VARCHAR(20)',
            'cod_pev' => 'VARCHAR(20)',
            'obs_ntr' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'ani_ntr IS NULL OR ani_ntr BETWEEN 1900 AND 2200',
        ],
        'unicos' => [],
        'grupo' => 'Traslados',
        'existente' => false,
    ],
];
