<section class="space-y-4 border-t pt-4" style="border-color: var(--ui-border);">
    <div><h4 class="ui-title font-black">Justificación y respaldo</h4><p class="ui-muted text-xs">Una solicitud o comunicado enviado no equivale a aprobación.</p></div>
    <x-lector-documento-institucional modelo="documentoCambio" accion="completarDesdePdf" identificador="pdf-paralelo" :aceptado="$mensajeAutollenado !== ''" :revision="$revisionDocumento" />
    <div><x-selector-institucional modelo="causaCambio" identificador="causa-paralelo" etiqueta="Motivo del cambio" :opciones="[['valor'=>'','etiqueta'=>'Selecciona el motivo'],['valor'=>'demanda','etiqueta'=>'Mayor demanda estudiantil'],['valor'=>'infraestructura','etiqueta'=>'Nueva infraestructura o espacios'],['valor'=>'reorganizacion','etiqueta'=>'Reorganización académica'],['valor'=>'rectificacion','etiqueta'=>'Corrección documentada del catálogo'],['valor'=>'otro','etiqueta'=>'Otro motivo justificado']]" /></div>
    <div><label for="motivo-paralelo" class="ui-label">Justificación concreta</label><textarea id="motivo-paralelo" wire:model.live.debounce.400ms="motivoCambio" class="ui-textarea" rows="3" maxlength="2000" placeholder="Ej.: Nuevos ambientes permiten organizar un paralelo adicional en el grado solicitado." aria-describedby="motivo-paralelo-ayuda"></textarea><p id="motivo-paralelo-ayuda" class="ui-muted mt-1 text-xs">Ejemplo orientativo: «Nuevos ambientes permiten organizar un paralelo adicional para atender la demanda del grado». Mínimo 30 caracteres y una frase comprensible; describe tu caso real.</p>@error('motivoCambio')<p class="ui-error">{{ $message }}</p>@enderror</div>
    <div class="grid gap-3 sm:grid-cols-2">
        <div><label for="gestion-paralelo" class="ui-label">Gestión solicitada</label><input id="gestion-paralelo" type="number" wire:model.live="gestionSolicitud" class="ui-input" placeholder="Ej.: {{ now()->year }}" aria-describedby="gestion-paralelo-ayuda" min="{{ now()->year }}" max="{{ now()->year + 1 }}"><p id="gestion-paralelo-ayuda" class="ui-muted mt-1 text-xs">Año autorizado en el PDF: {{ now()->year }} o {{ now()->year + 1 }}.</p>@error('gestionSolicitud')<p class="ui-error">{{ $message }}</p>@enderror</div>
        <div><x-selector-institucional modelo="tipoDocumento" identificador="tipo-doc-paralelo" etiqueta="Tipo de respaldo" :opciones="array_merge([['valor'=>'resolucion','etiqueta'=>'Resolución administrativa']], $modalEditar ? [['valor'=>'rectificacion','etiqueta'=>'Acta o informe de rectificación']] : [])" /></div>
        <div><label for="numero-doc-paralelo" class="ui-label">Número del documento</label><input id="numero-doc-paralelo" wire:model.live.debounce.400ms="numeroDocumento" class="ui-input" maxlength="100" placeholder="Ej.: DDE-123/{{ now()->year }}" aria-describedby="numero-doc-paralelo-ayuda"><p id="numero-doc-paralelo-ayuda" class="ui-muted mt-1 text-xs">Ejemplo de formato: 123/{{ now()->year }}. Copia la referencia completa; no uses este número de ejemplo como respaldo.</p>@error('numeroDocumento')<p class="ui-error">{{ $message }}</p>@enderror</div>
        <div><x-calendario-institucional modelo="fechaDocumento" identificador="fecha-doc-paralelo" etiqueta="Fecha de emisión" minimo="1900-01-01" :maximo="now('America/La_Paz')->toDateString()" :inicio="now('America/La_Paz')->toDateString()" :requerido="true" /><p id="fecha-doc-paralelo-ayuda" class="ui-muted mt-1 text-xs">Fecha de emisión del PDF, hasta hoy. Ejemplo de formato: 15/01/{{ now()->year }}.</p></div>
    </div>
    <div><label for="autoridad-paralelo" class="ui-label">Autoridad emisora</label><input id="autoridad-paralelo" wire:model.live.debounce.400ms="autoridadDocumento" class="ui-input" maxlength="200" placeholder="Ej.: Dirección Departamental de Educación de La Paz" aria-describedby="autoridad-paralelo-ayuda"><p id="autoridad-paralelo-ayuda" class="ui-muted mt-1 text-xs">Nombre completo del emisor, tal como figura en el documento; no solo «MINEDU» o un nombre de persona.</p>@error('autoridadDocumento')<p class="ui-error">{{ $message }}</p>@enderror</div>
    @if (!($enFases ?? false))
    <div><label for="verificacion-paralelo" class="ui-label">Comprobación con la autoridad</label><textarea id="verificacion-paralelo" wire:model.live.debounce.400ms="referenciaVerificacion" class="ui-textarea" rows="2" maxlength="500" placeholder="Ej.: Comprobado el 04/10/{{ now()->year }} por el canal oficial, expediente [referencia]."></textarea><p class="ui-muted mt-1 text-xs">Incluye fecha, canal oficial y referencia verificable. Completa tus datos reales; no se deduce del PDF.</p>@error('referenciaVerificacion')<p class="ui-error">{{ $message }}</p>@enderror</div>
    @endif
    @if (!($enFases ?? false))
    <button type="button" wire:click="revisarDocumento" wire:loading.attr="disabled" class="ui-btn-secondary">Revisar documento</button>
    @if ($revisionDocumento)<ul class="space-y-1 text-xs">@foreach ($revisionDocumento['reglas'] as $regla => $cumple)<li style="color: {{ $cumple ? 'var(--ui-primary)' : 'var(--ui-danger)' }};">{{ $cumple ? '✓' : 'Pendiente:' }} {{ $regla }}</li>@endforeach</ul>@endif
    <div class="ui-alert-info text-xs leading-5"><strong>Impacto previsto</strong><p>Se modifica el catálogo institucional. No se crean grupos, no se trasladan estudiantes ni se replica la incorporación en otras gestiones. La apertura por grado y turno necesita su autorización y planificación propias.</p>@if ($modalEditar)<p class="mt-1">Una corrección de nombre se verá también en referencias históricas. Cambiar la identidad de un paralelo utilizado está bloqueado.</p>@endif<p class="mt-1">La lectura del PDF detecta omisiones; la autenticidad se comprueba con la autoridad emisora.</p></div>
    @if ((int)$gestionSolicitud > now()->year)<div class="ui-alert-warning text-xs">Para la próxima gestión, el catálogo debe quedar inactivo. Su habilitación posterior requiere revisión; no se activa por el simple cambio de año.</div>@endif
    <label class="ui-title flex items-start gap-2 text-sm"><input type="checkbox" wire:model.live="confirmarImpacto" class="mt-1"> He comprobado el respaldo y comprendo el alcance del cambio.</label>@error('confirmarImpacto')<p class="ui-error">{{ $message }}</p>@enderror
    @endif
</section>