<?php

declare(strict_types=1);

/** Contrato PostgreSQL del módulo AulaVirtual. */
return [[
    'tabla' => 'clase_virtual',
    'sql' => 'CREATE TABLE "clase_virtual" (
 "cod_cla" character varying(20) NOT NULL,
 "cod_pas" character varying(20) NOT NULL,
 "nom_cla" character varying(150) NOT NULL,
 "des_cla" text,
 "fec_ini_cla" date,
 "fec_fin_cla" date,
 "est_cla" character varying(255) NOT NULL DEFAULT \'ACTIVA\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 "cod_pes" character varying(20),
 "vis_cla" boolean,
 PRIMARY KEY ("cod_cla")
)',
    'indices' => ['CREATE INDEX "clase_virtual_cod_pas_est_cla_index" ON "clase_virtual" ("cod_pas", "est_cla")', 'CREATE INDEX "clase_virtual_cod_pas_index" ON "clase_virtual" ("cod_pas")', 'CREATE INDEX "clase_virtual_est_cla_index" ON "clase_virtual" ("est_cla")', 'CREATE INDEX "clase_virtual_fec_ini_cla_fec_fin_cla_index" ON "clase_virtual" ("fec_ini_cla", "fec_fin_cla")'],
    'checks' => [['can_clase_virtual_est_cla_check', 'CHECK (((est_cla)::text = ANY ((ARRAY[\'ACTIVA\'::character varying, \'CERRADA\'::character varying, \'INACTIVA\'::character varying, \'ANULADA\'::character varying])::text[])))'], ['can_ofi_ck_354f090848992c5d', 'CHECK ((num_nonnulls(cod_pas, cod_pes) = 1))'], ['can_ofi_ck_dfe563ce8b60fdec', 'CHECK (((fec_fin_cla IS NULL) OR (fec_fin_cla >= fec_ini_cla)))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'clase_estudiante',
    'sql' => 'CREATE TABLE "clase_estudiante" (
 "cod_cla_est" character varying(20) NOT NULL,
 "cod_cla" character varying(20) NOT NULL,
 "cod_est" character varying(20) NOT NULL,
 "fec_inc_cla_est" date,
 "fec_ret_cla_est" date,
 "ult_acc_cla_est" timestamp(0) without time zone,
 "ult_act_cla_est" timestamp(0) without time zone,
 "cant_acc_cla_est" integer NOT NULL DEFAULT 0,
 "est_cla_est" character varying(255) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 PRIMARY KEY ("cod_cla_est"),
 CONSTRAINT "uq_clase_estudiante_unico" UNIQUE ("cod_cla", "cod_est")
)',
    'indices' => ['CREATE INDEX "clase_estudiante_cod_cla_est_cla_est_index" ON "clase_estudiante" ("cod_cla", "est_cla_est")', 'CREATE INDEX "clase_estudiante_cod_cla_index" ON "clase_estudiante" ("cod_cla")', 'CREATE INDEX "clase_estudiante_cod_est_est_cla_est_index" ON "clase_estudiante" ("cod_est", "est_cla_est")', 'CREATE INDEX "clase_estudiante_cod_est_index" ON "clase_estudiante" ("cod_est")', 'CREATE INDEX "clase_estudiante_est_cla_est_index" ON "clase_estudiante" ("est_cla_est")', 'CREATE INDEX "clase_estudiante_ult_acc_cla_est_index" ON "clase_estudiante" ("ult_acc_cla_est")'],
    'checks' => [['can_clase_estudiante_est_cla_est_check', 'CHECK (((est_cla_est)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'RETIRADO\'::character varying, \'TRANSFERIDO\'::character varying, \'INACTIVO\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_ofi_ck_150c48acd4a5658a', 'CHECK (((fec_ret_cla_est IS NULL) OR (fec_ret_cla_est >= fec_inc_cla_est)))'], ['can_ofi_ck_bf5b1fe962e6363e', 'CHECK ((cant_acc_cla_est >= 0))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'seccion_clase',
    'sql' => 'CREATE TABLE "seccion_clase" (
 "cod_sec" character varying(20) NOT NULL,
 "cod_cla" character varying(20) NOT NULL,
 "nom_sec" character varying(180) NOT NULL,
 "des_sec" text,
 "ord_sec" integer NOT NULL,
 "vis_sec" boolean NOT NULL DEFAULT true,
 "est_sec" character varying(20) NOT NULL DEFAULT \'ACTIVA\'::character varying,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "ofi_uq_9748788a98b872dd" UNIQUE ("cod_cla", "ord_sec"),
 CONSTRAINT "ofi_uq_9a634db978558185" UNIQUE ("cod_sec", "cod_cla"),
 PRIMARY KEY ("cod_sec")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_39ce54f72397abd7', 'CHECK (((est_sec)::text = ANY ((ARRAY[\'ACTIVA\'::character varying, \'OCULTA\'::character varying, \'ARCHIVADA\'::character varying, \'ANULADA\'::character varying])::text[])))'], ['can_ofi_ck_8eea7f3ed96cb95c', 'CHECK ((ord_sec > 0))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'publicacion_clase',
    'sql' => 'CREATE TABLE "publicacion_clase" (
 "cod_pub" character varying(20) NOT NULL,
 "cod_cla" character varying(20) NOT NULL,
 "cod_usu" character varying(20) NOT NULL,
 "tip_pub" character varying(255) NOT NULL DEFAULT \'GENERAL\'::character varying,
 "tit_pub" character varying(180) NOT NULL,
 "con_pub" text,
 "fec_pub" timestamp(0) without time zone,
 "est_pub" character varying(255) NOT NULL DEFAULT \'BORRADOR\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 "unidad_id" bigint,
 "cod_sec" character varying(20),
 CONSTRAINT "ofi_uq_19b7bb47a0cc6f74" UNIQUE ("cod_pub", "cod_cla"),
 PRIMARY KEY ("cod_pub")
)',
    'indices' => ['CREATE INDEX "publicacion_clase_cod_cla_est_pub_index" ON "publicacion_clase" ("cod_cla", "est_pub")', 'CREATE INDEX "publicacion_clase_cod_cla_index" ON "publicacion_clase" ("cod_cla")', 'CREATE INDEX "publicacion_clase_cod_cla_tip_pub_index" ON "publicacion_clase" ("cod_cla", "tip_pub")', 'CREATE INDEX "publicacion_clase_cod_usu_index" ON "publicacion_clase" ("cod_usu")', 'CREATE INDEX "publicacion_clase_est_pub_index" ON "publicacion_clase" ("est_pub")', 'CREATE INDEX "publicacion_clase_fec_pub_index" ON "publicacion_clase" ("fec_pub")', 'CREATE INDEX "publicacion_clase_tip_pub_index" ON "publicacion_clase" ("tip_pub")', 'CREATE INDEX "publicacion_clase_unit_context_idx" ON "publicacion_clase" ("unidad_id", "cod_cla")'],
    'checks' => [['can_publicacion_clase_est_pub_check', 'CHECK (((est_pub)::text = ANY ((ARRAY[\'BORRADOR\'::character varying, \'PUBLICADO\'::character varying, \'OCULTO\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_publicacion_clase_tip_pub_check', 'CHECK (((tip_pub)::text = ANY ((ARRAY[\'ANUNCIO\'::character varying, \'AVISO\'::character varying, \'MATERIAL\'::character varying, \'RECORDATORIO\'::character varying, \'GENERAL\'::character varying])::text[])))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'material_clase',
    'sql' => 'CREATE TABLE "material_clase" (
 "cod_mat" character varying(20) NOT NULL,
 "cod_cla" character varying(20) NOT NULL,
 "cod_pub" character varying(20),
 "cod_usu" character varying(20) NOT NULL,
 "nom_mat" character varying(180) NOT NULL,
 "tip_mat" character varying(255) NOT NULL DEFAULT \'ARCHIVO\'::character varying,
 "rut_mat" character varying(255),
 "url_mat" character varying(500),
 "mime_mat" character varying(120),
 "tam_mat" bigint,
 "est_mat" character varying(255) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 "unidad_id" bigint,
 "cod_sec" character varying(20),
 "has_mat" hash_sha256,
 PRIMARY KEY ("cod_mat")
)',
    'indices' => ['CREATE INDEX "material_clase_cod_cla_est_mat_index" ON "material_clase" ("cod_cla", "est_mat")', 'CREATE INDEX "material_clase_cod_cla_index" ON "material_clase" ("cod_cla")', 'CREATE INDEX "material_clase_cod_cla_tip_mat_index" ON "material_clase" ("cod_cla", "tip_mat")', 'CREATE INDEX "material_clase_cod_pub_index" ON "material_clase" ("cod_pub")', 'CREATE INDEX "material_clase_cod_usu_index" ON "material_clase" ("cod_usu")', 'CREATE INDEX "material_clase_est_mat_index" ON "material_clase" ("est_mat")', 'CREATE INDEX "material_clase_tip_mat_index" ON "material_clase" ("tip_mat")', 'CREATE INDEX "material_clase_unit_context_idx" ON "material_clase" ("unidad_id", "cod_cla")'],
    'checks' => [['can_material_clase_est_mat_check', 'CHECK (((est_mat)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'OCULTO\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_material_clase_tip_mat_check', 'CHECK (((tip_mat)::text = ANY ((ARRAY[\'ARCHIVO\'::character varying, \'ENLACE\'::character varying, \'PDF\'::character varying, \'VIDEO\'::character varying, \'IMAGEN\'::character varying, \'DOCUMENTO\'::character varying, \'OTRO\'::character varying])::text[])))'], ['can_ofi_ck_eccef73252bc7773', 'CHECK (((tam_mat IS NULL) OR (tam_mat >= 0)))'], ['can_ofi_ck_f449a3c8f76175bf', 'CHECK (((rut_mat IS NOT NULL) OR (url_mat IS NOT NULL)))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'tarea',
    'sql' => 'CREATE TABLE "tarea" (
 "cod_tar" character varying(20) NOT NULL,
 "cod_cla" character varying(20) NOT NULL,
 "cod_doc" character varying(20) NOT NULL,
 "tit_tar" character varying(180) NOT NULL,
 "des_tar" text,
 "tip_tar" character varying(255) NOT NULL DEFAULT \'TAREA\'::character varying,
 "fec_pub_tar" timestamp(0) without time zone,
 "fec_lim_tar" timestamp(0) without time zone,
 "pun_max_tar" numeric(6,2) NOT NULL DEFAULT \'100\'::numeric,
 "perm_ent_tardia" boolean NOT NULL DEFAULT false,
 "est_tar" character varying(255) NOT NULL DEFAULT \'BORRADOR\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 "unidad_id" bigint,
 "cod_sec" character varying(20),
 "cod_pev" character varying(20),
 "ape_tar" timestamp with time zone,
 "cor_tar" timestamp with time zone,
 "int_tar" integer,
 "arc_tar" integer,
 "tam_tar" bigint,
 PRIMARY KEY ("cod_tar")
)',
    'indices' => ['CREATE INDEX "tarea_cod_cla_est_tar_index" ON "tarea" ("cod_cla", "est_tar")', 'CREATE INDEX "tarea_cod_cla_index" ON "tarea" ("cod_cla")', 'CREATE INDEX "tarea_cod_cla_tip_tar_index" ON "tarea" ("cod_cla", "tip_tar")', 'CREATE INDEX "tarea_cod_doc_est_tar_index" ON "tarea" ("cod_doc", "est_tar")', 'CREATE INDEX "tarea_cod_doc_index" ON "tarea" ("cod_doc")', 'CREATE INDEX "tarea_est_tar_index" ON "tarea" ("est_tar")', 'CREATE INDEX "tarea_fec_lim_tar_index" ON "tarea" ("fec_lim_tar")', 'CREATE INDEX "tarea_fec_pub_tar_index" ON "tarea" ("fec_pub_tar")', 'CREATE INDEX "tarea_tip_tar_index" ON "tarea" ("tip_tar")', 'CREATE INDEX "tarea_unit_context_idx" ON "tarea" ("unidad_id", "cod_cla")'],
    'checks' => [['can_tarea_tip_tar_check', 'CHECK (((tip_tar)::text = ANY ((ARRAY[\'TAREA\'::character varying, \'PRACTICA\'::character varying, \'PROYECTO\'::character varying, \'INVESTIGACION\'::character varying, \'LABORATORIO\'::character varying, \'EVALUACION\'::character varying])::text[])))'], ['can_tarea_est_tar_check', 'CHECK (((est_tar)::text = ANY ((ARRAY[\'BORRADOR\'::character varying, \'PUBLICADA\'::character varying, \'CERRADA\'::character varying, \'ANULADA\'::character varying])::text[])))'], ['can_lms_task_maximum_check', 'CHECK (((pun_max_tar >= (1)::numeric) AND (pun_max_tar <= (1000)::numeric)))'], ['can_ofi_ck_99281024fe5bc021', 'CHECK ((pun_max_tar > (0)::numeric))'], ['can_ofi_ck_8778850609420f0c', 'CHECK ((int_tar > 0))'], ['can_ofi_ck_52e8767baba01551', 'CHECK (((arc_tar IS NULL) OR (arc_tar > 0)))'], ['can_ofi_ck_54ab001aecaeec09', 'CHECK (((tam_tar IS NULL) OR (tam_tar > 0)))'], ['can_ofi_ck_df3996f53d3216c2', 'CHECK ((((ape_tar IS NULL) OR (fec_lim_tar >= ape_tar)) AND ((cor_tar IS NULL) OR (cor_tar >= fec_lim_tar))))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'tarea_material',
    'sql' => 'CREATE TABLE "tarea_material" (
 "cod_tar_mat" character varying(20) NOT NULL,
 "cod_tar" character varying(20) NOT NULL,
 "nom_tar_mat" character varying(180) NOT NULL,
 "tip_tar_mat" character varying(255) NOT NULL DEFAULT \'ARCHIVO\'::character varying,
 "rut_tar_mat" character varying(255),
 "url_tar_mat" character varying(500),
 "mime_tar_mat" character varying(120),
 "tam_tar_mat" bigint,
 "est_tar_mat" character varying(255) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 "has_tma" hash_sha256,
 PRIMARY KEY ("cod_tar_mat")
)',
    'indices' => ['CREATE INDEX "tarea_material_cod_tar_est_tar_mat_index" ON "tarea_material" ("cod_tar", "est_tar_mat")', 'CREATE INDEX "tarea_material_cod_tar_index" ON "tarea_material" ("cod_tar")', 'CREATE INDEX "tarea_material_cod_tar_tip_tar_mat_index" ON "tarea_material" ("cod_tar", "tip_tar_mat")', 'CREATE INDEX "tarea_material_est_tar_mat_index" ON "tarea_material" ("est_tar_mat")', 'CREATE INDEX "tarea_material_tip_tar_mat_index" ON "tarea_material" ("tip_tar_mat")'],
    'checks' => [['can_ofi_ck_b1537e4523ef48de', 'CHECK (((tam_tar_mat IS NULL) OR (tam_tar_mat >= 0)))'], ['can_ofi_ck_c97709af34a76239', 'CHECK (((rut_tar_mat IS NOT NULL) OR (url_tar_mat IS NOT NULL)))'], ['can_tarea_material_est_tar_mat_check', 'CHECK (((est_tar_mat)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'OCULTO\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_tarea_material_tip_tar_mat_check', 'CHECK (((tip_tar_mat)::text = ANY ((ARRAY[\'ARCHIVO\'::character varying, \'ENLACE\'::character varying, \'PDF\'::character varying, \'VIDEO\'::character varying, \'IMAGEN\'::character varying, \'DOCUMENTO\'::character varying, \'OTRO\'::character varying])::text[])))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'entrega_tarea',
    'sql' => 'CREATE TABLE "entrega_tarea" (
 "cod_ent" character varying(20) NOT NULL,
 "cod_tar" character varying(20) NOT NULL,
 "cod_est" character varying(20) NOT NULL,
 "fec_ent" timestamp(0) without time zone,
 "tex_ent" text,
 "est_ent" character varying(255) NOT NULL DEFAULT \'PENDIENTE\'::character varying,
 "obs_ent" text,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 "int_ent" integer,
 "ini_ent" timestamp with time zone,
 PRIMARY KEY ("cod_ent"),
 CONSTRAINT "ofi_uq_ea4ef1874aae4e0d" UNIQUE ("cod_tar", "cod_est", "int_ent"),
 CONSTRAINT "uq_entrega_tarea_estudiante" UNIQUE ("cod_tar", "cod_est")
)',
    'indices' => ['CREATE INDEX "entrega_tarea_cod_est_est_ent_index" ON "entrega_tarea" ("cod_est", "est_ent")', 'CREATE INDEX "entrega_tarea_cod_est_index" ON "entrega_tarea" ("cod_est")', 'CREATE INDEX "entrega_tarea_cod_tar_cod_est_index" ON "entrega_tarea" ("cod_tar", "cod_est")', 'CREATE INDEX "entrega_tarea_cod_tar_est_ent_index" ON "entrega_tarea" ("cod_tar", "est_ent")', 'CREATE INDEX "entrega_tarea_cod_tar_index" ON "entrega_tarea" ("cod_tar")', 'CREATE INDEX "entrega_tarea_est_ent_index" ON "entrega_tarea" ("est_ent")', 'CREATE INDEX "entrega_tarea_fec_ent_index" ON "entrega_tarea" ("fec_ent")'],
    'checks' => [['can_entrega_tarea_est_ent_check', 'CHECK (((est_ent)::text = ANY ((ARRAY[\'PENDIENTE\'::character varying, \'ENTREGADO\'::character varying, \'ENTREGADO_TARDE\'::character varying, \'DEVUELTO\'::character varying, \'CALIFICADO\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_ofi_ck_3929070d877b2d1d', 'CHECK ((int_ent > 0))'], ['can_ofi_ck_f4f4e13a9d149fa8', 'CHECK (((fec_ent IS NULL) OR (fec_ent >= ini_ent)))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'entrega_archivo',
    'sql' => 'CREATE TABLE "entrega_archivo" (
 "cod_ent_arc" character varying(20) NOT NULL,
 "cod_ent" character varying(20) NOT NULL,
 "nom_arc" character varying(180) NOT NULL,
 "rut_arc" character varying(255) NOT NULL,
 "mime_arc" character varying(120),
 "tam_arc" bigint,
 "est_arc" character varying(255) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 "has_arc" hash_sha256,
 PRIMARY KEY ("cod_ent_arc")
)',
    'indices' => ['CREATE INDEX "entrega_archivo_cod_ent_est_arc_index" ON "entrega_archivo" ("cod_ent", "est_arc")', 'CREATE INDEX "entrega_archivo_cod_ent_index" ON "entrega_archivo" ("cod_ent")', 'CREATE INDEX "entrega_archivo_est_arc_index" ON "entrega_archivo" ("est_arc")', 'CREATE INDEX "entrega_archivo_mime_arc_index" ON "entrega_archivo" ("mime_arc")'],
    'checks' => [['can_entrega_archivo_est_arc_check', 'CHECK (((est_arc)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_ofi_ck_e81bc891ca39df1c', 'CHECK (((tam_arc IS NULL) OR (tam_arc >= 0)))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'calificacion_tarea',
    'sql' => 'CREATE TABLE "calificacion_tarea" (
 "cod_cal_tar" character varying(20) NOT NULL,
 "cod_ent" character varying(20) NOT NULL,
 "cod_tar" character varying(20) NOT NULL,
 "cod_est" character varying(20) NOT NULL,
 "cod_doc" character varying(20) NOT NULL,
 "pun_obt" numeric(6,2) NOT NULL DEFAULT \'0\'::numeric,
 "pun_max" numeric(6,2) NOT NULL DEFAULT \'100\'::numeric,
 "com_cal" text,
 "fec_cal" timestamp(0) without time zone,
 "est_cal" character varying(255) NOT NULL DEFAULT \'REGISTRADO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 "pub_cal" timestamp with time zone,
 PRIMARY KEY ("cod_cal_tar"),
 CONSTRAINT "uq_calificacion_por_entrega" UNIQUE ("cod_ent")
)',
    'indices' => ['CREATE INDEX "calificacion_tarea_cod_doc_est_cal_index" ON "calificacion_tarea" ("cod_doc", "est_cal")', 'CREATE INDEX "calificacion_tarea_cod_doc_index" ON "calificacion_tarea" ("cod_doc")', 'CREATE INDEX "calificacion_tarea_cod_est_index" ON "calificacion_tarea" ("cod_est")', 'CREATE INDEX "calificacion_tarea_cod_tar_cod_est_index" ON "calificacion_tarea" ("cod_tar", "cod_est")', 'CREATE INDEX "calificacion_tarea_cod_tar_index" ON "calificacion_tarea" ("cod_tar")', 'CREATE INDEX "calificacion_tarea_est_cal_index" ON "calificacion_tarea" ("est_cal")', 'CREATE INDEX "calificacion_tarea_fec_cal_index" ON "calificacion_tarea" ("fec_cal")'],
    'checks' => [['can_calificacion_tarea_est_cal_check', 'CHECK (((est_cal)::text = ANY ((ARRAY[\'REGISTRADO\'::character varying, \'RECTIFICADO\'::character varying, \'DEVUELTO\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_lms_submission_score_check', 'CHECK (((pun_max > (0)::numeric) AND (pun_obt >= (0)::numeric) AND (pun_obt <= pun_max)))'], ['can_ofi_ck_61ce6f975fac08dc', 'CHECK ((pun_obt >= (0)::numeric))'], ['can_ofi_ck_68bd518e7fc1cf2c', 'CHECK ((pun_max > (0)::numeric))'], ['can_ofi_ck_cdc849848a25439b', 'CHECK ((pun_obt <= pun_max))'], ['can_ofi_ck_ceb6537ffe2c3b12', 'CHECK (((pub_cal IS NULL) OR (pub_cal >= fec_cal)))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'retroalimentacion_archivo',
    'sql' => 'CREATE TABLE "retroalimentacion_archivo" (
 "cod_raf" character varying(20) NOT NULL,
 "cod_cal_tar" character varying(20) NOT NULL,
 "nom_raf" character varying(255) NOT NULL,
 "rut_raf" text NOT NULL,
 "mim_raf" character varying(150),
 "tam_raf" bigint,
 "has_raf" hash_sha256,
 "est_raf" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_raf")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_525cabdd83f33e6e', 'CHECK (((tam_raf IS NULL) OR (tam_raf >= 0)))'], ['can_ofi_ck_cb5c6ed0cf070050', 'CHECK (((est_raf)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'ANULADO\'::character varying])::text[])))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'cuestionario',
    'sql' => 'CREATE TABLE "cuestionario" (
 "cod_cue" character varying(20) NOT NULL,
 "cod_cla" character varying(20) NOT NULL,
 "cod_sec" character varying(20),
 "cod_doc" character varying(20) NOT NULL,
 "cod_pev" character varying(20),
 "tit_cue" character varying(220) NOT NULL,
 "des_cue" text,
 "pub_cue" timestamp with time zone,
 "ape_cue" timestamp with time zone NOT NULL,
 "cie_cue" timestamp with time zone NOT NULL,
 "dur_cue" integer,
 "int_cue" integer NOT NULL DEFAULT 1,
 "met_cue" character varying(40) NOT NULL DEFAULT \'ULTIMO\'::character varying,
 "mez_cue" boolean NOT NULL DEFAULT false,
 "mos_cue" boolean NOT NULL DEFAULT true,
 "max_cue" numeric(8,2) NOT NULL,
 "est_cue" character varying(20) NOT NULL DEFAULT \'BORRADOR\'::character varying,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_cue")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_a7ef990aa82e9790', 'CHECK (((dur_cue IS NULL) OR (dur_cue > 0)))'], ['can_ofi_ck_fd1e8f90744f4269', 'CHECK ((int_cue > 0))'], ['can_ofi_ck_0df70722414d7a52', 'CHECK (((met_cue)::text = ANY ((ARRAY[\'ULTIMO\'::character varying, \'MEJOR\'::character varying, \'PROMEDIO\'::character varying, \'PRIMERO\'::character varying])::text[])))'], ['can_ofi_ck_135eb13ffbc69fe4', 'CHECK ((max_cue > (0)::numeric))'], ['can_ofi_ck_67a95ae25131e8ef', 'CHECK (((est_cue)::text = ANY ((ARRAY[\'BORRADOR\'::character varying, \'PUBLICADO\'::character varying, \'CERRADO\'::character varying, \'ARCHIVADO\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_ofi_ck_f5804e6e6fe2ff76', 'CHECK ((cie_cue > ape_cue))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'pregunta_cuestionario',
    'sql' => 'CREATE TABLE "pregunta_cuestionario" (
 "cod_prc" character varying(20) NOT NULL,
 "cod_cue" character varying(20) NOT NULL,
 "tip_prc" character varying(40) NOT NULL,
 "enu_prc" text NOT NULL,
 "pun_prc" numeric(8,2) NOT NULL,
 "ord_prc" integer NOT NULL,
 "req_prc" boolean NOT NULL DEFAULT true,
 "est_prc" character varying(20) NOT NULL DEFAULT \'ACTIVA\'::character varying,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "ofi_uq_27c92f94a4230b51" UNIQUE ("cod_cue", "ord_prc"),
 PRIMARY KEY ("cod_prc")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_11a6748987574be0', 'CHECK ((ord_prc > 0))'], ['can_ofi_ck_1589eed4489f6cf4', 'CHECK (((tip_prc)::text = ANY ((ARRAY[\'OPCION_UNICA\'::character varying, \'OPCION_MULTIPLE\'::character varying, \'VERDADERO_FALSO\'::character varying, \'RESPUESTA_CORTA\'::character varying, \'DESARROLLO\'::character varying])::text[])))'], ['can_ofi_ck_67e8247d15290b29', 'CHECK (((est_prc)::text = ANY ((ARRAY[\'ACTIVA\'::character varying, \'INACTIVA\'::character varying, \'ANULADA\'::character varying])::text[])))'], ['can_ofi_ck_fad13f22360d736a', 'CHECK ((pun_prc > (0)::numeric))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'opcion_pregunta',
    'sql' => 'CREATE TABLE "opcion_pregunta" (
 "cod_opr" character varying(20) NOT NULL,
 "cod_prc" character varying(20) NOT NULL,
 "tex_opr" text NOT NULL,
 "por_opr" porcentaje_0_100 NOT NULL DEFAULT 0,
 "ord_opr" integer NOT NULL,
 "est_opr" character varying(20) NOT NULL DEFAULT \'ACTIVA\'::character varying,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "ofi_uq_5e33ad343e022794" UNIQUE ("cod_prc", "ord_opr"),
 PRIMARY KEY ("cod_opr")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_26bef1db7c6215a7', 'CHECK ((ord_opr > 0))'], ['can_ofi_ck_cfe8fdf2fb28e0b6', 'CHECK (((est_opr)::text = ANY ((ARRAY[\'ACTIVA\'::character varying, \'INACTIVA\'::character varying, \'ANULADA\'::character varying])::text[])))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'intento_cuestionario',
    'sql' => 'CREATE TABLE "intento_cuestionario" (
 "cod_inc" character varying(20) NOT NULL,
 "cod_cue" character varying(20) NOT NULL,
 "cod_est" character varying(20) NOT NULL,
 "num_inc" integer NOT NULL,
 "ini_inc" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "fin_inc" timestamp with time zone,
 "pun_inc" numeric(8,2),
 "max_inc" numeric(8,2) NOT NULL,
 "est_inc" character varying(20) NOT NULL DEFAULT \'EN_PROCESO\'::character varying,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_inc"),
 CONSTRAINT "ofi_uq_62fa1cf6d7b5587b" UNIQUE ("cod_cue", "cod_est", "num_inc")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_014148a235b277eb', 'CHECK ((max_inc > (0)::numeric))'], ['can_ofi_ck_2a619ea10b01fe54', 'CHECK (((pun_inc IS NULL) OR (pun_inc <= max_inc)))'], ['can_ofi_ck_9ff4654fb130c7e2', 'CHECK (((fin_inc IS NULL) OR (fin_inc >= ini_inc)))'], ['can_ofi_ck_a21a8a2574c387a8', 'CHECK (((est_inc)::text = ANY ((ARRAY[\'EN_PROCESO\'::character varying, \'FINALIZADO\'::character varying, \'CALIFICADO\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_ofi_ck_c80615ce39fcad3e', 'CHECK (((pun_inc IS NULL) OR (pun_inc >= (0)::numeric)))'], ['can_ofi_ck_f72560447da1a7c4', 'CHECK ((num_inc > 0))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'respuesta_cuestionario',
    'sql' => 'CREATE TABLE "respuesta_cuestionario" (
 "cod_rcu" character varying(20) NOT NULL,
 "cod_inc" character varying(20) NOT NULL,
 "cod_prc" character varying(20) NOT NULL,
 "tex_rcu" text,
 "pun_rcu" numeric(8,2),
 "cor_rcu" boolean,
 "doc_rcu" character varying(20),
 "fec_rcu" timestamp with time zone,
 "obs_rcu" text,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "ofi_uq_12a4dd5eb0e478af" UNIQUE ("cod_inc", "cod_prc"),
 PRIMARY KEY ("cod_rcu")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_c4b80996e657127c', 'CHECK (((pun_rcu IS NULL) OR (pun_rcu >= (0)::numeric)))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'respuesta_opcion',
    'sql' => 'CREATE TABLE "respuesta_opcion" (
 "cod_rop" character varying(20) NOT NULL,
 "cod_rcu" character varying(20) NOT NULL,
 "cod_opr" character varying(20) NOT NULL,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "ofi_uq_5d0c3abf35c780e7" UNIQUE ("cod_rcu", "cod_opr"),
 PRIMARY KEY ("cod_rop")
)',
    'indices' => [],
    'checks' => [],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'foro_clase',
    'sql' => 'CREATE TABLE "foro_clase" (
 "cod_for" character varying(20) NOT NULL,
 "cod_cla" character varying(20) NOT NULL,
 "cod_sec" character varying(20),
 "cod_doc" character varying(20) NOT NULL,
 "tit_for" character varying(220) NOT NULL,
 "des_for" text NOT NULL,
 "ape_for" timestamp with time zone NOT NULL,
 "cie_for" timestamp with time zone,
 "est_for" character varying(20) NOT NULL DEFAULT \'ABIERTO\'::character varying,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_for")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_626075ff8968ca02', 'CHECK (((cie_for IS NULL) OR (cie_for >= ape_for)))'], ['can_ofi_ck_bd98310e0987a851', 'CHECK (((est_for)::text = ANY ((ARRAY[\'BORRADOR\'::character varying, \'ABIERTO\'::character varying, \'CERRADO\'::character varying, \'ARCHIVADO\'::character varying, \'ANULADO\'::character varying])::text[])))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'foro_tema',
    'sql' => 'CREATE TABLE "foro_tema" (
 "cod_fte" character varying(20) NOT NULL,
 "cod_for" character varying(20) NOT NULL,
 "cod_usu" character varying(20) NOT NULL,
 "tit_fte" character varying(220) NOT NULL,
 "fec_fte" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "est_fte" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_fte")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_dcb33bae39d6a32d', 'CHECK (((est_fte)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'CERRADO\'::character varying, \'OCULTO\'::character varying, \'ANULADO\'::character varying])::text[])))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'foro_mensaje',
    'sql' => 'CREATE TABLE "foro_mensaje" (
 "cod_fme" character varying(20) NOT NULL,
 "cod_fte" character varying(20) NOT NULL,
 "cod_usu" character varying(20) NOT NULL,
 "pad_fme" character varying(20),
 "con_fme" text NOT NULL,
 "fec_fme" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "est_fme" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_fme")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_41a6e2a2369b4170', 'CHECK (((est_fme)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'EDITADO\'::character varying, \'OCULTO\'::character varying, \'ANULADO\'::character varying])::text[])))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'foro_archivo',
    'sql' => 'CREATE TABLE "foro_archivo" (
 "cod_far" character varying(20) NOT NULL,
 "cod_fme" character varying(20) NOT NULL,
 "nom_far" character varying(255) NOT NULL,
 "rut_far" text NOT NULL,
 "mim_far" character varying(150),
 "tam_far" bigint,
 "has_far" hash_sha256,
 "est_far" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_far")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_0bd58452c6aaef63', 'CHECK (((tam_far IS NULL) OR (tam_far >= 0)))'], ['can_ofi_ck_e9852b9cfdc06178', 'CHECK (((est_far)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'ANULADO\'::character varying])::text[])))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
], [
    'tabla' => 'registro_actividad_clase',
    'sql' => 'CREATE TABLE "registro_actividad_clase" (
 "cod_rac" character varying(20) NOT NULL,
 "cod_cla" character varying(20) NOT NULL,
 "cod_est" character varying(20),
 "cod_usu" character varying(20) NOT NULL,
 "tip_rac" character varying(80) NOT NULL,
 "pub_rac" character varying(20),
 "mat_rac" character varying(20),
 "tar_rac" character varying(20),
 "cue_rac" character varying(20),
 "for_rac" character varying(20),
 "men_rac" character varying(20),
 "fec_rac" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "met_rac" jsonb,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_rac")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_221dcc06ff3b395a', 'CHECK (((met_rac IS NULL) OR (jsonb_typeof(met_rac) = \'object\'::text)))'], ['can_ofi_ck_a4f9d924dec345a3', 'CHECK ((num_nonnulls(pub_rac, mat_rac, tar_rac, cue_rac, for_rac, men_rac) <= 1))']],
    'grupo' => 'AulaVirtual',
    'unicos' => [],
]];
