<?php

declare(strict_types=1);

/** Contrato aditivo Academico. Fuente: guía aprobada 2026-10-03; sin backfill ni retiro. */
return [
    [
        'tabla' => 'gestion_academica',
        'creacion' => 'CREATE TABLE "gestion_academica" (
 "cod_gea" VARCHAR(20) PRIMARY KEY,
 "ani_gea" INTEGER NOT NULL UNIQUE,
 "fii_gea" DATE NOT NULL,
 "ffi_gea" DATE NOT NULL,
 "est_gea" VARCHAR(20) NOT NULL DEFAULT \'PLANIFICADA\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'ani_gea' => '"ani_gea" INTEGER NULL',
            'fii_gea' => '"fii_gea" DATE NULL',
            'ffi_gea' => '"ffi_gea" DATE NULL',
            'est_gea' => '"est_gea" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_gea',
        'columnas' => [
            'cod_gea' => 'VARCHAR(20) PRIMARY KEY',
            'ani_gea' => 'INTEGER NOT NULL UNIQUE',
            'fii_gea' => 'DATE NOT NULL',
            'ffi_gea' => 'DATE NOT NULL',
            'est_gea' => 'VARCHAR(20) NOT NULL DEFAULT \'PLANIFICADA\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'ani_gea BETWEEN 2000 AND 2200',
            'est_gea IN (\'PLANIFICADA\',\'ACTIVA\',\'CERRADA\',\'ANULADA\')',
            'ffi_gea>=fii_gea',
        ],
        'unicos' => [
            [
                'ani_gea',
            ],
        ],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'periodo_evaluacion',
        'creacion' => 'CREATE TABLE "periodo_evaluacion" (
 "cod_pev" VARCHAR(20) PRIMARY KEY,
 "nom_pev" VARCHAR(120) NOT NULL UNIQUE,
 "ord_pev" SMALLINT NOT NULL UNIQUE,
 "est_pev" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'nom_pev' => '"nom_pev" VARCHAR(120) NULL',
            'ord_pev' => '"ord_pev" SMALLINT NULL',
            'est_pev' => '"est_pev" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_pev',
        'columnas' => [
            'cod_pev' => 'VARCHAR(20) PRIMARY KEY',
            'nom_pev' => 'VARCHAR(120) NOT NULL UNIQUE',
            'ord_pev' => 'SMALLINT NOT NULL UNIQUE',
            'est_pev' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'ord_pev>0',
            'est_pev IN (\'ACTIVO\',\'INACTIVO\')',
        ],
        'unicos' => [
            [
                'nom_pev',
            ],
            [
                'ord_pev',
            ],
        ],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'configuracion_calendario_gestion',
        'creacion' => 'CREATE TABLE "configuracion_calendario_gestion" (
 "cod_ccg" VARCHAR(20) PRIMARY KEY,
 "cod_gea" VARCHAR(20) NOT NULL,
 "cod_pev" VARCHAR(20) NOT NULL,
 "dias_req_ccg" INTEGER,
 "fii_tri_ccg" DATE NOT NULL,
 "ffi_tri_ccg" DATE NOT NULL,
 "cie_ccg" TIMESTAMPTZ,
 "est_ccg" VARCHAR(20) NOT NULL DEFAULT \'PLANIFICADO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_gea' => '"cod_gea" VARCHAR(20) NULL',
            'cod_pev' => '"cod_pev" VARCHAR(20) NULL',
            'dias_req_ccg' => '"dias_req_ccg" INTEGER NULL',
            'fii_tri_ccg' => '"fii_tri_ccg" DATE NULL',
            'ffi_tri_ccg' => '"ffi_tri_ccg" DATE NULL',
            'cie_ccg' => '"cie_ccg" TIMESTAMPTZ NULL',
            'est_ccg' => '"est_ccg" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_ccg',
        'columnas' => [
            'cod_ccg' => 'VARCHAR(20) PRIMARY KEY',
            'cod_gea' => 'VARCHAR(20) NOT NULL',
            'cod_pev' => 'VARCHAR(20) NOT NULL',
            'dias_req_ccg' => 'INTEGER',
            'fii_tri_ccg' => 'DATE NOT NULL',
            'ffi_tri_ccg' => 'DATE NOT NULL',
            'cie_ccg' => 'TIMESTAMPTZ',
            'est_ccg' => 'VARCHAR(20) NOT NULL DEFAULT \'PLANIFICADO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'dias_req_ccg IS NULL OR dias_req_ccg>0',
            'est_ccg IN (\'PLANIFICADO\',\'ACTIVO\',\'CERRADO\',\'ANULADO\')',
            'ffi_tri_ccg>=fii_tri_ccg',
        ],
        'unicos' => [
            [
                'cod_gea',
                'cod_pev',
            ],
        ],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'curso',
        'creacion' => 'CREATE TABLE "curso" (
 "cod_cur" VARCHAR(20) PRIMARY KEY,
 "nom_cur" VARCHAR(120) NOT NULL,
 "niv_cur" VARCHAR(80) NOT NULL,
 "ord_cur" SMALLINT,
 "est_cur" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'nom_cur' => '"nom_cur" VARCHAR(120) NULL',
            'niv_cur' => '"niv_cur" VARCHAR(80) NULL',
            'ord_cur' => '"ord_cur" SMALLINT NULL',
            'est_cur' => '"est_cur" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_cur',
        'columnas' => [
            'cod_cur' => 'VARCHAR(20) PRIMARY KEY',
            'nom_cur' => 'VARCHAR(120) NOT NULL',
            'niv_cur' => 'VARCHAR(80) NOT NULL',
            'ord_cur' => 'SMALLINT',
            'est_cur' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'ord_cur IS NULL OR ord_cur>0',
            'est_cur IN (\'ACTIVO\',\'INACTIVO\')',
        ],
        'unicos' => [
            [
                'nom_cur',
                'niv_cur',
            ],
        ],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'paralelo',
        'creacion' => 'CREATE TABLE "paralelo" (
 "cod_par" VARCHAR(20) PRIMARY KEY,
 "nom_par" VARCHAR(30) NOT NULL UNIQUE,
 "est_par" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'nom_par' => '"nom_par" VARCHAR(30) NULL',
            'est_par' => '"est_par" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_par',
        'columnas' => [
            'cod_par' => 'VARCHAR(20) PRIMARY KEY',
            'nom_par' => 'VARCHAR(30) NOT NULL UNIQUE',
            'est_par' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_par IN (\'ACTIVO\',\'INACTIVO\')',
        ],
        'unicos' => [
            [
                'nom_par',
            ],
        ],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'turno',
        'creacion' => 'CREATE TABLE "turno" (
 "cod_tur" VARCHAR(20) PRIMARY KEY,
 "nom_tur" VARCHAR(80) NOT NULL UNIQUE,
 "hor_ini_tur" TIME,
 "hor_fin_tur" TIME,
 "est_tur" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'nom_tur' => '"nom_tur" VARCHAR(80) NULL',
            'hor_ini_tur' => '"hor_ini_tur" TIME NULL',
            'hor_fin_tur' => '"hor_fin_tur" TIME NULL',
            'est_tur' => '"est_tur" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_tur',
        'columnas' => [
            'cod_tur' => 'VARCHAR(20) PRIMARY KEY',
            'nom_tur' => 'VARCHAR(80) NOT NULL UNIQUE',
            'hor_ini_tur' => 'TIME',
            'hor_fin_tur' => 'TIME',
            'est_tur' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_tur IN (\'ACTIVO\',\'INACTIVO\')',
            'hor_ini_tur IS NULL OR hor_fin_tur IS NULL OR hor_fin_tur>hor_ini_tur',
        ],
        'unicos' => [
            [
                'nom_tur',
            ],
        ],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'grupo_academico',
        'creacion' => 'CREATE TABLE "grupo_academico" (
 "cod_gac" VARCHAR(20) PRIMARY KEY,
 "cod_gea" VARCHAR(20) NOT NULL,
 "cod_cur" VARCHAR(20) NOT NULL,
 "cod_par" VARCHAR(20) NOT NULL,
 "cod_tur" VARCHAR(20) NOT NULL,
 "cap_gac" INTEGER,
 "est_gac" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "obs_gac" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_gea' => '"cod_gea" VARCHAR(20) NULL',
            'cod_cur' => '"cod_cur" VARCHAR(20) NULL',
            'cod_par' => '"cod_par" VARCHAR(20) NULL',
            'cod_tur' => '"cod_tur" VARCHAR(20) NULL',
            'cap_gac' => '"cap_gac" INTEGER NULL',
            'est_gac' => '"est_gac" VARCHAR(20) NULL',
            'obs_gac' => '"obs_gac" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_gac',
        'columnas' => [
            'cod_gac' => 'VARCHAR(20) PRIMARY KEY',
            'cod_gea' => 'VARCHAR(20) NOT NULL',
            'cod_cur' => 'VARCHAR(20) NOT NULL',
            'cod_par' => 'VARCHAR(20) NOT NULL',
            'cod_tur' => 'VARCHAR(20) NOT NULL',
            'cap_gac' => 'INTEGER',
            'est_gac' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'obs_gac' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'cap_gac IS NULL OR cap_gac>0',
            'est_gac IN (\'ACTIVO\',\'INACTIVO\',\'CERRADO\',\'ANULADO\')',
        ],
        'unicos' => [
            [
                'cod_gea',
                'cod_cur',
                'cod_par',
                'cod_tur',
            ],
        ],
        'grupo' => 'Academico',
        'existente' => false,
    ],
    [
        'tabla' => 'asignatura',
        'creacion' => 'CREATE TABLE "asignatura" (
 "cod_asi" VARCHAR(20) PRIMARY KEY,
 "nom_asi" VARCHAR(180) NOT NULL,
 "sig_asi" VARCHAR(30),
 "hor_asi" NUMERIC(6,2),
 "est_asi" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'nom_asi' => '"nom_asi" VARCHAR(180) NULL',
            'sig_asi' => '"sig_asi" VARCHAR(30) NULL',
            'hor_asi' => '"hor_asi" NUMERIC(6,2) NULL',
            'est_asi' => '"est_asi" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_asi',
        'columnas' => [
            'cod_asi' => 'VARCHAR(20) PRIMARY KEY',
            'nom_asi' => 'VARCHAR(180) NOT NULL',
            'sig_asi' => 'VARCHAR(30)',
            'hor_asi' => 'NUMERIC(6,2)',
            'est_asi' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'hor_asi IS NULL OR hor_asi>=0',
            'est_asi IN (\'ACTIVO\',\'INACTIVO\')',
        ],
        'unicos' => [],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'especialidad_tecnica',
        'creacion' => 'CREATE TABLE "especialidad_tecnica" (
 "cod_esp" VARCHAR(20) PRIMARY KEY,
 "nom_esp" VARCHAR(180) NOT NULL,
 "des_esp" TEXT,
 "est_esp" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'nom_esp' => '"nom_esp" VARCHAR(180) NULL',
            'des_esp' => '"des_esp" TEXT NULL',
            'est_esp' => '"est_esp" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_esp',
        'columnas' => [
            'cod_esp' => 'VARCHAR(20) PRIMARY KEY',
            'nom_esp' => 'VARCHAR(180) NOT NULL',
            'des_esp' => 'TEXT',
            'est_esp' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_esp IN (\'ACTIVO\',\'INACTIVO\')',
        ],
        'unicos' => [],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'aula',
        'creacion' => 'CREATE TABLE "aula" (
 "cod_aul" VARCHAR(20) PRIMARY KEY,
 "nom_aul" VARCHAR(120) NOT NULL UNIQUE,
 "tip_aul" VARCHAR(80),
 "ubi_aul" TEXT,
 "cap_aul" INTEGER,
 "est_aul" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'nom_aul' => '"nom_aul" VARCHAR(120) NULL',
            'tip_aul' => '"tip_aul" VARCHAR(80) NULL',
            'ubi_aul' => '"ubi_aul" TEXT NULL',
            'cap_aul' => '"cap_aul" INTEGER NULL',
            'est_aul' => '"est_aul" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_aul',
        'columnas' => [
            'cod_aul' => 'VARCHAR(20) PRIMARY KEY',
            'nom_aul' => 'VARCHAR(120) NOT NULL UNIQUE',
            'tip_aul' => 'VARCHAR(80)',
            'ubi_aul' => 'TEXT',
            'cap_aul' => 'INTEGER',
            'est_aul' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'cap_aul IS NULL OR cap_aul>0',
            'est_aul IN (\'ACTIVO\',\'INACTIVO\',\'MANTENIMIENTO\')',
        ],
        'unicos' => [
            [
                'nom_aul',
            ],
        ],
        'grupo' => 'Academico',
        'existente' => false,
    ],
    [
        'tabla' => 'plan_asignatura',
        'creacion' => 'CREATE TABLE "plan_asignatura" (
 "cod_pas" VARCHAR(20) PRIMARY KEY,
 "cod_asi" VARCHAR(20) NOT NULL,
 "cod_doc" VARCHAR(20) NOT NULL,
 "cod_gac" VARCHAR(20) NOT NULL,
 "hor_pas" NUMERIC(6,2),
 "fii_pas" DATE NOT NULL,
 "ffi_pas" DATE,
 "est_pas" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_asi' => '"cod_asi" VARCHAR(20) NULL',
            'cod_doc' => '"cod_doc" VARCHAR(20) NULL',
            'cod_gac' => '"cod_gac" VARCHAR(20) NULL',
            'hor_pas' => '"hor_pas" NUMERIC(6,2) NULL',
            'fii_pas' => '"fii_pas" DATE NULL',
            'ffi_pas' => '"ffi_pas" DATE NULL',
            'est_pas' => '"est_pas" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_pas',
        'columnas' => [
            'cod_pas' => 'VARCHAR(20) PRIMARY KEY',
            'cod_asi' => 'VARCHAR(20) NOT NULL',
            'cod_doc' => 'VARCHAR(20) NOT NULL',
            'cod_gac' => 'VARCHAR(20) NOT NULL',
            'hor_pas' => 'NUMERIC(6,2)',
            'fii_pas' => 'DATE NOT NULL',
            'ffi_pas' => 'DATE',
            'est_pas' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'hor_pas IS NULL OR hor_pas>=0',
            'est_pas IN (\'ACTIVO\',\'FINALIZADO\',\'SUSPENDIDO\',\'ANULADO\')',
            'ffi_pas IS NULL OR ffi_pas>=fii_pas',
        ],
        'unicos' => [],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'plan_especialidad',
        'creacion' => 'CREATE TABLE "plan_especialidad" (
 "cod_pes" VARCHAR(20) PRIMARY KEY,
 "cod_esp" VARCHAR(20) NOT NULL,
 "cod_doc" VARCHAR(20) NOT NULL,
 "cod_gac" VARCHAR(20) NOT NULL,
 "hor_pes" NUMERIC(6,2),
 "fii_pes" DATE NOT NULL,
 "ffi_pes" DATE,
 "est_pes" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_esp' => '"cod_esp" VARCHAR(20) NULL',
            'cod_doc' => '"cod_doc" VARCHAR(20) NULL',
            'cod_gac' => '"cod_gac" VARCHAR(20) NULL',
            'hor_pes' => '"hor_pes" NUMERIC(6,2) NULL',
            'fii_pes' => '"fii_pes" DATE NULL',
            'ffi_pes' => '"ffi_pes" DATE NULL',
            'est_pes' => '"est_pes" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_pes',
        'columnas' => [
            'cod_pes' => 'VARCHAR(20) PRIMARY KEY',
            'cod_esp' => 'VARCHAR(20) NOT NULL',
            'cod_doc' => 'VARCHAR(20) NOT NULL',
            'cod_gac' => 'VARCHAR(20) NOT NULL',
            'hor_pes' => 'NUMERIC(6,2)',
            'fii_pes' => 'DATE NOT NULL',
            'ffi_pes' => 'DATE',
            'est_pes' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'hor_pes IS NULL OR hor_pes>=0',
            'est_pes IN (\'ACTIVO\',\'FINALIZADO\',\'SUSPENDIDO\',\'ANULADO\')',
            'ffi_pes IS NULL OR ffi_pes>=fii_pes',
        ],
        'unicos' => [],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'plantilla_horaria',
        'creacion' => 'CREATE TABLE "plantilla_horaria" (
 "cod_pho" VARCHAR(20) PRIMARY KEY,
 "cod_tur" VARCHAR(20) NOT NULL,
 "nom_pho" VARCHAR(160) NOT NULL,
 "tip_pho" VARCHAR(80),
 "des_pho" TEXT,
 "fec_ini_pho" DATE,
 "fec_fin_pho" DATE,
 "dur_blo_pho" INTEGER,
 "ord_pho" SMALLINT,
 "act_pho" BOOLEAN NOT NULL DEFAULT TRUE,
 "est_pho" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_tur' => '"cod_tur" VARCHAR(20) NULL',
            'nom_pho' => '"nom_pho" VARCHAR(160) NULL',
            'tip_pho' => '"tip_pho" VARCHAR(80) NULL',
            'des_pho' => '"des_pho" TEXT NULL',
            'fec_ini_pho' => '"fec_ini_pho" DATE NULL',
            'fec_fin_pho' => '"fec_fin_pho" DATE NULL',
            'dur_blo_pho' => '"dur_blo_pho" INTEGER NULL',
            'ord_pho' => '"ord_pho" SMALLINT NULL',
            'act_pho' => '"act_pho" BOOLEAN NULL',
            'est_pho' => '"est_pho" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_pho',
        'columnas' => [
            'cod_pho' => 'VARCHAR(20) PRIMARY KEY',
            'cod_tur' => 'VARCHAR(20) NOT NULL',
            'nom_pho' => 'VARCHAR(160) NOT NULL',
            'tip_pho' => 'VARCHAR(80)',
            'des_pho' => 'TEXT',
            'fec_ini_pho' => 'DATE',
            'fec_fin_pho' => 'DATE',
            'dur_blo_pho' => 'INTEGER',
            'ord_pho' => 'SMALLINT',
            'act_pho' => 'BOOLEAN NOT NULL DEFAULT TRUE',
            'est_pho' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'dur_blo_pho IS NULL OR dur_blo_pho>0',
            'ord_pho IS NULL OR ord_pho>0',
            'est_pho IN (\'ACTIVO\',\'INACTIVO\',\'ANULADO\')',
            'fec_fin_pho IS NULL OR fec_ini_pho IS NULL OR fec_fin_pho>=fec_ini_pho',
        ],
        'unicos' => [
            [
                'cod_tur',
                'nom_pho',
            ],
        ],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'horario_bloque',
        'creacion' => 'CREATE TABLE "horario_bloque" (
 "cod_hbl" VARCHAR(20) PRIMARY KEY,
 "cod_pho" VARCHAR(20) NOT NULL,
 "num_hbl" SMALLINT NOT NULL,
 "hor_ini_hbl" TIME NOT NULL,
 "hor_fin_hbl" TIME NOT NULL,
 "nom_hbl" VARCHAR(120),
 "tip_hbl" VARCHAR(80),
 "obs_hbl" TEXT,
 "est_hbl" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_pho' => '"cod_pho" VARCHAR(20) NULL',
            'num_hbl' => '"num_hbl" SMALLINT NULL',
            'hor_ini_hbl' => '"hor_ini_hbl" TIME NULL',
            'hor_fin_hbl' => '"hor_fin_hbl" TIME NULL',
            'nom_hbl' => '"nom_hbl" VARCHAR(120) NULL',
            'tip_hbl' => '"tip_hbl" VARCHAR(80) NULL',
            'obs_hbl' => '"obs_hbl" TEXT NULL',
            'est_hbl' => '"est_hbl" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_hbl',
        'columnas' => [
            'cod_hbl' => 'VARCHAR(20) PRIMARY KEY',
            'cod_pho' => 'VARCHAR(20) NOT NULL',
            'num_hbl' => 'SMALLINT NOT NULL',
            'hor_ini_hbl' => 'TIME NOT NULL',
            'hor_fin_hbl' => 'TIME NOT NULL',
            'nom_hbl' => 'VARCHAR(120)',
            'tip_hbl' => 'VARCHAR(80)',
            'obs_hbl' => 'TEXT',
            'est_hbl' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'num_hbl>0',
            'est_hbl IN (\'ACTIVO\',\'INACTIVO\')',
            'hor_fin_hbl>hor_ini_hbl',
        ],
        'unicos' => [
            [
                'cod_pho',
                'num_hbl',
            ],
        ],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'horario',
        'creacion' => 'CREATE TABLE "horario" (
 "cod_hor" VARCHAR(20) PRIMARY KEY,
 "cod_gac" VARCHAR(20) NOT NULL,
 "cod_pho" VARCHAR(20) NOT NULL,
 "fii_hor" DATE NOT NULL,
 "ffi_hor" DATE,
 "obs_hor" TEXT,
 "est_hor" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_gac' => '"cod_gac" VARCHAR(20) NULL',
            'cod_pho' => '"cod_pho" VARCHAR(20) NULL',
            'fii_hor' => '"fii_hor" DATE NULL',
            'ffi_hor' => '"ffi_hor" DATE NULL',
            'obs_hor' => '"obs_hor" TEXT NULL',
            'est_hor' => '"est_hor" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_hor',
        'columnas' => [
            'cod_hor' => 'VARCHAR(20) PRIMARY KEY',
            'cod_gac' => 'VARCHAR(20) NOT NULL',
            'cod_pho' => 'VARCHAR(20) NOT NULL',
            'fii_hor' => 'DATE NOT NULL',
            'ffi_hor' => 'DATE',
            'obs_hor' => 'TEXT',
            'est_hor' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_hor IN (\'ACTIVO\',\'FINALIZADO\',\'ANULADO\')',
            'ffi_hor IS NULL OR ffi_hor>=fii_hor',
        ],
        'unicos' => [],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'horario_detalle',
        'creacion' => 'CREATE TABLE "horario_detalle" (
 "cod_hde" VARCHAR(20) PRIMARY KEY,
 "cod_hor" VARCHAR(20) NOT NULL,
 "cod_hbl" VARCHAR(20) NOT NULL,
 "dia_hde" SMALLINT NOT NULL,
 "cod_pas" VARCHAR(20),
 "cod_pes" VARCHAR(20),
 "cod_aul" VARCHAR(20),
 "obs_hde" TEXT,
 "est_hde" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_hor' => '"cod_hor" VARCHAR(20) NULL',
            'cod_hbl' => '"cod_hbl" VARCHAR(20) NULL',
            'dia_hde' => '"dia_hde" SMALLINT NULL',
            'cod_pas' => '"cod_pas" VARCHAR(20) NULL',
            'cod_pes' => '"cod_pes" VARCHAR(20) NULL',
            'cod_aul' => '"cod_aul" VARCHAR(20) NULL',
            'obs_hde' => '"obs_hde" TEXT NULL',
            'est_hde' => '"est_hde" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_hde',
        'columnas' => [
            'cod_hde' => 'VARCHAR(20) PRIMARY KEY',
            'cod_hor' => 'VARCHAR(20) NOT NULL',
            'cod_hbl' => 'VARCHAR(20) NOT NULL',
            'dia_hde' => 'SMALLINT NOT NULL',
            'cod_pas' => 'VARCHAR(20)',
            'cod_pes' => 'VARCHAR(20)',
            'cod_aul' => 'VARCHAR(20)',
            'obs_hde' => 'TEXT',
            'est_hde' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'dia_hde BETWEEN 1 AND 7',
            'est_hde IN (\'ACTIVO\',\'INACTIVO\',\'ANULADO\')',
            'num_nonnulls(cod_pas,cod_pes)=1',
        ],
        'unicos' => [],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'calendario_evento',
        'creacion' => 'CREATE TABLE "calendario_evento" (
 "cod_cae" VARCHAR(20) PRIMARY KEY,
 "cod_gea" VARCHAR(20) NOT NULL,
 "nom_cae" VARCHAR(200) NOT NULL,
 "tip_cae" VARCHAR(80) NOT NULL,
 "fii_cae" DATE NOT NULL,
 "ffi_cae" DATE,
 "hoi_cae" TIME,
 "hof_cae" TIME,
 "cod_tur" VARCHAR(20),
 "cod_cur" VARCHAR(20),
 "cod_par" VARCHAR(20),
 "cod_hde" VARCHAR(20),
 "est_cae" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "efe_cae" VARCHAR(120),
 "com_cae" TEXT,
 "cod_cae_ori" VARCHAR(20),
 "mot_cae" TEXT,
 "fue_cae" VARCHAR(255),
 "ent_cae" VARCHAR(255),
 "tip_doc_cae" VARCHAR(120),
 "num_doc_cae" VARCHAR(120),
 "fec_emi_cae" DATE,
 "fec_pub_cae" DATE,
 "url_cae" url_http,
 "niv_cae" VARCHAR(50),
 "cer_cae" BOOLEAN NOT NULL DEFAULT FALSE,
 "cod_cae_ant" VARCHAR(20),
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_gea' => '"cod_gea" VARCHAR(20) NULL',
            'nom_cae' => '"nom_cae" VARCHAR(200) NULL',
            'tip_cae' => '"tip_cae" VARCHAR(80) NULL',
            'fii_cae' => '"fii_cae" DATE NULL',
            'ffi_cae' => '"ffi_cae" DATE NULL',
            'hoi_cae' => '"hoi_cae" TIME NULL',
            'hof_cae' => '"hof_cae" TIME NULL',
            'cod_tur' => '"cod_tur" VARCHAR(20) NULL',
            'cod_cur' => '"cod_cur" VARCHAR(20) NULL',
            'cod_par' => '"cod_par" VARCHAR(20) NULL',
            'cod_hde' => '"cod_hde" VARCHAR(20) NULL',
            'est_cae' => '"est_cae" VARCHAR(20) NULL',
            'efe_cae' => '"efe_cae" VARCHAR(120) NULL',
            'com_cae' => '"com_cae" TEXT NULL',
            'cod_cae_ori' => '"cod_cae_ori" VARCHAR(20) NULL',
            'mot_cae' => '"mot_cae" TEXT NULL',
            'fue_cae' => '"fue_cae" VARCHAR(255) NULL',
            'ent_cae' => '"ent_cae" VARCHAR(255) NULL',
            'tip_doc_cae' => '"tip_doc_cae" VARCHAR(120) NULL',
            'num_doc_cae' => '"num_doc_cae" VARCHAR(120) NULL',
            'fec_emi_cae' => '"fec_emi_cae" DATE NULL',
            'fec_pub_cae' => '"fec_pub_cae" DATE NULL',
            'url_cae' => '"url_cae" url_http NULL',
            'niv_cae' => '"niv_cae" VARCHAR(50) NULL',
            'cer_cae' => '"cer_cae" BOOLEAN NULL',
            'cod_cae_ant' => '"cod_cae_ant" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_cae',
        'columnas' => [
            'cod_cae' => 'VARCHAR(20) PRIMARY KEY',
            'cod_gea' => 'VARCHAR(20) NOT NULL',
            'nom_cae' => 'VARCHAR(200) NOT NULL',
            'tip_cae' => 'VARCHAR(80) NOT NULL',
            'fii_cae' => 'DATE NOT NULL',
            'ffi_cae' => 'DATE',
            'hoi_cae' => 'TIME',
            'hof_cae' => 'TIME',
            'cod_tur' => 'VARCHAR(20)',
            'cod_cur' => 'VARCHAR(20)',
            'cod_par' => 'VARCHAR(20)',
            'cod_hde' => 'VARCHAR(20)',
            'est_cae' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'efe_cae' => 'VARCHAR(120)',
            'com_cae' => 'TEXT',
            'cod_cae_ori' => 'VARCHAR(20)',
            'mot_cae' => 'TEXT',
            'fue_cae' => 'VARCHAR(255)',
            'ent_cae' => 'VARCHAR(255)',
            'tip_doc_cae' => 'VARCHAR(120)',
            'num_doc_cae' => 'VARCHAR(120)',
            'fec_emi_cae' => 'DATE',
            'fec_pub_cae' => 'DATE',
            'url_cae' => 'url_http',
            'niv_cae' => 'VARCHAR(50)',
            'cer_cae' => 'BOOLEAN NOT NULL DEFAULT FALSE',
            'cod_cae_ant' => 'VARCHAR(20)',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_cae IN (\'ACTIVO\',\'INACTIVO\',\'ANULADO\')',
            'ffi_cae IS NULL OR ffi_cae>=fii_cae',
            'hoi_cae IS NULL OR hof_cae IS NULL OR hof_cae>hoi_cae',
        ],
        'unicos' => [],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'sesion_academica',
        'creacion' => 'CREATE TABLE "sesion_academica" (
 "cod_ses" VARCHAR(20) PRIMARY KEY,
 "cod_hde" VARCHAR(20) NOT NULL,
 "fec_ses" DATE NOT NULL,
 "hor_pla_ses" NUMERIC(5,2),
 "hor_rea_ses" NUMERIC(5,2),
 "est_ses" VARCHAR(20) NOT NULL DEFAULT \'PROGRAMADA\',
 "cod_cae" VARCHAR(20),
 "cod_ses_ori" VARCHAR(20),
 "obs_ses" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_hde' => '"cod_hde" VARCHAR(20) NULL',
            'fec_ses' => '"fec_ses" DATE NULL',
            'hor_pla_ses' => '"hor_pla_ses" NUMERIC(5,2) NULL',
            'hor_rea_ses' => '"hor_rea_ses" NUMERIC(5,2) NULL',
            'est_ses' => '"est_ses" VARCHAR(20) NULL',
            'cod_cae' => '"cod_cae" VARCHAR(20) NULL',
            'cod_ses_ori' => '"cod_ses_ori" VARCHAR(20) NULL',
            'obs_ses' => '"obs_ses" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_ses',
        'columnas' => [
            'cod_ses' => 'VARCHAR(20) PRIMARY KEY',
            'cod_hde' => 'VARCHAR(20) NOT NULL',
            'fec_ses' => 'DATE NOT NULL',
            'hor_pla_ses' => 'NUMERIC(5,2)',
            'hor_rea_ses' => 'NUMERIC(5,2)',
            'est_ses' => 'VARCHAR(20) NOT NULL DEFAULT \'PROGRAMADA\'',
            'cod_cae' => 'VARCHAR(20)',
            'cod_ses_ori' => 'VARCHAR(20)',
            'obs_ses' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'hor_pla_ses IS NULL OR hor_pla_ses>=0',
            'hor_rea_ses IS NULL OR hor_rea_ses>=0',
            'est_ses IN (\'PROGRAMADA\',\'REALIZADA\',\'SUSPENDIDA\',\'REPROGRAMADA\',\'ANULADA\')',
        ],
        'unicos' => [
            [
                'cod_hde',
                'fec_ses',
            ],
        ],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'inscripcion_estudiante',
        'creacion' => 'CREATE TABLE "inscripcion_estudiante" (
 "cod_ins" VARCHAR(20) PRIMARY KEY,
 "cod_est" VARCHAR(20) NOT NULL,
 "cod_gea" VARCHAR(20) NOT NULL,
 "fei_ins" DATE NOT NULL,
 "tip_ins" VARCHAR(80),
 "est_ins" VARCHAR(20) NOT NULL DEFAULT \'ACTIVA\',
 "fec_con_ins" TIMESTAMPTZ,
 "fec_anu_ins" TIMESTAMPTZ,
 "mot_anu_ins" TEXT,
 "fec_ret_ins" TIMESTAMPTZ,
 "mot_ret_ins" TEXT,
 "obs_ins" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_est' => '"cod_est" VARCHAR(20) NULL',
            'cod_gea' => '"cod_gea" VARCHAR(20) NULL',
            'fei_ins' => '"fei_ins" DATE NULL',
            'tip_ins' => '"tip_ins" VARCHAR(80) NULL',
            'est_ins' => '"est_ins" VARCHAR(20) NULL',
            'fec_con_ins' => '"fec_con_ins" TIMESTAMPTZ NULL',
            'fec_anu_ins' => '"fec_anu_ins" TIMESTAMPTZ NULL',
            'mot_anu_ins' => '"mot_anu_ins" TEXT NULL',
            'fec_ret_ins' => '"fec_ret_ins" TIMESTAMPTZ NULL',
            'mot_ret_ins' => '"mot_ret_ins" TEXT NULL',
            'obs_ins' => '"obs_ins" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_ins',
        'columnas' => [
            'cod_ins' => 'VARCHAR(20) PRIMARY KEY',
            'cod_est' => 'VARCHAR(20) NOT NULL',
            'cod_gea' => 'VARCHAR(20) NOT NULL',
            'fei_ins' => 'DATE NOT NULL',
            'tip_ins' => 'VARCHAR(80)',
            'est_ins' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVA\'',
            'fec_con_ins' => 'TIMESTAMPTZ',
            'fec_anu_ins' => 'TIMESTAMPTZ',
            'mot_anu_ins' => 'TEXT',
            'fec_ret_ins' => 'TIMESTAMPTZ',
            'mot_ret_ins' => 'TEXT',
            'obs_ins' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_ins IN (\'PENDIENTE\',\'ACTIVA\',\'RETIRADA\',\'ANULADA\',\'CERRADA\')',
        ],
        'unicos' => [
            [
                'cod_est',
                'cod_gea',
            ],
        ],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'inscripcion_vigencia',
        'creacion' => 'CREATE TABLE "inscripcion_vigencia" (
 "cod_ivg" VARCHAR(20) PRIMARY KEY,
 "cod_ins" VARCHAR(20) NOT NULL,
 "cod_gac" VARCHAR(20) NOT NULL,
 "cod_esp_tec" VARCHAR(20),
 "fii_ivg" DATE NOT NULL,
 "ffi_ivg" DATE,
 "tip_ivg" VARCHAR(80),
 "cie_ivg" VARCHAR(120),
 "mot_ivg" TEXT,
 "obs_ivg" TEXT,
 "est_ivg" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_ins' => '"cod_ins" VARCHAR(20) NULL',
            'cod_gac' => '"cod_gac" VARCHAR(20) NULL',
            'cod_esp_tec' => '"cod_esp_tec" VARCHAR(20) NULL',
            'fii_ivg' => '"fii_ivg" DATE NULL',
            'ffi_ivg' => '"ffi_ivg" DATE NULL',
            'tip_ivg' => '"tip_ivg" VARCHAR(80) NULL',
            'cie_ivg' => '"cie_ivg" VARCHAR(120) NULL',
            'mot_ivg' => '"mot_ivg" TEXT NULL',
            'obs_ivg' => '"obs_ivg" TEXT NULL',
            'est_ivg' => '"est_ivg" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_ivg',
        'columnas' => [
            'cod_ivg' => 'VARCHAR(20) PRIMARY KEY',
            'cod_ins' => 'VARCHAR(20) NOT NULL',
            'cod_gac' => 'VARCHAR(20) NOT NULL',
            'cod_esp_tec' => 'VARCHAR(20)',
            'fii_ivg' => 'DATE NOT NULL',
            'ffi_ivg' => 'DATE',
            'tip_ivg' => 'VARCHAR(80)',
            'cie_ivg' => 'VARCHAR(120)',
            'mot_ivg' => 'TEXT',
            'obs_ivg' => 'TEXT',
            'est_ivg' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_ivg IN (\'ACTIVO\',\'CERRADO\',\'ANULADO\')',
            'ffi_ivg IS NULL OR ffi_ivg>=fii_ivg',
        ],
        'unicos' => [],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'estado_asistencia',
        'creacion' => 'CREATE TABLE "estado_asistencia" (
 "cod_est_asi" VARCHAR(20) PRIMARY KEY,
 "nom_est_asi" VARCHAR(80) NOT NULL UNIQUE,
 "abr_est_asi" VARCHAR(10) NOT NULL UNIQUE,
 "des_est_asi" TEXT,
 "color_est_asi" VARCHAR(20),
 "valor_porcentual" porcentaje_0_100,
 "afecta_asistencia" BOOLEAN NOT NULL DEFAULT TRUE,
 "requiere_observacion" BOOLEAN NOT NULL DEFAULT FALSE,
 "est_est_asi" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'nom_est_asi' => '"nom_est_asi" VARCHAR(80) NULL',
            'abr_est_asi' => '"abr_est_asi" VARCHAR(10) NULL',
            'des_est_asi' => '"des_est_asi" TEXT NULL',
            'color_est_asi' => '"color_est_asi" VARCHAR(20) NULL',
            'valor_porcentual' => '"valor_porcentual" porcentaje_0_100 NULL',
            'afecta_asistencia' => '"afecta_asistencia" BOOLEAN NULL',
            'requiere_observacion' => '"requiere_observacion" BOOLEAN NULL',
            'est_est_asi' => '"est_est_asi" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_est_asi',
        'columnas' => [
            'cod_est_asi' => 'VARCHAR(20) PRIMARY KEY',
            'nom_est_asi' => 'VARCHAR(80) NOT NULL UNIQUE',
            'abr_est_asi' => 'VARCHAR(10) NOT NULL UNIQUE',
            'des_est_asi' => 'TEXT',
            'color_est_asi' => 'VARCHAR(20)',
            'valor_porcentual' => 'porcentaje_0_100',
            'afecta_asistencia' => 'BOOLEAN NOT NULL DEFAULT TRUE',
            'requiere_observacion' => 'BOOLEAN NOT NULL DEFAULT FALSE',
            'est_est_asi' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_est_asi IN (\'ACTIVO\',\'INACTIVO\')',
        ],
        'unicos' => [
            [
                'nom_est_asi',
            ],
            [
                'abr_est_asi',
            ],
        ],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'asistencia_clase',
        'creacion' => 'CREATE TABLE "asistencia_clase" (
 "cod_asi_cla" VARCHAR(20) PRIMARY KEY,
 "cod_ses" VARCHAR(20) NOT NULL UNIQUE,
 "cod_doc" VARCHAR(20) NOT NULL,
 "cod_usu_reg" VARCHAR(20) NOT NULL,
 "hor_ini_asi_cla" TIME,
 "hor_fin_asi_cla" TIME,
 "tip_asi_cla" VARCHAR(80),
 "tit_asi_cla" VARCHAR(200),
 "obs_asi_cla" TEXT,
 "ori_asi_cla" VARCHAR(80),
 "est_asi_cla" VARCHAR(20) NOT NULL DEFAULT \'ABIERTO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_ses' => '"cod_ses" VARCHAR(20) NULL',
            'cod_doc' => '"cod_doc" VARCHAR(20) NULL',
            'cod_usu_reg' => '"cod_usu_reg" VARCHAR(20) NULL',
            'hor_ini_asi_cla' => '"hor_ini_asi_cla" TIME NULL',
            'hor_fin_asi_cla' => '"hor_fin_asi_cla" TIME NULL',
            'tip_asi_cla' => '"tip_asi_cla" VARCHAR(80) NULL',
            'tit_asi_cla' => '"tit_asi_cla" VARCHAR(200) NULL',
            'obs_asi_cla' => '"obs_asi_cla" TEXT NULL',
            'ori_asi_cla' => '"ori_asi_cla" VARCHAR(80) NULL',
            'est_asi_cla' => '"est_asi_cla" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_asi_cla',
        'columnas' => [
            'cod_asi_cla' => 'VARCHAR(20) PRIMARY KEY',
            'cod_ses' => 'VARCHAR(20) NOT NULL UNIQUE',
            'cod_doc' => 'VARCHAR(20) NOT NULL',
            'cod_usu_reg' => 'VARCHAR(20) NOT NULL',
            'hor_ini_asi_cla' => 'TIME',
            'hor_fin_asi_cla' => 'TIME',
            'tip_asi_cla' => 'VARCHAR(80)',
            'tit_asi_cla' => 'VARCHAR(200)',
            'obs_asi_cla' => 'TEXT',
            'ori_asi_cla' => 'VARCHAR(80)',
            'est_asi_cla' => 'VARCHAR(20) NOT NULL DEFAULT \'ABIERTO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_asi_cla IN (\'ABIERTO\',\'CERRADO\',\'ANULADO\')',
            'hor_ini_asi_cla IS NULL OR hor_fin_asi_cla IS NULL OR hor_fin_asi_cla>=hor_ini_asi_cla',
        ],
        'unicos' => [
            [
                'cod_ses',
            ],
        ],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'asistencia_estudiante',
        'creacion' => 'CREATE TABLE "asistencia_estudiante" (
 "cod_asi_est" VARCHAR(20) PRIMARY KEY,
 "cod_asi_cla" VARCHAR(20) NOT NULL,
 "cod_est" VARCHAR(20) NOT NULL,
 "cod_est_asi" VARCHAR(20) NOT NULL,
 "cod_usu_reg" VARCHAR(20) NOT NULL,
 "cod_nes" VARCHAR(20),
 "min_retraso" INTEGER NOT NULL DEFAULT 0,
 "obs_asi_est" TEXT,
 "fec_reg_asi_est" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "est_asi_est" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_asi_cla' => '"cod_asi_cla" VARCHAR(20) NULL',
            'cod_est' => '"cod_est" VARCHAR(20) NULL',
            'cod_est_asi' => '"cod_est_asi" VARCHAR(20) NULL',
            'cod_usu_reg' => '"cod_usu_reg" VARCHAR(20) NULL',
            'cod_nes' => '"cod_nes" VARCHAR(20) NULL',
            'min_retraso' => '"min_retraso" INTEGER NULL',
            'obs_asi_est' => '"obs_asi_est" TEXT NULL',
            'fec_reg_asi_est' => '"fec_reg_asi_est" TIMESTAMPTZ NULL',
            'est_asi_est' => '"est_asi_est" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_asi_est',
        'columnas' => [
            'cod_asi_est' => 'VARCHAR(20) PRIMARY KEY',
            'cod_asi_cla' => 'VARCHAR(20) NOT NULL',
            'cod_est' => 'VARCHAR(20) NOT NULL',
            'cod_est_asi' => 'VARCHAR(20) NOT NULL',
            'cod_usu_reg' => 'VARCHAR(20) NOT NULL',
            'cod_nes' => 'VARCHAR(20)',
            'min_retraso' => 'INTEGER NOT NULL DEFAULT 0',
            'obs_asi_est' => 'TEXT',
            'fec_reg_asi_est' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'est_asi_est' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'min_retraso>=0',
            'est_asi_est IN (\'ACTIVO\',\'RECTIFICADO\',\'ANULADO\')',
        ],
        'unicos' => [
            [
                'cod_asi_cla',
                'cod_est',
            ],
        ],
        'grupo' => 'Academico',
        'existente' => true,
    ],
    [
        'tabla' => 'calificacion',
        'creacion' => 'CREATE TABLE "calificacion" (
 "cod_cal" VARCHAR(20) PRIMARY KEY,
 "cod_ins" VARCHAR(20) NOT NULL,
 "cod_pas" VARCHAR(20),
 "cod_pes" VARCHAR(20),
 "cod_pev" VARCHAR(20) NOT NULL,
 "not_cal" NUMERIC(5,2) NOT NULL,
 "obs_cal" TEXT,
 "est_cal" VARCHAR(20) NOT NULL DEFAULT \'VIGENTE\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_ins' => '"cod_ins" VARCHAR(20) NULL',
            'cod_pas' => '"cod_pas" VARCHAR(20) NULL',
            'cod_pes' => '"cod_pes" VARCHAR(20) NULL',
            'cod_pev' => '"cod_pev" VARCHAR(20) NULL',
            'not_cal' => '"not_cal" NUMERIC(5,2) NULL',
            'obs_cal' => '"obs_cal" TEXT NULL',
            'est_cal' => '"est_cal" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_cal',
        'columnas' => [
            'cod_cal' => 'VARCHAR(20) PRIMARY KEY',
            'cod_ins' => 'VARCHAR(20) NOT NULL',
            'cod_pas' => 'VARCHAR(20)',
            'cod_pes' => 'VARCHAR(20)',
            'cod_pev' => 'VARCHAR(20) NOT NULL',
            'not_cal' => 'NUMERIC(5,2) NOT NULL',
            'obs_cal' => 'TEXT',
            'est_cal' => 'VARCHAR(20) NOT NULL DEFAULT \'VIGENTE\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_cal IN (\'VIGENTE\',\'RECTIFICADA\',\'ANULADA\')',
            'num_nonnulls(cod_pas,cod_pes)=1',
        ],
        'unicos' => [],
        'grupo' => 'Academico',
        'existente' => true,
    ],
];
