<?php

// V001-V105 from arquitectura-maestra-savp/matrices/05-ventanas.csv.
// Runtime paths and provisional states from docs/implementacion-maestra/MATRIZ-CONCILIACION-105.csv.
// These states do not certify functional or visual PASS.
return array (
  0 => 
  array (
    'id' => 'V001',
    'actor' => 'Administrador',
    'name' => 'Inicio',
    'current_path' => '/dashboard',
    'target_path' => '/admin',
    'system' => 'Transversal',
    'runtime_path' => '/admin',
    'status' => 'PARTIAL',
  ),
  1 => 
  array (
    'id' => 'V002',
    'actor' => 'Administrador',
    'name' => 'Personas',
    'current_path' => '/admin/gestion-personas',
    'target_path' => '/admin/personas',
    'system' => 'Institucional',
    'runtime_path' => '/admin/gestion-personas',
    'status' => 'PARTIAL',
  ),
  2 => 
  array (
    'id' => 'V003',
    'actor' => 'Administrador',
    'name' => 'Usuarios',
    'current_path' => '/admin/gestion-usuarios',
    'target_path' => '/admin/usuarios',
    'system' => 'Institucional',
    'runtime_path' => '/admin/gestion-usuarios',
    'status' => 'PARTIAL',
  ),
  3 => 
  array (
    'id' => 'V004',
    'actor' => 'Administrador',
    'name' => 'Personal institucional',
    'current_path' => '/admin/personal-institucional',
    'target_path' => '/admin/personal',
    'system' => 'Institucional',
    'runtime_path' => '/admin/personal-institucional',
    'status' => 'PARTIAL',
  ),
  4 => 
  array (
    'id' => 'V005',
    'actor' => 'Administrador',
    'name' => 'Estudiantes',
    'current_path' => '/admin/gestion-estudiantes',
    'target_path' => '/admin/estudiantes',
    'system' => 'Institucional',
    'runtime_path' => '/admin/gestion-estudiantes',
    'status' => 'PARTIAL',
  ),
  5 => 
  array (
    'id' => 'V006',
    'actor' => 'Administrador',
    'name' => 'Docentes',
    'current_path' => '/admin/gestion-docentes',
    'target_path' => '/admin/docentes',
    'system' => 'Institucional',
    'runtime_path' => '/admin/gestion-docentes',
    'status' => 'PARTIAL',
  ),
  6 => 
  array (
    'id' => 'V007',
    'actor' => 'Administrador',
    'name' => 'Gestión académica',
    'current_path' => '/admin/gestion-academica',
    'target_path' => '/admin/gestion',
    'system' => 'Institucional',
    'runtime_path' => '/admin/gestion-academica',
    'status' => 'PARTIAL',
  ),
  7 => 
  array (
    'id' => 'V008',
    'actor' => 'Administrador',
    'name' => 'Cursos',
    'current_path' => '/admin/gestion-cursos',
    'target_path' => '/admin/cursos',
    'system' => 'Institucional',
    'runtime_path' => '/admin/gestion-cursos',
    'status' => 'PARTIAL',
  ),
  8 => 
  array (
    'id' => 'V009',
    'actor' => 'Administrador',
    'name' => 'Asignaturas',
    'current_path' => '/admin/gestion-asignaturas',
    'target_path' => '/admin/asignaturas',
    'system' => 'Institucional',
    'runtime_path' => '/admin/gestion-asignaturas',
    'status' => 'PARTIAL',
  ),
  9 => 
  array (
    'id' => 'V010',
    'actor' => 'Administrador',
    'name' => 'Paralelos',
    'current_path' => '/admin/gestion-paralelos',
    'target_path' => '/admin/paralelos',
    'system' => 'Institucional',
    'runtime_path' => '/admin/gestion-paralelos',
    'status' => 'PARTIAL',
  ),
  10 => 
  array (
    'id' => 'V011',
    'actor' => 'Administrador',
    'name' => 'Turnos',
    'current_path' => '/admin/gestion-turnos',
    'target_path' => '/admin/turnos',
    'system' => 'Institucional',
    'runtime_path' => '/admin/gestion-turnos',
    'status' => 'PARTIAL',
  ),
  11 => 
  array (
    'id' => 'V012',
    'actor' => 'Administrador',
    'name' => 'Inscripciones',
    'current_path' => '/admin/gestion-inscripciones',
    'target_path' => '/admin/inscripciones',
    'system' => 'Institucional',
    'runtime_path' => '/admin/gestion-inscripciones',
    'status' => 'PARTIAL',
  ),
  12 => 
  array (
    'id' => 'V013',
    'actor' => 'Administrador',
    'name' => 'Especialidades',
    'current_path' => '/admin/especialidades-tecnicas',
    'target_path' => '/admin/especialidades',
    'system' => 'Institucional',
    'runtime_path' => '/admin/especialidades-tecnicas',
    'status' => 'PARTIAL',
  ),
  13 => 
  array (
    'id' => 'V014',
    'actor' => 'Administrador',
    'name' => 'Planes de asignatura',
    'current_path' => '/admin/planes-asignatura',
    'target_path' => '/admin/planes',
    'system' => 'Institucional',
    'runtime_path' => '/admin/planes-asignatura',
    'status' => 'PARTIAL',
  ),
  14 => 
  array (
    'id' => 'V015',
    'actor' => 'Administrador',
    'name' => 'Períodos de evaluación',
    'current_path' => '/admin/periodo-evaluacion',
    'target_path' => '/admin/periodos',
    'system' => 'Institucional',
    'runtime_path' => '/admin/periodo-evaluacion',
    'status' => 'PARTIAL',
  ),
  15 => 
  array (
    'id' => 'V016',
    'actor' => 'Administrador',
    'name' => 'Calendario',
    'current_path' => '/admin/calendario-academico',
    'target_path' => '/admin/calendario',
    'system' => 'Transversal',
    'runtime_path' => '/admin/calendario',
    'status' => 'PARTIAL',
  ),
  16 => 
  array (
    'id' => 'V017',
    'actor' => 'Administrador',
    'name' => 'Calificaciones institucionales',
    'current_path' => '/admin/calificaciones',
    'target_path' => '/admin/notas-oficiales',
    'system' => 'Institucional',
    'runtime_path' => '/admin/calificaciones',
    'status' => 'PARTIAL',
  ),
  17 => 
  array (
    'id' => 'V018',
    'actor' => 'Administrador',
    'name' => 'Reportes académicos',
    'current_path' => '/admin/reportes-academicos',
    'target_path' => '/admin/reportes-academicos',
    'system' => 'Transversal',
    'runtime_path' => '/admin/reportes-academicos',
    'status' => 'PARTIAL',
  ),
  18 => 
  array (
    'id' => 'V019',
    'actor' => 'Administrador',
    'name' => 'Reportes administrativos',
    'current_path' => '/admin/reportes-administrativos',
    'target_path' => '/admin/reportes-administrativos',
    'system' => 'Institucional',
    'runtime_path' => '/admin/reportes-administrativos',
    'status' => 'PARTIAL',
  ),
  19 => 
  array (
    'id' => 'V020',
    'actor' => 'Administrador',
    'name' => 'Roles y permisos',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/admin/roles',
    'system' => 'Seguridad',
    'runtime_path' => '/admin/roles-permisos',
    'status' => 'PARTIAL',
  ),
  20 => 
  array (
    'id' => 'V021',
    'actor' => 'Administrador',
    'name' => 'Bitácora',
    'current_path' => '/admin/bitacora',
    'target_path' => '/admin/bitacora',
    'system' => 'Seguridad',
    'runtime_path' => '/admin/bitacora',
    'status' => 'PARTIAL',
  ),
  21 => 
  array (
    'id' => 'V022',
    'actor' => 'Administrador',
    'name' => 'Kardex parámetros/auditoría',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/admin/kardex-parametros',
    'system' => 'Kardex',
    'runtime_path' => '/admin/kardex-parametros',
    'status' => 'BLOCKED_EXTERNALLY_DB',
  ),
  22 => 
  array (
    'id' => 'V023',
    'actor' => 'Administrador',
    'name' => 'LMS institucional/supervisión',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/admin/lms-supervision',
    'system' => 'LMS',
    'runtime_path' => '/admin/consultas/lms',
    'status' => 'PARTIAL',
  ),
  23 => 
  array (
    'id' => 'V024',
    'actor' => 'Administrador',
    'name' => 'Configuración LMS',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/admin/lms-configuracion',
    'system' => 'LMS',
    'runtime_path' => '/admin/lms-configuracion',
    'status' => 'BLOCKED_EXTERNALLY_INSTITUTIONAL',
  ),
  24 => 
  array (
    'id' => 'V025',
    'actor' => 'Administrador',
    'name' => 'Configuración',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/admin/configuracion',
    'system' => 'Institucional',
    'runtime_path' => '/admin/configuracion',
    'status' => 'BLOCKED_EXTERNALLY_INSTITUTIONAL',
  ),
  25 => 
  array (
    'id' => 'V026',
    'actor' => 'Administrador',
    'name' => 'Mi perfil',
    'current_path' => '/user/profile (vendor; no incluido en 64)',
    'target_path' => '/admin/perfil',
    'system' => 'Identidad',
    'runtime_path' => '/user/profile',
    'status' => 'PARTIAL',
  ),
  26 => 
  array (
    'id' => 'V027',
    'actor' => 'Director',
    'name' => 'Inicio',
    'current_path' => '/dashboard',
    'target_path' => '/direccion',
    'system' => 'Transversal',
    'runtime_path' => '/direccion',
    'status' => 'PARTIAL',
  ),
  27 => 
  array (
    'id' => 'V028',
    'actor' => 'Director',
    'name' => 'Panorama institucional',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/direccion/panorama',
    'system' => 'Analítica',
    'runtime_path' => '/direccion',
    'status' => 'PARTIAL',
  ),
  28 => 
  array (
    'id' => 'V029',
    'actor' => 'Director',
    'name' => 'Gestión académica',
    'current_path' => '/admin/gestion-academica',
    'target_path' => '/direccion/gestion',
    'system' => 'Institucional',
    'runtime_path' => '/direccion/consultas/gestion',
    'status' => 'PARTIAL',
  ),
  29 => 
  array (
    'id' => 'V030',
    'actor' => 'Director',
    'name' => 'Rendimiento',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/direccion/rendimiento',
    'system' => 'Analítica',
    'runtime_path' => '/direccion/consultas/rendimiento',
    'status' => 'PARTIAL',
  ),
  30 => 
  array (
    'id' => 'V031',
    'actor' => 'Director',
    'name' => 'Cursos',
    'current_path' => '/admin/gestion-cursos',
    'target_path' => '/direccion/cursos',
    'system' => 'Institucional',
    'runtime_path' => '/direccion/consultas/cursos',
    'status' => 'PARTIAL',
  ),
  31 => 
  array (
    'id' => 'V032',
    'actor' => 'Director',
    'name' => 'Estudiantes',
    'current_path' => '/admin/gestion-estudiantes',
    'target_path' => '/direccion/estudiantes',
    'system' => 'Institucional',
    'runtime_path' => '/direccion/consultas/estudiantes',
    'status' => 'PARTIAL',
  ),
  32 => 
  array (
    'id' => 'V033',
    'actor' => 'Director',
    'name' => 'Docentes',
    'current_path' => '/admin/gestion-docentes',
    'target_path' => '/direccion/docentes',
    'system' => 'Institucional',
    'runtime_path' => '/direccion/consultas/docentes',
    'status' => 'PARTIAL',
  ),
  33 => 
  array (
    'id' => 'V034',
    'actor' => 'Director',
    'name' => 'Asistencia del alcance',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/direccion/asistencia-institucional',
    'system' => 'Institucional/LMS',
    'runtime_path' => '/direccion/consultas/asistencia',
    'status' => 'PARTIAL',
  ),
  34 => 
  array (
    'id' => 'V035',
    'actor' => 'Director',
    'name' => 'Kardex',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/direccion/kardex',
    'system' => 'Kardex',
    'runtime_path' => '/direccion/kardex',
    'status' => 'BLOCKED_EXTERNALLY_DB',
  ),
  35 => 
  array (
    'id' => 'V036',
    'actor' => 'Director',
    'name' => 'Prevención',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/direccion/prevencion',
    'system' => 'Seguimiento',
    'runtime_path' => '/direccion/prevencion',
    'status' => 'BLOCKED_EXTERNALLY_INSTITUTIONAL',
  ),
  36 => 
  array (
    'id' => 'V037',
    'actor' => 'Director',
    'name' => 'Orientación',
    'current_path' => '/aula-virtual/orientacion | /aula-virtual/orientacion/seguimiento',
    'target_path' => '/direccion/orientacion',
    'system' => 'Orientación',
    'runtime_path' => '/direccion/consultas/orientacion',
    'status' => 'PARTIAL',
  ),
  37 => 
  array (
    'id' => 'V038',
    'actor' => 'Director',
    'name' => 'Seguimientos',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/direccion/seguimientos',
    'system' => 'Seguimiento',
    'runtime_path' => '/direccion/seguimientos',
    'status' => 'BLOCKED_EXTERNALLY_DB',
  ),
  38 => 
  array (
    'id' => 'V039',
    'actor' => 'Director',
    'name' => 'LMS institucional/supervisión',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/direccion/lms-supervision',
    'system' => 'LMS',
    'runtime_path' => '/direccion/consultas/lms',
    'status' => 'PARTIAL',
  ),
  39 => 
  array (
    'id' => 'V040',
    'actor' => 'Director',
    'name' => 'Reportes académicos',
    'current_path' => '/admin/reportes-academicos',
    'target_path' => '/direccion/reportes-academicos',
    'system' => 'Transversal',
    'runtime_path' => '/direccion/consultas/reportes',
    'status' => 'PARTIAL',
  ),
  40 => 
  array (
    'id' => 'V041',
    'actor' => 'Director',
    'name' => 'Reportes administrativos',
    'current_path' => '/admin/reportes-administrativos',
    'target_path' => '/direccion/reportes-administrativos',
    'system' => 'Institucional',
    'runtime_path' => '/direccion/consultas/reportes',
    'status' => 'PARTIAL',
  ),
  41 => 
  array (
    'id' => 'V042',
    'actor' => 'Director',
    'name' => 'Calendario',
    'current_path' => '/admin/calendario-academico',
    'target_path' => '/direccion/calendario',
    'system' => 'Transversal',
    'runtime_path' => '/direccion/calendario',
    'status' => 'PARTIAL',
  ),
  42 => 
  array (
    'id' => 'V043',
    'actor' => 'Director',
    'name' => 'Mi perfil',
    'current_path' => '/user/profile (vendor; no incluido en 64)',
    'target_path' => '/direccion/perfil',
    'system' => 'Identidad',
    'runtime_path' => '/user/profile',
    'status' => 'PARTIAL',
  ),
  43 => 
  array (
    'id' => 'V044',
    'actor' => 'Secretaria',
    'name' => 'Inicio',
    'current_path' => '/dashboard',
    'target_path' => '/secretaria',
    'system' => 'Transversal',
    'runtime_path' => '/secretaria',
    'status' => 'PARTIAL',
  ),
  44 => 
  array (
    'id' => 'V045',
    'actor' => 'Secretaria',
    'name' => 'Personas',
    'current_path' => '/admin/gestion-personas',
    'target_path' => '/secretaria/personas',
    'system' => 'Institucional',
    'runtime_path' => '/secretaria/personas',
    'status' => 'PARTIAL',
  ),
  45 => 
  array (
    'id' => 'V046',
    'actor' => 'Secretaria',
    'name' => 'Estudiantes',
    'current_path' => '/admin/gestion-estudiantes',
    'target_path' => '/secretaria/estudiantes',
    'system' => 'Institucional',
    'runtime_path' => '/secretaria/estudiantes',
    'status' => 'PARTIAL',
  ),
  46 => 
  array (
    'id' => 'V047',
    'actor' => 'Secretaria',
    'name' => 'Inscripciones',
    'current_path' => '/admin/gestion-inscripciones',
    'target_path' => '/secretaria/inscripciones',
    'system' => 'Institucional',
    'runtime_path' => '/secretaria/inscripciones',
    'status' => 'PARTIAL',
  ),
  47 => 
  array (
    'id' => 'V048',
    'actor' => 'Secretaria',
    'name' => 'Documentación',
    'current_path' => '/admin/gestion-inscripciones',
    'target_path' => '/secretaria/documentacion',
    'system' => 'Institucional',
    'runtime_path' => '/secretaria/documentacion',
    'status' => 'PARTIAL',
  ),
  48 => 
  array (
    'id' => 'V049',
    'actor' => 'Secretaria',
    'name' => 'Institución de procedencia',
    'current_path' => '/admin/institucion-procedencia',
    'target_path' => '/secretaria/procedencia',
    'system' => 'Institucional',
    'runtime_path' => '/secretaria/procedencia',
    'status' => 'PARTIAL',
  ),
  49 => 
  array (
    'id' => 'V050',
    'actor' => 'Secretaria',
    'name' => 'Tipo de vinculación',
    'current_path' => '/admin/tipo-vinculacion-estudiante',
    'target_path' => '/secretaria/vinculacion',
    'system' => 'Institucional',
    'runtime_path' => '/secretaria/vinculacion',
    'status' => 'PARTIAL',
  ),
  50 => 
  array (
    'id' => 'V051',
    'actor' => 'Secretaria',
    'name' => 'Cursos',
    'current_path' => '/admin/gestion-cursos',
    'target_path' => '/secretaria/cursos',
    'system' => 'Institucional',
    'runtime_path' => '/secretaria/cursos',
    'status' => 'PARTIAL',
  ),
  51 => 
  array (
    'id' => 'V052',
    'actor' => 'Secretaria',
    'name' => 'Paralelos',
    'current_path' => '/admin/gestion-paralelos',
    'target_path' => '/secretaria/paralelos',
    'system' => 'Institucional',
    'runtime_path' => '/secretaria/paralelos',
    'status' => 'PARTIAL',
  ),
  52 => 
  array (
    'id' => 'V053',
    'actor' => 'Secretaria',
    'name' => 'Turnos',
    'current_path' => '/admin/gestion-turnos',
    'target_path' => '/secretaria/turnos',
    'system' => 'Institucional',
    'runtime_path' => '/secretaria/turnos',
    'status' => 'PARTIAL',
  ),
  53 => 
  array (
    'id' => 'V054',
    'actor' => 'Secretaria',
    'name' => 'Calendario',
    'current_path' => '/admin/calendario-academico',
    'target_path' => '/secretaria/calendario',
    'system' => 'Transversal',
    'runtime_path' => '/secretaria/calendario',
    'status' => 'PARTIAL',
  ),
  54 => 
  array (
    'id' => 'V055',
    'actor' => 'Secretaria',
    'name' => 'Kardex',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/secretaria/kardex',
    'system' => 'Kardex',
    'runtime_path' => '/secretaria/kardex',
    'status' => 'BLOCKED_EXTERNALLY_DB',
  ),
  55 => 
  array (
    'id' => 'V056',
    'actor' => 'Secretaria',
    'name' => 'Reportes administrativos',
    'current_path' => '/admin/reportes-administrativos',
    'target_path' => '/secretaria/reportes-administrativos',
    'system' => 'Institucional',
    'runtime_path' => '/secretaria/reportes',
    'status' => 'PARTIAL',
  ),
  56 => 
  array (
    'id' => 'V057',
    'actor' => 'Secretaria',
    'name' => 'Mi perfil',
    'current_path' => '/user/profile (vendor; no incluido en 64)',
    'target_path' => '/secretaria/perfil',
    'system' => 'Identidad',
    'runtime_path' => '/user/profile',
    'status' => 'PARTIAL',
  ),
  57 => 
  array (
    'id' => 'V058',
    'actor' => 'Regente',
    'name' => 'Inicio',
    'current_path' => '/dashboard',
    'target_path' => '/regencia',
    'system' => 'Transversal',
    'runtime_path' => '/regencia',
    'status' => 'PARTIAL',
  ),
  58 => 
  array (
    'id' => 'V059',
    'actor' => 'Regente',
    'name' => 'Mis grados',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/regencia/mis-grados',
    'system' => 'Institucional',
    'runtime_path' => '/regencia/mis-grados',
    'status' => 'PARTIAL',
  ),
  59 => 
  array (
    'id' => 'V060',
    'actor' => 'Regente',
    'name' => 'Cursos',
    'current_path' => '/admin/gestion-cursos',
    'target_path' => '/regencia/cursos',
    'system' => 'Institucional',
    'runtime_path' => '/regencia/consultas/cursos',
    'status' => 'PARTIAL',
  ),
  60 => 
  array (
    'id' => 'V061',
    'actor' => 'Regente',
    'name' => 'Estudiantes',
    'current_path' => '/admin/gestion-estudiantes',
    'target_path' => '/regencia/estudiantes',
    'system' => 'Institucional',
    'runtime_path' => '/regencia/consultas/estudiantes',
    'status' => 'PARTIAL',
  ),
  61 => 
  array (
    'id' => 'V062',
    'actor' => 'Regente',
    'name' => 'Asistencia del alcance',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/regencia/asistencia-institucional',
    'system' => 'Institucional/LMS',
    'runtime_path' => '/regencia/consultas/asistencia',
    'status' => 'PARTIAL',
  ),
  62 => 
  array (
    'id' => 'V063',
    'actor' => 'Regente',
    'name' => 'Kardex',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/regencia/kardex',
    'system' => 'Kardex',
    'runtime_path' => '/regencia/kardex',
    'status' => 'BLOCKED_EXTERNALLY_DB',
  ),
  63 => 
  array (
    'id' => 'V064',
    'actor' => 'Regente',
    'name' => 'Seguimientos',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/regencia/seguimientos',
    'system' => 'Seguimiento',
    'runtime_path' => '/regencia/seguimientos',
    'status' => 'BLOCKED_EXTERNALLY_DB',
  ),
  64 => 
  array (
    'id' => 'V065',
    'actor' => 'Regente',
    'name' => 'LMS institucional/supervisión',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/regencia/lms-supervision',
    'system' => 'LMS',
    'runtime_path' => '/regencia/consultas/lms',
    'status' => 'PARTIAL',
  ),
  65 => 
  array (
    'id' => 'V066',
    'actor' => 'Regente',
    'name' => 'Alertas',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/regencia/alertas',
    'system' => 'Seguimiento',
    'runtime_path' => '/regencia/alertas',
    'status' => 'BLOCKED_EXTERNALLY_INSTITUTIONAL',
  ),
  66 => 
  array (
    'id' => 'V067',
    'actor' => 'Regente',
    'name' => 'Calendario',
    'current_path' => '/admin/calendario-academico',
    'target_path' => '/regencia/calendario',
    'system' => 'Transversal',
    'runtime_path' => '/regencia/calendario',
    'status' => 'PARTIAL',
  ),
  67 => 
  array (
    'id' => 'V068',
    'actor' => 'Regente',
    'name' => 'Reportes académicos',
    'current_path' => '/admin/reportes-academicos',
    'target_path' => '/regencia/reportes-academicos',
    'system' => 'Transversal',
    'runtime_path' => '/regencia/reportes',
    'status' => 'PARTIAL',
  ),
  68 => 
  array (
    'id' => 'V069',
    'actor' => 'Regente',
    'name' => 'Mi perfil',
    'current_path' => '/user/profile (vendor; no incluido en 64)',
    'target_path' => '/regencia/perfil',
    'system' => 'Identidad',
    'runtime_path' => '/user/profile',
    'status' => 'PARTIAL',
  ),
  69 => 
  array (
    'id' => 'V070',
    'actor' => 'Docente',
    'name' => 'Inicio',
    'current_path' => '/dashboard',
    'target_path' => '/docente',
    'system' => 'Transversal',
    'runtime_path' => '/docente',
    'status' => 'PARTIAL',
  ),
  70 => 
  array (
    'id' => 'V071',
    'actor' => 'Docente',
    'name' => 'Mis cursos/materias',
    'current_path' => '/aula-virtual/mis-cursos',
    'target_path' => '/docente/mis-cursos',
    'system' => 'LMS',
    'runtime_path' => '/docente/cursos',
    'status' => 'PARTIAL',
  ),
  71 => 
  array (
    'id' => 'V072',
    'actor' => 'Docente',
    'name' => 'Curso: resumen',
    'current_path' => '/aula-virtual/mis-cursos/{curso}',
    'target_path' => '/docente/curso',
    'system' => 'LMS',
    'runtime_path' => '/docente/cursos/{curso}?tab=resumen',
    'status' => 'PARTIAL',
  ),
  72 => 
  array (
    'id' => 'V073',
    'actor' => 'Docente',
    'name' => 'Curso: contenido/unidades',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/docente/aula/{curso}/contenido (alias opcional D1; opción A mantiene /aula-virtual)',
    'system' => 'LMS',
    'runtime_path' => '/docente/cursos/{curso}?tab=contenido',
    'status' => 'PARTIAL',
  ),
  73 => 
  array (
    'id' => 'V074',
    'actor' => 'Docente',
    'name' => 'Curso: materiales',
    'current_path' => '/aula-virtual/cursos/{curso}/materiales',
    'target_path' => '/docente/aula/{curso}/materiales (alias opcional D1; opción A mantiene /aula-virtual)',
    'system' => 'LMS',
    'runtime_path' => '/docente/cursos/{curso}?tab=materiales',
    'status' => 'PARTIAL',
  ),
  74 => 
  array (
    'id' => 'V075',
    'actor' => 'Docente',
    'name' => 'Curso: actividades',
    'current_path' => '/aula-virtual/mis-cursos/{curso}',
    'target_path' => '/docente/aula/{curso}/actividades (alias opcional D1; opción A mantiene /aula-virtual)',
    'system' => 'LMS',
    'runtime_path' => '/docente/cursos/{curso}?tab=actividades',
    'status' => 'PARTIAL',
  ),
  75 => 
  array (
    'id' => 'V076',
    'actor' => 'Docente',
    'name' => 'Curso: tareas',
    'current_path' => '/aula-virtual/mis-cursos/{curso}',
    'target_path' => '/docente/aula/{curso}/tareas (alias opcional D1; opción A mantiene /aula-virtual)',
    'system' => 'LMS',
    'runtime_path' => '/docente/cursos/{curso}?tab=tareas',
    'status' => 'PARTIAL',
  ),
  76 => 
  array (
    'id' => 'V077',
    'actor' => 'Docente',
    'name' => 'Curso: entregas',
    'current_path' => '/aula-virtual/tareas/{tarea}/revisar',
    'target_path' => '/docente/aula/{curso}/entregas (alias opcional D1; opción A mantiene /aula-virtual)',
    'system' => 'LMS',
    'runtime_path' => '/docente/cursos/{curso}?tab=entregas',
    'status' => 'PARTIAL',
  ),
  77 => 
  array (
    'id' => 'V078',
    'actor' => 'Docente',
    'name' => 'Curso: asistencia',
    'current_path' => '/aula-virtual/mis-cursos/{curso}/asistencia/registrar',
    'target_path' => '/docente/aula/{curso}/asistencia-aula (alias opcional D1; opción A mantiene /aula-virtual)',
    'system' => 'LMS',
    'runtime_path' => '/docente/cursos/{curso}?tab=asistencia',
    'status' => 'PARTIAL',
  ),
  78 => 
  array (
    'id' => 'V079',
    'actor' => 'Docente',
    'name' => 'Curso: calificaciones',
    'current_path' => '/aula-virtual/tareas/{tarea}/revisar',
    'target_path' => '/docente/aula/{curso}/notas-aula (alias opcional D1; opción A mantiene /aula-virtual)',
    'system' => 'LMS',
    'runtime_path' => '/docente/cursos/{curso}?tab=calificaciones',
    'status' => 'PARTIAL',
  ),
  79 => 
  array (
    'id' => 'V080',
    'actor' => 'Docente',
    'name' => 'Curso: estudiantes',
    'current_path' => '/aula-virtual/mis-cursos/{curso}',
    'target_path' => '/docente/aula/{curso}/alumnos-aula (alias opcional D1; opción A mantiene /aula-virtual)',
    'system' => 'LMS',
    'runtime_path' => '/docente/cursos/{curso}?tab=estudiantes',
    'status' => 'PARTIAL',
  ),
  80 => 
  array (
    'id' => 'V081',
    'actor' => 'Docente',
    'name' => 'Calendario',
    'current_path' => '/admin/calendario-academico',
    'target_path' => '/docente/calendario',
    'system' => 'Transversal',
    'runtime_path' => '/docente/calendario',
    'status' => 'PARTIAL',
  ),
  81 => 
  array (
    'id' => 'V082',
    'actor' => 'Docente',
    'name' => 'Kardex',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/docente/kardex',
    'system' => 'Kardex',
    'runtime_path' => '/docente/kardex',
    'status' => 'BLOCKED_EXTERNALLY_DB',
  ),
  82 => 
  array (
    'id' => 'V083',
    'actor' => 'Docente',
    'name' => 'Seguimientos',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/docente/seguimientos',
    'system' => 'Seguimiento',
    'runtime_path' => '/docente/seguimientos',
    'status' => 'BLOCKED_EXTERNALLY_DB',
  ),
  83 => 
  array (
    'id' => 'V084',
    'actor' => 'Docente',
    'name' => 'Orientación',
    'current_path' => '/aula-virtual/orientacion',
    'target_path' => '/docente/orientacion',
    'system' => 'Orientación',
    'runtime_path' => '/aula-virtual/orientacion/seguimiento',
    'status' => 'PARTIAL',
  ),
  84 => 
  array (
    'id' => 'V085',
    'actor' => 'Docente',
    'name' => 'Reportes académicos',
    'current_path' => '/admin/reportes-academicos',
    'target_path' => '/docente/reportes-academicos',
    'system' => 'Transversal',
    'runtime_path' => '/aula-virtual/reportes',
    'status' => 'PARTIAL',
  ),
  85 => 
  array (
    'id' => 'V086',
    'actor' => 'Docente',
    'name' => 'Mi perfil',
    'current_path' => '/user/profile (vendor; no incluido en 64)',
    'target_path' => '/docente/perfil',
    'system' => 'Identidad',
    'runtime_path' => '/user/profile',
    'status' => 'PARTIAL',
  ),
  86 => 
  array (
    'id' => 'V087',
    'actor' => 'Estudiante',
    'name' => 'Inicio',
    'current_path' => '/dashboard',
    'target_path' => '/estudiante',
    'system' => 'Transversal',
    'runtime_path' => '/estudiante',
    'status' => 'PARTIAL',
  ),
  87 => 
  array (
    'id' => 'V088',
    'actor' => 'Estudiante',
    'name' => 'Mis cursos/materias',
    'current_path' => '/aula-virtual/mis-asignaturas',
    'target_path' => '/estudiante/mis-cursos',
    'system' => 'LMS',
    'runtime_path' => '/estudiante/materias',
    'status' => 'PARTIAL',
  ),
  88 => 
  array (
    'id' => 'V089',
    'actor' => 'Estudiante',
    'name' => 'Curso: resumen',
    'current_path' => '/aula-virtual/mis-asignaturas/{curso}',
    'target_path' => '/estudiante/curso',
    'system' => 'LMS',
    'runtime_path' => '/estudiante/materias/{curso}?tab=resumen',
    'status' => 'PARTIAL',
  ),
  89 => 
  array (
    'id' => 'V090',
    'actor' => 'Estudiante',
    'name' => 'Curso: contenido/unidades',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/estudiante/aula/{curso}/contenido (alias opcional D1; opción A mantiene /aula-virtual)',
    'system' => 'LMS',
    'runtime_path' => '/estudiante/materias/{curso}?tab=contenido',
    'status' => 'PARTIAL',
  ),
  90 => 
  array (
    'id' => 'V091',
    'actor' => 'Estudiante',
    'name' => 'Curso: materiales',
    'current_path' => '/aula-virtual/cursos/{curso}/materiales',
    'target_path' => '/estudiante/aula/{curso}/materiales (alias opcional D1; opción A mantiene /aula-virtual)',
    'system' => 'LMS',
    'runtime_path' => '/estudiante/materias/{curso}?tab=materiales',
    'status' => 'PARTIAL',
  ),
  91 => 
  array (
    'id' => 'V092',
    'actor' => 'Estudiante',
    'name' => 'Curso: tareas',
    'current_path' => '/aula-virtual/mis-asignaturas/{curso}',
    'target_path' => '/estudiante/aula/{curso}/tareas (alias opcional D1; opción A mantiene /aula-virtual)',
    'system' => 'LMS',
    'runtime_path' => '/estudiante/materias/{curso}?tab=tareas',
    'status' => 'PARTIAL',
  ),
  92 => 
  array (
    'id' => 'V093',
    'actor' => 'Estudiante',
    'name' => 'Curso: entregas',
    'current_path' => '/aula-virtual/tareas/{tarea}/entregar',
    'target_path' => '/estudiante/aula/{curso}/entregas (alias opcional D1; opción A mantiene /aula-virtual)',
    'system' => 'LMS',
    'runtime_path' => '/estudiante/materias/{curso}?tab=entregas',
    'status' => 'PARTIAL',
  ),
  93 => 
  array (
    'id' => 'V094',
    'actor' => 'Estudiante',
    'name' => 'Curso: calificaciones',
    'current_path' => '/aula-virtual/mis-asignaturas/{curso}',
    'target_path' => '/estudiante/aula/{curso}/notas-aula (alias opcional D1; opción A mantiene /aula-virtual)',
    'system' => 'LMS',
    'runtime_path' => '/estudiante/materias/{curso}?tab=calificaciones',
    'status' => 'PARTIAL',
  ),
  94 => 
  array (
    'id' => 'V095',
    'actor' => 'Estudiante',
    'name' => 'Curso: asistencia',
    'current_path' => '/aula-virtual/mi-asistencia',
    'target_path' => '/estudiante/aula/{curso}/asistencia-aula (alias opcional D1; opción A mantiene /aula-virtual)',
    'system' => 'LMS',
    'runtime_path' => '/estudiante/materias/{curso}?tab=asistencia',
    'status' => 'PARTIAL',
  ),
  95 => 
  array (
    'id' => 'V096',
    'actor' => 'Estudiante',
    'name' => 'Calendario',
    'current_path' => '/admin/calendario-academico',
    'target_path' => '/estudiante/calendario',
    'system' => 'Transversal',
    'runtime_path' => '/estudiante/calendario',
    'status' => 'PARTIAL',
  ),
  96 => 
  array (
    'id' => 'V097',
    'actor' => 'Estudiante',
    'name' => 'Mi progreso',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/estudiante/progreso',
    'system' => 'Analítica/LMS',
    'runtime_path' => '/estudiante/progreso',
    'status' => 'PARTIAL',
  ),
  97 => 
  array (
    'id' => 'V098',
    'actor' => 'Estudiante',
    'name' => 'Seguimientos',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/estudiante/seguimientos',
    'system' => 'Seguimiento',
    'runtime_path' => '/estudiante/seguimientos',
    'status' => 'BLOCKED_EXTERNALLY_DB',
  ),
  98 => 
  array (
    'id' => 'V099',
    'actor' => 'Estudiante',
    'name' => 'Mis intereses',
    'current_path' => '/aula-virtual/orientacion/explorador',
    'target_path' => '/estudiante/mis-intereses',
    'system' => 'Orientación',
    'runtime_path' => '/estudiante/intereses -> /aula-virtual/orientacion/explorador',
    'status' => 'PARTIAL',
  ),
  99 => 
  array (
    'id' => 'V100',
    'actor' => 'Estudiante',
    'name' => 'Mi futuro académico',
    'current_path' => '/aula-virtual/orientacion/resultados',
    'target_path' => '/estudiante/futuro',
    'system' => 'Orientación',
    'runtime_path' => '/estudiante/futuro',
    'status' => 'PARTIAL',
  ),
  100 => 
  array (
    'id' => 'V101',
    'actor' => 'Estudiante',
    'name' => 'Mi preparación',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/estudiante/preparacion',
    'system' => 'Orientación',
    'runtime_path' => '/estudiante/preparacion',
    'status' => 'PARTIAL',
  ),
  101 => 
  array (
    'id' => 'V102',
    'actor' => 'Estudiante',
    'name' => 'Mi plan',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/estudiante/plan',
    'system' => 'Orientación',
    'runtime_path' => '/estudiante/plan',
    'status' => 'BLOCKED_EXTERNALLY_DB',
  ),
  102 => 
  array (
    'id' => 'V103',
    'actor' => 'Estudiante',
    'name' => 'Fuentes académicas',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/estudiante/fuentes',
    'system' => 'Orientación',
    'runtime_path' => '/estudiante/fuentes',
    'status' => 'PARTIAL',
  ),
  103 => 
  array (
    'id' => 'V104',
    'actor' => 'Estudiante',
    'name' => 'Asistente de estudio',
    'current_path' => 'NO EXISTE RUTA ESPECÍFICA CONFIRMADA',
    'target_path' => '/estudiante/asistente',
    'system' => 'Orientación/LMS',
    'runtime_path' => '/estudiante/asistente',
    'status' => 'PARTIAL',
  ),
  104 => 
  array (
    'id' => 'V105',
    'actor' => 'Estudiante',
    'name' => 'Mi perfil',
    'current_path' => '/user/profile (vendor; no incluido en 64)',
    'target_path' => '/estudiante/perfil',
    'system' => 'Identidad',
    'runtime_path' => '/user/profile',
    'status' => 'PARTIAL',
  ),
);
