@php
    $personaCarga=$docenteDetalle->personalInstitucional?->persona;
    $nombreCarga=mb_strtoupper(trim(($personaCarga?->nom_per??'').' '.($personaCarga?->ape_pat_per??'').' '.($personaCarga?->ape_mat_per??'')));
    $horasRegistradas=(int)$docenteDetalle->planAsignaturas->where('est_pas','ACTIVO')->where('cod_gea',$codGestionActual)->sum('hor_pas')+(int)$docenteDetalle->planEspecialidades->where('est_pes','ACTIVO')->where('cod_gea',$codGestionActual)->sum('hor_pes');
    $horasDisponibles=max(0,$maxHorasDocente-$horasRegistradas);
    $esMateriaCarga=$formAsignacion['tipo_carga']==='MATERIA';
    $duplicadoCarga=($esMateriaCarga?$docenteDetalle->planAsignaturas:$docenteDetalle->planEspecialidades)->contains(fn($plan)=>$plan->getAttribute($esMateriaCarga?'cod_asi':'cod_esp')===($formAsignacion[$esMateriaCarga?'cod_asi':'cod_esp']??'') && $plan->cod_cur===$formAsignacion['cod_cur'] && $plan->cod_par===$formAsignacion['cod_par'] && $plan->cod_tur===$formAsignacion['cod_tur'] && $plan->cod_gea===$formAsignacion['cod_gea'] && $plan->getAttribute($esMateriaCarga?'fii_pas':'fii_pes')?->format('Y-m-d')===($formAsignacion['fii_plan']??''));
@endphp
@teleport('body')
<div class="personas-modal" x-data="formCargaInstitucional($wire.entangle('formAsignacion.tipo_carga').live,$wire.entangle('formAsignacion.cod_asi').live,$wire.entangle('formAsignacion.cod_esp').live,$wire.entangle('formAsignacion.cod_cur').live,$wire.entangle('formAsignacion.cod_par').live,$wire.entangle('formAsignacion.hor_car').live,$wire.entangle('formAsignacion.est_car').live,{{ $horasDisponibles }})" x-trap.inert.noscroll="true" role="dialog" aria-modal="true" aria-labelledby="personal-carga-titulo" x-on:keydown.escape.window="$wire.cerrarModalAsignar()"><div class="personas-modal-fondo" wire:click="cerrarModalAsignar" aria-hidden="true"></div><section class="personas-modal-panel personal-modal-panel"><header class="personas-modal-cabecera"><div><p class="ui-kicker">Designación académica</p><h2 id="personal-carga-titulo" class="ui-title mt-2 text-xl font-bold">Asignar carga académica</h2><p class="ui-muted mt-2 text-sm">{{ $nombreCarga }}</p></div><button type="button" wire:click="cerrarModalAsignar" class="personas-accion" aria-label="Cerrar asignación"><i class="ph-duotone ph-x" aria-hidden="true"></i></button></header><div class="personas-modal-contenido personal-form-layout"><div class="personal-form-campos">
    <x-selector-institucional modelo="formAsignacion.tipo_carga" identificador="carga-tipo" etiqueta="Tipo de asignación" :requerido="true" :opciones="[['valor'=>'MATERIA','etiqueta'=>'Materia curricular'],['valor'=>'ESPECIALIDAD','etiqueta'=>'Especialidad técnica']]" />
    @if($formAsignacion['tipo_carga']==='MATERIA')<x-selector-institucional modelo="formAsignacion.cod_asi" identificador="carga-materia" etiqueta="Materia" :requerido="true" :opciones="array_merge([['valor'=>'','etiqueta'=>'Seleccionar materia']],$asignaturas->map(fn($a)=>['valor'=>$a->cod_asi,'etiqueta'=>$a->nom_asi])->all())" />@else<x-selector-institucional modelo="formAsignacion.cod_esp" identificador="carga-especialidad" etiqueta="Especialidad técnica" :requerido="true" :opciones="array_merge([['valor'=>'','etiqueta'=>'Seleccionar especialidad']],$especialidadesTecnicas->map(fn($e)=>['valor'=>$e->cod_esp,'etiqueta'=>$e->nom_esp])->all())" />@endif
    <div class="personal-form-grid"><x-selector-institucional modelo="formAsignacion.cod_cur" identificador="carga-curso" etiqueta="Curso" :requerido="true" :opciones="array_merge([['valor'=>'','etiqueta'=>'Seleccionar curso']],$cursos->map(fn($c)=>['valor'=>$c->cod_cur,'etiqueta'=>$c->nom_cur])->all())" /><x-selector-institucional modelo="formAsignacion.cod_par" identificador="carga-paralelo" etiqueta="Paralelo" :requerido="true" :opciones="array_merge([['valor'=>'','etiqueta'=>'Seleccionar paralelo']],$paralelos->map(fn($p)=>['valor'=>$p->cod_par,'etiqueta'=>$p->nom_par])->all())" /></div>
    <div><label class="ui-label" for="carga-horas">Horas asignadas *</label><input id="carga-horas" type="number" min="1" max="{{ $horasDisponibles }}" step="1" x-model="horas" x-on:input="tocado=true" x-on:blur="tocado=true" class="ui-input mt-2 w-full" :aria-invalid="tocado&&!!errorHoras" aria-describedby="carga-horas-error" /><p id="carga-horas-error" class="ui-error mt-2" x-show="tocado&&errorHoras" x-cloak x-text="errorHoras"></p><x-input-error for="formAsignacion.hor_car" /><p class="ui-muted text-xs mt-2">Entre 1 y {{ $horasDisponibles }} horas enteras disponibles.</p></div>
    <div class="personal-form-grid"><div><label class="ui-label" for="carga-inicio">Inicio académico *</label><input id="carga-inicio" type="date" wire:model="formAsignacion.fii_plan" required class="ui-input mt-2 w-full" /><x-input-error for="formAsignacion.fii_plan" /></div><div><label class="ui-label" for="carga-fin">Fin académico</label><input id="carga-fin" type="date" wire:model="formAsignacion.ffi_plan" class="ui-input mt-2 w-full" /><x-input-error for="formAsignacion.ffi_plan" /></div></div>
    <x-selector-institucional modelo="formAsignacion.est_car" identificador="carga-estado" etiqueta="Estado de la asignación" :requerido="true" :opciones="[['valor'=>'ACTIVO','etiqueta'=>'Activa'],['valor'=>'INACTIVO','etiqueta'=>'Inactiva']]" />
    @if($duplicadoCarga)<p class="ui-alert-warning text-xs">Esta asignación ya existe para el mismo curso, paralelo, turno y gestión. Elige una combinación diferente.</p>@endif<p class="ui-alert-info text-xs">El turno y la gestión se determinan automáticamente según la configuración institucional.</p><x-input-error for="formAsignacion.cod_tur" /><x-input-error for="formAsignacion.cod_gea" />
    </div><aside class="ui-card-soft personal-preview"><h3 class="ui-title font-bold">Vista previa de la carga</h3><p class="ui-muted text-xs mt-2">Provisional · aún no registrada.</p><dl class="personas-preview-datos mt-4"><div><dt>Horas actuales</dt><dd>{{ $horasRegistradas }} h</dd></div><div><dt>Disponibles</dt><dd>{{ $horasDisponibles }} h</dd></div><div><dt>Gestión</dt><dd>{{ $nombreGestionActual }}</dd></div><div><dt>Turno</dt><dd x-text="tipo==='MATERIA'?@js($nombreTurnoManana):@js($nombreTurnoTarde)"></dd></div><div><dt>Total previsto</dt><dd x-text="{{ $horasRegistradas }}+(Number(horas)||0)+' h'"></dd></div></dl><p class="ui-error mt-4 text-xs" x-show="!valido" x-text="'Completa: '+faltantes+'.'"></p><p class="ui-muted text-xs mt-4">El servidor vuelve a comprobar docente, duplicados, configuración y límite antes de registrar.</p></aside></div><footer class="personas-modal-pie"><button type="button" class="ui-btn ui-btn-secondary" wire:click="cerrarModalAsignar">Cancelar</button><button type="button" class="ui-btn ui-btn-primary" wire:click="guardarAsignacion" :disabled="!valido || @js($duplicadoCarga)" @disabled(!$this->puedeGuardarAsignacion() || $duplicadoCarga) wire:loading.attr="disabled" wire:target="guardarAsignacion">Registrar carga</button></footer></section></div>
@endteleport
