@php($personaPerfil=$docenteDetalle->personalInstitucional?->persona)
@php($nombrePerfil=mb_strtoupper(trim(($personaPerfil?->nom_per??'').' '.($personaPerfil?->ape_pat_per??'').' '.($personaPerfil?->ape_mat_per??''))))
@php($editor=$this->editorEspecialidad)
@teleport('body')
<div class="personas-modal personal-perfil-modal" x-data="{}" x-trap.inert.noscroll="true" role="dialog" aria-modal="true" aria-labelledby="personal-perfil-titulo" x-on:keydown.escape.window="$wire.cerrarModalEditar()"><div class="personas-modal-fondo" wire:click="cerrarModalEditar" aria-hidden="true"></div>
<section class="personas-modal-panel" wire:key="perfil-especialidades-{{ $perfilDocenteCodigo }}"><header class="personas-modal-cabecera"><div><p class="ui-kicker">Perfil profesional</p><h2 id="personal-perfil-titulo" class="ui-title mt-2 text-xl font-bold">Actualizar especialidades</h2><p class="ui-muted mt-2 text-sm">{{ $nombrePerfil }}</p></div><button type="button" class="personas-accion" wire:click="cerrarModalEditar" aria-label="Cerrar perfil"><i class="ph-duotone ph-x" aria-hidden="true"></i></button></header>
<div class="personas-modal-contenido personal-form-campos">
<x-selector-institucional modelo="seleccionEspecialidad" identificador="perfil-especialidades" etiqueta="Materias y especialidades profesionales" :multiple="true" :opciones="collect($editor['opciones'])->map(fn($o)=>['valor'=>$o['valor'],'etiqueta'=>$o['tipo'].' · '.$o['etiqueta']])->all()" />
<p class="ui-muted text-xs">Puedes seleccionar varias: por ejemplo Inglés y Comunicación y Lenguaje. Se conservan las denominaciones del catálogo.</p>
<button type="button" class="ui-btn ui-btn-secondary" wire:click="$toggle('habilitarOtraEspecialidad')" aria-pressed="{{ $habilitarOtraEspecialidad?'true':'false' }}"><i class="ph-duotone {{ $habilitarOtraEspecialidad?'ph-minus':'ph-plus' }}" aria-hidden="true"></i>{{ $habilitarOtraEspecialidad?'Quitar Otra':'Otra especialidad' }}</button>
@if($habilitarOtraEspecialidad)<div><label for="perfil-otra" class="ui-label">Otra especialidad *</label><input id="perfil-otra" type="text" wire:model.live.debounce.350ms="otraEspecialidad" maxlength="150" class="ui-input mt-2" placeholder="Ej.: Literatura comparada" /><x-input-error for="otraEspecialidad" /><p class="ui-muted text-xs mt-2">Un dato histórico no reconocido se conserva aquí para que lo revises; no se descarta automáticamente.</p></div>@endif
<p class="ui-alert-info text-xs">Modificaciones disponibles: {{ max(0,3-(int)$docenteDetalle->num_mod_doc) }}.</p>
<div class="ui-card-soft p-4"><h3 class="ui-title font-bold">Perfil que se guardará</h3><p class="ui-muted mt-2 text-sm">{{ $editor['propuesta'] ?: 'Selecciona tus materias o especialidades.' }}</p>@if($editor['error'])<p class="ui-error mt-2 text-xs" role="status">{{ $editor['error'] }}</p>@endif</div>
</div><footer class="personas-modal-pie"><button type="button" class="ui-btn ui-btn-secondary" wire:click="cerrarModalEditar">Cancelar</button><button type="button" class="ui-btn ui-btn-primary" wire:click="actualizarDocente" @disabled($editor['error']!=='' || (int)$docenteDetalle->num_mod_doc>=3) wire:loading.attr="disabled" wire:target="actualizarDocente">Guardar perfil</button></footer></section></div>
@endteleport
