@php
    $personaFicha = $personalDetalle->persona;
    $nombreFicha = mb_strtoupper(trim(($personaFicha?->nom_per ?? '').' '.($personaFicha?->ape_pat_per ?? '').' '.($personaFicha?->ape_mat_per ?? '')) ?: 'Identidad por revisar');
    $docenteFicha = $personalDetalle->docente;
    $planesMateria = $docenteFicha?->planAsignaturas->where('est_pas','ACTIVO') ?? collect();
    $planesTecnicos = $docenteFicha?->planEspecialidades->where('est_pes','ACTIVO') ?? collect();
    $horasFicha = (int)$planesMateria->sum('hor_pas') + (int)$planesTecnicos->sum('hor_pes');
    $disponibleFicha = max(0,$maxHorasDocente-$horasFicha);
@endphp
@teleport('body')
<div class="personas-modal" x-data="{seccion:@js($seccionFicha)}" x-trap.inert.noscroll="true" role="dialog" aria-modal="true" aria-labelledby="personal-ficha-titulo" x-on:keydown.escape.window="$wire.cerrarFichaPersonal()">
    <div class="personas-modal-fondo" wire:click="cerrarFichaPersonal" aria-hidden="true"></div>
    <section class="personas-modal-panel personal-modal-panel"><header class="personas-modal-cabecera"><div class="usuarios-ficha-identidad"><x-avatar-institucional :user="$personaFicha?->usuario" :nombre="$nombreFicha" /><div><p class="ui-kicker">Ficha institucional · {{ ucfirst(mb_strtolower($personalDetalle->car_pin ?? 'Cargo por revisar')) }}</p><h2 id="personal-ficha-titulo" class="ui-title mt-2 text-xl font-bold">{{ $nombreFicha }}</h2></div></div><button type="button" class="personas-accion" wire:click="cerrarFichaPersonal" aria-label="Cerrar ficha institucional"><i class="ph-duotone ph-x" aria-hidden="true"></i></button></header>
        <div class="personas-modal-contenido personal-ficha-contenido"><div class="personas-tipos-vista" role="group" aria-label="Secciones de la ficha institucional"><button type="button" x-on:click="seccion='institucion'" :aria-pressed="seccion==='institucion'">Vinculación</button><button type="button" x-on:click="seccion='historial'" :aria-pressed="seccion==='historial'">Historial y documentos</button>@if($docenteFicha)<button type="button" x-on:click="seccion='carga'" :aria-pressed="seccion==='carga'">Carga académica</button>@endif</div>
            <section x-show="seccion==='institucion'" x-transition.opacity.duration.140ms class="mt-5"><dl class="personal-ficha-datos"><div><dt>Cargo registrado</dt><dd>{{ ucfirst(mb_strtolower($personalDetalle->car_pin ?? 'Cargo por revisar')) }}</dd></div><div><dt>Cuenta del sistema</dt><dd>{{ $personaFicha?->usuario?->email ?: 'Sin cuenta vinculada' }}</dd></div><div><dt>Estado de acceso</dt><dd>{{ $personaFicha?->usuario ? ($personaFicha->usuario->est_usu==='ACTIVO'?'Cuenta activa':'Cuenta inactiva') : 'Pendiente de vinculación' }}</dd></div><div><dt>Roles asignados en el sistema</dt><dd>{{ $personaFicha?->usuario?->roles->pluck('name')->implode(', ') ?: 'Sin roles registrados' }}</dd></div><div><dt>Registro institucional desde</dt><dd>{{ $personalDetalle->created_at?->timezone('America/La_Paz')->format('d/m/Y') ?: 'Sin fecha disponible' }}</dd></div><div><dt>Correo de contacto de Persona</dt><dd>{{ $personaFicha?->ema_per ?: 'Sin correo registrado' }}</dd></div><div><dt>Teléfono de contacto</dt><dd>{{ $personaFicha?->tel_per ?: 'Sin teléfono registrado' }}</dd></div></dl><p class="ui-muted mt-4 text-xs">El cargo institucional y el rol de acceso se consultan por separado. La fecha del registro no acredita antigüedad laboral.</p></section>
            <section x-show="seccion==='historial'" x-cloak x-transition.opacity.duration.140ms class="mt-5"><h3 class="ui-title font-bold">Vinculaciones registradas</h3><ol class="personal-asignaciones mt-4">@if($personalDetalle->relationLoaded('vinculoPersonalRegistros'))@forelse($personalDetalle->vinculoPersonalRegistros as $vinculo)<li><strong class="ui-title">{{ $vinculo->cargoInstitucional?->nom_cai ?: 'Cargo por revisar' }}</strong><p class="ui-muted text-sm mt-2">{{ $vinculo->tip_vpe }} · {{ $vinculo->fii_vpe?->format('d/m/Y') ?: 'Inicio sin registro' }} — {{ $vinculo->ffi_vpe?->format('d/m/Y') ?: 'Sin fecha de cierre' }}</p>@if($vinculo->obs_vpe)<p class="ui-muted text-sm mt-2">{{ $vinculo->obs_vpe }}</p>@endif</li>@empty<li class="ui-muted text-sm">No hay vinculaciones laborales disponibles para consultar.</li>@endforelse @else<li class="ui-muted text-sm">No hay historial de vinculaciones disponible para consultar.</li>@endif</ol><h3 class="ui-title font-bold mt-5">Documentos del personal</h3><ol class="personal-asignaciones mt-4">@if($personalDetalle->relationLoaded('documentoPersonalRegistros'))@forelse($personalDetalle->documentoPersonalRegistros as $documento)<li><strong class="ui-title">{{ $documento->tipoDocumentoPersonal?->nom_tdp ?: 'Documento institucional' }}</strong><p class="ui-muted mt-2 text-sm">{{ ucfirst(mb_strtolower($documento->est_dpe)) }} · {{ $documento->emi_dpe?->format('d/m/Y') ?: 'Emisión sin registro' }}</p></li>@empty<li class="ui-muted text-sm">Sin documentos disponibles para consultar.</li>@endforelse @else<li class="ui-muted text-sm">Sin documentos disponibles para consultar.</li>@endif</ol></section>
            @if($docenteFicha)<section x-show="seccion==='carga'" x-cloak x-transition.opacity.duration.140ms class="mt-5"><div class="ui-card-soft p-4"><p class="ui-title font-bold">{{ $horasFicha }} horas académicas activas</p><p class="ui-muted text-xs mt-2">{{ $planesMateria->count() }} asignaciones de materias · {{ $planesTecnicos->count() }} asignaciones técnicas.</p></div>@if($horasFicha>$maxHorasDocente)<p class="ui-alert-warning mt-4">La carga registrada supera el límite actual de {{ $maxHorasDocente }} h. Revisa las asignaciones antes de añadir horas.</p>@endif<div class="mt-5"><x-horario-institucional :eventos="$horarioPersonal" identificador="personal-horario" /></div><x-plegable-institucional class="personal-cargas-detalle mt-5" icono="ph-books"><x-slot:titulo>Consultar todas las cargas asignadas</x-slot:titulo><ol class="personal-asignaciones mt-4">@foreach($planesMateria as $plan)<li><strong class="ui-title">{{ $plan->asignatura?->nom_asi ?: 'Materia por revisar' }}</strong><p class="ui-muted mt-2 text-xs">{{ $plan->curso?->nom_cur ?: 'Curso por revisar' }} · {{ $plan->paralelo?->nom_par ?: 'Paralelo por revisar' }} · {{ $plan->hor_pas }} h · Materia curricular</p></li>@endforeach @foreach($planesTecnicos as $plan)<li><strong class="ui-title">{{ $plan->especialidad?->nom_esp ?: 'Especialidad por revisar' }}</strong><p class="ui-muted mt-2 text-xs">{{ $plan->curso?->nom_cur ?: 'Curso por revisar' }} · {{ $plan->paralelo?->nom_par ?: 'Paralelo por revisar' }} · {{ $plan->hor_pes }} h · Especialidad técnica</p></li>@endforeach @if($planesMateria->isEmpty()&&$planesTecnicos->isEmpty())<li class="ui-muted text-sm">No tiene asignaciones académicas activas.</li>@endif</ol></x-plegable-institucional></section>@endif
        </div><footer class="personas-modal-pie"><button type="button" wire:click="cerrarFichaPersonal" class="ui-btn ui-btn-secondary">Cerrar</button>@if($docenteFicha)<div class="personas-acciones"><button type="button" wire:click="abrirModalEditar(@js($docenteFicha->cod_doc))" class="ui-btn ui-btn-secondary" @disabled((int)$docenteFicha->num_mod_doc >= $maxModificaciones) title="{{ (int)$docenteFicha->num_mod_doc >= $maxModificaciones?'Límite de modificaciones alcanzado':'Editar perfil profesional' }}">Perfil profesional</button><button type="button" wire:click="abrirModalAsignar(@js($docenteFicha->cod_doc))" class="ui-btn ui-btn-primary" @disabled(!$disponibleFicha || $personaFicha?->usuario?->est_usu!=='ACTIVO') title="{{ !$disponibleFicha ? 'Sin horas disponibles para otra asignación' : ($personaFicha?->usuario?->est_usu!=='ACTIVO'?'La cuenta vinculada no tiene acceso activo':'Asignar horas académicas') }}">Asignar carga</button></div>@endif</footer>
    </section>
</div>
@endteleport
