<section class="ui-card personal-filtros" aria-label="Buscar y filtrar personal">
    <div class="personal-filtros-grid">
        <div><label for="personal-busqueda" class="ui-label">Buscar integrante</label><input id="personal-busqueda" type="search" wire:model.live.debounce.350ms="search" class="ui-input mt-2 w-full" placeholder="Nombre, apellido, cargo o materia…" /></div>
        <x-selector-institucional modelo="cargoFiltro" identificador="personal-cargo" etiqueta="Cargo institucional" :opciones="array_merge([['valor'=>'','etiqueta'=>'Todos los cargos']],$cargosPersonal->map(fn($c)=>['valor'=>$c->car_pin,'etiqueta'=>ucfirst(mb_strtolower($c->car_pin))])->all())" />
        <x-selector-institucional modelo="orden" identificador="personal-orden" etiqueta="Ordenar por" :opciones="[['valor'=>'APELLIDO_AZ','etiqueta'=>'Apellidos · A a Z'],['valor'=>'APELLIDO_ZA','etiqueta'=>'Apellidos · Z a A'],['valor'=>'NOMBRE_AZ','etiqueta'=>'Nombres · A a Z'],['valor'=>'NOMBRE_ZA','etiqueta'=>'Nombres · Z a A'],['valor'=>'REGISTRO_RECIENTE','etiqueta'=>'Registro más reciente'],['valor'=>'REGISTRO_ANTIGUO','etiqueta'=>'Registro más antiguo']]" />
    </div>
    <div class="personal-filtros-pie">
        <p class="ui-muted text-sm" role="status"><strong class="ui-title">{{ $personal->total() }}</strong> integrantes encontrados</p>
        <div class="personas-acciones"><button type="button" class="ui-btn ui-btn-secondary" x-on:click="masFiltros=!masFiltros" :aria-expanded="masFiltros" aria-controls="personal-filtros-adicionales"><i class="ph-duotone ph-sliders-horizontal" aria-hidden="true"></i>Más filtros @if($cantidadFiltrosAdicionales)<span class="ui-badge-success">{{ $cantidadFiltrosAdicionales }}</span>@endif</button><button type="button" wire:click="limpiarFiltros" class="personas-enlace" wire:loading.attr="disabled">Limpiar filtros</button></div>
        <div class="personas-tipos-vista personal-vistas" role="group" aria-label="Vista del personal"><button type="button" x-on:click="vista='directorio'" :aria-pressed="vista==='directorio'"><i class="ph-duotone ph-squares-four" aria-hidden="true"></i>Directorio</button><button type="button" x-on:click="vista='tabla'" :aria-pressed="vista==='tabla'"><i class="ph-duotone ph-table" aria-hidden="true"></i>Tabla</button><button type="button" x-on:click="vista='lista'" :aria-pressed="vista==='lista'"><i class="ph-duotone ph-list-bullets" aria-hidden="true"></i>Lista</button><button type="button" x-on:click="vista='cargas'" :aria-pressed="vista==='cargas'"><i class="ph-duotone ph-clock" aria-hidden="true"></i>Carga horaria</button></div>
    </div>
    <div id="personal-filtros-adicionales" class="personal-filtros-adicionales" x-show="masFiltros" x-cloak x-transition.opacity.duration.160ms>
        <p class="ui-muted text-xs">Los filtros académicos consultan docentes con asignaciones activas. Al combinar materia o especialidad con curso, deben coincidir en la misma asignación.</p>
        <div class="personal-filtros-extra-grid">
            <x-selector-institucional modelo="tipoCargaFiltro" identificador="personal-trayecto" etiqueta="Tipo de asignación" :opciones="[['valor'=>'','etiqueta'=>'Cualquier asignación'],['valor'=>'MATERIA','etiqueta'=>'Con materias curriculares'],['valor'=>'ESPECIALIDAD','etiqueta'=>'Con especialidades técnicas'],['valor'=>'AMBAS','etiqueta'=>'Con ambos tipos']]" />
            <x-selector-institucional modelo="carga" identificador="personal-horas" etiqueta="Carga horaria docente" :opciones="[['valor'=>'','etiqueta'=>'Cualquier carga'],['valor'=>'SIN_ASIGNACION','etiqueta'=>'Sin carga activa'],['valor'=>'NORMAL','etiqueta'=>'De 1 a 10 horas'],['valor'=>'MEDIA','etiqueta'=>'De 11 a 18 horas'],['valor'=>'COMPLETA','etiqueta'=>'De 19 a 24 horas'],['valor'=>'EXCESO','etiqueta'=>'Más de 24 horas']]" />
            <x-selector-institucional modelo="materiaFiltro" identificador="personal-materia" etiqueta="Materia curricular" :opciones="array_merge([['valor'=>'','etiqueta'=>'Todas las materias']],$asignaturas->map(fn($a)=>['valor'=>$a->cod_asi,'etiqueta'=>$a->nom_asi])->all())" />
            <x-selector-institucional modelo="especialidadFiltro" identificador="personal-especialidad" etiqueta="Especialidad técnica" :opciones="array_merge([['valor'=>'','etiqueta'=>'Todas las especialidades']],$especialidadesTecnicas->map(fn($e)=>['valor'=>$e->cod_esp,'etiqueta'=>$e->nom_esp])->all())" />
            <x-selector-institucional modelo="cursoFiltro" identificador="personal-curso" etiqueta="Curso asignado" :opciones="array_merge([['valor'=>'','etiqueta'=>'Todos los cursos']],$cursos->map(fn($c)=>['valor'=>$c->cod_cur,'etiqueta'=>$c->nom_cur])->all())" />
            <x-selector-institucional modelo="contactoFiltro" identificador="personal-contacto" etiqueta="Contacto por completar" :opciones="[['valor'=>'','etiqueta'=>'Todos los contactos'],['valor'=>'SIN_CORREO','etiqueta'=>'Sin correo registrado'],['valor'=>'SIN_TELEFONO','etiqueta'=>'Sin teléfono registrado']]" />
        </div>
    </div>
    @if($filtrosActivos)<div class="personal-filtros-activos" aria-label="Filtros aplicados">@foreach($filtrosActivos as $filtro)<button type="button" class="ui-badge-info" wire:click="$set(@js($filtro['propiedad']), '')" aria-label="Quitar filtro {{ $filtro['etiqueta'] }}">{{ $filtro['etiqueta'] }}<i class="ph-duotone ph-x" aria-hidden="true"></i></button>@endforeach</div>@endif
</section>
