<section class="personal-indicadores" x-show="indicadores" x-transition.opacity.duration.180ms aria-label="Indicadores institucionales">
<div class="personal-indicadores-columna">
    <article class="ui-card personal-grafico"><p class="ui-kicker">Composición institucional</p><h2 class="ui-title mt-2 font-bold">Cargos del equipo</h2><p class="ui-muted mt-2 text-xs">Integrantes registrados por función, en toda la institución.</p><div class="personal-cargos mt-4">@forelse($cargosPersonal as $cargo)<button type="button" wire:click="$set('cargoFiltro', @js($cargo->car_pin))" class="ui-card-soft" aria-label="Filtrar cargo {{ $cargo->car_pin }}"><i class="ph-duotone ph-identification-card" aria-hidden="true"></i><strong>{{ $cargo->cantidad }}</strong><span>{{ ucfirst(mb_strtolower($cargo->car_pin)) ?: 'Cargo por revisar' }}</span></button>@empty<p class="ui-muted">Sin cargos disponibles.</p>@endforelse</div></article>
    <article class="ui-card personal-grafico"><p class="ui-kicker">Carga horaria docente</p><h2 class="ui-title mt-2 font-bold">Mapa de horas del equipo</h2><p class="ui-muted mt-2 text-xs">Cada casilla es un docente. Consulta su nombre y horas.</p><div class="personal-mapa mt-4"><template x-for="(item,i) in datos.distribucion" :key="i"><button type="button" :class="'personal-carga-'+item.nivel" :title="item.nombre+' · '+item.horas+' horas'" :aria-label="item.nombre+' · '+item.horas+' horas'" x-on:click="detalleCarga=item"><span x-text="item.horas"></span></button></template></div><p class="ui-muted mt-3 text-xs" aria-live="polite" x-text="detalleCarga ? detalleCarga.nombre+' · '+detalleCarga.horas+' horas registradas' : 'Selecciona una casilla para consultar sus horas.'"></p><div class="personal-rangos mt-4"><span><i class="personal-carga-vacia"></i>Sin carga</span><span><i class="personal-carga-normal"></i>1–10 h</span><span><i class="personal-carga-media"></i>11–18 h</span><span><i class="personal-carga-alta"></i>19–24 h</span><span><i class="personal-carga-exceso"></i>Más de 24 h</span></div><p class="ui-alert-warning mt-4 text-xs" x-show="datos.exceso" x-text="datos.exceso+' docentes tienen más de '+{{ $maxHorasDocente }}+' horas registradas. Revisa su distribución antes de añadir carga.'"></p></article>
</div>
<div class="personal-indicadores-columna">
    <article class="ui-card personal-grafico"><p class="ui-kicker">Horas asignadas</p><h2 class="ui-title mt-2 font-bold">Materias y especialidades</h2><p class="ui-muted mt-2 text-xs">Horas de las asignaciones activas del personal filtrado.</p><div class="personal-dona-layout mt-4"><div class="personal-dona" :style="`--personal-proporcion:${porcentajeMateria}%`" role="img" :aria-label="`Materias: ${datos.horas_materias} horas. Especialidades: ${datos.horas_especialidades} horas.`"><div><strong x-text="horasTotales"></strong><span>horas</span></div></div><dl class="personal-leyenda"><div><dt><i class="personal-punto personal-color-materia"></i>Materias</dt><dd x-text="datos.horas_materias+' h'"></dd></div><div><dt><i class="personal-punto personal-color-especialidad"></i>Especialidades</dt><dd x-text="datos.horas_especialidades+' h'"></dd></div><div><dt>Docentes filtrados</dt><dd x-text="datos.total"></dd></div></dl></div><p class="ui-muted text-xs mt-3" x-show="!horasTotales">Sin cargas activas para estos filtros.</p></article>
    <article class="ui-card personal-grafico personal-grafico-ancho"><div class="personal-grafico-titulo"><div><p class="ui-kicker">Distribución académica</p><h2 class="ui-title mt-2 font-bold" x-text="tipoGrafico==='materias'?'Horas por materia':'Horas por especialidad'"></h2></div><div class="personas-tipos-vista" role="group" aria-label="Tipo de asignación en el gráfico"><button type="button" x-on:click="tipoGrafico='materias'" :aria-pressed="tipoGrafico==='materias'">Materias</button><button type="button" x-on:click="tipoGrafico='especialidades'" :aria-pressed="tipoGrafico==='especialidades'">Especialidades</button></div></div><p class="ui-muted mt-2 text-xs">La posición del punto representa las horas acumuladas. Cada asignación corresponde a un curso y paralelo.</p><div class="personal-lollipop mt-4"><template x-for="item in cargasGrafico" :key="item.nombre"><div class="personal-lollipop-fila"><div><strong class="ui-title" x-text="item.nombre"></strong><p class="ui-muted" x-text="item.asignaciones+' asignaciones'"></p></div><div class="personal-lollipop-eje" aria-hidden="true"><span :style="`width:${item.horas/maximoGrafico*100}%`"><i></i></span></div><strong class="ui-title" x-text="item.horas+' h'"></strong></div></template><p class="ui-muted text-sm" x-show="!cargasGrafico.length">No hay asignaciones activas en esta selección.</p></div><button type="button" class="personas-enlace mt-3" x-show="datos[tipoGrafico].length>6" x-on:click="verTodas=!verTodas" x-text="verTodas?'Ver las seis principales':'Ver todas las asignaturas'"></button></article>
</div>
</section>
