<div wire:ignore.self class="personal-pagina" x-data="personalInstitucionalPage(@js($indicadoresPersonal))" x-on:indicadores-personal.window="datos=$event.detail.datos" x-on:error-general.window="avisar('warning',$event.detail.mensaje)" x-on:docente-actualizado.window="avisar('success','Perfil profesional actualizado.')" x-on:asignacion-creada.window="avisar('success','Carga académica registrada.')">
    <header class="ui-card personal-cabecera"><div><p class="ui-kicker">Equipo de la unidad educativa</p><h1 class="ui-title mt-2 text-2xl font-extrabold">Personal institucional</h1><p class="ui-muted mt-2 text-sm">Personas, cargos y vinculación con la institución. Una visión completa de nuestro equipo.</p></div><div class="personas-acciones"><button type="button" class="ui-btn ui-btn-secondary" x-on:click="indicadores=!indicadores" :aria-expanded="indicadores"><i class="ph-duotone ph-chart-pie-slice" aria-hidden="true"></i>Indicadores</button><a href="{{ route('admin.gestion-personas') }}" class="ui-btn ui-btn-primary"><i class="ph-duotone ph-user-list" aria-hidden="true"></i>Gestionar personas</a></div></header>
    <section class="ui-card personal-cifras" aria-label="Resumen del equipo institucional">@foreach([['users-three',$resumenPersonal['total'],'Integrantes'],['check-circle',$resumenPersonal['activos'],'Con acceso activo'],['shield-check',$resumenPersonal['con_cuenta'],'Con cuenta de acceso'],['user-circle-plus',$resumenPersonal['sin_cuenta'],'Sin cuenta de acceso']] as [$icono,$valor,$titulo])<div><i class="ph-duotone ph-{{ $icono }}" aria-hidden="true"></i><strong>{{ $valor }}</strong><span>{{ $titulo }}</span></div>@endforeach</section>
    <section class="personal-contexto"><div class="ui-card-soft"><i class="ph-duotone ph-identification-card" aria-hidden="true"></i><div><strong class="ui-title">El equipo y su función</strong><p class="ui-muted">Personal docente, administrativo y de apoyo registrado.</p></div></div><div class="ui-card-soft"><i class="ph-duotone ph-clock" aria-hidden="true"></i><div><strong class="ui-title">{{ $nombreGestionActual }}</strong><p class="ui-muted">Materias: {{ $nombreTurnoManana }} · Especialidades: {{ $nombreTurnoTarde }}.</p></div></div></section>
    @include('livewire.admin.personal.indicadores')
    @include('livewire.admin.personal.filtros')
    <div x-ref="resultados" class="personal-resultados"><x-estado-carga-institucional objetivo="search,cargoFiltro,carga,tipoCargaFiltro,materiaFiltro,especialidadFiltro,cursoFiltro,contactoFiltro,orden,perPage,gotoPage,limpiarFiltros" mensaje="Actualizando el equipo institucional…" />
        <div class="personal-directorio" x-show="vista==='directorio'">@forelse($personal as $integrante)@include('livewire.admin.personal.tarjeta', ['registro'=>$integrante])@empty<div class="ui-card personas-vacio"><i class="ph-duotone ph-users-three" aria-hidden="true"></i><h2 class="ui-title font-bold">Sin integrantes para estos filtros</h2><p class="ui-muted mt-2">Limpia la búsqueda o elige otro cargo.</p></div>@endforelse</div>
        <section class="ui-card personal-tabla" x-show="vista==='tabla'" x-cloak><table class="ui-table"><thead><tr><th>Integrante</th><th>Cargo institucional</th><th>Cuenta de acceso</th><th>Acceso del usuario</th><th>Acciones</th></tr></thead><tbody>@forelse($personal as $integrante)@php($persona=$integrante->persona)@php($nombre=mb_strtoupper(trim(($persona?->nom_per??'').' '.($persona?->ape_pat_per??'').' '.($persona?->ape_mat_per??'')) ?: 'Identidad por revisar'))<tr wire:key="personal-tabla-{{ $integrante->getKey() }}"><td><strong>{{ $nombre }}</strong><p class="ui-muted text-xs mt-1">{{ $persona?->ema_per ?: 'Sin correo registrado' }}</p></td><td>{{ ucfirst(mb_strtolower($integrante->car_pin ?? 'Cargo por revisar')) }}</td><td><span class="{{ $persona?->usuario ? 'ui-badge-success' : 'ui-badge-warning' }}">{{ $persona?->usuario ? 'Vinculada' : 'Sin cuenta' }}</span></td><td><span class="{{ $persona?->usuario?->est_usu==='ACTIVO'?'ui-badge-success':'ui-badge-warning' }}">{{ !$persona?->usuario ? 'Sin cuenta' : ($persona->usuario->est_usu==='ACTIVO'?'Activo':'Inactivo') }}</span></td><td><div class="personal-accesos-tabla">@if($integrante->docente)<button type="button" wire:click="abrirFichaPersonal(@js($integrante->getKey()), 'carga')" class="personas-accion" aria-label="Ver carga horaria de {{ $nombre }}" title="Carga horaria"><i class="ph-duotone ph-calendar-dots" aria-hidden="true"></i></button>@endif<button type="button" wire:click="abrirFichaPersonal(@js($integrante->getKey()))" class="personas-accion" aria-label="Ver ficha institucional de {{ $nombre }}"><i class="ph-duotone ph-eye" aria-hidden="true"></i></button></div></td></tr>@empty<tr><td colspan="5" class="ui-muted p-5">Sin resultados. Revisa los filtros.</td></tr>@endforelse</tbody></table></section>
        @include('livewire.admin.personal.vistas')
    </div>
    {{ $personal->onEachSide(1)->links('vendor.livewire.paginacion-institucional', ['cantidad'=>$perPage,'entidad'=>'integrantes','singular'=>'integrante']) }}
    @if($modalPersonal && $personalDetalle)@include('livewire.admin.personal.ficha')@endif
    @if($modalAsignar && $docenteDetalle)@include('livewire.admin.personal.asignar-carga')@endif
    @if($modalEditar && $docenteDetalle)@include('livewire.admin.personal.editar-perfil')@endif
</div>
