@extends('diseno-local.base')
@section('contenido')
<main class="diseno-contenedor" x-data="{
    ventanas:@js($ventanas), actor:'Administrador', buscar:'', seleccion:'admin.gestion-academica',
    get visibles(){return this.ventanas.filter(v=>v.actor===this.actor && v.titulo.toLocaleLowerCase('es').includes(this.buscar.toLocaleLowerCase('es')))},
    get actual(){return this.ventanas.find(v=>v.id===this.seleccion)},
    cambiarActor(actor){this.actor=actor;this.buscar='';this.seleccion=this.ventanas.find(v=>v.actor===actor)?.id??''}
}">
    <header class="ui-card diseno-cabecera"><div><p class="ui-kicker">SAVP · Modo de diseño</p><h1 class="ui-title text-2xl mt-1">Un espacio para revisar todas las vistas</h1><p class="ui-muted text-sm mt-2">Cambia de rol y consulta sus referencias visuales en el mismo lugar.</p></div><div class="diseno-tema"><button type="button" class="ui-btn ui-btn-secondary" onclick="window.themeManager?.toggle()" aria-label="Cambiar tema"><i class="ph-duotone ph-moon-stars" aria-hidden="true"></i></button><form method="POST" action="{{ route('diseno.salir') }}">@csrf<button class="ui-btn ui-btn-secondary" type="submit">Salir del diseño</button></form></div></header>
    <div class="diseno-aviso"><strong>Vista de referencia.</strong> Las capturas corresponden a revisiones anteriores. Sus datos no describen la nueva BD; las acciones de las imágenes no ejecutan operaciones.</div>
    <nav class="diseno-roles" aria-label="Vistas por rol y Aula Virtual">@foreach($actores as $actor)<button type="button" class="ui-btn ui-btn-secondary" x-on:click="cambiarActor(@js($actor))" :aria-pressed="actor===@js($actor)">{{ $actor==='Secretaria'?'Secretaría':$actor }}</button>@endforeach</nav>
    <div class="diseno-catalogo"><aside class="ui-card p-4"><label for="buscar-ventana" class="ui-label">Buscar ventana</label><input id="buscar-ventana" type="search" class="ui-input mt-2" x-model="buscar" placeholder="Calendario, cursos, reportes…"><p class="ui-muted text-xs mt-3"><span x-text="visibles.length"></span> ventanas en el catálogo</p><div class="diseno-lista" role="group" aria-label="Ventanas del catálogo"><template x-for="ventana in visibles" :key="ventana.id"><button type="button" x-on:click="seleccion=ventana.id" :aria-pressed="seleccion===ventana.id"><span x-text="ventana.titulo"></span><small x-text="ventana.imagen?'Captura disponible':'Captura pendiente'"></small></button></template><p class="ui-muted p-3" x-show="!visibles.length" x-cloak>Prueba otro nombre de ventana.</p></div></aside>
    <section class="ui-card diseno-visor" aria-live="polite"><template x-if="actual"><div><p class="ui-kicker" x-text="actual.actor"></p><h2 class="ui-title text-xl mt-2" x-text="actual.titulo"></h2><template x-if="actual.imagen"><img class="diseno-captura" :src="actual.imagen" :alt="'Captura de referencia: '+actual.titulo"></template><div class="diseno-vacio" x-show="!actual.imagen"><i class="ph-duotone ph-layout text-4xl" aria-hidden="true"></i><h3 class="ui-title mt-3">Sin captura de referencia todavía</h3><p class="ui-muted text-sm mt-2">Esta ventana está catalogada. Su vista previa se incorporará al revisar su diseño.</p></div></div></template></section></div>
</main>
@endsection
