@php
    $prefijo = $editar ? 'formEditar' : 'form';
    $datos = $editar ? $formEditar : $form;
    $analisis = $editar ? $analisisPersonaEditar : $analisisPersona;
    $archivo = $editar ? $fotoEditar : $foto;
    $campoFoto = $editar ? 'fotoEditar' : 'foto';
    $modo = $editar ? $modoDireccionEditar : $modoDireccionCrear;
    $accionCerrar = $editar ? 'cerrarModalEditar' : 'cerrarModalCrear';
    $puedeGuardar = $editar ? $this->puedeActualizarPersona() : $this->puedeGuardarPersona();
    $estadoRevision = $analisis['estado_inteligente'] ?? 'INCOMPLETO';
    $requeridos = ['nom_per'=>'Nombre', 'ape_pat_per'=>'Apellido paterno', 'ci_per'=>'CI', 'exp_per'=>'Expedido', 'fec_nac_per'=>'Fecha de nacimiento', 'gen_per'=>'Género'];
    $faltantes = array_filter($requeridos, fn ($campo) => blank($datos[$campo] ?? null), ARRAY_FILTER_USE_KEY);
@endphp
@teleport('body')
<div class="personas-modal" x-data="formularioPersona('{{ $editar ? 'editar' : 'crear' }}')" x-on:keydown.escape.window="$wire.{{ $accionCerrar }}()" role="dialog" aria-modal="true" aria-labelledby="persona-form-titulo" x-trap.inert.noscroll="true">
    <div class="personas-modal-fondo" aria-hidden="true" x-on:click="$wire.{{ $accionCerrar }}()"></div>
    <form class="personas-modal-panel personas-modal-grande" x-ref="formulario" novalidate x-on:submit.prevent="enviar()" x-on:input="tocar($event.target)" x-on:blur.capture="tocar($event.target)">
        <header class="personas-modal-cabecera"><div><p class="ui-kicker">{{ $editar ? 'Actualizar registro' : 'Nuevo registro' }}</p><h2 id="persona-form-titulo" class="ui-title mt-2 text-xl font-extrabold">{{ $editar ? 'Editar persona' : 'Registrar persona' }}</h2><p class="ui-muted mt-2 text-sm">Los campos con * son necesarios. Tus cambios se guardarán al confirmar.</p></div><button type="button" class="personas-accion" wire:click="{{ $accionCerrar }}" aria-label="Cerrar formulario"><i class="ph-duotone ph-x" aria-hidden="true"></i></button></header>
        <div class="personas-modal-contenido"><div class="personas-form-layout">
            <div class="personas-form-campos">
                <section class="ui-card-soft personas-bloque"><h3 class="ui-title font-bold">Fotografía <span class="ui-muted text-xs font-normal">· opcional</span></h3><div class="personas-foto-form">
                    <span class="personas-avatar personas-avatar-form" x-data="{fallo:false}">
                        @if($archivo && in_array(strtolower($archivo->getClientOriginalExtension()), ['jpg','jpeg','png','webp']))<img src="{{ $archivo->temporaryUrl() }}" alt="Vista previa de la foto" class="h-full w-full object-cover" x-show="!fallo" x-on:error="fallo=true" />
                        @elseif($datos['fot_per'] ?? null)<img src="{{ Storage::disk('public')->url($datos['fot_per']) }}" alt="Foto registrada" class="h-full w-full object-cover" x-show="!fallo" x-on:error="fallo=true" />@endif
                        <i class="ph-duotone ph-user-circle" aria-hidden="true" @if(($archivo && in_array(strtolower($archivo->getClientOriginalExtension()), ['jpg','jpeg','png','webp'])) || ($datos['fot_per'] ?? null)) x-show="fallo" x-cloak @endif></i>
                    </span>
                    <div><label for="persona-fotografia" class="ui-label">Seleccionar imagen</label><input id="persona-fotografia" type="file" wire:model="{{ $campoFoto }}" accept="image/jpeg,image/png,image/webp" class="personas-archivo mt-2" /><p class="ui-muted mt-2 text-xs">JPG, PNG o WEBP · máximo 2 MB.</p><p class="ui-muted text-xs" wire:loading wire:target="{{ $campoFoto }}">Preparando imagen…</p><x-input-error :for="$campoFoto" /></div>
                </div></section>
                <section class="personas-bloque"><h3 class="ui-title mb-4 font-bold">Identidad y contacto</h3><div class="personas-form-grid">
                    @foreach(['nom_per'=>['Nombre',true,100], 'ape_pat_per'=>['Apellido paterno',true,100], 'ape_mat_per'=>['Apellido materno',false,100], 'ci_per'=>['CI',true,12], 'com_per'=>['Complemento',false,10]] as $campo => [$etiqueta,$requerido,$maximo])
                    <div><label class="ui-label" for="persona-{{ $campo }}">{{ $etiqueta }}{{ $requerido ? ' *' : '' }}</label><input id="persona-{{ $campo }}" name="{{ $campo }}" class="ui-input mt-2 w-full" :class="tocado['persona-{{ $campo }}'] && errores['persona-{{ $campo }}'] ? 'personas-invalido' : ''" :aria-invalid="!!(tocado['persona-{{ $campo }}'] && errores['persona-{{ $campo }}'])" aria-describedby="ayuda-{{ $campo }}" type="text" wire:model.live.debounce.450ms="{{ $prefijo }}.{{ $campo }}" maxlength="{{ $maximo }}" @if($requerido) required @endif @if(in_array($campo, ['nom_per','ape_pat_per'])) minlength="2" @endif @if(in_array($campo, ['nom_per','ape_pat_per','ape_mat_per'])) pattern="[\p{L}\p{M}][\p{L}\p{M} .'’\-]*" @endif @if($campo === 'ci_per') inputmode="numeric" pattern="[0-9]{4,12}" @endif @if($campo === 'com_per') pattern="[A-Za-z0-9\-]*" @endif /><p id="ayuda-{{ $campo }}" x-show="tocado['persona-{{ $campo }}'] && errores['persona-{{ $campo }}']" x-cloak x-text="errores['persona-{{ $campo }}']" class="ui-error mt-2"></p><x-input-error :for="$prefijo.'.'.$campo" />@if($campo === 'ci_per')@if($analisis['coincidencias']['duplicado_ci'] ?? false)<p class="ui-error personas-ci-duplicado" role="alert">Este CI ya pertenece a otra persona registrada. Revisa el número antes de continuar.</p>@endif@endif</div>
                    @endforeach
                    <div><label class="ui-label" for="persona-exp_per">Expedido *</label><select id="persona-exp_per" name="exp_per" :class="tocado['persona-exp_per'] && errores['persona-exp_per'] ? 'personas-invalido' : ''" :aria-invalid="!!(tocado['persona-exp_per'] && errores['persona-exp_per'])" aria-describedby="ayuda-exp_per" class="ui-select mt-2 w-full" wire:model.live="{{ $prefijo }}.exp_per" required><option value="">Seleccionar</option>@foreach(['LP','CBBA','SCZ','ORU','PT','CH','TJ','BN','PD'] as $valor)<option value="{{ $valor }}">{{ $valor }}</option>@endforeach</select><p id="ayuda-exp_per" x-show="tocado['persona-exp_per'] && errores['persona-exp_per']" x-cloak x-text="errores['persona-exp_per']" class="ui-error mt-2"></p><x-input-error :for="$prefijo.'.exp_per'" /></div>
                    @include('livewire.admin.personas.fecha-nacimiento')
                    <div><label class="ui-label" for="persona-gen_per">Género *</label><select id="persona-gen_per" name="gen_per" :class="tocado['persona-gen_per'] && errores['persona-gen_per'] ? 'personas-invalido' : ''" :aria-invalid="!!(tocado['persona-gen_per'] && errores['persona-gen_per'])" aria-describedby="ayuda-gen_per" class="ui-select mt-2 w-full" wire:model.live="{{ $prefijo }}.gen_per" required><option value="">Seleccionar</option><option value="M">Masculino</option><option value="F">Femenino</option></select><p id="ayuda-gen_per" x-show="tocado['persona-gen_per'] && errores['persona-gen_per']" x-cloak x-text="errores['persona-gen_per']" class="ui-error mt-2"></p><x-input-error :for="$prefijo.'.gen_per'" /></div>
                    <div><label class="ui-label" for="persona-tel_per">Teléfono</label><input id="persona-tel_per" name="tel_per" :class="tocado['persona-tel_per'] && errores['persona-tel_per'] ? 'personas-invalido' : ''" :aria-invalid="!!(tocado['persona-tel_per'] && errores['persona-tel_per'])" aria-describedby="ayuda-tel_per" class="ui-input mt-2 w-full" type="tel" wire:model.live.debounce.450ms="{{ $prefijo }}.tel_per" autocomplete="tel" maxlength="30" pattern="[0-9\+\-\s]*" /><p id="ayuda-tel_per" x-show="tocado['persona-tel_per'] && errores['persona-tel_per']" x-cloak x-text="errores['persona-tel_per']" class="ui-error mt-2"></p><x-input-error :for="$prefijo.'.tel_per'" /></div>
                    <div><label class="ui-label" for="persona-ema_per">Correo electrónico</label><input id="persona-ema_per" name="ema_per" :class="tocado['persona-ema_per'] && errores['persona-ema_per'] ? 'personas-invalido' : ''" :aria-invalid="!!(tocado['persona-ema_per'] && errores['persona-ema_per'])" aria-describedby="ayuda-ema_per" class="ui-input mt-2 w-full" type="email" wire:model.live.debounce.450ms="{{ $prefijo }}.ema_per" autocomplete="email" maxlength="150" /><p id="ayuda-ema_per" x-show="tocado['persona-ema_per'] && errores['persona-ema_per']" x-cloak x-text="errores['persona-ema_per']" class="ui-error mt-2"></p><x-input-error :for="$prefijo.'.ema_per'" /></div>
                </div></section>
                <section class="ui-card-soft personas-bloque" aria-labelledby="persona-direccion-titulo">
                    <div class="personas-direccion-cabecera"><h3 id="persona-direccion-titulo" class="ui-title font-bold">Dirección</h3><div class="personas-tipos-vista" role="group" aria-label="Cómo ingresar la dirección">
                    <button type="button" aria-pressed="{{ $modo === 'inteligente' ? 'true':'false' }}" wire:click="{{ $editar ? 'cambiarModoDireccionEditar' : 'cambiarModoDireccionCrear' }}('inteligente')"><i class="ph-duotone ph-sparkle" aria-hidden="true"></i> Desde texto</button>
                    <button type="button" aria-pressed="{{ $modo === 'manual' ? 'true':'false' }}" wire:click="{{ $editar ? 'cambiarModoDireccionEditar' : 'cambiarModoDireccionCrear' }}('manual')"><i class="ph-duotone ph-pencil-simple" aria-hidden="true"></i> Por campos</button></div></div>
                    <p class="ui-muted mt-3 text-sm">{{ $modo === 'inteligente' ? 'Escribe la dirección completa. Te ayudamos a reconocer sus partes; revísalas antes de guardar.' : 'Completa las partes que conozcas. La dirección completa se arma con tus datos.' }}</p>
                    <label for="persona-dir_per" class="ui-label mt-4 block">{{ $modo === 'inteligente' ? 'Dirección completa' : 'Dirección que se guardará' }}</label><textarea id="persona-dir_per" name="dir_per" class="ui-textarea mt-2 w-full" rows="2" maxlength="255" wire:model.blur="{{ $prefijo }}.dir_per" @if($modo === 'manual') readonly @endif></textarea><x-input-error :for="$prefijo.'.dir_per'" />
                    @if($modo === 'manual')
                    <div class="personas-form-grid mt-4">
                        @foreach(['zona_per'=>['Zona',100], 'ave_per'=>['Avenida',120], 'cal_per'=>['Calle',120], 'num_per'=>['Número',30], 'ciu_per'=>['Ciudad',100], 'mun_per'=>['Municipio',100], 'dep_per'=>['Departamento',100], 'ref_per'=>['Referencia',255]] as $campo=>[$etiqueta,$maximo])
                        <div><label for="persona-{{ $campo }}" class="ui-label">{{ $etiqueta }}</label><input id="persona-{{ $campo }}" name="{{ $campo }}" class="ui-input mt-2 w-full" type="text" maxlength="{{ $maximo }}" wire:model.live.debounce.450ms="{{ $prefijo }}.{{ $campo }}" /><x-input-error :for="$prefijo.'.'.$campo" />@if($campo === 'ci_per')@if($analisis['coincidencias']['duplicado_ci'] ?? false)<p class="ui-error personas-ci-duplicado" role="alert">Este CI ya pertenece a otra persona registrada. Revisa el número antes de continuar.</p>@endif@endif</div>
                        @endforeach
                    </div>
                    @else
                    <x-plegable-institucional class="personas-direccion-reconocida mt-4" icono="ph-map-pin"><x-slot:titulo>Ver partes reconocidas</x-slot:titulo><dl class="personas-form-grid mt-3">@foreach(['zona_per'=>'Zona','ave_per'=>'Avenida','cal_per'=>'Calle','num_per'=>'Número','ciu_per'=>'Ciudad','mun_per'=>'Municipio','dep_per'=>'Departamento','ref_per'=>'Referencia'] as $campo=>$etiqueta)<div><dt class="ui-muted text-xs">{{ $etiqueta }}</dt><dd class="ui-title mt-1 text-sm">{{ ($datos[$campo] ?? null) ?: 'Sin identificar' }}</dd></div>@endforeach</dl><p class="ui-muted mt-3 text-xs">Si una parte no se reconoció, puedes completarla con «Por campos».</p></x-plegable-institucional>
                    @endif
                </section>
            </div>
            <aside class="personas-revision">
                <section class="ui-card-soft personas-bloque"><div class="personas-indicador-titulo"><h3 class="ui-title font-bold">Vista previa</h3><i class="ph-duotone ph-identification-card" aria-hidden="true"></i></div>
                    <p class="ui-muted mt-2 text-xs">Provisional · aún no se ha guardado.</p>
                    <p class="personas-revisando" wire:loading wire:target="{{ $prefijo }}"><i class="ph-duotone ph-spinner-gap" aria-hidden="true"></i> Actualizando vista previa…</p>
                    <div wire:loading.class="personas-preview-pendiente" wire:target="{{ $prefijo }}">
                    <h4 class="ui-title mt-4 text-lg font-bold personas-texto-largo">{{ trim(($datos['nom_per'] ?? '').' '.($datos['ape_pat_per'] ?? '').' '.($datos['ape_mat_per'] ?? '')) ?: 'La persona que registrarás' }}</h4>
                    <dl class="personas-preview-datos mt-4"><div><dt>Identificación</dt><dd>{{ $datos['ci_per'] ?: 'Por completar' }}{{ $datos['com_per'] ? '-'.$datos['com_per'] : '' }}{{ $datos['exp_per'] ? ' · '.$datos['exp_per'] : '' }}</dd></div><div><dt>Nacimiento y edad</dt><dd>{{ $this->edadPersona($datos['fec_nac_per'] ?? '') !== null ? \Carbon\Carbon::parse($datos['fec_nac_per'])->format('d/m/Y') : 'Por completar' }} @if(isset($analisis['resumen']['edad'])) · {{ $analisis['resumen']['edad'] }} años @endif</dd></div><div><dt>Contacto</dt><dd>{{ $datos['tel_per'] ?: 'Sin teléfono' }}<br>{{ $datos['ema_per'] ?: 'Sin correo' }}</dd></div><div><dt>Dirección</dt><dd>{{ $datos['dir_per'] ?: 'Sin dirección' }}</dd></div></dl>
                    </div>
                </section>
                <section class="personas-bloque personas-ayudas" aria-live="polite" aria-atomic="false">
                    <h3 class="ui-title font-bold">Revisión de datos</h3><p class="personas-revisando" wire:loading wire:target="{{ $prefijo }}"><i class="ph-duotone ph-spinner-gap" aria-hidden="true"></i> Verificando los datos y posibles duplicados…</p>
                    <div wire:loading.remove wire:target="{{ $prefijo }}">
                    @if($faltantes)
                        <p class="ui-muted mt-3 text-sm">Completa {{ implode(', ', array_values($faltantes)) }} para poder guardar.</p>
                    @elseif($puedeGuardar)<p class="mt-3 text-sm text-[var(--ui-primary)]"><i class="ph-duotone ph-check-circle" aria-hidden="true"></i> Los datos necesarios están completos.</p>@endif
                    @if($estadoRevision !== 'INCOMPLETO' && !empty($analisis['bloqueos']))<div class="ui-alert-danger mt-4"><h4 class="font-semibold text-sm">Necesita corrección</h4><ul class="mt-2 space-y-2 text-sm">@foreach($analisis['bloqueos'] as $nota)<li>{{ $nota }}</li>@endforeach</ul></div>@endif
                    @if(!empty($analisis['advertencias']))<x-plegable-institucional class="personas-notas mt-4" icono="ph-info"><x-slot:titulo>{{ count($analisis['advertencias']) }} {{ count($analisis['advertencias']) === 1 ? 'nota para revisar' : 'notas para revisar' }}</x-slot:titulo><ul class="mt-3 space-y-3 text-sm">@foreach($analisis['advertencias'] as $nota)<li>{{ $nota }}</li>@endforeach</ul><p class="ui-muted mt-3 text-xs">Estas notas no impiden guardar cuando los campos requeridos son válidos.</p></x-plegable-institucional>@endif
                    @if(!empty($analisis['sugerencias']))<x-plegable-institucional class="personas-notas mt-4" icono="ph-lightbulb"><x-slot:titulo>Ayudas para completar</x-slot:titulo><ul class="mt-3 space-y-3 text-sm ui-muted">@foreach($analisis['sugerencias'] as $nota)<li>{{ $nota }}</li>@endforeach</ul></x-plegable-institucional>@endif
                    </div>
                    <p class="ui-muted mt-4 text-xs leading-5">{{ $editar ? 'Las vinculaciones de esta persona se conservan.' : 'La nueva persona quedará activa. Podrás gestionar su cuenta de acceso desde Usuarios.' }}</p>
                </section>
            </aside>
        </div></div>
        <footer class="personas-modal-pie"><div class="personas-estado-guardado"><p class="ui-error text-xs" x-show="Object.values(errores).some(Boolean)" x-cloak>Corrige los campos marcados antes de guardar. Tus datos se conservan.</p><p class="ui-muted text-xs" x-show="!Object.values(errores).some(Boolean)" wire:loading.remove wire:target="{{ $prefijo }}">@if(!$puedeGuardar) Revisa los campos necesarios y las indicaciones antes de guardar. @else Vista previa lista · confirma para guardar. @endif</p><p class="ui-muted text-xs" wire:loading wire:target="{{ $prefijo }}">Revisando los últimos cambios…</p></div><div class="personas-acciones"><button type="button" class="ui-btn ui-btn-secondary" wire:click="{{ $accionCerrar }}">Cancelar</button><button type="submit" class="ui-btn ui-btn-primary" wire:loading.attr="disabled" wire:target="{{ $prefijo }},guardarPersona,actualizarPersona,{{ $campoFoto }}" x-bind:disabled="Object.values(errores).some(Boolean) || {{ $puedeGuardar ? 'false' : 'true' }}" @disabled(!$puedeGuardar)><i class="ph-duotone ph-check" aria-hidden="true"></i><span wire:loading.remove wire:target="guardarPersona,actualizarPersona">{{ $editar ? 'Guardar cambios' : 'Registrar persona' }}</span><span wire:loading wire:target="guardarPersona,actualizarPersona">Guardando…</span></button></div></footer>
    </form>
</div>
@endteleport
