@teleport('body')
<div class="personas-modal usuarios-modal" x-data="{correo: $wire.entangle('form.email').live}" x-trap.inert.noscroll="true" x-on:keydown.escape.window="$wire.cerrarModalCrear()" role="dialog" aria-modal="true" aria-labelledby="usuario-crear-titulo">
    <div class="personas-modal-fondo" wire:click="cerrarModalCrear" aria-hidden="true"></div>
    <form class="personas-modal-panel usuarios-modal-crear" wire:submit="guardarUsuario">
        <header class="personas-modal-cabecera"><div><p class="ui-kicker">De persona a usuario</p><h2 id="usuario-crear-titulo" class="ui-title text-xl font-bold mt-2">Crear cuenta institucional</h2><p class="ui-muted mt-2 text-sm">Vincula una persona registrada y prepara su acceso por correo.</p></div><button type="button" class="personas-accion" wire:click="cerrarModalCrear" aria-label="Cerrar formulario"><i class="ph-duotone ph-x" aria-hidden="true"></i></button></header>
        <div class="personas-modal-contenido usuarios-crear-layout">
            <section class="usuarios-form-campos">
                @if(!auth()->user()->can('usuarios.crear') || !auth()->user()->can('usuarios.asignar_roles'))<p class="ui-alert-warning text-sm">Puedes revisar el formulario. Tu cuenta no tiene los permisos necesarios para crear cuentas y asignar roles.</p>@endif
                @error('general')<p class="ui-alert-danger" role="alert">{{ $message }}</p>@enderror
                @if($personasDisponibles->isEmpty())<div class="ui-card-soft p-4"><h3 class="ui-title font-bold">No hay personas sin cuenta</h3><p class="ui-muted mt-2 text-sm">Registra primero a la persona en Personas. Cada persona puede tener una sola cuenta.</p><a class="personas-enlace" href="{{ url('/admin/gestion-personas') }}">Ir a Personas</a></div>@endif
                <x-selector-institucional modelo="form.cod_per" identificador="usuario-persona" etiqueta="Persona registrada" :requerido="true" :opciones="array_merge([['valor'=>'','etiqueta'=>'Seleccionar persona sin cuenta']], $personasDisponibles->map(fn($persona)=>['valor'=>$persona->cod_per,'etiqueta'=>trim($persona->nom_per.' '.$persona->ape_pat_per.' '.$persona->ape_mat_per).' · CI '.$persona->ci_per])->all())" />
                <div><label for="usuario-correo" class="ui-label">Correo de acceso *</label><input id="usuario-correo" class="ui-input mt-2 w-full" type="email" readonly x-model="correo" wire:model.live.debounce.450ms="form.email" autocomplete="email" maxlength="255" required aria-describedby="usuario-correo-ayuda" /><p id="usuario-correo-ayuda" class="ui-muted mt-2 text-xs">Generado con nombres, apellido paterno y dos letras del materno. Este correo de acceso es fijo.</p><x-input-error for="form.email" /></div>
                @include('livewire.admin.usuarios.entrega-acceso', ['prefijo' => 'crear'])
                <div><x-selector-institucional modelo="form.role" identificador="usuario-rol" etiqueta="Rol institucional" :requerido="true" :opciones="array_merge([['valor'=>'','etiqueta'=>'Seleccionar rol']], $rolesDisponibles->map(fn($item)=>['valor'=>$item->name,'etiqueta'=>$item->name])->all())" /><p class="ui-muted mt-2 text-xs">El rol determina sus permisos. Revisa la función real antes de confirmar.</p></div>
                @include('livewire.admin.usuarios.estado-acceso', ['prefijo' => 'crear', 'modeloEstado' => 'form.est_usu'])
                <div class="ui-card-soft p-4"><i class="ph-duotone ph-lock-key" aria-hidden="true"></i><strong class="ui-title ml-2 text-sm">Contraseña personal</strong><p class="ui-muted mt-2 text-sm">La persona elige su contraseña desde el enlace temporal. No enviamos ni mostramos contraseñas.</p></div>
            </section>
            <aside class="ui-card-soft usuarios-preview"><h3 class="ui-title font-bold">Vista previa del acceso</h3><p class="ui-muted mt-2 text-xs">Provisional · aún no se ha creado.</p><dl class="personas-preview-datos mt-4"><div><dt>Persona</dt><dd>{{ ($elegida = $personasDisponibles->firstWhere('cod_per', $form['cod_per'])) ? trim($elegida->nom_per.' '.$elegida->ape_pat_per.' '.$elegida->ape_mat_per) : 'Por seleccionar' }}</dd></div><div><dt>Correo de acceso</dt><dd x-text="correo || 'Por completar'"></dd></div><div><dt>Enviar a</dt><dd>{{ $correoEntrega ?: 'Por confirmar' }}</dd></div><div><dt>Rol</dt><dd>{{ $form['role'] ?: 'Por seleccionar' }}</dd></div><div><dt>Activación</dt><dd>{{ $programarActivacion ? ($fechaActivacion ?: 'Fecha por elegir') : 'Manual' }}</dd></div><div><dt>Estado inicial</dt><dd>{{ $form['est_usu'] === 'ACTIVO' ? 'Activo' : 'Inactivo' }}</dd></div></dl><p class="ui-muted mt-4 text-xs">El enlace vence en {{ config('auth.passwords.users.expire') }} minutos. La cuenta se conserva si el envío falla; podrás reintentarlo.</p>
            @if($bloqueoCorreo)<p class="ui-alert-warning mt-4 text-sm">{{ $bloqueoCorreo }}</p>@endif</aside>
        </div>
        <footer class="personas-modal-pie"><p class="ui-muted text-xs">{{ $bloqueoCorreo ?: 'Completa persona, correo y rol. Confirma antes de crear y enviar.' }}</p><div class="personas-acciones"><button type="button" class="ui-btn ui-btn-secondary" wire:click="cerrarModalCrear">Cancelar</button><button type="submit" class="ui-btn ui-btn-primary" wire:loading.attr="disabled" wire:target="guardarUsuario,form" @disabled(!$this->puedeGuardarUsuario() || !auth()->user()->can('usuarios.crear') || !auth()->user()->can('usuarios.asignar_roles'))><i class="ph-duotone ph-envelope-simple" aria-hidden="true"></i><span wire:loading.remove wire:target="guardarUsuario">{{ $programarActivacion ? 'Crear y programar activación' : ($form['est_usu'] === 'ACTIVO' ? 'Crear y enviar acceso' : 'Crear cuenta inactiva') }}</span><span wire:loading wire:target="guardarUsuario">Preparando acceso…</span></button></div></footer>
    </form>
</div>
@endteleport
