@php
    $personaFicha = $usuarioDetalle->persona;
    $nombreFicha = trim(($personaFicha?->nom_per ?? '').' '.($personaFicha?->ape_pat_per ?? '').' '.($personaFicha?->ape_mat_per ?? '')) ?: 'Persona sin vincular';
    $fechaFicha = fn($fecha) => $fecha?->timezone('America/La_Paz')->format('d/m/Y H:i') ?? 'Sin registro disponible';
    $programacionFicha = $activacionesPendientes->get($usuarioDetalle->cod_usu);
@endphp
@teleport('body')
<div class="personas-modal usuarios-modal" x-data="{seccion:'acceso',secciones:['acceso','permisos','actividad'],moverTab(evento){if(!['ArrowLeft','ArrowRight','Home','End'].includes(evento.key))return;evento.preventDefault();const indice=this.secciones.indexOf(this.seccion);this.seccion=evento.key==='Home'?'acceso':evento.key==='End'?'actividad':this.secciones[(indice+(evento.key==='ArrowRight'?1:2))%3];this.$nextTick(()=>this.$refs.tabs.querySelector('[aria-selected=true]').focus());}}" x-trap.inert.noscroll="true" x-on:keydown.escape.window="$wire.cerrarModalVer()" role="dialog" aria-modal="true" aria-labelledby="usuario-ficha-titulo">
    <div class="personas-modal-fondo" wire:click="cerrarModalVer" aria-hidden="true"></div>
    <section class="personas-modal-panel usuarios-modal-ficha">
        <header class="personas-modal-cabecera"><div class="usuarios-ficha-identidad"><x-avatar-institucional :user="$usuarioDetalle" :nombre="$nombreFicha" /><div><p class="ui-kicker">Ficha de acceso institucional</p><h2 id="usuario-ficha-titulo" class="ui-title mt-2 text-xl font-bold">{{ $nombreFicha }}</h2><p class="ui-muted mt-2 text-xs">{{ $formVer['role'] ?: 'Rol por revisar' }}</p></div></div><button type="button" class="personas-accion" wire:click="cerrarModalVer" aria-label="Cerrar ficha"><i class="ph-duotone ph-x" aria-hidden="true"></i></button></header>
        <div class="personas-modal-contenido usuarios-ficha-contenido">
            <div class="usuarios-ficha-resumen"><span class="{{ $usuarioDetalle->est_usu === 'ACTIVO' ? 'ui-badge-success' : 'ui-badge-warning' }}">{{ $usuarioDetalle->est_usu === 'ACTIVO' ? 'Cuenta activa' : 'Cuenta sin acceso' }}</span><p class="ui-muted text-sm">{{ $usuarioDetalle->est_usu === 'ACTIVO' ? 'Puede iniciar sesión según sus permisos.' : 'El estado impide iniciar sesión; sus datos se conservan.' }}</p></div>
            <div class="personas-tipos-vista usuarios-ficha-tabs mt-5" role="tablist" aria-label="Información de la cuenta" x-ref="tabs" x-on:keydown="moverTab($event)">
                @foreach(['acceso'=>['Acceso','shield-check'],'permisos'=>['Permisos','key'],'actividad'=>['Actividad','clock-counter-clockwise']] as $id=>[$titulo,$icono])<button id="usuario-tab-{{ $id }}" role="tab" type="button" :aria-selected="seccion==='{{ $id }}'" :tabindex="seccion==='{{ $id }}'?0:-1" aria-controls="usuario-panel-{{ $id }}" x-on:click="seccion='{{ $id }}'"><i class="ph-duotone ph-{{ $icono }}" aria-hidden="true"></i>{{ $titulo }}</button>@endforeach
            </div>
            <section id="usuario-panel-acceso" role="tabpanel" aria-labelledby="usuario-tab-acceso" x-show="seccion==='acceso'" x-transition.opacity.duration.140ms class="mt-5">
                <dl class="usuarios-ficha-datos"><div><dt><i class="ph-duotone ph-envelope-simple" aria-hidden="true"></i>Correo de acceso fijo</dt><dd class="personas-texto-largo"><x-contacto-institucional tipo="correo" :correo="$usuarioDetalle->email" /></dd></div><div><dt>Teléfono registrado en Personas</dt><dd><x-contacto-institucional :telefono="$personaFicha?->tel_per" /></dd></div><div><dt>Contacto registrado en Personas</dt><dd class="personas-texto-largo"><x-contacto-institucional tipo="correo" :correo="$personaFicha?->ema_per" /></dd></div><div><dt>Último inicio de sesión registrado</dt><dd>{{ $fechaFicha($usuarioDetalle->last_login_at) }}</dd></div><div><dt>Método de acceso</dt><dd>{{ $usuarioDetalle->auth_provider === 'google' ? 'Cuenta Google vinculada' : 'Correo y contraseña' }}</dd></div><div><dt>Cuenta creada</dt><dd>{{ $fechaFicha($usuarioDetalle->created_at) }}</dd></div><div><dt>Última actualización</dt><dd>{{ $fechaFicha($usuarioDetalle->updated_at) }}</dd></div><div><dt>Autenticación en dos pasos</dt><dd>{{ $usuarioDetalle->two_factor_confirmed_at ? 'Confirmada' : 'Sin confirmación registrada' }}</dd></div><div><dt>Incorporación programada</dt><dd>{{ $programacionFicha ? $programacionFicha->fecha_activacion->timezone('America/La_Paz')->format('d/m/Y').' · 00:00' : 'Sin activación pendiente' }}</dd></div></dl>
                <p class="ui-muted mt-4 text-xs">Las contraseñas y los códigos de seguridad permanecen protegidos.</p>
            </section>
            <section id="usuario-panel-permisos" role="tabpanel" aria-labelledby="usuario-tab-permisos" x-show="seccion==='permisos'" x-cloak x-transition.opacity.duration.140ms class="mt-5"><h3 class="ui-title font-bold">{{ count($permisosUsuario) }} permisos asignados</h3><p class="ui-muted mt-2 text-xs">Estos permisos describen su alcance. La autorización se comprueba en cada operación.</p><div class="usuarios-permisos mt-4">@forelse($permisosUsuario as $permiso)<div class="ui-card-soft p-3"><strong class="ui-title text-sm">{{ $permiso['label'] }}</strong><p class="ui-muted mt-1 text-xs">{{ $permiso['scope_label'] }}</p></div>@empty<p class="ui-muted text-sm">No hay permisos explícitos registrados para esta cuenta.</p>@endforelse</div></section>
            <section id="usuario-panel-actividad" role="tabpanel" aria-labelledby="usuario-tab-actividad" x-show="seccion==='actividad'" x-cloak x-transition.opacity.duration.140ms class="mt-5"><h3 class="ui-title font-bold">Movimientos recientes de esta cuenta</h3><ol class="usuarios-actividad mt-4">@forelse($actividadUsuario as $movimiento)<li><i class="ph-duotone ph-clock" aria-hidden="true"></i><div><p class="ui-title text-sm">{{ $movimiento['descripcion'] }}</p><p class="ui-muted mt-2 text-xs">{{ $movimiento['fecha'] ?: 'Fecha sin registro' }} · {{ $movimiento['resultado'] }}</p></div></li>@empty<li><i class="ph-duotone ph-note-blank" aria-hidden="true"></i><p class="ui-muted text-sm">No hay movimientos de cuenta registrados en bitácora.</p></li>@endforelse</ol></section>
        </div>
        <footer class="personas-modal-pie"><p class="ui-muted text-xs">{{ $personaFicha ? 'Identidad vinculada a Personas' : 'Identidad pendiente de vinculación' }}</p><button type="button" class="ui-btn ui-btn-secondary" wire:click="cerrarModalVer">Cerrar ficha</button></footer>
    </section>
</div>
@endteleport
