<?php

declare(strict_types=1);

/** Contrato aditivo AulaVirtual. Fuente: guía aprobada 2026-10-03; sin backfill ni retiro. */
return [
    [
        'tabla' => 'clase_virtual',
        'creacion' => 'CREATE TABLE "clase_virtual" (
 "cod_cla" VARCHAR(20) PRIMARY KEY,
 "cod_pas" VARCHAR(20),
 "cod_pes" VARCHAR(20),
 "nom_cla" VARCHAR(200) NOT NULL,
 "des_cla" TEXT,
 "fec_ini_cla" DATE NOT NULL,
 "fec_fin_cla" DATE,
 "vis_cla" BOOLEAN NOT NULL DEFAULT TRUE,
 "est_cla" VARCHAR(20) NOT NULL DEFAULT \'ACTIVA\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_pas' => '"cod_pas" VARCHAR(20) NULL',
            'cod_pes' => '"cod_pes" VARCHAR(20) NULL',
            'nom_cla' => '"nom_cla" VARCHAR(200) NULL',
            'des_cla' => '"des_cla" TEXT NULL',
            'fec_ini_cla' => '"fec_ini_cla" DATE NULL',
            'fec_fin_cla' => '"fec_fin_cla" DATE NULL',
            'vis_cla' => '"vis_cla" BOOLEAN NULL',
            'est_cla' => '"est_cla" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_cla',
        'columnas' => [
            'cod_cla' => 'VARCHAR(20) PRIMARY KEY',
            'cod_pas' => 'VARCHAR(20)',
            'cod_pes' => 'VARCHAR(20)',
            'nom_cla' => 'VARCHAR(200) NOT NULL',
            'des_cla' => 'TEXT',
            'fec_ini_cla' => 'DATE NOT NULL',
            'fec_fin_cla' => 'DATE',
            'vis_cla' => 'BOOLEAN NOT NULL DEFAULT TRUE',
            'est_cla' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVA\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_cla IN (\'ACTIVA\',\'CERRADA\',\'ARCHIVADA\',\'ANULADA\')',
            'num_nonnulls(cod_pas,cod_pes)=1',
            'fec_fin_cla IS NULL OR fec_fin_cla>=fec_ini_cla',
        ],
        'unicos' => [],
        'grupo' => 'AulaVirtual',
        'existente' => true,
    ],
    [
        'tabla' => 'clase_estudiante',
        'creacion' => 'CREATE TABLE "clase_estudiante" (
 "cod_cla_est" VARCHAR(20) PRIMARY KEY,
 "cod_cla" VARCHAR(20) NOT NULL,
 "cod_est" VARCHAR(20) NOT NULL,
 "fec_inc_cla_est" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "fec_ret_cla_est" TIMESTAMPTZ,
 "ult_acc_cla_est" TIMESTAMPTZ,
 "ult_act_cla_est" TIMESTAMPTZ,
 "cant_acc_cla_est" BIGINT NOT NULL DEFAULT 0,
 "est_cla_est" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_cla' => '"cod_cla" VARCHAR(20) NULL',
            'cod_est' => '"cod_est" VARCHAR(20) NULL',
            'fec_inc_cla_est' => '"fec_inc_cla_est" TIMESTAMPTZ NULL',
            'fec_ret_cla_est' => '"fec_ret_cla_est" TIMESTAMPTZ NULL',
            'ult_acc_cla_est' => '"ult_acc_cla_est" TIMESTAMPTZ NULL',
            'ult_act_cla_est' => '"ult_act_cla_est" TIMESTAMPTZ NULL',
            'cant_acc_cla_est' => '"cant_acc_cla_est" BIGINT NULL',
            'est_cla_est' => '"est_cla_est" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_cla_est',
        'columnas' => [
            'cod_cla_est' => 'VARCHAR(20) PRIMARY KEY',
            'cod_cla' => 'VARCHAR(20) NOT NULL',
            'cod_est' => 'VARCHAR(20) NOT NULL',
            'fec_inc_cla_est' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'fec_ret_cla_est' => 'TIMESTAMPTZ',
            'ult_acc_cla_est' => 'TIMESTAMPTZ',
            'ult_act_cla_est' => 'TIMESTAMPTZ',
            'cant_acc_cla_est' => 'BIGINT NOT NULL DEFAULT 0',
            'est_cla_est' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'cant_acc_cla_est>=0',
            'est_cla_est IN (\'ACTIVO\',\'RETIRADO\',\'SUSPENDIDO\',\'ANULADO\')',
            'fec_ret_cla_est IS NULL OR fec_ret_cla_est>=fec_inc_cla_est',
        ],
        'unicos' => [
            [
                'cod_cla',
                'cod_est',
            ],
        ],
        'grupo' => 'AulaVirtual',
        'existente' => true,
    ],
    [
        'tabla' => 'seccion_clase',
        'creacion' => 'CREATE TABLE "seccion_clase" (
 "cod_sec" VARCHAR(20) PRIMARY KEY,
 "cod_cla" VARCHAR(20) NOT NULL,
 "nom_sec" VARCHAR(180) NOT NULL,
 "des_sec" TEXT,
 "ord_sec" INTEGER NOT NULL,
 "vis_sec" BOOLEAN NOT NULL DEFAULT TRUE,
 "est_sec" VARCHAR(20) NOT NULL DEFAULT \'ACTIVA\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_cla' => '"cod_cla" VARCHAR(20) NULL',
            'nom_sec' => '"nom_sec" VARCHAR(180) NULL',
            'des_sec' => '"des_sec" TEXT NULL',
            'ord_sec' => '"ord_sec" INTEGER NULL',
            'vis_sec' => '"vis_sec" BOOLEAN NULL',
            'est_sec' => '"est_sec" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_sec',
        'columnas' => [
            'cod_sec' => 'VARCHAR(20) PRIMARY KEY',
            'cod_cla' => 'VARCHAR(20) NOT NULL',
            'nom_sec' => 'VARCHAR(180) NOT NULL',
            'des_sec' => 'TEXT',
            'ord_sec' => 'INTEGER NOT NULL',
            'vis_sec' => 'BOOLEAN NOT NULL DEFAULT TRUE',
            'est_sec' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVA\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'ord_sec>0',
            'est_sec IN (\'ACTIVA\',\'OCULTA\',\'ARCHIVADA\',\'ANULADA\')',
        ],
        'unicos' => [
            [
                'cod_cla',
                'ord_sec',
            ],
            [
                'cod_sec',
                'cod_cla',
            ],
        ],
        'grupo' => 'AulaVirtual',
        'existente' => false,
    ],
    [
        'tabla' => 'publicacion_clase',
        'creacion' => 'CREATE TABLE "publicacion_clase" (
 "cod_pub" VARCHAR(20) PRIMARY KEY,
 "cod_cla" VARCHAR(20) NOT NULL,
 "cod_sec" VARCHAR(20),
 "cod_usu" VARCHAR(20) NOT NULL,
 "tip_pub" VARCHAR(60) NOT NULL,
 "tit_pub" VARCHAR(220) NOT NULL,
 "con_pub" TEXT NOT NULL,
 "fec_pub" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "est_pub" VARCHAR(20) NOT NULL DEFAULT \'PUBLICADA\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_cla' => '"cod_cla" VARCHAR(20) NULL',
            'cod_sec' => '"cod_sec" VARCHAR(20) NULL',
            'cod_usu' => '"cod_usu" VARCHAR(20) NULL',
            'tip_pub' => '"tip_pub" VARCHAR(60) NULL',
            'tit_pub' => '"tit_pub" VARCHAR(220) NULL',
            'con_pub' => '"con_pub" TEXT NULL',
            'fec_pub' => '"fec_pub" TIMESTAMPTZ NULL',
            'est_pub' => '"est_pub" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_pub',
        'columnas' => [
            'cod_pub' => 'VARCHAR(20) PRIMARY KEY',
            'cod_cla' => 'VARCHAR(20) NOT NULL',
            'cod_sec' => 'VARCHAR(20)',
            'cod_usu' => 'VARCHAR(20) NOT NULL',
            'tip_pub' => 'VARCHAR(60) NOT NULL',
            'tit_pub' => 'VARCHAR(220) NOT NULL',
            'con_pub' => 'TEXT NOT NULL',
            'fec_pub' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'est_pub' => 'VARCHAR(20) NOT NULL DEFAULT \'PUBLICADA\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_pub IN (\'BORRADOR\',\'PROGRAMADA\',\'PUBLICADA\',\'OCULTA\',\'ANULADA\')',
        ],
        'unicos' => [
            [
                'cod_pub',
                'cod_cla',
            ],
        ],
        'grupo' => 'AulaVirtual',
        'existente' => true,
    ],
    [
        'tabla' => 'material_clase',
        'creacion' => 'CREATE TABLE "material_clase" (
 "cod_mat" VARCHAR(20) PRIMARY KEY,
 "cod_cla" VARCHAR(20) NOT NULL,
 "cod_sec" VARCHAR(20),
 "cod_pub" VARCHAR(20),
 "cod_usu" VARCHAR(20) NOT NULL,
 "nom_mat" VARCHAR(255) NOT NULL,
 "tip_mat" VARCHAR(80) NOT NULL,
 "rut_mat" TEXT,
 "url_mat" url_http,
 "mime_mat" VARCHAR(150),
 "tam_mat" BIGINT,
 "has_mat" hash_sha256,
 "est_mat" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_cla' => '"cod_cla" VARCHAR(20) NULL',
            'cod_sec' => '"cod_sec" VARCHAR(20) NULL',
            'cod_pub' => '"cod_pub" VARCHAR(20) NULL',
            'cod_usu' => '"cod_usu" VARCHAR(20) NULL',
            'nom_mat' => '"nom_mat" VARCHAR(255) NULL',
            'tip_mat' => '"tip_mat" VARCHAR(80) NULL',
            'rut_mat' => '"rut_mat" TEXT NULL',
            'url_mat' => '"url_mat" url_http NULL',
            'mime_mat' => '"mime_mat" VARCHAR(150) NULL',
            'tam_mat' => '"tam_mat" BIGINT NULL',
            'has_mat' => '"has_mat" hash_sha256 NULL',
            'est_mat' => '"est_mat" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_mat',
        'columnas' => [
            'cod_mat' => 'VARCHAR(20) PRIMARY KEY',
            'cod_cla' => 'VARCHAR(20) NOT NULL',
            'cod_sec' => 'VARCHAR(20)',
            'cod_pub' => 'VARCHAR(20)',
            'cod_usu' => 'VARCHAR(20) NOT NULL',
            'nom_mat' => 'VARCHAR(255) NOT NULL',
            'tip_mat' => 'VARCHAR(80) NOT NULL',
            'rut_mat' => 'TEXT',
            'url_mat' => 'url_http',
            'mime_mat' => 'VARCHAR(150)',
            'tam_mat' => 'BIGINT',
            'has_mat' => 'hash_sha256',
            'est_mat' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'tam_mat IS NULL OR tam_mat>=0',
            'est_mat IN (\'ACTIVO\',\'OCULTO\',\'ANULADO\')',
            'rut_mat IS NOT NULL OR url_mat IS NOT NULL',
        ],
        'unicos' => [],
        'grupo' => 'AulaVirtual',
        'existente' => true,
    ],
    [
        'tabla' => 'tarea',
        'creacion' => 'CREATE TABLE "tarea" (
 "cod_tar" VARCHAR(20) PRIMARY KEY,
 "cod_cla" VARCHAR(20) NOT NULL,
 "cod_sec" VARCHAR(20),
 "cod_doc" VARCHAR(20) NOT NULL,
 "cod_pev" VARCHAR(20),
 "tit_tar" VARCHAR(220) NOT NULL,
 "des_tar" TEXT NOT NULL,
 "tip_tar" VARCHAR(80),
 "fec_pub_tar" TIMESTAMPTZ,
 "ape_tar" TIMESTAMPTZ,
 "fec_lim_tar" TIMESTAMPTZ NOT NULL,
 "cor_tar" TIMESTAMPTZ,
 "pun_max_tar" NUMERIC(8,2) NOT NULL,
 "perm_ent_tardia" BOOLEAN NOT NULL DEFAULT FALSE,
 "int_tar" INTEGER NOT NULL DEFAULT 1,
 "arc_tar" INTEGER,
 "tam_tar" BIGINT,
 "est_tar" VARCHAR(20) NOT NULL DEFAULT \'BORRADOR\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_cla' => '"cod_cla" VARCHAR(20) NULL',
            'cod_sec' => '"cod_sec" VARCHAR(20) NULL',
            'cod_doc' => '"cod_doc" VARCHAR(20) NULL',
            'cod_pev' => '"cod_pev" VARCHAR(20) NULL',
            'tit_tar' => '"tit_tar" VARCHAR(220) NULL',
            'des_tar' => '"des_tar" TEXT NULL',
            'tip_tar' => '"tip_tar" VARCHAR(80) NULL',
            'fec_pub_tar' => '"fec_pub_tar" TIMESTAMPTZ NULL',
            'ape_tar' => '"ape_tar" TIMESTAMPTZ NULL',
            'fec_lim_tar' => '"fec_lim_tar" TIMESTAMPTZ NULL',
            'cor_tar' => '"cor_tar" TIMESTAMPTZ NULL',
            'pun_max_tar' => '"pun_max_tar" NUMERIC(8,2) NULL',
            'perm_ent_tardia' => '"perm_ent_tardia" BOOLEAN NULL',
            'int_tar' => '"int_tar" INTEGER NULL',
            'arc_tar' => '"arc_tar" INTEGER NULL',
            'tam_tar' => '"tam_tar" BIGINT NULL',
            'est_tar' => '"est_tar" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_tar',
        'columnas' => [
            'cod_tar' => 'VARCHAR(20) PRIMARY KEY',
            'cod_cla' => 'VARCHAR(20) NOT NULL',
            'cod_sec' => 'VARCHAR(20)',
            'cod_doc' => 'VARCHAR(20) NOT NULL',
            'cod_pev' => 'VARCHAR(20)',
            'tit_tar' => 'VARCHAR(220) NOT NULL',
            'des_tar' => 'TEXT NOT NULL',
            'tip_tar' => 'VARCHAR(80)',
            'fec_pub_tar' => 'TIMESTAMPTZ',
            'ape_tar' => 'TIMESTAMPTZ',
            'fec_lim_tar' => 'TIMESTAMPTZ NOT NULL',
            'cor_tar' => 'TIMESTAMPTZ',
            'pun_max_tar' => 'NUMERIC(8,2) NOT NULL',
            'perm_ent_tardia' => 'BOOLEAN NOT NULL DEFAULT FALSE',
            'int_tar' => 'INTEGER NOT NULL DEFAULT 1',
            'arc_tar' => 'INTEGER',
            'tam_tar' => 'BIGINT',
            'est_tar' => 'VARCHAR(20) NOT NULL DEFAULT \'BORRADOR\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'pun_max_tar>0',
            'int_tar>0',
            'arc_tar IS NULL OR arc_tar>0',
            'tam_tar IS NULL OR tam_tar>0',
            'est_tar IN (\'BORRADOR\',\'PUBLICADA\',\'CERRADA\',\'ARCHIVADA\',\'ANULADA\')',
            '(ape_tar IS NULL OR fec_lim_tar>=ape_tar) AND (cor_tar IS NULL OR cor_tar>=fec_lim_tar)',
        ],
        'unicos' => [],
        'grupo' => 'AulaVirtual',
        'existente' => true,
    ],
    [
        'tabla' => 'tarea_material',
        'creacion' => 'CREATE TABLE "tarea_material" (
 "cod_tar_mat" VARCHAR(20) PRIMARY KEY,
 "cod_tar" VARCHAR(20) NOT NULL,
 "nom_tar_mat" VARCHAR(255) NOT NULL,
 "tip_tar_mat" VARCHAR(80) NOT NULL,
 "rut_tar_mat" TEXT,
 "url_tar_mat" url_http,
 "mime_tar_mat" VARCHAR(150),
 "tam_tar_mat" BIGINT,
 "has_tma" hash_sha256,
 "est_tar_mat" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_tar' => '"cod_tar" VARCHAR(20) NULL',
            'nom_tar_mat' => '"nom_tar_mat" VARCHAR(255) NULL',
            'tip_tar_mat' => '"tip_tar_mat" VARCHAR(80) NULL',
            'rut_tar_mat' => '"rut_tar_mat" TEXT NULL',
            'url_tar_mat' => '"url_tar_mat" url_http NULL',
            'mime_tar_mat' => '"mime_tar_mat" VARCHAR(150) NULL',
            'tam_tar_mat' => '"tam_tar_mat" BIGINT NULL',
            'has_tma' => '"has_tma" hash_sha256 NULL',
            'est_tar_mat' => '"est_tar_mat" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_tar_mat',
        'columnas' => [
            'cod_tar_mat' => 'VARCHAR(20) PRIMARY KEY',
            'cod_tar' => 'VARCHAR(20) NOT NULL',
            'nom_tar_mat' => 'VARCHAR(255) NOT NULL',
            'tip_tar_mat' => 'VARCHAR(80) NOT NULL',
            'rut_tar_mat' => 'TEXT',
            'url_tar_mat' => 'url_http',
            'mime_tar_mat' => 'VARCHAR(150)',
            'tam_tar_mat' => 'BIGINT',
            'has_tma' => 'hash_sha256',
            'est_tar_mat' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'tam_tar_mat IS NULL OR tam_tar_mat>=0',
            'est_tar_mat IN (\'ACTIVO\',\'OCULTO\',\'ANULADO\')',
            'rut_tar_mat IS NOT NULL OR url_tar_mat IS NOT NULL',
        ],
        'unicos' => [],
        'grupo' => 'AulaVirtual',
        'existente' => true,
    ],
    [
        'tabla' => 'entrega_tarea',
        'creacion' => 'CREATE TABLE "entrega_tarea" (
 "cod_ent" VARCHAR(20) PRIMARY KEY,
 "cod_tar" VARCHAR(20) NOT NULL,
 "cod_est" VARCHAR(20) NOT NULL,
 "int_ent" INTEGER NOT NULL,
 "ini_ent" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "fec_ent" TIMESTAMPTZ,
 "tex_ent" TEXT,
 "est_ent" VARCHAR(20) NOT NULL DEFAULT \'BORRADOR\',
 "obs_ent" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_tar' => '"cod_tar" VARCHAR(20) NULL',
            'cod_est' => '"cod_est" VARCHAR(20) NULL',
            'int_ent' => '"int_ent" INTEGER NULL',
            'ini_ent' => '"ini_ent" TIMESTAMPTZ NULL',
            'fec_ent' => '"fec_ent" TIMESTAMPTZ NULL',
            'tex_ent' => '"tex_ent" TEXT NULL',
            'est_ent' => '"est_ent" VARCHAR(20) NULL',
            'obs_ent' => '"obs_ent" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_ent',
        'columnas' => [
            'cod_ent' => 'VARCHAR(20) PRIMARY KEY',
            'cod_tar' => 'VARCHAR(20) NOT NULL',
            'cod_est' => 'VARCHAR(20) NOT NULL',
            'int_ent' => 'INTEGER NOT NULL',
            'ini_ent' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'fec_ent' => 'TIMESTAMPTZ',
            'tex_ent' => 'TEXT',
            'est_ent' => 'VARCHAR(20) NOT NULL DEFAULT \'BORRADOR\'',
            'obs_ent' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'int_ent>0',
            'est_ent IN (\'BORRADOR\',\'ENTREGADA\',\'REABIERTA\',\'RETIRADA\',\'ANULADA\')',
            'fec_ent IS NULL OR fec_ent>=ini_ent',
        ],
        'unicos' => [
            [
                'cod_tar',
                'cod_est',
                'int_ent',
            ],
        ],
        'grupo' => 'AulaVirtual',
        'existente' => true,
    ],
    [
        'tabla' => 'entrega_archivo',
        'creacion' => 'CREATE TABLE "entrega_archivo" (
 "cod_ent_arc" VARCHAR(20) PRIMARY KEY,
 "cod_ent" VARCHAR(20) NOT NULL,
 "nom_arc" VARCHAR(255) NOT NULL,
 "rut_arc" TEXT NOT NULL,
 "mime_arc" VARCHAR(150),
 "tam_arc" BIGINT,
 "has_arc" hash_sha256,
 "est_arc" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_ent' => '"cod_ent" VARCHAR(20) NULL',
            'nom_arc' => '"nom_arc" VARCHAR(255) NULL',
            'rut_arc' => '"rut_arc" TEXT NULL',
            'mime_arc' => '"mime_arc" VARCHAR(150) NULL',
            'tam_arc' => '"tam_arc" BIGINT NULL',
            'has_arc' => '"has_arc" hash_sha256 NULL',
            'est_arc' => '"est_arc" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_ent_arc',
        'columnas' => [
            'cod_ent_arc' => 'VARCHAR(20) PRIMARY KEY',
            'cod_ent' => 'VARCHAR(20) NOT NULL',
            'nom_arc' => 'VARCHAR(255) NOT NULL',
            'rut_arc' => 'TEXT NOT NULL',
            'mime_arc' => 'VARCHAR(150)',
            'tam_arc' => 'BIGINT',
            'has_arc' => 'hash_sha256',
            'est_arc' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'tam_arc IS NULL OR tam_arc>=0',
            'est_arc IN (\'ACTIVO\',\'ANULADO\')',
        ],
        'unicos' => [],
        'grupo' => 'AulaVirtual',
        'existente' => true,
    ],
    [
        'tabla' => 'calificacion_tarea',
        'creacion' => 'CREATE TABLE "calificacion_tarea" (
 "cod_cal_tar" VARCHAR(20) PRIMARY KEY,
 "cod_ent" VARCHAR(20) NOT NULL UNIQUE,
 "cod_doc" VARCHAR(20) NOT NULL,
 "pun_obt" NUMERIC(8,2) NOT NULL,
 "pun_max" NUMERIC(8,2) NOT NULL,
 "com_cal" TEXT,
 "fec_cal" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "pub_cal" TIMESTAMPTZ,
 "est_cal" VARCHAR(20) NOT NULL DEFAULT \'BORRADOR\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_ent' => '"cod_ent" VARCHAR(20) NULL',
            'cod_doc' => '"cod_doc" VARCHAR(20) NULL',
            'pun_obt' => '"pun_obt" NUMERIC(8,2) NULL',
            'pun_max' => '"pun_max" NUMERIC(8,2) NULL',
            'com_cal' => '"com_cal" TEXT NULL',
            'fec_cal' => '"fec_cal" TIMESTAMPTZ NULL',
            'pub_cal' => '"pub_cal" TIMESTAMPTZ NULL',
            'est_cal' => '"est_cal" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_cal_tar',
        'columnas' => [
            'cod_cal_tar' => 'VARCHAR(20) PRIMARY KEY',
            'cod_ent' => 'VARCHAR(20) NOT NULL UNIQUE',
            'cod_doc' => 'VARCHAR(20) NOT NULL',
            'pun_obt' => 'NUMERIC(8,2) NOT NULL',
            'pun_max' => 'NUMERIC(8,2) NOT NULL',
            'com_cal' => 'TEXT',
            'fec_cal' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'pub_cal' => 'TIMESTAMPTZ',
            'est_cal' => 'VARCHAR(20) NOT NULL DEFAULT \'BORRADOR\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'pun_obt>=0',
            'pun_max>0',
            'est_cal IN (\'BORRADOR\',\'PUBLICADA\',\'RECTIFICADA\',\'ANULADA\')',
            'pun_obt<=pun_max',
            'pub_cal IS NULL OR pub_cal>=fec_cal',
        ],
        'unicos' => [
            [
                'cod_ent',
            ],
        ],
        'grupo' => 'AulaVirtual',
        'existente' => true,
    ],
    [
        'tabla' => 'retroalimentacion_archivo',
        'creacion' => 'CREATE TABLE "retroalimentacion_archivo" (
 "cod_raf" VARCHAR(20) PRIMARY KEY,
 "cod_cal_tar" VARCHAR(20) NOT NULL,
 "nom_raf" VARCHAR(255) NOT NULL,
 "rut_raf" TEXT NOT NULL,
 "mim_raf" VARCHAR(150),
 "tam_raf" BIGINT,
 "has_raf" hash_sha256,
 "est_raf" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_cal_tar' => '"cod_cal_tar" VARCHAR(20) NULL',
            'nom_raf' => '"nom_raf" VARCHAR(255) NULL',
            'rut_raf' => '"rut_raf" TEXT NULL',
            'mim_raf' => '"mim_raf" VARCHAR(150) NULL',
            'tam_raf' => '"tam_raf" BIGINT NULL',
            'has_raf' => '"has_raf" hash_sha256 NULL',
            'est_raf' => '"est_raf" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_raf',
        'columnas' => [
            'cod_raf' => 'VARCHAR(20) PRIMARY KEY',
            'cod_cal_tar' => 'VARCHAR(20) NOT NULL',
            'nom_raf' => 'VARCHAR(255) NOT NULL',
            'rut_raf' => 'TEXT NOT NULL',
            'mim_raf' => 'VARCHAR(150)',
            'tam_raf' => 'BIGINT',
            'has_raf' => 'hash_sha256',
            'est_raf' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'tam_raf IS NULL OR tam_raf>=0',
            'est_raf IN (\'ACTIVO\',\'ANULADO\')',
        ],
        'unicos' => [],
        'grupo' => 'AulaVirtual',
        'existente' => false,
    ],
    [
        'tabla' => 'cuestionario',
        'creacion' => 'CREATE TABLE "cuestionario" (
 "cod_cue" VARCHAR(20) PRIMARY KEY,
 "cod_cla" VARCHAR(20) NOT NULL,
 "cod_sec" VARCHAR(20),
 "cod_doc" VARCHAR(20) NOT NULL,
 "cod_pev" VARCHAR(20),
 "tit_cue" VARCHAR(220) NOT NULL,
 "des_cue" TEXT,
 "pub_cue" TIMESTAMPTZ,
 "ape_cue" TIMESTAMPTZ NOT NULL,
 "cie_cue" TIMESTAMPTZ NOT NULL,
 "dur_cue" INTEGER,
 "int_cue" INTEGER NOT NULL DEFAULT 1,
 "met_cue" VARCHAR(40) NOT NULL DEFAULT \'ULTIMO\',
 "mez_cue" BOOLEAN NOT NULL DEFAULT FALSE,
 "mos_cue" BOOLEAN NOT NULL DEFAULT TRUE,
 "max_cue" NUMERIC(8,2) NOT NULL,
 "est_cue" VARCHAR(20) NOT NULL DEFAULT \'BORRADOR\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_cla' => '"cod_cla" VARCHAR(20) NULL',
            'cod_sec' => '"cod_sec" VARCHAR(20) NULL',
            'cod_doc' => '"cod_doc" VARCHAR(20) NULL',
            'cod_pev' => '"cod_pev" VARCHAR(20) NULL',
            'tit_cue' => '"tit_cue" VARCHAR(220) NULL',
            'des_cue' => '"des_cue" TEXT NULL',
            'pub_cue' => '"pub_cue" TIMESTAMPTZ NULL',
            'ape_cue' => '"ape_cue" TIMESTAMPTZ NULL',
            'cie_cue' => '"cie_cue" TIMESTAMPTZ NULL',
            'dur_cue' => '"dur_cue" INTEGER NULL',
            'int_cue' => '"int_cue" INTEGER NULL',
            'met_cue' => '"met_cue" VARCHAR(40) NULL',
            'mez_cue' => '"mez_cue" BOOLEAN NULL',
            'mos_cue' => '"mos_cue" BOOLEAN NULL',
            'max_cue' => '"max_cue" NUMERIC(8,2) NULL',
            'est_cue' => '"est_cue" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_cue',
        'columnas' => [
            'cod_cue' => 'VARCHAR(20) PRIMARY KEY',
            'cod_cla' => 'VARCHAR(20) NOT NULL',
            'cod_sec' => 'VARCHAR(20)',
            'cod_doc' => 'VARCHAR(20) NOT NULL',
            'cod_pev' => 'VARCHAR(20)',
            'tit_cue' => 'VARCHAR(220) NOT NULL',
            'des_cue' => 'TEXT',
            'pub_cue' => 'TIMESTAMPTZ',
            'ape_cue' => 'TIMESTAMPTZ NOT NULL',
            'cie_cue' => 'TIMESTAMPTZ NOT NULL',
            'dur_cue' => 'INTEGER',
            'int_cue' => 'INTEGER NOT NULL DEFAULT 1',
            'met_cue' => 'VARCHAR(40) NOT NULL DEFAULT \'ULTIMO\'',
            'mez_cue' => 'BOOLEAN NOT NULL DEFAULT FALSE',
            'mos_cue' => 'BOOLEAN NOT NULL DEFAULT TRUE',
            'max_cue' => 'NUMERIC(8,2) NOT NULL',
            'est_cue' => 'VARCHAR(20) NOT NULL DEFAULT \'BORRADOR\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'dur_cue IS NULL OR dur_cue>0',
            'int_cue>0',
            'met_cue IN (\'ULTIMO\',\'MEJOR\',\'PROMEDIO\',\'PRIMERO\')',
            'max_cue>0',
            'est_cue IN (\'BORRADOR\',\'PUBLICADO\',\'CERRADO\',\'ARCHIVADO\',\'ANULADO\')',
            'cie_cue>ape_cue',
        ],
        'unicos' => [],
        'grupo' => 'AulaVirtual',
        'existente' => false,
    ],
    [
        'tabla' => 'pregunta_cuestionario',
        'creacion' => 'CREATE TABLE "pregunta_cuestionario" (
 "cod_prc" VARCHAR(20) PRIMARY KEY,
 "cod_cue" VARCHAR(20) NOT NULL,
 "tip_prc" VARCHAR(40) NOT NULL,
 "enu_prc" TEXT NOT NULL,
 "pun_prc" NUMERIC(8,2) NOT NULL,
 "ord_prc" INTEGER NOT NULL,
 "req_prc" BOOLEAN NOT NULL DEFAULT TRUE,
 "est_prc" VARCHAR(20) NOT NULL DEFAULT \'ACTIVA\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_cue' => '"cod_cue" VARCHAR(20) NULL',
            'tip_prc' => '"tip_prc" VARCHAR(40) NULL',
            'enu_prc' => '"enu_prc" TEXT NULL',
            'pun_prc' => '"pun_prc" NUMERIC(8,2) NULL',
            'ord_prc' => '"ord_prc" INTEGER NULL',
            'req_prc' => '"req_prc" BOOLEAN NULL',
            'est_prc' => '"est_prc" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_prc',
        'columnas' => [
            'cod_prc' => 'VARCHAR(20) PRIMARY KEY',
            'cod_cue' => 'VARCHAR(20) NOT NULL',
            'tip_prc' => 'VARCHAR(40) NOT NULL',
            'enu_prc' => 'TEXT NOT NULL',
            'pun_prc' => 'NUMERIC(8,2) NOT NULL',
            'ord_prc' => 'INTEGER NOT NULL',
            'req_prc' => 'BOOLEAN NOT NULL DEFAULT TRUE',
            'est_prc' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVA\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'tip_prc IN (\'OPCION_UNICA\',\'OPCION_MULTIPLE\',\'VERDADERO_FALSO\',\'RESPUESTA_CORTA\',\'DESARROLLO\')',
            'pun_prc>0',
            'ord_prc>0',
            'est_prc IN (\'ACTIVA\',\'INACTIVA\',\'ANULADA\')',
        ],
        'unicos' => [
            [
                'cod_cue',
                'ord_prc',
            ],
        ],
        'grupo' => 'AulaVirtual',
        'existente' => false,
    ],
    [
        'tabla' => 'opcion_pregunta',
        'creacion' => 'CREATE TABLE "opcion_pregunta" (
 "cod_opr" VARCHAR(20) PRIMARY KEY,
 "cod_prc" VARCHAR(20) NOT NULL,
 "tex_opr" TEXT NOT NULL,
 "por_opr" porcentaje_0_100 NOT NULL DEFAULT 0,
 "ord_opr" INTEGER NOT NULL,
 "est_opr" VARCHAR(20) NOT NULL DEFAULT \'ACTIVA\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_prc' => '"cod_prc" VARCHAR(20) NULL',
            'tex_opr' => '"tex_opr" TEXT NULL',
            'por_opr' => '"por_opr" porcentaje_0_100 NULL',
            'ord_opr' => '"ord_opr" INTEGER NULL',
            'est_opr' => '"est_opr" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_opr',
        'columnas' => [
            'cod_opr' => 'VARCHAR(20) PRIMARY KEY',
            'cod_prc' => 'VARCHAR(20) NOT NULL',
            'tex_opr' => 'TEXT NOT NULL',
            'por_opr' => 'porcentaje_0_100 NOT NULL DEFAULT 0',
            'ord_opr' => 'INTEGER NOT NULL',
            'est_opr' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVA\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'ord_opr>0',
            'est_opr IN (\'ACTIVA\',\'INACTIVA\',\'ANULADA\')',
        ],
        'unicos' => [
            [
                'cod_prc',
                'ord_opr',
            ],
        ],
        'grupo' => 'AulaVirtual',
        'existente' => false,
    ],
    [
        'tabla' => 'intento_cuestionario',
        'creacion' => 'CREATE TABLE "intento_cuestionario" (
 "cod_inc" VARCHAR(20) PRIMARY KEY,
 "cod_cue" VARCHAR(20) NOT NULL,
 "cod_est" VARCHAR(20) NOT NULL,
 "num_inc" INTEGER NOT NULL,
 "ini_inc" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "fin_inc" TIMESTAMPTZ,
 "pun_inc" NUMERIC(8,2),
 "max_inc" NUMERIC(8,2) NOT NULL,
 "est_inc" VARCHAR(20) NOT NULL DEFAULT \'EN_PROCESO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_cue' => '"cod_cue" VARCHAR(20) NULL',
            'cod_est' => '"cod_est" VARCHAR(20) NULL',
            'num_inc' => '"num_inc" INTEGER NULL',
            'ini_inc' => '"ini_inc" TIMESTAMPTZ NULL',
            'fin_inc' => '"fin_inc" TIMESTAMPTZ NULL',
            'pun_inc' => '"pun_inc" NUMERIC(8,2) NULL',
            'max_inc' => '"max_inc" NUMERIC(8,2) NULL',
            'est_inc' => '"est_inc" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_inc',
        'columnas' => [
            'cod_inc' => 'VARCHAR(20) PRIMARY KEY',
            'cod_cue' => 'VARCHAR(20) NOT NULL',
            'cod_est' => 'VARCHAR(20) NOT NULL',
            'num_inc' => 'INTEGER NOT NULL',
            'ini_inc' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'fin_inc' => 'TIMESTAMPTZ',
            'pun_inc' => 'NUMERIC(8,2)',
            'max_inc' => 'NUMERIC(8,2) NOT NULL',
            'est_inc' => 'VARCHAR(20) NOT NULL DEFAULT \'EN_PROCESO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'num_inc>0',
            'pun_inc IS NULL OR pun_inc>=0',
            'max_inc>0',
            'est_inc IN (\'EN_PROCESO\',\'FINALIZADO\',\'CALIFICADO\',\'ANULADO\')',
            'fin_inc IS NULL OR fin_inc>=ini_inc',
            'pun_inc IS NULL OR pun_inc<=max_inc',
        ],
        'unicos' => [
            [
                'cod_cue',
                'cod_est',
                'num_inc',
            ],
        ],
        'grupo' => 'AulaVirtual',
        'existente' => false,
    ],
    [
        'tabla' => 'respuesta_cuestionario',
        'creacion' => 'CREATE TABLE "respuesta_cuestionario" (
 "cod_rcu" VARCHAR(20) PRIMARY KEY,
 "cod_inc" VARCHAR(20) NOT NULL,
 "cod_prc" VARCHAR(20) NOT NULL,
 "tex_rcu" TEXT,
 "pun_rcu" NUMERIC(8,2),
 "cor_rcu" BOOLEAN,
 "doc_rcu" VARCHAR(20),
 "fec_rcu" TIMESTAMPTZ,
 "obs_rcu" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_inc' => '"cod_inc" VARCHAR(20) NULL',
            'cod_prc' => '"cod_prc" VARCHAR(20) NULL',
            'tex_rcu' => '"tex_rcu" TEXT NULL',
            'pun_rcu' => '"pun_rcu" NUMERIC(8,2) NULL',
            'cor_rcu' => '"cor_rcu" BOOLEAN NULL',
            'doc_rcu' => '"doc_rcu" VARCHAR(20) NULL',
            'fec_rcu' => '"fec_rcu" TIMESTAMPTZ NULL',
            'obs_rcu' => '"obs_rcu" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_rcu',
        'columnas' => [
            'cod_rcu' => 'VARCHAR(20) PRIMARY KEY',
            'cod_inc' => 'VARCHAR(20) NOT NULL',
            'cod_prc' => 'VARCHAR(20) NOT NULL',
            'tex_rcu' => 'TEXT',
            'pun_rcu' => 'NUMERIC(8,2)',
            'cor_rcu' => 'BOOLEAN',
            'doc_rcu' => 'VARCHAR(20)',
            'fec_rcu' => 'TIMESTAMPTZ',
            'obs_rcu' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'pun_rcu IS NULL OR pun_rcu>=0',
        ],
        'unicos' => [
            [
                'cod_inc',
                'cod_prc',
            ],
        ],
        'grupo' => 'AulaVirtual',
        'existente' => false,
    ],
    [
        'tabla' => 'respuesta_opcion',
        'creacion' => 'CREATE TABLE "respuesta_opcion" (
 "cod_rop" VARCHAR(20) PRIMARY KEY,
 "cod_rcu" VARCHAR(20) NOT NULL,
 "cod_opr" VARCHAR(20) NOT NULL,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_rcu' => '"cod_rcu" VARCHAR(20) NULL',
            'cod_opr' => '"cod_opr" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_rop',
        'columnas' => [
            'cod_rop' => 'VARCHAR(20) PRIMARY KEY',
            'cod_rcu' => 'VARCHAR(20) NOT NULL',
            'cod_opr' => 'VARCHAR(20) NOT NULL',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [],
        'unicos' => [
            [
                'cod_rcu',
                'cod_opr',
            ],
        ],
        'grupo' => 'AulaVirtual',
        'existente' => false,
    ],
    [
        'tabla' => 'foro_clase',
        'creacion' => 'CREATE TABLE "foro_clase" (
 "cod_for" VARCHAR(20) PRIMARY KEY,
 "cod_cla" VARCHAR(20) NOT NULL,
 "cod_sec" VARCHAR(20),
 "cod_doc" VARCHAR(20) NOT NULL,
 "tit_for" VARCHAR(220) NOT NULL,
 "des_for" TEXT NOT NULL,
 "ape_for" TIMESTAMPTZ NOT NULL,
 "cie_for" TIMESTAMPTZ,
 "est_for" VARCHAR(20) NOT NULL DEFAULT \'ABIERTO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_cla' => '"cod_cla" VARCHAR(20) NULL',
            'cod_sec' => '"cod_sec" VARCHAR(20) NULL',
            'cod_doc' => '"cod_doc" VARCHAR(20) NULL',
            'tit_for' => '"tit_for" VARCHAR(220) NULL',
            'des_for' => '"des_for" TEXT NULL',
            'ape_for' => '"ape_for" TIMESTAMPTZ NULL',
            'cie_for' => '"cie_for" TIMESTAMPTZ NULL',
            'est_for' => '"est_for" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_for',
        'columnas' => [
            'cod_for' => 'VARCHAR(20) PRIMARY KEY',
            'cod_cla' => 'VARCHAR(20) NOT NULL',
            'cod_sec' => 'VARCHAR(20)',
            'cod_doc' => 'VARCHAR(20) NOT NULL',
            'tit_for' => 'VARCHAR(220) NOT NULL',
            'des_for' => 'TEXT NOT NULL',
            'ape_for' => 'TIMESTAMPTZ NOT NULL',
            'cie_for' => 'TIMESTAMPTZ',
            'est_for' => 'VARCHAR(20) NOT NULL DEFAULT \'ABIERTO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_for IN (\'BORRADOR\',\'ABIERTO\',\'CERRADO\',\'ARCHIVADO\',\'ANULADO\')',
            'cie_for IS NULL OR cie_for>=ape_for',
        ],
        'unicos' => [],
        'grupo' => 'AulaVirtual',
        'existente' => false,
    ],
    [
        'tabla' => 'foro_tema',
        'creacion' => 'CREATE TABLE "foro_tema" (
 "cod_fte" VARCHAR(20) PRIMARY KEY,
 "cod_for" VARCHAR(20) NOT NULL,
 "cod_usu" VARCHAR(20) NOT NULL,
 "tit_fte" VARCHAR(220) NOT NULL,
 "fec_fte" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "est_fte" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_for' => '"cod_for" VARCHAR(20) NULL',
            'cod_usu' => '"cod_usu" VARCHAR(20) NULL',
            'tit_fte' => '"tit_fte" VARCHAR(220) NULL',
            'fec_fte' => '"fec_fte" TIMESTAMPTZ NULL',
            'est_fte' => '"est_fte" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_fte',
        'columnas' => [
            'cod_fte' => 'VARCHAR(20) PRIMARY KEY',
            'cod_for' => 'VARCHAR(20) NOT NULL',
            'cod_usu' => 'VARCHAR(20) NOT NULL',
            'tit_fte' => 'VARCHAR(220) NOT NULL',
            'fec_fte' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'est_fte' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_fte IN (\'ACTIVO\',\'CERRADO\',\'OCULTO\',\'ANULADO\')',
        ],
        'unicos' => [],
        'grupo' => 'AulaVirtual',
        'existente' => false,
    ],
    [
        'tabla' => 'foro_mensaje',
        'creacion' => 'CREATE TABLE "foro_mensaje" (
 "cod_fme" VARCHAR(20) PRIMARY KEY,
 "cod_fte" VARCHAR(20) NOT NULL,
 "cod_usu" VARCHAR(20) NOT NULL,
 "pad_fme" VARCHAR(20),
 "con_fme" TEXT NOT NULL,
 "fec_fme" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "est_fme" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_fte' => '"cod_fte" VARCHAR(20) NULL',
            'cod_usu' => '"cod_usu" VARCHAR(20) NULL',
            'pad_fme' => '"pad_fme" VARCHAR(20) NULL',
            'con_fme' => '"con_fme" TEXT NULL',
            'fec_fme' => '"fec_fme" TIMESTAMPTZ NULL',
            'est_fme' => '"est_fme" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_fme',
        'columnas' => [
            'cod_fme' => 'VARCHAR(20) PRIMARY KEY',
            'cod_fte' => 'VARCHAR(20) NOT NULL',
            'cod_usu' => 'VARCHAR(20) NOT NULL',
            'pad_fme' => 'VARCHAR(20)',
            'con_fme' => 'TEXT NOT NULL',
            'fec_fme' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'est_fme' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_fme IN (\'ACTIVO\',\'EDITADO\',\'OCULTO\',\'ANULADO\')',
        ],
        'unicos' => [],
        'grupo' => 'AulaVirtual',
        'existente' => false,
    ],
    [
        'tabla' => 'foro_archivo',
        'creacion' => 'CREATE TABLE "foro_archivo" (
 "cod_far" VARCHAR(20) PRIMARY KEY,
 "cod_fme" VARCHAR(20) NOT NULL,
 "nom_far" VARCHAR(255) NOT NULL,
 "rut_far" TEXT NOT NULL,
 "mim_far" VARCHAR(150),
 "tam_far" BIGINT,
 "has_far" hash_sha256,
 "est_far" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_fme' => '"cod_fme" VARCHAR(20) NULL',
            'nom_far' => '"nom_far" VARCHAR(255) NULL',
            'rut_far' => '"rut_far" TEXT NULL',
            'mim_far' => '"mim_far" VARCHAR(150) NULL',
            'tam_far' => '"tam_far" BIGINT NULL',
            'has_far' => '"has_far" hash_sha256 NULL',
            'est_far' => '"est_far" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_far',
        'columnas' => [
            'cod_far' => 'VARCHAR(20) PRIMARY KEY',
            'cod_fme' => 'VARCHAR(20) NOT NULL',
            'nom_far' => 'VARCHAR(255) NOT NULL',
            'rut_far' => 'TEXT NOT NULL',
            'mim_far' => 'VARCHAR(150)',
            'tam_far' => 'BIGINT',
            'has_far' => 'hash_sha256',
            'est_far' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'tam_far IS NULL OR tam_far>=0',
            'est_far IN (\'ACTIVO\',\'ANULADO\')',
        ],
        'unicos' => [],
        'grupo' => 'AulaVirtual',
        'existente' => false,
    ],
    [
        'tabla' => 'registro_actividad_clase',
        'creacion' => 'CREATE TABLE "registro_actividad_clase" (
 "cod_rac" VARCHAR(20) PRIMARY KEY,
 "cod_cla" VARCHAR(20) NOT NULL,
 "cod_est" VARCHAR(20),
 "cod_usu" VARCHAR(20) NOT NULL,
 "tip_rac" VARCHAR(80) NOT NULL,
 "pub_rac" VARCHAR(20),
 "mat_rac" VARCHAR(20),
 "tar_rac" VARCHAR(20),
 "cue_rac" VARCHAR(20),
 "for_rac" VARCHAR(20),
 "men_rac" VARCHAR(20),
 "fec_rac" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "met_rac" JSONB,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_cla' => '"cod_cla" VARCHAR(20) NULL',
            'cod_est' => '"cod_est" VARCHAR(20) NULL',
            'cod_usu' => '"cod_usu" VARCHAR(20) NULL',
            'tip_rac' => '"tip_rac" VARCHAR(80) NULL',
            'pub_rac' => '"pub_rac" VARCHAR(20) NULL',
            'mat_rac' => '"mat_rac" VARCHAR(20) NULL',
            'tar_rac' => '"tar_rac" VARCHAR(20) NULL',
            'cue_rac' => '"cue_rac" VARCHAR(20) NULL',
            'for_rac' => '"for_rac" VARCHAR(20) NULL',
            'men_rac' => '"men_rac" VARCHAR(20) NULL',
            'fec_rac' => '"fec_rac" TIMESTAMPTZ NULL',
            'met_rac' => '"met_rac" JSONB NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_rac',
        'columnas' => [
            'cod_rac' => 'VARCHAR(20) PRIMARY KEY',
            'cod_cla' => 'VARCHAR(20) NOT NULL',
            'cod_est' => 'VARCHAR(20)',
            'cod_usu' => 'VARCHAR(20) NOT NULL',
            'tip_rac' => 'VARCHAR(80) NOT NULL',
            'pub_rac' => 'VARCHAR(20)',
            'mat_rac' => 'VARCHAR(20)',
            'tar_rac' => 'VARCHAR(20)',
            'cue_rac' => 'VARCHAR(20)',
            'for_rac' => 'VARCHAR(20)',
            'men_rac' => 'VARCHAR(20)',
            'fec_rac' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'met_rac' => 'JSONB',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'num_nonnulls(pub_rac,mat_rac,tar_rac,cue_rac,for_rac,men_rac)<=1',
            'met_rac IS NULL OR jsonb_typeof(met_rac)=\'object\'',
        ],
        'unicos' => [],
        'grupo' => 'AulaVirtual',
        'existente' => false,
    ],
];
