                    <div class="ui-card-soft p-5"><p class="ui-kicker">1 · Grado</p><h3 class="ui-title font-bold mt-2">¿Qué grado necesitas preparar?</h3><p class="ui-muted text-sm mt-2">El catálogo actual llega a sexto. Puedes escribir un grado adicional, como séptimo, para revisar su autorización. Otro paralelo es un grupo del mismo grado.</p>
                        <label class="ui-label block mt-4" for="curso-entrada">Nombre del grado</label><div class="cursos-entrada mt-2"><input id="curso-entrada" class="ui-input" wire:model="entradaCurso" type="text" maxlength="120" placeholder="Ejemplo: cuarto de secundaria" @readonly(in_array($operacion,['desactivar','reactivar'])) /><button type="button" class="ui-btn ui-btn-secondary" x-on:click="interpretar()" :disabled="!!procesando"><i class="ph-duotone" :class="procesando==='interpretar'?'ph-spinner-gap cursos-giro':'ph-sparkle'" aria-hidden="true"></i><span x-text="procesando==='interpretar'?'Revisando…':'Reconocer'"></span></button></div><x-input-error for="entradaCurso" />
                        @if(in_array($operacion,['crear','editar']))<div class="cursos-grados-opciones mt-3">@foreach(range(1,6) as $grado)<button type="button" x-on:click="elegirGrado({{ $grado }})" :disabled="!!procesando" aria-pressed="{{ ($interpretacion['orden']??null)===$grado?'true':'false' }}">{{ $grado }}° <span>Secundaria</span></button>@endforeach</div>@endif
                        @if($entradaCurso!=='' && $interpretacion)<p class="mt-4 text-sm {{ ($interpretacion['valido']??false)?'ui-muted':'ui-error' }}" role="status">{{ $interpretacion['mensaje'] }}</p>@endif
                        @if($interpretacion['valido']??false)<div class="cursos-vista-previa mt-4"><i class="ph-duotone ph-graduation-cap" aria-hidden="true"></i><div><strong>{{ $interpretacion['nombre'] }}</strong><span>{{ $interpretacion['categoria'] }} · {{ ($interpretacion['extraordinario']??false)?'Pendiente de autorización':($operacion==='crear'?'Se creará habilitado':'Conserva su historial') }}</span></div></div>
                        @if($interpretacion['extraordinario']??false)<p class="ui-alert-warning text-sm mt-3">Se reconoció el grado adicional. El PDF debe autorizar expresamente este grado y citar la norma que permite ampliar la estructura para la gestión seleccionada. La comprobación con la autoridad sigue siendo obligatoria.</p>@endif
                        @if(in_array($operacion,['crear','editar']) && $resumen->contains(fn($c)=>$c['orden']===$interpretacion['orden'] && $c['cod_cur']!==$cursoCambio))<p class="ui-alert-warning mt-3 text-sm">Este grado ya existe. Si necesitas otra aula, registra un paralelo; no se duplica el grado.</p>@endif
                        @endif
                    </div>
                    <p class="ui-alert-info mt-4 text-sm">Este proceso registra únicamente el grado y su autorización. Los grupos por paralelo y turno se organizan por separado; las materias y los docentes se asignan desde el horario.</p>
