<?php

declare(strict_types=1);

/** Contrato aditivo Personal. Fuente: guía aprobada 2026-10-03; sin backfill ni retiro. */
return [
    [
        'tabla' => 'personal_institucional',
        'creacion' => 'CREATE TABLE "personal_institucional" (
 "cod_pin" VARCHAR(20) PRIMARY KEY,
 "cod_per" VARCHAR(20) NOT NULL UNIQUE,
 "est_pin" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_per' => '"cod_per" VARCHAR(20) NULL',
            'est_pin' => '"est_pin" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_pin',
        'columnas' => [
            'cod_pin' => 'VARCHAR(20) PRIMARY KEY',
            'cod_per' => 'VARCHAR(20) NOT NULL UNIQUE',
            'est_pin' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_pin IN (\'ACTIVO\',\'INACTIVO\',\'RETIRADO\',\'ANULADO\')',
        ],
        'unicos' => [
            [
                'cod_per',
            ],
        ],
        'grupo' => 'Personal',
        'existente' => true,
    ],
    [
        'tabla' => 'cargo_institucional',
        'creacion' => 'CREATE TABLE "cargo_institucional" (
 "cod_cai" VARCHAR(20) PRIMARY KEY,
 "cla_cai" VARCHAR(50) NOT NULL UNIQUE,
 "nom_cai" VARCHAR(120) NOT NULL,
 "des_cai" TEXT,
 "est_cai" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cla_cai' => '"cla_cai" VARCHAR(50) NULL',
            'nom_cai' => '"nom_cai" VARCHAR(120) NULL',
            'des_cai' => '"des_cai" TEXT NULL',
            'est_cai' => '"est_cai" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_cai',
        'columnas' => [
            'cod_cai' => 'VARCHAR(20) PRIMARY KEY',
            'cla_cai' => 'VARCHAR(50) NOT NULL UNIQUE',
            'nom_cai' => 'VARCHAR(120) NOT NULL',
            'des_cai' => 'TEXT',
            'est_cai' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_cai IN (\'ACTIVO\',\'INACTIVO\')',
        ],
        'unicos' => [
            [
                'cla_cai',
            ],
        ],
        'grupo' => 'Personal',
        'existente' => false,
    ],
    [
        'tabla' => 'vinculo_personal',
        'creacion' => 'CREATE TABLE "vinculo_personal" (
 "cod_vpe" VARCHAR(20) PRIMARY KEY,
 "cod_pin" VARCHAR(20) NOT NULL,
 "cod_cai" VARCHAR(20) NOT NULL,
 "tip_vpe" VARCHAR(80) NOT NULL,
 "fii_vpe" DATE NOT NULL,
 "ffi_vpe" DATE,
 "ref_vpe" VARCHAR(255),
 "est_vpe" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "obs_vpe" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_pin' => '"cod_pin" VARCHAR(20) NULL',
            'cod_cai' => '"cod_cai" VARCHAR(20) NULL',
            'tip_vpe' => '"tip_vpe" VARCHAR(80) NULL',
            'fii_vpe' => '"fii_vpe" DATE NULL',
            'ffi_vpe' => '"ffi_vpe" DATE NULL',
            'ref_vpe' => '"ref_vpe" VARCHAR(255) NULL',
            'est_vpe' => '"est_vpe" VARCHAR(20) NULL',
            'obs_vpe' => '"obs_vpe" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_vpe',
        'columnas' => [
            'cod_vpe' => 'VARCHAR(20) PRIMARY KEY',
            'cod_pin' => 'VARCHAR(20) NOT NULL',
            'cod_cai' => 'VARCHAR(20) NOT NULL',
            'tip_vpe' => 'VARCHAR(80) NOT NULL',
            'fii_vpe' => 'DATE NOT NULL',
            'ffi_vpe' => 'DATE',
            'ref_vpe' => 'VARCHAR(255)',
            'est_vpe' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'obs_vpe' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_vpe IN (\'ACTIVO\',\'FINALIZADO\',\'SUSPENDIDO\',\'ANULADO\')',
            'ffi_vpe IS NULL OR ffi_vpe>=fii_vpe',
        ],
        'unicos' => [],
        'grupo' => 'Personal',
        'existente' => false,
    ],
    [
        'tabla' => 'tipo_documento_personal',
        'creacion' => 'CREATE TABLE "tipo_documento_personal" (
 "cod_tdp" VARCHAR(20) PRIMARY KEY,
 "cla_tdp" VARCHAR(60) NOT NULL UNIQUE,
 "nom_tdp" VARCHAR(150) NOT NULL,
 "des_tdp" TEXT,
 "ven_tdp" BOOLEAN NOT NULL DEFAULT FALSE,
 "est_tdp" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cla_tdp' => '"cla_tdp" VARCHAR(60) NULL',
            'nom_tdp' => '"nom_tdp" VARCHAR(150) NULL',
            'des_tdp' => '"des_tdp" TEXT NULL',
            'ven_tdp' => '"ven_tdp" BOOLEAN NULL',
            'est_tdp' => '"est_tdp" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_tdp',
        'columnas' => [
            'cod_tdp' => 'VARCHAR(20) PRIMARY KEY',
            'cla_tdp' => 'VARCHAR(60) NOT NULL UNIQUE',
            'nom_tdp' => 'VARCHAR(150) NOT NULL',
            'des_tdp' => 'TEXT',
            'ven_tdp' => 'BOOLEAN NOT NULL DEFAULT FALSE',
            'est_tdp' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_tdp IN (\'ACTIVO\',\'INACTIVO\')',
        ],
        'unicos' => [
            [
                'cla_tdp',
            ],
        ],
        'grupo' => 'Personal',
        'existente' => false,
    ],
    [
        'tabla' => 'requisito_documento_cargo',
        'creacion' => 'CREATE TABLE "requisito_documento_cargo" (
 "cod_rdc" VARCHAR(20) PRIMARY KEY,
 "cod_cai" VARCHAR(20) NOT NULL,
 "cod_tdp" VARCHAR(20) NOT NULL,
 "obl_rdc" BOOLEAN NOT NULL DEFAULT TRUE,
 "vig_rdc" BOOLEAN NOT NULL DEFAULT FALSE,
 "dia_rdc" INTEGER,
 "est_rdc" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_cai' => '"cod_cai" VARCHAR(20) NULL',
            'cod_tdp' => '"cod_tdp" VARCHAR(20) NULL',
            'obl_rdc' => '"obl_rdc" BOOLEAN NULL',
            'vig_rdc' => '"vig_rdc" BOOLEAN NULL',
            'dia_rdc' => '"dia_rdc" INTEGER NULL',
            'est_rdc' => '"est_rdc" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_rdc',
        'columnas' => [
            'cod_rdc' => 'VARCHAR(20) PRIMARY KEY',
            'cod_cai' => 'VARCHAR(20) NOT NULL',
            'cod_tdp' => 'VARCHAR(20) NOT NULL',
            'obl_rdc' => 'BOOLEAN NOT NULL DEFAULT TRUE',
            'vig_rdc' => 'BOOLEAN NOT NULL DEFAULT FALSE',
            'dia_rdc' => 'INTEGER',
            'est_rdc' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_rdc IN (\'ACTIVO\',\'INACTIVO\')',
            'dia_rdc IS NULL OR dia_rdc>0',
        ],
        'unicos' => [
            [
                'cod_cai',
                'cod_tdp',
            ],
        ],
        'grupo' => 'Personal',
        'existente' => false,
    ],
    [
        'tabla' => 'documento_personal',
        'creacion' => 'CREATE TABLE "documento_personal" (
 "cod_dpe" VARCHAR(20) PRIMARY KEY,
 "cod_pin" VARCHAR(20) NOT NULL,
 "cod_tdp" VARCHAR(20) NOT NULL,
 "cod_vpe" VARCHAR(20),
 "num_dpe" VARCHAR(120),
 "emi_dpe" DATE,
 "ven_dpe" DATE,
 "rut_dpe" TEXT NOT NULL,
 "mim_dpe" VARCHAR(150),
 "tam_dpe" BIGINT,
 "has_dpe" hash_sha256,
 "est_dpe" VARCHAR(20) NOT NULL DEFAULT \'PENDIENTE\',
 "val_dpe" VARCHAR(20),
 "fec_dpe" TIMESTAMPTZ,
 "obs_dpe" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_pin' => '"cod_pin" VARCHAR(20) NULL',
            'cod_tdp' => '"cod_tdp" VARCHAR(20) NULL',
            'cod_vpe' => '"cod_vpe" VARCHAR(20) NULL',
            'num_dpe' => '"num_dpe" VARCHAR(120) NULL',
            'emi_dpe' => '"emi_dpe" DATE NULL',
            'ven_dpe' => '"ven_dpe" DATE NULL',
            'rut_dpe' => '"rut_dpe" TEXT NULL',
            'mim_dpe' => '"mim_dpe" VARCHAR(150) NULL',
            'tam_dpe' => '"tam_dpe" BIGINT NULL',
            'has_dpe' => '"has_dpe" hash_sha256 NULL',
            'est_dpe' => '"est_dpe" VARCHAR(20) NULL',
            'val_dpe' => '"val_dpe" VARCHAR(20) NULL',
            'fec_dpe' => '"fec_dpe" TIMESTAMPTZ NULL',
            'obs_dpe' => '"obs_dpe" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_dpe',
        'columnas' => [
            'cod_dpe' => 'VARCHAR(20) PRIMARY KEY',
            'cod_pin' => 'VARCHAR(20) NOT NULL',
            'cod_tdp' => 'VARCHAR(20) NOT NULL',
            'cod_vpe' => 'VARCHAR(20)',
            'num_dpe' => 'VARCHAR(120)',
            'emi_dpe' => 'DATE',
            'ven_dpe' => 'DATE',
            'rut_dpe' => 'TEXT NOT NULL',
            'mim_dpe' => 'VARCHAR(150)',
            'tam_dpe' => 'BIGINT',
            'has_dpe' => 'hash_sha256',
            'est_dpe' => 'VARCHAR(20) NOT NULL DEFAULT \'PENDIENTE\'',
            'val_dpe' => 'VARCHAR(20)',
            'fec_dpe' => 'TIMESTAMPTZ',
            'obs_dpe' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'tam_dpe IS NULL OR tam_dpe>=0',
            'est_dpe IN (\'PENDIENTE\',\'VALIDADO\',\'RECHAZADO\',\'VENCIDO\',\'ANULADO\')',
            'ven_dpe IS NULL OR emi_dpe IS NULL OR ven_dpe>=emi_dpe',
        ],
        'unicos' => [],
        'grupo' => 'Personal',
        'existente' => false,
    ],
    [
        'tabla' => 'docente',
        'creacion' => 'CREATE TABLE "docente" (
 "cod_doc" VARCHAR(20) PRIMARY KEY,
 "cod_pin" VARCHAR(20) NOT NULL UNIQUE,
 "est_doc" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_pin' => '"cod_pin" VARCHAR(20) NULL',
            'est_doc' => '"est_doc" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_doc',
        'columnas' => [
            'cod_doc' => 'VARCHAR(20) PRIMARY KEY',
            'cod_pin' => 'VARCHAR(20) NOT NULL UNIQUE',
            'est_doc' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_doc IN (\'ACTIVO\',\'INACTIVO\',\'SUSPENDIDO\',\'RETIRADO\')',
        ],
        'unicos' => [
            [
                'cod_pin',
            ],
        ],
        'grupo' => 'Personal',
        'existente' => true,
    ],
    [
        'tabla' => 'formacion_docente',
        'creacion' => 'CREATE TABLE "formacion_docente" (
 "cod_fdo" VARCHAR(20) PRIMARY KEY,
 "cod_doc" VARCHAR(20) NOT NULL,
 "niv_fdo" VARCHAR(100) NOT NULL,
 "tit_fdo" VARCHAR(255) NOT NULL,
 "ins_fdo" VARCHAR(255) NOT NULL,
 "pai_fdo" codigo_pais_iso2,
 "fec_fdo" DATE,
 "cod_dpe" VARCHAR(20),
 "est_fdo" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "obs_fdo" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_doc' => '"cod_doc" VARCHAR(20) NULL',
            'niv_fdo' => '"niv_fdo" VARCHAR(100) NULL',
            'tit_fdo' => '"tit_fdo" VARCHAR(255) NULL',
            'ins_fdo' => '"ins_fdo" VARCHAR(255) NULL',
            'pai_fdo' => '"pai_fdo" codigo_pais_iso2 NULL',
            'fec_fdo' => '"fec_fdo" DATE NULL',
            'cod_dpe' => '"cod_dpe" VARCHAR(20) NULL',
            'est_fdo' => '"est_fdo" VARCHAR(20) NULL',
            'obs_fdo' => '"obs_fdo" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_fdo',
        'columnas' => [
            'cod_fdo' => 'VARCHAR(20) PRIMARY KEY',
            'cod_doc' => 'VARCHAR(20) NOT NULL',
            'niv_fdo' => 'VARCHAR(100) NOT NULL',
            'tit_fdo' => 'VARCHAR(255) NOT NULL',
            'ins_fdo' => 'VARCHAR(255) NOT NULL',
            'pai_fdo' => 'codigo_pais_iso2',
            'fec_fdo' => 'DATE',
            'cod_dpe' => 'VARCHAR(20)',
            'est_fdo' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'obs_fdo' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_fdo IN (\'ACTIVO\',\'INACTIVO\',\'ANULADO\')',
        ],
        'unicos' => [],
        'grupo' => 'Personal',
        'existente' => false,
    ],
    [
        'tabla' => 'experiencia_docente',
        'creacion' => 'CREATE TABLE "experiencia_docente" (
 "cod_edo" VARCHAR(20) PRIMARY KEY,
 "cod_doc" VARCHAR(20) NOT NULL,
 "ins_edo" VARCHAR(255) NOT NULL,
 "car_edo" VARCHAR(180) NOT NULL,
 "fii_edo" DATE NOT NULL,
 "ffi_edo" DATE,
 "cod_dpe" VARCHAR(20),
 "est_edo" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "obs_edo" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_doc' => '"cod_doc" VARCHAR(20) NULL',
            'ins_edo' => '"ins_edo" VARCHAR(255) NULL',
            'car_edo' => '"car_edo" VARCHAR(180) NULL',
            'fii_edo' => '"fii_edo" DATE NULL',
            'ffi_edo' => '"ffi_edo" DATE NULL',
            'cod_dpe' => '"cod_dpe" VARCHAR(20) NULL',
            'est_edo' => '"est_edo" VARCHAR(20) NULL',
            'obs_edo' => '"obs_edo" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_edo',
        'columnas' => [
            'cod_edo' => 'VARCHAR(20) PRIMARY KEY',
            'cod_doc' => 'VARCHAR(20) NOT NULL',
            'ins_edo' => 'VARCHAR(255) NOT NULL',
            'car_edo' => 'VARCHAR(180) NOT NULL',
            'fii_edo' => 'DATE NOT NULL',
            'ffi_edo' => 'DATE',
            'cod_dpe' => 'VARCHAR(20)',
            'est_edo' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'obs_edo' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_edo IN (\'ACTIVO\',\'INACTIVO\',\'ANULADO\')',
            'ffi_edo IS NULL OR ffi_edo>=fii_edo',
        ],
        'unicos' => [],
        'grupo' => 'Personal',
        'existente' => false,
    ],
    [
        'tabla' => 'capacitacion_docente',
        'creacion' => 'CREATE TABLE "capacitacion_docente" (
 "cod_cdo" VARCHAR(20) PRIMARY KEY,
 "cod_doc" VARCHAR(20) NOT NULL,
 "nom_cdo" VARCHAR(255) NOT NULL,
 "ins_cdo" VARCHAR(255) NOT NULL,
 "hor_cdo" NUMERIC(8,2),
 "fec_cdo" DATE,
 "cod_dpe" VARCHAR(20),
 "est_cdo" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "obs_cdo" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_doc' => '"cod_doc" VARCHAR(20) NULL',
            'nom_cdo' => '"nom_cdo" VARCHAR(255) NULL',
            'ins_cdo' => '"ins_cdo" VARCHAR(255) NULL',
            'hor_cdo' => '"hor_cdo" NUMERIC(8,2) NULL',
            'fec_cdo' => '"fec_cdo" DATE NULL',
            'cod_dpe' => '"cod_dpe" VARCHAR(20) NULL',
            'est_cdo' => '"est_cdo" VARCHAR(20) NULL',
            'obs_cdo' => '"obs_cdo" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_cdo',
        'columnas' => [
            'cod_cdo' => 'VARCHAR(20) PRIMARY KEY',
            'cod_doc' => 'VARCHAR(20) NOT NULL',
            'nom_cdo' => 'VARCHAR(255) NOT NULL',
            'ins_cdo' => 'VARCHAR(255) NOT NULL',
            'hor_cdo' => 'NUMERIC(8,2)',
            'fec_cdo' => 'DATE',
            'cod_dpe' => 'VARCHAR(20)',
            'est_cdo' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'obs_cdo' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'hor_cdo IS NULL OR hor_cdo>=0',
            'est_cdo IN (\'ACTIVO\',\'INACTIVO\',\'ANULADO\')',
        ],
        'unicos' => [],
        'grupo' => 'Personal',
        'existente' => false,
    ],
];
