<?php

declare(strict_types=1);

/** Contrato PostgreSQL del módulo Academico. */
return [[
    'tabla' => 'persona',
    'sql' => 'CREATE TABLE "persona" (
 "cod_per" character varying(20) NOT NULL,
 "nom_per" character varying(100) NOT NULL,
 "ape_pat_per" character varying(100) NOT NULL,
 "ape_mat_per" character varying(100),
 "ci_per" character varying(20) NOT NULL,
 "com_per" character varying(20),
 "exp_per" character varying(20),
 "fec_nac_per" date,
 "gen_per" character varying(20),
 "tel_per" character varying(20),
 "ema_per" character varying(150),
 "dir_per" character varying(255),
 "fot_per" character varying(255),
 "est_per" boolean NOT NULL DEFAULT true,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 CONSTRAINT "persona_ci_per_unique" UNIQUE ("ci_per"),
 CONSTRAINT "persona_ema_per_unique" UNIQUE ("ema_per"),
 PRIMARY KEY ("cod_per")
)',
    'indices' => [],
    'checks' => [],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'personal_institucional',
    'sql' => 'CREATE TABLE "personal_institucional" (
 "cod_pin" VARCHAR(20) PRIMARY KEY,
 "cod_per" VARCHAR(20) NOT NULL UNIQUE,
 "est_pin" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
    'indices' => ['CREATE UNIQUE INDEX can_personal_institucional_uq_0 ON "personal_institucional" ("cod_per")'],
    'checks' => [['can_personal_institucional_ck_0', 'CHECK (est_pin IN (\'ACTIVO\',\'INACTIVO\',\'RETIRADO\',\'ANULADO\'))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'cargo_institucional',
    'sql' => 'CREATE TABLE "cargo_institucional" (
 "cod_cai" character varying(20) NOT NULL,
 "cla_cai" character varying(50) NOT NULL,
 "nom_cai" character varying(120) NOT NULL,
 "des_cai" text,
 "est_cai" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "cargo_institucional_cla_cai_key" UNIQUE ("cla_cai"),
 PRIMARY KEY ("cod_cai")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_a8a8f434ec7b51e6', 'CHECK (((est_cai)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'INACTIVO\'::character varying])::text[])))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'vinculo_personal',
    'sql' => 'CREATE TABLE "vinculo_personal" (
 "cod_vpe" character varying(20) NOT NULL,
 "cod_pin" character varying(20) NOT NULL,
 "cod_cai" character varying(20) NOT NULL,
 "tip_vpe" character varying(80) NOT NULL,
 "fii_vpe" date NOT NULL,
 "ffi_vpe" date,
 "ref_vpe" character varying(255),
 "est_vpe" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "obs_vpe" text,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_vpe")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_a152cc59200ae2d7', 'CHECK (((ffi_vpe IS NULL) OR (ffi_vpe >= fii_vpe)))'], ['can_ofi_ck_d5ef11e72f2c6c77', 'CHECK (((est_vpe)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'FINALIZADO\'::character varying, \'SUSPENDIDO\'::character varying, \'ANULADO\'::character varying])::text[])))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'tipo_documento_personal',
    'sql' => 'CREATE TABLE "tipo_documento_personal" (
 "cod_tdp" character varying(20) NOT NULL,
 "cla_tdp" character varying(60) NOT NULL,
 "nom_tdp" character varying(150) NOT NULL,
 "des_tdp" text,
 "ven_tdp" boolean NOT NULL DEFAULT false,
 "est_tdp" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "tipo_documento_personal_cla_tdp_key" UNIQUE ("cla_tdp"),
 PRIMARY KEY ("cod_tdp")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_9120d4ccba60ba87', 'CHECK (((est_tdp)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'INACTIVO\'::character varying])::text[])))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'requisito_documento_cargo',
    'sql' => 'CREATE TABLE "requisito_documento_cargo" (
 "cod_rdc" character varying(20) NOT NULL,
 "cod_cai" character varying(20) NOT NULL,
 "cod_tdp" character varying(20) NOT NULL,
 "obl_rdc" boolean NOT NULL DEFAULT true,
 "vig_rdc" boolean NOT NULL DEFAULT false,
 "dia_rdc" integer,
 "est_rdc" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "ofi_uq_9d35f7f3657de3e3" UNIQUE ("cod_cai", "cod_tdp"),
 PRIMARY KEY ("cod_rdc")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_263951dd0f1430b4', 'CHECK (((dia_rdc IS NULL) OR (dia_rdc > 0)))'], ['can_ofi_ck_556251b1291ca76a', 'CHECK (((est_rdc)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'INACTIVO\'::character varying])::text[])))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'documento_personal',
    'sql' => 'CREATE TABLE "documento_personal" (
 "cod_dpe" character varying(20) NOT NULL,
 "cod_pin" character varying(20) NOT NULL,
 "cod_tdp" character varying(20) NOT NULL,
 "cod_vpe" character varying(20),
 "num_dpe" character varying(120),
 "emi_dpe" date,
 "ven_dpe" date,
 "rut_dpe" text NOT NULL,
 "mim_dpe" character varying(150),
 "tam_dpe" bigint,
 "has_dpe" hash_sha256,
 "est_dpe" character varying(20) NOT NULL DEFAULT \'PENDIENTE\'::character varying,
 "val_dpe" character varying(20),
 "fec_dpe" timestamp with time zone,
 "obs_dpe" text,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_dpe")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_28322a21238b4324', 'CHECK (((tam_dpe IS NULL) OR (tam_dpe >= 0)))'], ['can_ofi_ck_9a63570486c7c611', 'CHECK (((est_dpe)::text = ANY ((ARRAY[\'PENDIENTE\'::character varying, \'VALIDADO\'::character varying, \'RECHAZADO\'::character varying, \'VENCIDO\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_ofi_ck_d892d0dd7be6e64d', 'CHECK (((ven_dpe IS NULL) OR (emi_dpe IS NULL) OR (ven_dpe >= emi_dpe)))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'docente',
    'sql' => 'CREATE TABLE "docente" (
 "cod_doc" character varying(20) NOT NULL,
 "cod_pin" character varying(20) NOT NULL,
 "esp_doc" character varying(150),
 "num_mod_doc" integer NOT NULL DEFAULT 0,
 "est_doc" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 PRIMARY KEY ("cod_doc"),
 CONSTRAINT "ofi_uq_c2a1ab78c8d3dcfc" UNIQUE ("cod_pin")
)',
    'indices' => [],
    'checks' => [],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'formacion_docente',
    'sql' => 'CREATE TABLE "formacion_docente" (
 "cod_fdo" character varying(20) NOT NULL,
 "cod_doc" character varying(20) NOT NULL,
 "niv_fdo" character varying(100) NOT NULL,
 "tit_fdo" character varying(255) NOT NULL,
 "ins_fdo" character varying(255) NOT NULL,
 "pai_fdo" codigo_pais_iso2,
 "fec_fdo" date,
 "cod_dpe" character varying(20),
 "est_fdo" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "obs_fdo" text,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_fdo")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_a93ebdbe6bc7e870', 'CHECK (((est_fdo)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'INACTIVO\'::character varying, \'ANULADO\'::character varying])::text[])))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'experiencia_docente',
    'sql' => 'CREATE TABLE "experiencia_docente" (
 "cod_edo" character varying(20) NOT NULL,
 "cod_doc" character varying(20) NOT NULL,
 "ins_edo" character varying(255) NOT NULL,
 "car_edo" character varying(180) NOT NULL,
 "fii_edo" date NOT NULL,
 "ffi_edo" date,
 "cod_dpe" character varying(20),
 "est_edo" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "obs_edo" text,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_edo")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_5fd928da74213b70', 'CHECK (((ffi_edo IS NULL) OR (ffi_edo >= fii_edo)))'], ['can_ofi_ck_856c632deda09ced', 'CHECK (((est_edo)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'INACTIVO\'::character varying, \'ANULADO\'::character varying])::text[])))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'capacitacion_docente',
    'sql' => 'CREATE TABLE "capacitacion_docente" (
 "cod_cdo" character varying(20) NOT NULL,
 "cod_doc" character varying(20) NOT NULL,
 "nom_cdo" character varying(255) NOT NULL,
 "ins_cdo" character varying(255) NOT NULL,
 "hor_cdo" numeric(8,2),
 "fec_cdo" date,
 "cod_dpe" character varying(20),
 "est_cdo" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "obs_cdo" text,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_cdo")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_d903aa6c7920e2bd', 'CHECK (((est_cdo)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'INACTIVO\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_ofi_ck_fc3d148d9015f65e', 'CHECK (((hor_cdo IS NULL) OR (hor_cdo >= (0)::numeric)))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'tipo_vinculacion_estudiante',
    'sql' => 'CREATE TABLE "tipo_vinculacion_estudiante" (
 "cod_tve" character varying(20) NOT NULL,
 "nom_tve" character varying(100) NOT NULL,
 "des_tve" character varying(255),
 "est_tve" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 CONSTRAINT "ofi_uq_f31f9860c6d2a76b" UNIQUE ("nom_tve"),
 PRIMARY KEY ("cod_tve")
)',
    'indices' => [],
    'checks' => [],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'estudiante',
    'sql' => 'CREATE TABLE "estudiante" (
 "cod_est" character varying(20) NOT NULL,
 "rud_est" character varying(20) NOT NULL,
 "cod_per" character varying(20) NOT NULL,
 "cod_tve" character varying(20) NOT NULL,
 "cod_ipe" character varying(20),
 "cod_esp" character varying(20),
 "est_est" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 PRIMARY KEY ("cod_est"),
 CONSTRAINT "estudiante_rud_est_unique" UNIQUE ("rud_est"),
 CONSTRAINT "ofi_uq_5eb85d6580c16790" UNIQUE ("cod_per")
)',
    'indices' => [],
    'checks' => [],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'estudiante_responsable',
    'sql' => 'CREATE TABLE "estudiante_responsable" (
 "cod_ere" character varying(20) NOT NULL,
 "cod_est" character varying(20) NOT NULL,
 "cod_per" character varying(20) NOT NULL,
 "par_ere" character varying(80) NOT NULL,
 "pri_ere" boolean NOT NULL DEFAULT false,
 "aut_ere" boolean NOT NULL DEFAULT true,
 "con_ere" boolean NOT NULL DEFAULT true,
 "fii_ere" date NOT NULL DEFAULT CURRENT_DATE,
 "ffi_ere" date,
 "est_ere" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "obs_ere" text,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_ere")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_bdadecc9e9a26574', 'CHECK (((ffi_ere IS NULL) OR (ffi_ere >= fii_ere)))'], ['can_ofi_ck_dd36e2d154fda804', 'CHECK (((est_ere)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'INACTIVO\'::character varying, \'ANULADO\'::character varying])::text[])))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'institucion_procedencia',
    'sql' => 'CREATE TABLE "institucion_procedencia" (
 "cod_ipe" character varying(20) NOT NULL,
 "nom_ipe" character varying(150) NOT NULL,
 "tip_ipe" character varying(50),
 "ciu_ipe" character varying(100),
 "est_ipe" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 "dep_ipe" character varying(120),
 "dir_ipe" text,
 "tel_ipe" telefono_e164,
 "web_ipe" url_http,
 PRIMARY KEY ("cod_ipe")
)',
    'indices' => [],
    'checks' => [],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'expediente_traslado',
    'sql' => 'CREATE TABLE "expediente_traslado" (
 "cod_ext" character varying(20) NOT NULL,
 "cod_est" character varying(20) NOT NULL,
 "cod_ipe" character varying(20),
 "tip_ext" character varying(40) NOT NULL,
 "ref_ext" character varying(255),
 "fec_ext" date,
 "est_ext" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "obs_ext" text,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_ext")
)',
    'indices' => ['CREATE INDEX "ofi_idx_6a36b82cfc2d13f3" ON "expediente_traslado" ("cod_est")'],
    'checks' => [['can_ofi_ck_bede7d9f63b1c173', 'CHECK (((est_ext)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'CERRADO\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_ofi_ck_fbd6ff081fba7a19', 'CHECK (((tip_ext)::text = ANY ((ARRAY[\'INGRESO\'::character varying, \'SALIDA\'::character varying])::text[])))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'documento_traslado',
    'sql' => 'CREATE TABLE "documento_traslado" (
 "cod_dtr" character varying(20) NOT NULL,
 "cod_ext" character varying(20) NOT NULL,
 "tip_dtr" character varying(120) NOT NULL,
 "nom_dtr" character varying(255) NOT NULL,
 "fec_dtr" date,
 "rut_dtr" text NOT NULL,
 "mim_dtr" character varying(150),
 "tam_dtr" bigint,
 "has_dtr" hash_sha256,
 "est_dtr" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "obs_dtr" text,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_dtr")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_2f80e24317363d25', 'CHECK (((tam_dtr IS NULL) OR (tam_dtr >= 0)))'], ['can_ofi_ck_5ad83ffcc7dac3ca', 'CHECK (((est_dtr)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'INACTIVO\'::character varying, \'ANULADO\'::character varying])::text[])))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'gestion_academica',
    'sql' => 'CREATE TABLE "gestion_academica" (
 "cod_gea" character varying(20) NOT NULL,
 "ani_gea" integer NOT NULL,
 "fii_gea" date,
 "ffi_gea" date,
 "est_gea" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 PRIMARY KEY ("cod_gea"),
 CONSTRAINT "ofi_uq_4a1b5902e34e03b8" UNIQUE ("ani_gea")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_42123100644f1794', 'CHECK (((ani_gea >= 2000) AND (ani_gea <= 2200)))'], ['can_ofi_ck_ab702d1968911562', 'CHECK ((ffi_gea >= fii_gea))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'periodo_evaluacion',
    'sql' => 'CREATE TABLE "periodo_evaluacion" (
 "cod_pev" VARCHAR(20) PRIMARY KEY,
 "nom_pev" VARCHAR(120) NOT NULL UNIQUE,
 "ord_pev" SMALLINT NOT NULL UNIQUE,
 "est_pev" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
    'indices' => ['CREATE UNIQUE INDEX can_periodo_evaluacion_uq_0 ON "periodo_evaluacion" ("nom_pev")', 'CREATE UNIQUE INDEX can_periodo_evaluacion_uq_1 ON "periodo_evaluacion" ("ord_pev")'],
    'checks' => [['can_periodo_evaluacion_ck_0', 'CHECK (ord_pev>0)'], ['can_periodo_evaluacion_ck_1', 'CHECK (est_pev IN (\'ACTIVO\',\'INACTIVO\'))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'configuracion_calendario_gestion',
    'sql' => 'CREATE TABLE "configuracion_calendario_gestion" (
 "cod_ccg" VARCHAR(20) PRIMARY KEY,
 "cod_gea" VARCHAR(20) NOT NULL,
 "cod_pev" VARCHAR(20) NOT NULL,
 "dias_req_ccg" INTEGER,
 "fii_tri_ccg" DATE NOT NULL,
 "ffi_tri_ccg" DATE NOT NULL,
 "cie_ccg" TIMESTAMPTZ,
 "est_ccg" VARCHAR(20) NOT NULL DEFAULT \'PLANIFICADO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
    'indices' => ['CREATE UNIQUE INDEX can_configuracion_calendario_gestion_uq_0 ON "configuracion_calendario_gestion" ("cod_gea", "cod_pev")'],
    'checks' => [['can_configuracion_calendario_gestion_ck_0', 'CHECK (dias_req_ccg IS NULL OR dias_req_ccg>0)'], ['can_configuracion_calendario_gestion_ck_1', 'CHECK (est_ccg IN (\'PLANIFICADO\',\'ACTIVO\',\'CERRADO\',\'ANULADO\'))'], ['can_configuracion_calendario_gestion_ck_2', 'CHECK (ffi_tri_ccg>=fii_tri_ccg)']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'curso',
    'sql' => 'CREATE TABLE "curso" (
 "cod_cur" character varying(20) NOT NULL,
 "nom_cur" character varying(100) NOT NULL,
 "niv_cur" character varying(50),
 "est_cur" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 "ord_cur" smallint,
 PRIMARY KEY ("cod_cur"),
 CONSTRAINT "ofi_uq_79dab6e53421b46d" UNIQUE ("nom_cur", "niv_cur")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_58a935c0e19432c1', 'CHECK (((ord_cur IS NULL) OR (ord_cur > 0)))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'paralelo',
    'sql' => 'CREATE TABLE "paralelo" (
 "cod_par" character varying(20) NOT NULL,
 "nom_par" character varying(50) NOT NULL,
 "est_par" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 CONSTRAINT "ofi_uq_8c73c0e93053137b" UNIQUE ("nom_par"),
 PRIMARY KEY ("cod_par")
)',
    'indices' => [],
    'checks' => [],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'turno',
    'sql' => 'CREATE TABLE "turno" (
 "cod_tur" character varying(20) NOT NULL,
 "nom_tur" character varying(50) NOT NULL,
 "hor_ini_tur" character varying(10),
 "hor_fin_tur" character varying(10),
 "est_tur" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 CONSTRAINT "ofi_uq_e3f10ddad0bbdc32" UNIQUE ("nom_tur"),
 PRIMARY KEY ("cod_tur")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_46fe8e671634c8b5', 'CHECK (((hor_ini_tur IS NULL) OR (hor_fin_tur IS NULL) OR ((hor_fin_tur)::text > (hor_ini_tur)::text)))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'grupo_academico',
    'sql' => 'CREATE TABLE "grupo_academico" (
 "cod_gac" character varying(20) NOT NULL,
 "cod_gea" character varying(20) NOT NULL,
 "cod_cur" character varying(20) NOT NULL,
 "cod_par" character varying(20) NOT NULL,
 "cod_tur" character varying(20) NOT NULL,
 "cap_gac" integer,
 "est_gac" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "obs_gac" text,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_gac"),
 CONSTRAINT "ofi_uq_897846a4f9eaa85a" UNIQUE ("cod_gea", "cod_cur", "cod_par", "cod_tur")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_23d36301fdef4a43', 'CHECK (((est_gac)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'INACTIVO\'::character varying, \'CERRADO\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_ofi_ck_8279a1aafa242c64', 'CHECK (((cap_gac IS NULL) OR (cap_gac > 0)))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'asignatura',
    'sql' => 'CREATE TABLE "asignatura" (
 "cod_asi" character varying(20) NOT NULL,
 "nom_asi" character varying(150) NOT NULL,
 "sig_asi" character varying(20),
 "hor_asi" integer,
 "est_asi" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 PRIMARY KEY ("cod_asi")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_f84c38b6f24be6f0', 'CHECK (((hor_asi IS NULL) OR (hor_asi >= 0)))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'especialidad_tecnica',
    'sql' => 'CREATE TABLE "especialidad_tecnica" (
 "cod_esp" character varying(20) NOT NULL,
 "nom_esp" character varying(150) NOT NULL,
 "des_esp" character varying(255),
 "est_esp" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 PRIMARY KEY ("cod_esp")
)',
    'indices' => [],
    'checks' => [],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'aula',
    'sql' => 'CREATE TABLE "aula" (
 "cod_aul" character varying(20) NOT NULL,
 "nom_aul" character varying(120) NOT NULL,
 "tip_aul" character varying(80),
 "ubi_aul" text,
 "cap_aul" integer,
 "est_aul" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "aula_nom_aul_key" UNIQUE ("nom_aul"),
 PRIMARY KEY ("cod_aul")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_ad05cef44521d82d', 'CHECK (((cap_aul IS NULL) OR (cap_aul > 0)))'], ['can_ofi_ck_ae0e2764d21a40b2', 'CHECK (((est_aul)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'INACTIVO\'::character varying, \'MANTENIMIENTO\'::character varying])::text[])))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'plan_asignatura',
    'sql' => 'CREATE TABLE "plan_asignatura" (
 "cod_pas" VARCHAR(20) PRIMARY KEY,
 "cod_asi" VARCHAR(20) NOT NULL,
 "cod_doc" VARCHAR(20) NOT NULL,
 "cod_gac" VARCHAR(20) NOT NULL,
 "hor_pas" NUMERIC(6,2),
 "fii_pas" DATE NOT NULL,
 "ffi_pas" DATE,
 "est_pas" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
    'indices' => [],
    'checks' => [['can_plan_asignatura_ck_0', 'CHECK (hor_pas IS NULL OR hor_pas>=0)'], ['can_plan_asignatura_ck_1', 'CHECK (est_pas IN (\'ACTIVO\',\'FINALIZADO\',\'SUSPENDIDO\',\'ANULADO\'))'], ['can_plan_asignatura_ck_2', 'CHECK (ffi_pas IS NULL OR ffi_pas>=fii_pas)']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'plan_especialidad',
    'sql' => 'CREATE TABLE "plan_especialidad" (
 "cod_pes" VARCHAR(20) PRIMARY KEY,
 "cod_esp" VARCHAR(20) NOT NULL,
 "cod_doc" VARCHAR(20) NOT NULL,
 "cod_gac" VARCHAR(20) NOT NULL,
 "hor_pes" NUMERIC(6,2),
 "fii_pes" DATE NOT NULL,
 "ffi_pes" DATE,
 "est_pes" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
    'indices' => [],
    'checks' => [['can_plan_especialidad_ck_0', 'CHECK (hor_pes IS NULL OR hor_pes>=0)'], ['can_plan_especialidad_ck_1', 'CHECK (est_pes IN (\'ACTIVO\',\'FINALIZADO\',\'SUSPENDIDO\',\'ANULADO\'))'], ['can_plan_especialidad_ck_2', 'CHECK (ffi_pes IS NULL OR ffi_pes>=fii_pes)']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'nota_traslado',
    'sql' => 'CREATE TABLE "nota_traslado" (
 "cod_ntr" character varying(20) NOT NULL,
 "cod_ext" character varying(20) NOT NULL,
 "ani_ntr" integer,
 "cur_ntr" character varying(120) NOT NULL,
 "mat_ntr" character varying(180) NOT NULL,
 "per_ntr" character varying(120),
 "ori_ntr" character varying(120) NOT NULL,
 "not_ntr" numeric(8,2),
 "esc_ntr" character varying(120),
 "cod_cur" character varying(20),
 "cod_asi" character varying(20),
 "cod_pev" character varying(20),
 "obs_ntr" text,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_ntr")
)',
    'indices' => ['CREATE INDEX "ofi_idx_d3f2d9c72879164e" ON "nota_traslado" ("cod_ext", "ani_ntr")'],
    'checks' => [['can_ofi_ck_1a52dc7e3b7c90f2', 'CHECK (((ani_ntr IS NULL) OR ((ani_ntr >= 1900) AND (ani_ntr <= 2200))))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'plantilla_horaria',
    'sql' => 'CREATE TABLE "plantilla_horaria" (
 "cod_pho" character varying(20) NOT NULL,
 "cod_tur" character varying(20) NOT NULL,
 "nom_pho" character varying(120) NOT NULL,
 "tip_pho" character varying(30) NOT NULL DEFAULT \'REGULAR\'::character varying,
 "des_pho" text,
 "fec_ini_pho" date,
 "fec_fin_pho" date,
 "dur_blo_pho" smallint,
 "ord_pho" smallint NOT NULL DEFAULT \'1\'::smallint,
 "act_pho" boolean NOT NULL DEFAULT false,
 "est_pho" boolean NOT NULL DEFAULT true,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 CONSTRAINT "ofi_uq_082c71a87d23708d" UNIQUE ("cod_tur", "nom_pho"),
 PRIMARY KEY ("cod_pho"),
 CONSTRAINT "plantilla_horaria_turno_tipo_nombre_unique" UNIQUE ("cod_tur", "tip_pho", "nom_pho")
)',
    'indices' => ['CREATE INDEX "plantilla_horaria_act_pho_index" ON "plantilla_horaria" ("act_pho")', 'CREATE INDEX "plantilla_horaria_cod_tur_index" ON "plantilla_horaria" ("cod_tur")', 'CREATE INDEX "plantilla_horaria_est_pho_index" ON "plantilla_horaria" ("est_pho")', 'CREATE INDEX "plantilla_horaria_fechas_index" ON "plantilla_horaria" ("fec_ini_pho", "fec_fin_pho")', 'CREATE INDEX "plantilla_horaria_tip_pho_index" ON "plantilla_horaria" ("tip_pho")'],
    'checks' => [['can_ofi_ck_0c7573d6f57f1197', 'CHECK (((dur_blo_pho IS NULL) OR (dur_blo_pho > 0)))'], ['can_ofi_ck_89f82a424e886264', 'CHECK (((ord_pho IS NULL) OR (ord_pho > 0)))'], ['can_ofi_ck_a419a916b1238f20', 'CHECK (((fec_fin_pho IS NULL) OR (fec_ini_pho IS NULL) OR (fec_fin_pho >= fec_ini_pho)))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'horario_bloque',
    'sql' => 'CREATE TABLE "horario_bloque" (
 "cod_hbl" character varying(20) NOT NULL,
 "cod_pho" character varying(20) NOT NULL,
 "num_hbl" smallint NOT NULL,
 "hor_ini_hbl" time(0) without time zone NOT NULL,
 "hor_fin_hbl" time(0) without time zone NOT NULL,
 "nom_hbl" character varying(80),
 "tip_hbl" character varying(30) NOT NULL DEFAULT \'CLASE\'::character varying,
 "obs_hbl" text,
 "est_hbl" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 CONSTRAINT "horario_bloque_pho_horas_unique" UNIQUE ("cod_pho", "hor_ini_hbl", "hor_fin_hbl"),
 CONSTRAINT "horario_bloque_pho_num_unique" UNIQUE ("cod_pho", "num_hbl"),
 PRIMARY KEY ("cod_hbl")
)',
    'indices' => ['CREATE INDEX "horario_bloque_cod_pho_index" ON "horario_bloque" ("cod_pho")', 'CREATE INDEX "horario_bloque_est_hbl_index" ON "horario_bloque" ("est_hbl")', 'CREATE INDEX "horario_bloque_num_hbl_index" ON "horario_bloque" ("num_hbl")', 'CREATE INDEX "horario_bloque_tip_hbl_index" ON "horario_bloque" ("tip_hbl")'],
    'checks' => [['can_horario_bloque_estado_check', 'CHECK (((est_hbl)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'INACTIVO\'::character varying])::text[])))'], ['can_horario_bloque_horas_check', 'CHECK ((hor_fin_hbl > hor_ini_hbl))'], ['can_horario_bloque_tipo_check', 'CHECK (((tip_hbl)::text = ANY ((ARRAY[\'CLASE\'::character varying, \'RECREO\'::character varying, \'DESCANSO\'::character varying, \'FORMACION\'::character varying, \'SALIDA\'::character varying, \'OTRO\'::character varying])::text[])))'], ['can_ofi_ck_102ca33904eeee23', 'CHECK ((num_hbl > 0))'], ['can_ofi_ck_6752dccef9d19dd4', 'CHECK ((hor_fin_hbl > hor_ini_hbl))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'horario',
    'sql' => 'CREATE TABLE "horario" (
 "cod_hor" VARCHAR(20) PRIMARY KEY,
 "cod_gac" VARCHAR(20) NOT NULL,
 "cod_pho" VARCHAR(20) NOT NULL,
 "fii_hor" DATE NOT NULL,
 "ffi_hor" DATE,
 "obs_hor" TEXT,
 "est_hor" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
    'indices' => [],
    'checks' => [['can_horario_ck_0', 'CHECK (est_hor IN (\'ACTIVO\',\'FINALIZADO\',\'ANULADO\'))'], ['can_horario_ck_1', 'CHECK (ffi_hor IS NULL OR ffi_hor>=fii_hor)']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'horario_detalle',
    'sql' => 'CREATE TABLE "horario_detalle" (
 "cod_hde" character varying(20) NOT NULL,
 "cod_hor" character varying(20) NOT NULL,
 "cod_hbl" character varying(20) NOT NULL,
 "dia_hde" character varying(15) NOT NULL,
 "cod_pas" character varying(20),
 "cod_pes" character varying(20),
 "aul_hde" character varying(100),
 "obs_hde" text,
 "est_hde" character varying(20) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 "cod_aul" character varying(20),
 CONSTRAINT "horario_detalle_hor_bloque_dia_unique" UNIQUE ("cod_hor", "cod_hbl", "dia_hde"),
 PRIMARY KEY ("cod_hde")
)',
    'indices' => ['CREATE INDEX "horario_detalle_cod_hbl_index" ON "horario_detalle" ("cod_hbl")', 'CREATE INDEX "horario_detalle_cod_hor_index" ON "horario_detalle" ("cod_hor")', 'CREATE INDEX "horario_detalle_cod_pas_index" ON "horario_detalle" ("cod_pas")', 'CREATE INDEX "horario_detalle_cod_pes_index" ON "horario_detalle" ("cod_pes")', 'CREATE INDEX "horario_detalle_dia_hde_index" ON "horario_detalle" ("dia_hde")', 'CREATE INDEX "horario_detalle_est_hde_index" ON "horario_detalle" ("est_hde")'],
    'checks' => [['can_horario_detalle_dia_check', 'CHECK (((dia_hde)::text = ANY ((ARRAY[\'LUNES\'::character varying, \'MARTES\'::character varying, \'MIERCOLES\'::character varying, \'JUEVES\'::character varying, \'VIERNES\'::character varying])::text[])))'], ['can_horario_detalle_estado_check', 'CHECK (((est_hde)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'INACTIVO\'::character varying, \'SUSPENDIDO\'::character varying])::text[])))'], ['can_horario_detalle_plan_check', 'CHECK ((((cod_pas IS NOT NULL) AND (cod_pes IS NULL)) OR ((cod_pas IS NULL) AND (cod_pes IS NOT NULL))))'], ['can_ofi_ck_2093aeb4051a9363', 'CHECK ((num_nonnulls(cod_pas, cod_pes) = 1))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'calendario_evento',
    'sql' => 'CREATE TABLE "calendario_evento" (
 "cod_cae" character varying(20) NOT NULL,
 "cod_gea" character varying(20) NOT NULL,
 "nom_cae" character varying(180) NOT NULL,
 "tip_cae" character varying(40) NOT NULL,
 "fii_cae" date NOT NULL,
 "ffi_cae" date NOT NULL,
 "hoi_cae" time(0) without time zone,
 "hof_cae" time(0) without time zone,
 "cod_tur" character varying(20),
 "cod_cur" character varying(20),
 "cod_par" character varying(20),
 "est_cae" character varying(20) NOT NULL DEFAULT \'PREALERTA\'::character varying,
 "efe_cae" character varying(30) NOT NULL DEFAULT \'INFORMATIVO\'::character varying,
 "cod_cae_ori" character varying(20),
 "mot_cae" text NOT NULL,
 "fue_cae" text,
 "created_by" character varying(20) NOT NULL,
 "created_at" timestamp(0) with time zone,
 "updated_at" timestamp(0) with time zone,
 "cod_hde" character varying(20),
 "com_cae" text,
 "ent_cae" character varying(255),
 "tip_doc_cae" character varying(120),
 "num_doc_cae" character varying(120),
 "fec_emi_cae" date,
 "fec_pub_cae" date,
 "url_cae" url_http,
 "niv_cae" character varying(50),
 "cer_cae" boolean,
 "cod_cae_ant" character varying(20),
 PRIMARY KEY ("cod_cae")
)',
    'indices' => ['CREATE INDEX "calendario_evento_cod_cur_index" ON "calendario_evento" ("cod_cur")', 'CREATE INDEX "calendario_evento_cod_gea_cod_cur_est_cae_index" ON "calendario_evento" ("cod_gea", "cod_cur", "est_cae")', 'CREATE INDEX "calendario_evento_cod_gea_fii_cae_ffi_cae_index" ON "calendario_evento" ("cod_gea", "fii_cae", "ffi_cae")', 'CREATE INDEX "calendario_evento_cod_par_index" ON "calendario_evento" ("cod_par")', 'CREATE INDEX "calendario_evento_cod_tur_index" ON "calendario_evento" ("cod_tur")', 'CREATE INDEX "calendario_evento_created_by_index" ON "calendario_evento" ("created_by")'],
    'checks' => [['can_calendar_event_content_check', 'CHECK (((ffi_cae >= fii_cae) AND (((hoi_cae IS NULL) AND (hof_cae IS NULL)) OR ((hoi_cae IS NOT NULL) AND (hof_cae IS NOT NULL) AND (hof_cae > hoi_cae))) AND ((cod_par IS NULL) OR (cod_cur IS NOT NULL)) AND ((cod_cae_ori IS NULL) OR ((cod_cae_ori)::text <> (cod_cae)::text)) AND ((est_cae)::text = ANY ((ARRAY[\'PREALERTA\'::character varying, \'CONFIRMADO\'::character varying, \'CANCELADO\'::character varying, \'FINALIZADO\'::character varying])::text[])) AND ((efe_cae)::text = ANY ((ARRAY[\'INFORMATIVO\'::character varying, \'SIN_CLASES\'::character varying, \'SUSPENSION_PARCIAL\'::character varying, \'INGRESO_DIFERIDO\'::character varying, \'SALIDA_ANTICIPADA\'::character varying, \'HORARIO_AJUSTADO\'::character varying, \'RECUPERACION\'::character varying, \'ACTIVIDAD_INSTITUCIONAL\'::character varying])::text[])) AND (NULLIF(TRIM(BOTH FROM mot_cae), \'\'::text) IS NOT NULL)))'], ['can_ofi_ck_b24f68032e1e411c', 'CHECK (((ffi_cae IS NULL) OR (ffi_cae >= fii_cae)))'], ['can_ofi_ck_3378156ac5f10ca8', 'CHECK (((hoi_cae IS NULL) OR (hof_cae IS NULL) OR (hof_cae > hoi_cae)))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'sesion_academica',
    'sql' => 'CREATE TABLE "sesion_academica" (
 "cod_ses" VARCHAR(20) PRIMARY KEY,
 "cod_hde" VARCHAR(20) NOT NULL,
 "fec_ses" DATE NOT NULL,
 "hor_pla_ses" NUMERIC(5,2),
 "hor_rea_ses" NUMERIC(5,2),
 "est_ses" VARCHAR(20) NOT NULL DEFAULT \'PROGRAMADA\',
 "cod_cae" VARCHAR(20),
 "cod_ses_ori" VARCHAR(20),
 "obs_ses" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
    'indices' => ['CREATE UNIQUE INDEX can_sesion_academica_uq_0 ON "sesion_academica" ("cod_hde", "fec_ses")'],
    'checks' => [['can_sesion_academica_ck_0', 'CHECK (hor_pla_ses IS NULL OR hor_pla_ses>=0)'], ['can_sesion_academica_ck_1', 'CHECK (hor_rea_ses IS NULL OR hor_rea_ses>=0)'], ['can_sesion_academica_ck_2', 'CHECK (est_ses IN (\'PROGRAMADA\',\'REALIZADA\',\'SUSPENDIDA\',\'REPROGRAMADA\',\'ANULADA\'))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'inscripcion_estudiante',
    'sql' => 'CREATE TABLE "inscripcion_estudiante" (
 "cod_ins" character varying(20) NOT NULL,
 "cod_est" character varying(20) NOT NULL,
 "cod_gea" character varying(20) NOT NULL,
 "cod_cur" character varying(20) NOT NULL,
 "cod_par" character varying(20) NOT NULL,
 "cod_tur" character varying(20) NOT NULL,
 "fei_ins" date NOT NULL,
 "tip_ins" character varying(30) NOT NULL DEFAULT \'REGULAR\'::character varying,
 "con_ins" character varying(30) NOT NULL DEFAULT \'NORMAL\'::character varying,
 "est_ins" character varying(30) NOT NULL DEFAULT \'PENDIENTE\'::character varying,
 "pro_ins" character varying(180),
 "obs_ins" text,
 "mot_obs_ins" text,
 "doc_com_ins" boolean NOT NULL DEFAULT false,
 "sob_aut_ins" boolean NOT NULL DEFAULT false,
 "sie_ins" boolean NOT NULL DEFAULT false,
 "fec_sie_ins" timestamp(0) without time zone,
 "cod_esp_tec" character varying(20),
 "est_esp_tec_ins" character varying(30) NOT NULL DEFAULT \'NO_APLICA\'::character varying,
 "obs_esp_tec_ins" text,
 "fec_con_ins" timestamp(0) without time zone,
 "fec_anu_ins" timestamp(0) without time zone,
 "mot_anu_ins" text,
 "fec_ret_ins" timestamp(0) without time zone,
 "mot_ret_ins" text,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 PRIMARY KEY ("cod_ins"),
 CONSTRAINT "uq_inscripcion_estudiante_por_gestion" UNIQUE ("cod_est", "cod_gea")
)',
    'indices' => ['CREATE INDEX "inscripcion_cod_cur_index" ON "inscripcion_estudiante" ("cod_cur")', 'CREATE INDEX "inscripcion_cod_esp_tec_index" ON "inscripcion_estudiante" ("cod_esp_tec")', 'CREATE INDEX "inscripcion_cod_est_index" ON "inscripcion_estudiante" ("cod_est")', 'CREATE INDEX "inscripcion_cod_gea_index" ON "inscripcion_estudiante" ("cod_gea")', 'CREATE INDEX "inscripcion_cod_par_index" ON "inscripcion_estudiante" ("cod_par")', 'CREATE INDEX "inscripcion_cod_tur_index" ON "inscripcion_estudiante" ("cod_tur")', 'CREATE INDEX "inscripcion_con_ins_index" ON "inscripcion_estudiante" ("con_ins")', 'CREATE INDEX "inscripcion_est_ins_index" ON "inscripcion_estudiante" ("est_ins")', 'CREATE INDEX "inscripcion_fei_ins_index" ON "inscripcion_estudiante" ("fei_ins")', 'CREATE INDEX "inscripcion_sie_ins_index" ON "inscripcion_estudiante" ("sie_ins")', 'CREATE INDEX "inscripcion_tip_ins_index" ON "inscripcion_estudiante" ("tip_ins")', 'CREATE INDEX "ofi_idx_dabcf6ee6a3f67ea" ON "inscripcion_estudiante" ("cod_gea", "est_ins")'],
    'checks' => [['can_inscripcion_tip_check', 'CHECK (((tip_ins)::text = ANY ((ARRAY[\'NUEVO\'::character varying, \'REGULAR\'::character varying, \'TRASLADO\'::character varying, \'EXTERIOR\'::character varying, \'VULNERABLE\'::character varying, \'EXCEPCIONAL\'::character varying, \'PREINSCRIPCION\'::character varying])::text[])))'], ['can_inscripcion_con_check', 'CHECK (((con_ins)::text = ANY ((ARRAY[\'NORMAL\'::character varying, \'OBSERVADA\'::character varying, \'CONDICIONAL\'::character varying, \'PROVISIONAL\'::character varying, \'SOBRECUPO\'::character varying, \'REZAGO_ESCOLAR\'::character varying])::text[])))'], ['can_inscripcion_est_check', 'CHECK (((est_ins)::text = ANY ((ARRAY[\'PENDIENTE\'::character varying, \'CONFIRMADA\'::character varying, \'ACTIVA\'::character varying, \'OBSERVADA\'::character varying, \'ANULADA\'::character varying, \'RETIRADA\'::character varying, \'ARCHIVADA\'::character varying])::text[])))'], ['can_inscripcion_esp_tec_est_check', 'CHECK (((est_esp_tec_ins)::text = ANY ((ARRAY[\'NO_APLICA\'::character varying, \'PENDIENTE\'::character varying, \'ASIGNADA\'::character varying, \'OBSERVADA\'::character varying, \'RETIRADA\'::character varying])::text[])))'], ['can_inscripcion_fechas_estado_check', 'CHECK ((((fec_anu_ins IS NULL) OR (fec_anu_ins >= fei_ins)) AND ((fec_ret_ins IS NULL) OR (fec_ret_ins >= fei_ins)) AND ((fec_con_ins IS NULL) OR (fec_con_ins >= fei_ins))))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'inscripcion_vigencia',
    'sql' => 'CREATE TABLE "inscripcion_vigencia" (
 "cod_ivg" VARCHAR(20) PRIMARY KEY,
 "cod_ins" VARCHAR(20) NOT NULL,
 "cod_gac" VARCHAR(20) NOT NULL,
 "cod_esp_tec" VARCHAR(20),
 "fii_ivg" DATE NOT NULL,
 "ffi_ivg" DATE,
 "tip_ivg" VARCHAR(80),
 "cie_ivg" VARCHAR(120),
 "mot_ivg" TEXT,
 "obs_ivg" TEXT,
 "est_ivg" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
    'indices' => [],
    'checks' => [['can_inscripcion_vigencia_ck_0', 'CHECK (est_ivg IN (\'ACTIVO\',\'CERRADO\',\'ANULADO\'))'], ['can_inscripcion_vigencia_ck_1', 'CHECK (ffi_ivg IS NULL OR ffi_ivg>=fii_ivg)']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'documento_inscripcion_estudiante',
    'sql' => 'CREATE TABLE "documento_inscripcion_estudiante" (
 "cod_die" character varying(20) NOT NULL,
 "cod_ins" character varying(20) NOT NULL,
 "nom_die" character varying(150) NOT NULL,
 "tip_die" character varying(40) NOT NULL DEFAULT \'GENERAL\'::character varying,
 "est_die" character varying(30) NOT NULL DEFAULT \'PENDIENTE\'::character varying,
 "obl_die" boolean NOT NULL DEFAULT false,
 "fec_lim_die" date,
 "fec_pre_die" date,
 "rut_die" character varying(255),
 "for_die" character varying(20),
 "tam_die" bigint,
 "has_die" character varying(128),
 "obs_die" text,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 PRIMARY KEY ("cod_die")
)',
    'indices' => ['CREATE INDEX "idx_documento_inscripcion_cod_ins" ON "documento_inscripcion_estudiante" ("cod_ins")', 'CREATE INDEX "idx_documento_inscripcion_est_die" ON "documento_inscripcion_estudiante" ("est_die")', 'CREATE INDEX "idx_documento_inscripcion_fec_lim_die" ON "documento_inscripcion_estudiante" ("fec_lim_die")', 'CREATE INDEX "idx_documento_inscripcion_fec_pre_die" ON "documento_inscripcion_estudiante" ("fec_pre_die")', 'CREATE INDEX "idx_documento_inscripcion_obl_die" ON "documento_inscripcion_estudiante" ("obl_die")', 'CREATE INDEX "idx_documento_inscripcion_tip_die" ON "documento_inscripcion_estudiante" ("tip_die")'],
    'checks' => [['can_documento_inscripcion_est_check', 'CHECK (((est_die)::text = ANY ((ARRAY[\'PENDIENTE\'::character varying, \'PRESENTADO\'::character varying, \'OBSERVADO\'::character varying, \'VALIDADO\'::character varying, \'NO_APLICA\'::character varying, \'VENCIDO\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_documento_inscripcion_fechas_check', 'CHECK (((fec_pre_die IS NULL) OR (fec_lim_die IS NULL) OR (fec_pre_die >= fec_lim_die) OR ((est_die)::text = ANY ((ARRAY[\'PRESENTADO\'::character varying, \'VALIDADO\'::character varying, \'OBSERVADO\'::character varying])::text[]))))'], ['can_documento_inscripcion_for_check', 'CHECK (((for_die IS NULL) OR ((for_die)::text = ANY ((ARRAY[\'PDF\'::character varying, \'JPG\'::character varying, \'JPEG\'::character varying, \'PNG\'::character varying, \'DOCX\'::character varying, \'XLSX\'::character varying, \'ZIP\'::character varying])::text[]))))'], ['can_documento_inscripcion_tip_check', 'CHECK (((tip_die)::text = ANY ((ARRAY[\'IDENTIDAD\'::character varying, \'RUDE\'::character varying, \'VACUNAS\'::character varying, \'ACADEMICO\'::character varying, \'TRASLADO\'::character varying, \'EXTERIOR\'::character varying, \'VULNERABILIDAD\'::character varying, \'ESPECIALIDAD\'::character varying, \'AUTORIZACION\'::character varying, \'GENERAL\'::character varying])::text[])))'], ['can_ofi_ck_8f873b592a42d728', 'CHECK (((tam_die IS NULL) OR (tam_die >= 0)))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'novedad_estudiante',
    'sql' => 'CREATE TABLE "novedad_estudiante" (
 "cod_nes" character varying(20) NOT NULL,
 "cod_ins" character varying(20) NOT NULL,
 "tip_nes" character varying(100) NOT NULL,
 "fii_nes" date NOT NULL,
 "ffi_nes" date,
 "est_nes" character varying(20) NOT NULL DEFAULT \'ACTIVA\'::character varying,
 "mot_nes" text NOT NULL,
 "obs_nes" text,
 "rut_res_nes" text,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY ("cod_nes")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_a32c873c124c067a', 'CHECK (((est_nes)::text = ANY ((ARRAY[\'ACTIVA\'::character varying, \'CERRADA\'::character varying, \'ANULADA\'::character varying])::text[])))'], ['can_ofi_ck_b478722915f730e3', 'CHECK (((ffi_nes IS NULL) OR (ffi_nes >= fii_nes)))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'seguimiento_academico',
    'sql' => 'CREATE TABLE "seguimiento_academico" (
 "cod_seg" VARCHAR(20) PRIMARY KEY,
 "cod_ins" VARCHAR(20) NOT NULL,
 "tip_seg" VARCHAR(100) NOT NULL,
 "ori_seg" VARCHAR(100),
 "mot_seg" TEXT NOT NULL,
 "niv_ape_seg" VARCHAR(60),
 "est_seg" VARCHAR(20) NOT NULL DEFAULT \'ABIERTO\',
 "vis_seg" VARCHAR(30),
 "cod_usu_res" VARCHAR(20),
 "fec_ape_seg" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "fec_pro_seg" TIMESTAMPTZ,
 "fec_cie_seg" TIMESTAMPTZ,
 "res_seg" TEXT,
 "pro_acc_seg" TEXT,
 "obs_seg" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
    'indices' => [],
    'checks' => [['can_seguimiento_academico_ck_0', 'CHECK (est_seg IN (\'ABIERTO\',\'EN_SEGUIMIENTO\',\'CERRADO\',\'ANULADO\'))'], ['can_seguimiento_academico_ck_1', 'CHECK ((fec_pro_seg IS NULL OR fec_pro_seg>=fec_ape_seg) AND (fec_cie_seg IS NULL OR fec_cie_seg>=fec_ape_seg))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'resultado_anual',
    'sql' => 'CREATE TABLE "resultado_anual" (
 "cod_ran" character varying(20) NOT NULL,
 "cod_ins" character varying(20) NOT NULL,
 "res_ran" character varying(20) NOT NULL,
 "fec_ran" date NOT NULL,
 "cod_usu" character varying(20) NOT NULL,
 "ref_ran" character varying(255),
 "obs_ran" text,
 "est_ran" character varying(20) NOT NULL DEFAULT \'VIGENTE\'::character varying,
 "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT "resultado_anual_cod_ins_key" UNIQUE ("cod_ins"),
 PRIMARY KEY ("cod_ran")
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_52b42cb425d464dc', 'CHECK (((est_ran)::text = ANY ((ARRAY[\'VIGENTE\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_ofi_ck_8aee48613c134a3d', 'CHECK (((res_ran)::text = ANY ((ARRAY[\'PROMOVIDO\'::character varying, \'RETENIDO\'::character varying, \'EGRESADO\'::character varying, \'RETIRADO\'::character varying, \'ANULADO\'::character varying])::text[])))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'estado_asistencia',
    'sql' => 'CREATE TABLE "estado_asistencia" (
 "cod_est_asi" character varying(20) NOT NULL,
 "nom_est_asi" character varying(80) NOT NULL,
 "abr_est_asi" character varying(10) NOT NULL,
 "des_est_asi" text,
 "color_est_asi" character varying(30),
 "valor_porcentual" numeric(5,2) NOT NULL DEFAULT \'0\'::numeric,
 "afecta_asistencia" boolean NOT NULL DEFAULT true,
 "requiere_observacion" boolean NOT NULL DEFAULT false,
 "est_est_asi" character varying(255) NOT NULL DEFAULT \'ACTIVO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 PRIMARY KEY ("cod_est_asi"),
 CONSTRAINT "uq_estado_asistencia_abreviatura" UNIQUE ("abr_est_asi"),
 CONSTRAINT "uq_estado_asistencia_nombre" UNIQUE ("nom_est_asi")
)',
    'indices' => ['CREATE INDEX "estado_asistencia_afecta_asistencia_index" ON "estado_asistencia" ("afecta_asistencia")', 'CREATE INDEX "estado_asistencia_est_est_asi_index" ON "estado_asistencia" ("est_est_asi")', 'CREATE INDEX "estado_asistencia_requiere_observacion_index" ON "estado_asistencia" ("requiere_observacion")'],
    'checks' => [['can_estado_asistencia_est_est_asi_check', 'CHECK (((est_est_asi)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'INACTIVO\'::character varying, \'ANULADO\'::character varying])::text[])))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'asistencia_clase',
    'sql' => 'CREATE TABLE "asistencia_clase" (
 "cod_asi_cla" character varying(20) NOT NULL,
 "cod_cla" character varying(20) NOT NULL,
 "cod_doc" character varying(20) NOT NULL,
 "cod_hbl" character varying(20),
 "cod_usu_reg" character varying(20) NOT NULL,
 "fec_asi_cla" date NOT NULL,
 "hor_ini_asi_cla" time(0) without time zone,
 "hor_fin_asi_cla" time(0) without time zone,
 "tip_asi_cla" character varying(255) NOT NULL DEFAULT \'CLASE\'::character varying,
 "tit_asi_cla" character varying(150),
 "obs_asi_cla" text,
 "ori_asi_cla" character varying(255) NOT NULL DEFAULT \'MANUAL\'::character varying,
 "est_asi_cla" character varying(255) NOT NULL DEFAULT \'BORRADOR\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 "cod_ses" character varying(20),
 PRIMARY KEY ("cod_asi_cla"),
 CONSTRAINT "ofi_uq_2bce8e0412d67734" UNIQUE ("cod_ses"),
 CONSTRAINT "uq_asistencia_clase_bloque_estado" UNIQUE ("cod_cla", "cod_hbl", "fec_asi_cla", "est_asi_cla")
)',
    'indices' => ['CREATE INDEX "asistencia_clase_cod_cla_est_asi_cla_index" ON "asistencia_clase" ("cod_cla", "est_asi_cla")', 'CREATE INDEX "asistencia_clase_cod_cla_fec_asi_cla_index" ON "asistencia_clase" ("cod_cla", "fec_asi_cla")', 'CREATE INDEX "asistencia_clase_cod_cla_index" ON "asistencia_clase" ("cod_cla")', 'CREATE INDEX "asistencia_clase_cod_doc_fec_asi_cla_index" ON "asistencia_clase" ("cod_doc", "fec_asi_cla")', 'CREATE INDEX "asistencia_clase_cod_doc_index" ON "asistencia_clase" ("cod_doc")', 'CREATE INDEX "asistencia_clase_cod_hbl_index" ON "asistencia_clase" ("cod_hbl")', 'CREATE INDEX "asistencia_clase_cod_usu_reg_index" ON "asistencia_clase" ("cod_usu_reg")', 'CREATE INDEX "asistencia_clase_est_asi_cla_index" ON "asistencia_clase" ("est_asi_cla")', 'CREATE INDEX "asistencia_clase_fec_asi_cla_index" ON "asistencia_clase" ("fec_asi_cla")', 'CREATE INDEX "asistencia_clase_ori_asi_cla_index" ON "asistencia_clase" ("ori_asi_cla")', 'CREATE INDEX "asistencia_clase_tip_asi_cla_index" ON "asistencia_clase" ("tip_asi_cla")'],
    'checks' => [['can_asistencia_clase_tip_asi_cla_check', 'CHECK (((tip_asi_cla)::text = ANY ((ARRAY[\'CLASE\'::character varying, \'LABORATORIO\'::character varying, \'PRACTICA\'::character varying, \'EVALUACION\'::character varying, \'ACTIVIDAD\'::character varying])::text[])))'], ['can_asistencia_clase_ori_asi_cla_check', 'CHECK (((ori_asi_cla)::text = ANY ((ARRAY[\'MANUAL\'::character varying, \'GENERADA\'::character varying, \'IMPORTADA\'::character varying])::text[])))'], ['can_asistencia_clase_est_asi_cla_check', 'CHECK (((est_asi_cla)::text = ANY ((ARRAY[\'BORRADOR\'::character varying, \'ABIERTA\'::character varying, \'CERRADA\'::character varying, \'ANULADA\'::character varying])::text[])))'], ['can_ofi_ck_51a6acce01b131ba', 'CHECK (((hor_ini_asi_cla IS NULL) OR (hor_fin_asi_cla IS NULL) OR (hor_fin_asi_cla >= hor_ini_asi_cla)))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'asistencia_estudiante',
    'sql' => 'CREATE TABLE "asistencia_estudiante" (
 "cod_asi_est" character varying(20) NOT NULL,
 "cod_asi_cla" character varying(20) NOT NULL,
 "cod_est" character varying(20) NOT NULL,
 "cod_est_asi" character varying(20) NOT NULL,
 "cod_usu_reg" character varying(20) NOT NULL,
 "min_retraso" smallint NOT NULL DEFAULT \'0\'::smallint,
 "obs_asi_est" text,
 "fec_reg_asi_est" timestamp(0) without time zone,
 "est_asi_est" character varying(255) NOT NULL DEFAULT \'REGISTRADO\'::character varying,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 "cod_nes" character varying(20),
 PRIMARY KEY ("cod_asi_est"),
 CONSTRAINT "uq_asistencia_estudiante_unico" UNIQUE ("cod_asi_cla", "cod_est")
)',
    'indices' => ['CREATE INDEX "asistencia_estudiante_cod_asi_cla_est_asi_est_index" ON "asistencia_estudiante" ("cod_asi_cla", "est_asi_est")', 'CREATE INDEX "asistencia_estudiante_cod_asi_cla_index" ON "asistencia_estudiante" ("cod_asi_cla")', 'CREATE INDEX "asistencia_estudiante_cod_est_asi_est_asi_est_index" ON "asistencia_estudiante" ("cod_est_asi", "est_asi_est")', 'CREATE INDEX "asistencia_estudiante_cod_est_asi_index" ON "asistencia_estudiante" ("cod_est_asi")', 'CREATE INDEX "asistencia_estudiante_cod_est_est_asi_est_index" ON "asistencia_estudiante" ("cod_est", "est_asi_est")', 'CREATE INDEX "asistencia_estudiante_cod_est_index" ON "asistencia_estudiante" ("cod_est")', 'CREATE INDEX "asistencia_estudiante_cod_usu_reg_index" ON "asistencia_estudiante" ("cod_usu_reg")', 'CREATE INDEX "asistencia_estudiante_est_asi_est_index" ON "asistencia_estudiante" ("est_asi_est")', 'CREATE INDEX "asistencia_estudiante_fec_reg_asi_est_index" ON "asistencia_estudiante" ("fec_reg_asi_est")', 'CREATE INDEX "ofi_idx_742e714140a8e149" ON "asistencia_estudiante" ("cod_est", "cod_asi_cla")'],
    'checks' => [['can_asistencia_estudiante_est_asi_est_check', 'CHECK (((est_asi_est)::text = ANY ((ARRAY[\'REGISTRADO\'::character varying, \'RECTIFICADO\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_ofi_ck_614573633fb4f36c', 'CHECK ((min_retraso >= 0))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'calificacion',
    'sql' => 'CREATE TABLE "calificacion" (
 "cod_cal" VARCHAR(20) PRIMARY KEY,
 "cod_ins" VARCHAR(20) NOT NULL,
 "cod_pas" VARCHAR(20),
 "cod_pes" VARCHAR(20),
 "cod_pev" VARCHAR(20) NOT NULL,
 "not_cal" NUMERIC(5,2) NOT NULL,
 "obs_cal" TEXT,
 "est_cal" VARCHAR(20) NOT NULL DEFAULT \'VIGENTE\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
    'indices' => [],
    'checks' => [['can_calificacion_ck_0', 'CHECK (est_cal IN (\'VIGENTE\',\'RECTIFICADA\',\'ANULADA\'))'], ['can_calificacion_ck_1', 'CHECK (num_nonnulls(cod_pas,cod_pes)=1)']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'bitacora',
    'sql' => 'CREATE TABLE "bitacora" (
 "cod_bit" character varying(20) NOT NULL,
 "cod_usu" character varying(20),
 "rol_bit" character varying(100),
 "acc_bit" character varying(150) NOT NULL,
 "mod_bit" character varying(150),
 "tab_bit" character varying(100) NOT NULL,
 "reg_bit" character varying(50),
 "nom_reg_bit" character varying(255),
 "des_bit" text,
 "niv_bit" character varying(30) NOT NULL DEFAULT \'INFO\'::character varying,
 "res_bit" character varying(30) NOT NULL DEFAULT \'EXITOSO\'::character varying,
 "ip_bit" character varying(45),
 "age_bit" text,
 "rut_bit" character varying(255),
 "met_bit" character varying(20),
 "val_ant_bit" json,
 "val_nue_bit" json,
 "err_bit" text,
 "fec_bit" timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "usr_bit" text,
 "tra_bit" bigint,
 "created_at" timestamp with time zone,
 PRIMARY KEY ("cod_bit")
)',
    'indices' => [],
    'checks' => [],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'reportes_generados',
    'sql' => 'CREATE TABLE "reportes_generados" (
 "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "codigo" character varying(40) NOT NULL,
 "tipo_reporte" character varying(60) NOT NULL,
 "formato" character varying(10) NOT NULL DEFAULT \'pdf\'::character varying,
 "nombre_archivo" character varying(220) NOT NULL,
 "ruta_archivo" character varying(500) NOT NULL,
 "tamano_bytes" bigint NOT NULL DEFAULT \'0\'::bigint,
 "hash_archivo" character varying(64),
 "generado_por" character varying(80),
 "estado" character varying(20) NOT NULL DEFAULT \'generado\'::character varying,
 "observacion" text,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 "cod_usu" character varying(20),
 CONSTRAINT "reportes_generados_codigo_unique" UNIQUE ("codigo"),
 PRIMARY KEY ("id")
)',
    'indices' => ['CREATE INDEX "reportes_generados_created_at_index" ON "reportes_generados" ("created_at")', 'CREATE INDEX "reportes_generados_formato_index" ON "reportes_generados" ("formato")', 'CREATE INDEX "reportes_generados_tipo_reporte_index" ON "reportes_generados" ("tipo_reporte")'],
    'checks' => [['can_ofi_ck_c2a873a708d273ae', 'CHECK (((tamano_bytes IS NULL) OR (tamano_bytes >= 0)))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'respaldo_gestion_academica',
    'sql' => 'CREATE TABLE "respaldo_gestion_academica" (
 "cod_rga" character varying(20) NOT NULL,
 "cod_gea" character varying(20) NOT NULL,
 "tip_rga" character varying(30) NOT NULL DEFAULT \'CIERRE\'::character varying,
 "for_rga" character varying(20) NOT NULL DEFAULT \'ZIP\'::character varying,
 "rut_rga" character varying(255),
 "tam_rga" bigint,
 "has_rga" character varying(128),
 "fec_rga" timestamp(0) without time zone,
 "est_rga" character varying(20) NOT NULL DEFAULT \'GENERADO\'::character varying,
 "obs_rga" text,
 "created_at" timestamp(0) without time zone,
 "updated_at" timestamp(0) without time zone,
 "cod_usu" character varying(20),
 PRIMARY KEY ("cod_rga")
)',
    'indices' => ['CREATE INDEX "ofi_idx_7f66fdf7ddb89a8f" ON "respaldo_gestion_academica" ("cod_gea", "fec_rga")', 'CREATE INDEX "respaldo_gestion_cod_gea_index" ON "respaldo_gestion_academica" ("cod_gea")', 'CREATE INDEX "respaldo_gestion_est_rga_index" ON "respaldo_gestion_academica" ("est_rga")', 'CREATE INDEX "respaldo_gestion_fec_rga_index" ON "respaldo_gestion_academica" ("fec_rga")', 'CREATE INDEX "respaldo_gestion_for_rga_index" ON "respaldo_gestion_academica" ("for_rga")', 'CREATE INDEX "respaldo_gestion_tip_rga_index" ON "respaldo_gestion_academica" ("tip_rga")'],
    'checks' => [['can_ofi_ck_f40f885377c64f75', 'CHECK (((tam_rga IS NULL) OR (tam_rga >= 0)))'], ['can_respaldo_gestion_est_check', 'CHECK (((est_rga)::text = ANY ((ARRAY[\'GENERADO\'::character varying, \'VALIDADO\'::character varying, \'OBSERVADO\'::character varying, \'ARCHIVADO\'::character varying, \'ANULADO\'::character varying])::text[])))'], ['can_respaldo_gestion_for_check', 'CHECK (((for_rga)::text = ANY ((ARRAY[\'ZIP\'::character varying, \'PDF\'::character varying, \'XLSX\'::character varying, \'JSON\'::character varying])::text[])))'], ['can_respaldo_gestion_tip_check', 'CHECK (((tip_rga)::text = ANY ((ARRAY[\'PRELIMINAR\'::character varying, \'CIERRE\'::character varying, \'AUDITORIA\'::character varying, \'RECUPERACION\'::character varying])::text[])))']],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'user_status_logs',
    'sql' => 'CREATE TABLE "user_status_logs" (
 "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "cod_usu" VARCHAR(20) NOT NULL,
 "ant_usl" VARCHAR(20),
 "nue_usl" VARCHAR(20) NOT NULL,
 "mot_usl" TEXT,
 "cod_usu_admin" VARCHAR(20),
 "fec_usl" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
    'indices' => [],
    'checks' => [],
    'grupo' => 'Academico',
    'unicos' => [],
], [
    'tabla' => 'regente_asignaciones',
    'sql' => 'CREATE TABLE regente_asignaciones (
 cod_ras varchar(20) PRIMARY KEY, cod_vpe varchar(20) NOT NULL,
 cod_gea varchar(20) NOT NULL, cod_cur varchar(20) NOT NULL,
 fii_ras date NOT NULL, ffi_ras date, est_ras varchar(20) NOT NULL DEFAULT \'ACTIVO\',
 obs_ras text, created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
)',
    'indices' => [],
    'checks' => [['can_ofi_ck_59963dd3940c6bd2', 'CHECK (((ffi_ras IS NULL) OR (ffi_ras >= fii_ras)))'], ['can_ofi_ck_c0b2fe5bf50d5570', 'CHECK (((est_ras)::text = ANY ((ARRAY[\'ACTIVO\'::character varying, \'FINALIZADO\'::character varying, \'ANULADO\'::character varying])::text[])))']],
    'grupo' => 'Academico',
    'unicos' => [],
]];
