<?php

declare(strict_types=1);

/** Contrato aditivo Institucional. Fuente: guía aprobada 2026-10-03; sin backfill ni retiro. */
return [
    [
        'tabla' => 'persona',
        'creacion' => 'CREATE TABLE "persona" (
 "cod_per" VARCHAR(20) PRIMARY KEY,
 "ci_per" VARCHAR(30),
 "com_per" VARCHAR(10),
 "exp_per" VARCHAR(20),
 "nom_per" VARCHAR(120) NOT NULL,
 "ape_pat_per" VARCHAR(120) NOT NULL,
 "ape_mat_per" VARCHAR(120),
 "fec_nac_per" DATE,
 "gen_per" VARCHAR(30),
 "tel_per" telefono_e164,
 "ema_per" CITEXT,
 "dir_per" TEXT,
 "fot_per" TEXT,
 "est_per" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'ci_per' => '"ci_per" VARCHAR(30) NULL',
            'com_per' => '"com_per" VARCHAR(10) NULL',
            'exp_per' => '"exp_per" VARCHAR(20) NULL',
            'nom_per' => '"nom_per" VARCHAR(120) NULL',
            'ape_pat_per' => '"ape_pat_per" VARCHAR(120) NULL',
            'ape_mat_per' => '"ape_mat_per" VARCHAR(120) NULL',
            'fec_nac_per' => '"fec_nac_per" DATE NULL',
            'gen_per' => '"gen_per" VARCHAR(30) NULL',
            'tel_per' => '"tel_per" telefono_e164 NULL',
            'ema_per' => '"ema_per" CITEXT NULL',
            'dir_per' => '"dir_per" TEXT NULL',
            'fot_per' => '"fot_per" TEXT NULL',
            'est_per' => '"est_per" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_per',
        'columnas' => [
            'cod_per' => 'VARCHAR(20) PRIMARY KEY',
            'ci_per' => 'VARCHAR(30)',
            'com_per' => 'VARCHAR(10)',
            'exp_per' => 'VARCHAR(20)',
            'nom_per' => 'VARCHAR(120) NOT NULL',
            'ape_pat_per' => 'VARCHAR(120) NOT NULL',
            'ape_mat_per' => 'VARCHAR(120)',
            'fec_nac_per' => 'DATE',
            'gen_per' => 'VARCHAR(30)',
            'tel_per' => 'telefono_e164',
            'ema_per' => 'CITEXT',
            'dir_per' => 'TEXT',
            'fot_per' => 'TEXT',
            'est_per' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            '(est_per IN (\'ACTIVO\',\'INACTIVO\',\'FALLECIDO\',\'ANULADO\')',
        ],
        'unicos' => [],
        'grupo' => 'Institucional',
        'existente' => true,
    ],
    [
        'tabla' => 'tipo_vinculacion_estudiante',
        'creacion' => 'CREATE TABLE "tipo_vinculacion_estudiante" (
 "cod_tve" VARCHAR(20) PRIMARY KEY,
 "nom_tve" VARCHAR(120) NOT NULL UNIQUE,
 "des_tve" TEXT,
 "est_tve" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'nom_tve' => '"nom_tve" VARCHAR(120) NULL',
            'des_tve' => '"des_tve" TEXT NULL',
            'est_tve' => '"est_tve" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_tve',
        'columnas' => [
            'cod_tve' => 'VARCHAR(20) PRIMARY KEY',
            'nom_tve' => 'VARCHAR(120) NOT NULL UNIQUE',
            'des_tve' => 'TEXT',
            'est_tve' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_tve IN (\'ACTIVO\',\'INACTIVO\')',
        ],
        'unicos' => [
            [
                'nom_tve',
            ],
        ],
        'grupo' => 'Institucional',
        'existente' => true,
    ],
    [
        'tabla' => 'estudiante',
        'creacion' => 'CREATE TABLE "estudiante" (
 "cod_est" VARCHAR(20) PRIMARY KEY,
 "rud_est" VARCHAR(50) NOT NULL UNIQUE,
 "cod_per" VARCHAR(20) NOT NULL UNIQUE,
 "cod_tve" VARCHAR(20) NOT NULL,
 "est_est" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'rud_est' => '"rud_est" VARCHAR(50) NULL',
            'cod_per' => '"cod_per" VARCHAR(20) NULL',
            'cod_tve' => '"cod_tve" VARCHAR(20) NULL',
            'est_est' => '"est_est" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_est',
        'columnas' => [
            'cod_est' => 'VARCHAR(20) PRIMARY KEY',
            'rud_est' => 'VARCHAR(50) NOT NULL UNIQUE',
            'cod_per' => 'VARCHAR(20) NOT NULL UNIQUE',
            'cod_tve' => 'VARCHAR(20) NOT NULL',
            'est_est' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_est IN (\'ACTIVO\',\'INACTIVO\',\'EGRESADO\',\'RETIRADO\',\'ANULADO\')',
        ],
        'unicos' => [
            [
                'rud_est',
            ],
            [
                'cod_per',
            ],
        ],
        'grupo' => 'Institucional',
        'existente' => true,
    ],
    [
        'tabla' => 'estudiante_responsable',
        'creacion' => 'CREATE TABLE "estudiante_responsable" (
 "cod_ere" VARCHAR(20) PRIMARY KEY,
 "cod_est" VARCHAR(20) NOT NULL,
 "cod_per" VARCHAR(20) NOT NULL,
 "par_ere" VARCHAR(80) NOT NULL,
 "pri_ere" BOOLEAN NOT NULL DEFAULT FALSE,
 "aut_ere" BOOLEAN NOT NULL DEFAULT TRUE,
 "con_ere" BOOLEAN NOT NULL DEFAULT TRUE,
 "fii_ere" DATE NOT NULL DEFAULT CURRENT_DATE,
 "ffi_ere" DATE,
 "est_ere" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "obs_ere" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_est' => '"cod_est" VARCHAR(20) NULL',
            'cod_per' => '"cod_per" VARCHAR(20) NULL',
            'par_ere' => '"par_ere" VARCHAR(80) NULL',
            'pri_ere' => '"pri_ere" BOOLEAN NULL',
            'aut_ere' => '"aut_ere" BOOLEAN NULL',
            'con_ere' => '"con_ere" BOOLEAN NULL',
            'fii_ere' => '"fii_ere" DATE NULL',
            'ffi_ere' => '"ffi_ere" DATE NULL',
            'est_ere' => '"est_ere" VARCHAR(20) NULL',
            'obs_ere' => '"obs_ere" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_ere',
        'columnas' => [
            'cod_ere' => 'VARCHAR(20) PRIMARY KEY',
            'cod_est' => 'VARCHAR(20) NOT NULL',
            'cod_per' => 'VARCHAR(20) NOT NULL',
            'par_ere' => 'VARCHAR(80) NOT NULL',
            'pri_ere' => 'BOOLEAN NOT NULL DEFAULT FALSE',
            'aut_ere' => 'BOOLEAN NOT NULL DEFAULT TRUE',
            'con_ere' => 'BOOLEAN NOT NULL DEFAULT TRUE',
            'fii_ere' => 'DATE NOT NULL DEFAULT CURRENT_DATE',
            'ffi_ere' => 'DATE',
            'est_ere' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'obs_ere' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_ere IN (\'ACTIVO\',\'INACTIVO\',\'ANULADO\')',
            'ffi_ere IS NULL OR ffi_ere>=fii_ere',
        ],
        'unicos' => [],
        'grupo' => 'Institucional',
        'existente' => false,
    ],
    [
        'tabla' => 'documento_inscripcion_estudiante',
        'creacion' => 'CREATE TABLE "documento_inscripcion_estudiante" (
 "cod_die" VARCHAR(20) PRIMARY KEY,
 "cod_ins" VARCHAR(20) NOT NULL,
 "tip_die" VARCHAR(120) NOT NULL,
 "nom_die" VARCHAR(255) NOT NULL,
 "obl_die" BOOLEAN NOT NULL DEFAULT FALSE,
 "est_die" VARCHAR(20) NOT NULL DEFAULT \'PENDIENTE\',
 "fec_lim_die" DATE,
 "fec_pre_die" TIMESTAMPTZ,
 "rut_die" TEXT,
 "for_die" VARCHAR(100),
 "tam_die" BIGINT,
 "has_die" hash_sha256,
 "obs_die" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_ins' => '"cod_ins" VARCHAR(20) NULL',
            'tip_die' => '"tip_die" VARCHAR(120) NULL',
            'nom_die' => '"nom_die" VARCHAR(255) NULL',
            'obl_die' => '"obl_die" BOOLEAN NULL',
            'est_die' => '"est_die" VARCHAR(20) NULL',
            'fec_lim_die' => '"fec_lim_die" DATE NULL',
            'fec_pre_die' => '"fec_pre_die" TIMESTAMPTZ NULL',
            'rut_die' => '"rut_die" TEXT NULL',
            'for_die' => '"for_die" VARCHAR(100) NULL',
            'tam_die' => '"tam_die" BIGINT NULL',
            'has_die' => '"has_die" hash_sha256 NULL',
            'obs_die' => '"obs_die" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_die',
        'columnas' => [
            'cod_die' => 'VARCHAR(20) PRIMARY KEY',
            'cod_ins' => 'VARCHAR(20) NOT NULL',
            'tip_die' => 'VARCHAR(120) NOT NULL',
            'nom_die' => 'VARCHAR(255) NOT NULL',
            'obl_die' => 'BOOLEAN NOT NULL DEFAULT FALSE',
            'est_die' => 'VARCHAR(20) NOT NULL DEFAULT \'PENDIENTE\'',
            'fec_lim_die' => 'DATE',
            'fec_pre_die' => 'TIMESTAMPTZ',
            'rut_die' => 'TEXT',
            'for_die' => 'VARCHAR(100)',
            'tam_die' => 'BIGINT',
            'has_die' => 'hash_sha256',
            'obs_die' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_die IN (\'PENDIENTE\',\'PRESENTADO\',\'VALIDADO\',\'OBSERVADO\',\'RECHAZADO\',\'ANULADO\')',
            'tam_die IS NULL OR tam_die>=0',
        ],
        'unicos' => [],
        'grupo' => 'Institucional',
        'existente' => true,
    ],
    [
        'tabla' => 'novedad_estudiante',
        'creacion' => 'CREATE TABLE "novedad_estudiante" (
 "cod_nes" VARCHAR(20) PRIMARY KEY,
 "cod_ins" VARCHAR(20) NOT NULL,
 "tip_nes" VARCHAR(100) NOT NULL,
 "fii_nes" DATE NOT NULL,
 "ffi_nes" DATE,
 "est_nes" VARCHAR(20) NOT NULL DEFAULT \'ACTIVA\',
 "mot_nes" TEXT NOT NULL,
 "obs_nes" TEXT,
 "rut_res_nes" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_ins' => '"cod_ins" VARCHAR(20) NULL',
            'tip_nes' => '"tip_nes" VARCHAR(100) NULL',
            'fii_nes' => '"fii_nes" DATE NULL',
            'ffi_nes' => '"ffi_nes" DATE NULL',
            'est_nes' => '"est_nes" VARCHAR(20) NULL',
            'mot_nes' => '"mot_nes" TEXT NULL',
            'obs_nes' => '"obs_nes" TEXT NULL',
            'rut_res_nes' => '"rut_res_nes" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_nes',
        'columnas' => [
            'cod_nes' => 'VARCHAR(20) PRIMARY KEY',
            'cod_ins' => 'VARCHAR(20) NOT NULL',
            'tip_nes' => 'VARCHAR(100) NOT NULL',
            'fii_nes' => 'DATE NOT NULL',
            'ffi_nes' => 'DATE',
            'est_nes' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVA\'',
            'mot_nes' => 'TEXT NOT NULL',
            'obs_nes' => 'TEXT',
            'rut_res_nes' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_nes IN (\'ACTIVA\',\'CERRADA\',\'ANULADA\')',
            'ffi_nes IS NULL OR ffi_nes>=fii_nes',
        ],
        'unicos' => [],
        'grupo' => 'Institucional',
        'existente' => true,
    ],
    [
        'tabla' => 'seguimiento_academico',
        'creacion' => 'CREATE TABLE "seguimiento_academico" (
 "cod_seg" VARCHAR(20) PRIMARY KEY,
 "cod_ins" VARCHAR(20) NOT NULL,
 "tip_seg" VARCHAR(100) NOT NULL,
 "ori_seg" VARCHAR(100),
 "mot_seg" TEXT NOT NULL,
 "niv_ape_seg" VARCHAR(60),
 "est_seg" VARCHAR(20) NOT NULL DEFAULT \'ABIERTO\',
 "vis_seg" VARCHAR(30),
 "cod_usu_res" VARCHAR(20),
 "fec_ape_seg" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "fec_pro_seg" TIMESTAMPTZ,
 "fec_cie_seg" TIMESTAMPTZ,
 "res_seg" TEXT,
 "pro_acc_seg" TEXT,
 "obs_seg" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_ins' => '"cod_ins" VARCHAR(20) NULL',
            'tip_seg' => '"tip_seg" VARCHAR(100) NULL',
            'ori_seg' => '"ori_seg" VARCHAR(100) NULL',
            'mot_seg' => '"mot_seg" TEXT NULL',
            'niv_ape_seg' => '"niv_ape_seg" VARCHAR(60) NULL',
            'est_seg' => '"est_seg" VARCHAR(20) NULL',
            'vis_seg' => '"vis_seg" VARCHAR(30) NULL',
            'cod_usu_res' => '"cod_usu_res" VARCHAR(20) NULL',
            'fec_ape_seg' => '"fec_ape_seg" TIMESTAMPTZ NULL',
            'fec_pro_seg' => '"fec_pro_seg" TIMESTAMPTZ NULL',
            'fec_cie_seg' => '"fec_cie_seg" TIMESTAMPTZ NULL',
            'res_seg' => '"res_seg" TEXT NULL',
            'pro_acc_seg' => '"pro_acc_seg" TEXT NULL',
            'obs_seg' => '"obs_seg" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_seg',
        'columnas' => [
            'cod_seg' => 'VARCHAR(20) PRIMARY KEY',
            'cod_ins' => 'VARCHAR(20) NOT NULL',
            'tip_seg' => 'VARCHAR(100) NOT NULL',
            'ori_seg' => 'VARCHAR(100)',
            'mot_seg' => 'TEXT NOT NULL',
            'niv_ape_seg' => 'VARCHAR(60)',
            'est_seg' => 'VARCHAR(20) NOT NULL DEFAULT \'ABIERTO\'',
            'vis_seg' => 'VARCHAR(30)',
            'cod_usu_res' => 'VARCHAR(20)',
            'fec_ape_seg' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'fec_pro_seg' => 'TIMESTAMPTZ',
            'fec_cie_seg' => 'TIMESTAMPTZ',
            'res_seg' => 'TEXT',
            'pro_acc_seg' => 'TEXT',
            'obs_seg' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_seg IN (\'ABIERTO\',\'EN_SEGUIMIENTO\',\'CERRADO\',\'ANULADO\')',
            '(fec_pro_seg IS NULL OR fec_pro_seg>=fec_ape_seg) AND (fec_cie_seg IS NULL OR fec_cie_seg>=fec_ape_seg)',
        ],
        'unicos' => [],
        'grupo' => 'Institucional',
        'existente' => true,
    ],
    [
        'tabla' => 'resultado_anual',
        'creacion' => 'CREATE TABLE "resultado_anual" (
 "cod_ran" VARCHAR(20) PRIMARY KEY,
 "cod_ins" VARCHAR(20) NOT NULL UNIQUE,
 "res_ran" VARCHAR(20) NOT NULL,
 "fec_ran" DATE NOT NULL,
 "cod_usu" VARCHAR(20) NOT NULL,
 "ref_ran" VARCHAR(255),
 "obs_ran" TEXT,
 "est_ran" VARCHAR(20) NOT NULL DEFAULT \'VIGENTE\',
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_ins' => '"cod_ins" VARCHAR(20) NULL',
            'res_ran' => '"res_ran" VARCHAR(20) NULL',
            'fec_ran' => '"fec_ran" DATE NULL',
            'cod_usu' => '"cod_usu" VARCHAR(20) NULL',
            'ref_ran' => '"ref_ran" VARCHAR(255) NULL',
            'obs_ran' => '"obs_ran" TEXT NULL',
            'est_ran' => '"est_ran" VARCHAR(20) NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_ran',
        'columnas' => [
            'cod_ran' => 'VARCHAR(20) PRIMARY KEY',
            'cod_ins' => 'VARCHAR(20) NOT NULL UNIQUE',
            'res_ran' => 'VARCHAR(20) NOT NULL',
            'fec_ran' => 'DATE NOT NULL',
            'cod_usu' => 'VARCHAR(20) NOT NULL',
            'ref_ran' => 'VARCHAR(255)',
            'obs_ran' => 'TEXT',
            'est_ran' => 'VARCHAR(20) NOT NULL DEFAULT \'VIGENTE\'',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'res_ran IN (\'PROMOVIDO\',\'RETENIDO\',\'EGRESADO\',\'RETIRADO\',\'ANULADO\')',
            'est_ran IN (\'VIGENTE\',\'ANULADO\')',
        ],
        'unicos' => [
            [
                'cod_ins',
            ],
        ],
        'grupo' => 'Institucional',
        'existente' => false,
    ],
    [
        'tabla' => 'regente_asignaciones',
        'creacion' => 'CREATE TABLE "regente_asignaciones" (
 "cod_ras" VARCHAR(20) PRIMARY KEY,
 "cod_vpe" VARCHAR(20) NOT NULL,
 "cod_gea" VARCHAR(20) NOT NULL,
 "cod_cur" VARCHAR(20) NOT NULL,
 "fii_ras" DATE NOT NULL,
 "ffi_ras" DATE,
 "est_ras" VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\',
 "obs_ras" TEXT,
 "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);',
        'adiciones' => [
            'cod_vpe' => '"cod_vpe" VARCHAR(20) NULL',
            'cod_gea' => '"cod_gea" VARCHAR(20) NULL',
            'cod_cur' => '"cod_cur" VARCHAR(20) NULL',
            'fii_ras' => '"fii_ras" DATE NULL',
            'ffi_ras' => '"ffi_ras" DATE NULL',
            'est_ras' => '"est_ras" VARCHAR(20) NULL',
            'obs_ras' => '"obs_ras" TEXT NULL',
            'created_at' => '"created_at" TIMESTAMPTZ NULL',
            'updated_at' => '"updated_at" TIMESTAMPTZ NULL',
        ],
        'pk' => 'cod_ras',
        'columnas' => [
            'cod_ras' => 'VARCHAR(20) PRIMARY KEY',
            'cod_vpe' => 'VARCHAR(20) NOT NULL',
            'cod_gea' => 'VARCHAR(20) NOT NULL',
            'cod_cur' => 'VARCHAR(20) NOT NULL',
            'fii_ras' => 'DATE NOT NULL',
            'ffi_ras' => 'DATE',
            'est_ras' => 'VARCHAR(20) NOT NULL DEFAULT \'ACTIVO\'',
            'obs_ras' => 'TEXT',
            'created_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
        'checks' => [
            'est_ras IN (\'ACTIVO\',\'FINALIZADO\',\'ANULADO\')',
            'ffi_ras IS NULL OR ffi_ras>=fii_ras',
        ],
        'unicos' => [],
        'grupo' => 'Institucional',
        'existente' => false,
    ],
];
