<div class="ga-grilla" :class="{'ga-analista-layout':seccion==='impacto'}">
        <div class="space-y-5">
            <article class="ui-card" x-show="seccion==='agenda'" x-transition.opacity.duration.140ms><header><div><p class="ui-kicker">Calendario de la gestión</p><h2 class="ui-title mt-1">Feriados, actividades y contingencias</h2><p class="ui-muted text-sm mt-2">Consulta lo registrado y revisa su respaldo antes de tomar una decisión.</p></div><span class="ui-badge-info">{{ count($panelAcademico['eventos']) }} {{ count($panelAcademico['eventos'])===1?'evento':'eventos' }}</span></header>
                @if($gestionSeleccionada)<x-calendario-academico :anio="$gestionSeleccionada['anio']" :periodos="$periodosCalendario" :eventos="$panelAcademico['eventos']" :preparar-caso="$puedeAnalizar" />@endif
                <x-plegable-institucional class="ga-lista-eventos" icono="ph-calendar-dots"><x-slot:titulo>Consultar la lista de eventos</x-slot:titulo><div class="ga-filtros"><x-selector-institucional modelo="filtroCalendario" identificador="academica-tipo-evento" etiqueta="Tipo de evento" :opciones="array_merge([['valor'=>'','etiqueta'=>'Todos los eventos']],collect($panelAcademico['eventos'])->pluck('tipo')->unique()->map(fn($tipo)=>['valor'=>$tipo,'etiqueta'=>ucfirst(mb_strtolower(str_replace('_',' ',$tipo)))])->values()->all())" /><x-selector-institucional modelo="mesCalendario" identificador="academica-mes-evento" etiqueta="Mes" :opciones="array_merge([['valor'=>'','etiqueta'=>'Todos los meses']],collect(['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'])->map(fn($mes,$i)=>['valor'=>str_pad($i+1,2,'0',STR_PAD_LEFT),'etiqueta'=>$mes])->all())" /></div>
                <div class="ga-eventos">
                @forelse(collect($panelAcademico['eventos'])->filter(fn($e)=>(!$filtroCalendario || $e['tipo']===$filtroCalendario) && (!$mesCalendario || substr($e['inicio'],5,2)<=$mesCalendario && substr($e['fin'],5,2)>=$mesCalendario)) as $evento)
                    <article class="ga-evento"><time datetime="{{ $evento['inicio'] }}">{{ \Carbon\Carbon::parse($evento['inicio'])->format('d') }}<small>{{ \Carbon\Carbon::parse($evento['inicio'])->locale('es')->translatedFormat('M') }}</small></time><div><h3 class="ui-title">{{ $evento['nombre'] }}</h3><p class="ui-muted text-xs mt-1">{{ $formatDate($evento['inicio']) }}{{ $evento['inicio']!==$evento['fin']?' — '.$formatDate($evento['fin']):'' }} · {{ ucfirst(mb_strtolower(str_replace('_',' ',$evento['efecto']))) }}</p><span class="ui-badge-info mt-2">{{ ucfirst(mb_strtolower(str_replace('_',' ',$evento['estado']))) }}</span><x-plegable-institucional icono="ph-file-text" :compacto="true"><x-slot:titulo>Motivo y documentación</x-slot:titulo><p class="ui-muted mt-2">{{ $evento['motivo'] ?: 'Motivo pendiente de registro.' }}</p><p class="ui-muted mt-2"><strong>Fuente registrada:</strong> {{ $evento['fuente'] ?: 'Sin fuente registrada.' }}</p><p class="ui-muted mt-1">{{ ucfirst(mb_strtolower($evento['alcance'])) }} · {{ $evento['documento'] ?: 'Documento por revisar' }}</p>@if($evento['url'])<a href="{{ $evento['url'] }}" class="ui-link text-xs" target="_blank" rel="noopener noreferrer">Abrir documento de respaldo</a>@else<p class="ui-muted mt-1">Puedes preparar un caso sin documento. Su confirmación requiere revisión institucional.</p>@endif</x-plegable-institucional><button type="button" class="ui-btn ui-btn-secondary mt-3" wire:click="usarFechaImpacto('{{ $evento['inicio'] }}')">Explorar impacto de esta fecha</button></div></article>
                @empty
                    <div class="ga-vacio"><i class="ph-duotone ph-calendar-blank" aria-hidden="true"></i><h3 class="ui-title">No hay eventos en esta selección</h3><p>Cambia el mes o el tipo para ampliar la consulta.</p></div>
                @endforelse
                </div></x-plegable-institucional>
            </article>
            <article class="ui-card" x-show="seccion==='referencias'" x-cloak x-transition.opacity.duration.140ms><p class="ui-kicker">Disposiciones para contrastar</p><h2 class="ui-title mt-1">Referencias oficiales · {{ $gestionSeleccionada['anio'] ?? 'Sin gestión' }}</h2><p class="ui-muted text-sm mt-2">La revisión compara estas fechas con las suspensiones generales registradas. La revisión conserva la decisión institucional.</p><div class="ga-referencias">
                @if((int)($gestionSeleccionada['anio']??0)===2026)<div class="ga-referencia"><p class="ui-kicker">Ministerio de Educación</p><h3 class="ui-title">Normativa de Educación Regular 2026</h3><p class="ui-muted">Tres trimestres y 200 días efectivos de trabajo curricular. Las divisiones y adecuaciones institucionales deben revisarse por separado.</p><a href="{{ \App\Support\Academico\PanelGestionAcademica::NORMA_2026 }}" target="_blank" rel="noopener noreferrer">RM 0001/2026 · Artículo 3</a></div>@endif
                <p class="ui-kicker mt-2">Ministerio de Trabajo · disposiciones de 2026</p>
                @forelse($panelAcademico['referencias'] as $referencia)<div class="ga-referencia"><h3 class="ui-title">{{ $referencia['nombre'] }}</h3><p class="ui-muted">{{ $formatDate($referencia['fecha']) }} · {{ $referencia['registrado']?'Figura en el calendario':'Pendiente de revisar en el calendario' }}</p><a href="{{ $referencia['url'] }}" target="_blank" rel="noopener noreferrer">{{ $referencia['fuente'] }} <i class="ph-duotone ph-arrow-square-out" aria-hidden="true"></i></a><button type="button" class="ui-btn ui-btn-secondary mt-3" wire:click="usarFechaImpacto('{{ $referencia['fecha'] }}')">Analizar esta fecha</button></div>@empty<p class="ui-muted text-sm">Las disposiciones de esta gestión necesitan una revisión de sus fuentes oficiales.</p>@endforelse
            </div><p class="ui-muted text-xs mt-3">Fuentes revisadas el 04/10/2026. Consulta las nuevas disposiciones antes de aprobar cambios.</p></article>
        </div>
        <div class="space-y-5">
            @include('livewire.admin.academica.balance-calendario')

            @if($inicioCurricular)<article class="ui-card ga-inicio-clases" x-show="seccion==='agenda'"><p class="ui-kicker">Inicio de clases</p><h2 class="ui-title mt-2">Primer lunes de febrero</h2><strong class="ga-fecha-inicio">{{ $formatDate($inicioCurricular['primero']) }}</strong><p class="ui-muted text-sm mt-2">{{ $inicioCurricular['mensaje'] }}</p><x-plegable-institucional class="mt-3" icono="ph-calendar-dots"><x-slot:titulo>Ver la alternativa y la fecha registrada</x-slot:titulo><p class="ui-muted text-xs mt-2">Segundo lunes: {{ $formatDate($inicioCurricular['segundo']) }} · Inicio registrado: {{ $formatDate($inicioCurricular['registrado']) }}. La fecha aprobada para este año tiene prioridad sobre la sugerencia.</p></x-plegable-institucional></article>@endif
            <article class="ui-card" x-show="borrador" x-cloak><p class="ui-kicker">Tu propuesta pendiente</p><h2 class="ui-title mt-2">Retomar el borrador</h2><p class="ui-muted text-sm mt-2">Guardado en este navegador para esta gestión.</p><button type="button" class="ui-btn ui-btn-secondary mt-3" x-on:click="restaurar()">Recuperar campos y PDF</button></article>

            <article class="ui-card" x-show="seccion!=='impacto'"><p class="ui-kicker">Antes de tomar una decisión</p><h2 class="ui-title mt-1">¿Qué cambiaría si se interrumpe una jornada?</h2><p class="ui-muted text-sm mt-2">El analista cruza fechas, horarios, vigencias estudiantiles y vencimientos. Puedes revisar un caso sin modificar el calendario.</p><button type="button" class="ui-btn ui-btn-primary mt-4" x-on:click="seccion='impacto'">Abrir analista de impacto</button><button type="button" class="ui-btn ui-btn-secondary mt-3" x-on:click="seccion='referencias'">Consultar las fuentes</button></article>
            @include('livewire.admin.academica.caso-calendario')
        </div>
    </div>
