<article class="ui-card ga-caso-card" x-show="seccion==='impacto'" x-cloak x-transition.opacity.duration.140ms id="academica-impacto" x-data="{resultadoVigente:true,errorRecuperacion:''}" x-on:input.capture="resultadoVigente=false" x-on:academica-enfocar-impacto.window="$el.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})">
    <header><div><p class="ui-kicker">Antes de decidir</p><h2 class="ui-title mt-1">¿Qué cambiaría en las clases?</h2><p class="ui-muted text-sm mt-2">Prepara el caso y revisa cursos, materias y docentes con sus horarios registrados.</p></div><span class="ui-badge-info">Vista previa</span></header>
    @if($puedeAnalizar && $gestionSeleccionada['fecha_inicio'] && $gestionSeleccionada['fecha_fin'])
    <form wire:submit="analizarImpacto" x-on:submit="resultadoVigente=true" id="form-caso-calendario"><fieldset class="ga-caso-form" wire:loading.attr="disabled" wire:target="analizarImpacto,comprobarUniversidad">
        <section class="ga-caso-seccion"><h3 class="ui-title"><span>1</span> El caso y su alcance</h3><div class="ga-campos">
            <x-selector-institucional modelo="casoImpacto.tipo" identificador="caso-tipo" etiqueta="Tipo de caso" :opciones="collect($tiposCaso)->map(fn($v,$k)=>['valor'=>$k,'etiqueta'=>$v['nombre']])->values()->all()" :requerido="true" />
            <x-selector-institucional modelo="casoImpacto.efecto" identificador="caso-efecto" etiqueta="¿Qué pasará con las clases?" :opciones="collect($efectosCaso)->map(fn($v,$k)=>['valor'=>$k,'etiqueta'=>$v])->values()->all()" :requerido="true" />
            <div class="ga-nota-fuente ga-campo-ancho" role="status"><i class="ph-duotone ph-lightbulb" aria-hidden="true"></i><p>{{ $tiposCaso[$casoImpacto['tipo']]['sugerencia'] ?? 'Describe el caso para orientar la revisión.' }}</p></div>
            @if($casoImpacto['tipo']==='FERIADO')<div class="ga-campo-ancho"><x-selector-institucional modelo="casoImpacto.anual" identificador="caso-anual" etiqueta="¿Deseas recordarlo para otras gestiones?" :opciones="[['valor'=>'NO','etiqueta'=>'Solo esta gestión'],['valor'=>'SI','etiqueta'=>'Proponerlo cada año, con revisión']]" /><p class="ui-muted text-xs mt-2">Los feriados anuales se revisan al preparar el siguiente calendario. Una celebración o actividad sin clases se registra como su propio tipo de caso.</p></div>@endif
            <x-selector-institucional modelo="casoImpacto.alcance" identificador="caso-alcance" etiqueta="¿A quiénes afecta?" :opciones="[['valor'=>'INSTITUCIONAL','etiqueta'=>'Todo el colegio'],['valor'=>'TURNO','etiqueta'=>'Elegir uno o varios turnos'],['valor'=>'GRUPO','etiqueta'=>'Elegir uno o varios cursos']]" />
            @if($casoImpacto['alcance']==='GRUPO')<x-selector-institucional modelo="casoImpacto.grupos" identificador="caso-grupo" etiqueta="Cursos y paralelos participantes" :opciones="$gruposCaso" :multiple="true" :requerido="true" />@elseif($casoImpacto['alcance']==='TURNO')<x-selector-institucional modelo="casoImpacto.turnos" identificador="caso-turno" etiqueta="Turnos afectados" :opciones="$turnosCaso" :multiple="true" :requerido="true" />@endif
            @if(in_array($casoImpacto['tipo'],['BLOQUEO_PARO','EMERGENCIA_SALUD','OTRO'],true))<div><label for="caso-zona" class="ui-label">Zona o lugar · opcional</label><input id="caso-zona" wire:model="casoImpacto.zona" maxlength="150" class="ui-input" placeholder="Por ejemplo: La Paz, zona afectada" /><x-input-error for="casoImpacto.zona" /></div>@endif
            @if(in_array($casoImpacto['tipo'],['VISITA_UNIVERSIDAD','VIAJE'],true) || $casoImpacto['efecto']==='SALIDA')<div class="ga-campo-ancho"><x-selector-institucional modelo="casoImpacto.responsable" identificador="caso-responsable" etiqueta="Docente acompañante propuesto" :opciones="array_merge([['valor'=>'','etiqueta'=>'Por definir']],$docentesCaso)" /><p class="ui-muted text-xs mt-2">Revisaremos si imparte las clases afectadas y si tiene otras clases en esas horas. La autorización se confirma por separado.</p></div>@endif
            @if($casoImpacto['tipo']==='VISITA_UNIVERSIDAD')@include('livewire.admin.academica.universidad-visita')@endif
        </div></section>
        <section class="ga-caso-seccion"><h3 class="ui-title"><span>2</span> Fechas y horas del cambio</h3><div class="ga-campos">
            <div class="ga-campo-ancho"><x-selector-institucional modelo="casoImpacto.periodo" identificador="caso-periodo" etiqueta="¿Cuánto durará el caso?" :opciones="[['valor'=>'DIA','etiqueta'=>'Un solo día'],['valor'=>'RANGO','etiqueta'=>'Varios días']]" /></div>
            <x-calendario-institucional modelo="casoImpacto.inicio" identificador="academica-impacto-inicio" :etiqueta="$casoImpacto['periodo']==='DIA' ? 'Fecha del caso' : 'Desde'" :minimo="substr($gestionSeleccionada['fecha_inicio'],0,10)" :maximo="substr($gestionSeleccionada['fecha_fin'],0,10)" :inicio="substr($gestionSeleccionada['fecha_inicio'],0,10)" :requerido="true" />
            @if($casoImpacto['periodo']==='RANGO')<x-calendario-institucional modelo="casoImpacto.fin" identificador="academica-impacto-fin" etiqueta="Hasta" :minimo="$casoImpacto['inicio'] ?: substr($gestionSeleccionada['fecha_inicio'],0,10)" :maximo="substr($gestionSeleccionada['fecha_fin'],0,10)" :inicio="$casoImpacto['inicio'] ?: substr($gestionSeleccionada['fecha_inicio'],0,10)" :requerido="true" />@endif
            <div class="ga-campo-ancho"><button type="button" class="ui-btn ui-btn-secondary" wire:click="usarHoy">Usar la fecha de hoy</button></div>
            @if($casoImpacto['tipo']==='FESTEJO_TRASLADADO')<div class="ga-campo-ancho"><x-calendario-institucional modelo="casoImpacto.fecha_original" identificador="caso-fecha-original" etiqueta="Fecha conmemorativa · opcional" :minimo="$gestionSeleccionada['anio'].'-01-01'" :maximo="$gestionSeleccionada['anio'].'-12-31'" :inicio="$casoImpacto['inicio'] ?: $gestionSeleccionada['anio'].'-01-01'" /><p class="ui-muted text-xs mt-2">Desde y Hasta indican la celebración elegida; esta fecha conserva la conmemoración original.</p>@if($casoImpacto['fecha_original'])<div class="ga-acciones mt-2">@foreach(['previous'=>'Viernes anterior','next'=>'Lunes siguiente'] as $sentido=>$titulo)<button type="button" class="ui-btn ui-btn-secondary" wire:click="sugerirCelebracion('{{ $sentido }}')">{{ $titulo }}</button>@endforeach</div>@endif</div>@endif
            <div class="ga-campo-ancho"><x-selector-institucional modelo="casoImpacto.jornada" identificador="caso-jornada" etiqueta="Duración de cada jornada" :opciones="[['valor'=>'COMPLETA','etiqueta'=>'Toda la jornada'],['valor'=>'PARCIAL','etiqueta'=>'Solo algunas horas']]" /></div>
            @if($casoImpacto['jornada']==='PARCIAL')<div><label for="caso-hora-inicio" class="ui-label">Empieza a las *</label><input id="caso-hora-inicio" type="time" wire:model="casoImpacto.hora_inicio" required class="ui-input" /><x-input-error for="casoImpacto.hora_inicio" /></div><div><label for="caso-hora-fin" class="ui-label">Termina a las *</label><input id="caso-hora-fin" type="time" wire:model="casoImpacto.hora_fin" required class="ui-input" /><x-input-error for="casoImpacto.hora_fin" /></div>@if($casoImpacto['tipo']==='ENTREGA_NOTAS')<button type="button" class="ui-btn ui-btn-secondary ga-campo-ancho" wire:click="usarDespuesRecreo"><i class="ph-duotone ph-clock" aria-hidden="true"></i>Usar desde el final del recreo</button>@endif<p class="ui-muted text-xs ga-campo-ancho">Solo cuentan los minutos que coinciden con las clases. En varios días, este horario se aplica a cada jornada.</p>@endif
        </div></section>
        <section class="ga-caso-seccion ga-campo-ancho"><h3 class="ui-title"><span>3</span> Revisión de clases</h3><x-selector-institucional modelo="casoImpacto.revision" identificador="caso-revision" etiqueta="¿Quieres revisar las clases afectadas?" :opciones="[['valor'=>'NO','etiqueta'=>'Ahora no, preparar el caso'],['valor'=>'SI','etiqueta'=>'Sí, revisar impacto y reprogramación']]" /><p class="ui-muted text-xs mt-2">Puedes preparar el caso sin calcular su impacto. Al revisar, veremos el alumnado, las materias y los docentes que coinciden con las fechas y horas elegidas.</p>@if($casoImpacto['revision']==='SI')<div class="mt-4"><x-selector-institucional modelo="casoImpacto.recuperacion" identificador="caso-recuperacion" etiqueta="¿Se propone reprogramar las clases?" :opciones="[['valor'=>'PENDIENTE','etiqueta'=>'Pendiente de revisar'],['valor'=>'NO','etiqueta'=>'No se propone reprogramar'],['valor'=>'POR_CONFIRMAR','etiqueta'=>'Sí, con el día por confirmar'],['valor'=>'PROPUESTA','etiqueta'=>'Sí, proponer fecha y horas']]" />
            @if(in_array($casoImpacto['recuperacion'],['POR_CONFIRMAR','PROPUESTA'],true))
                <div class="mt-4"><x-selector-institucional modelo="casoImpacto.modalidad_recuperacion" identificador="caso-modalidad-recuperacion" etiqueta="¿Cómo recuperarán las clases?" :opciones="[['valor'=>'POR_DEFINIR','etiqueta'=>'Modalidad por confirmar'],['valor'=>'PRESENCIAL','etiqueta'=>'Presencial'],['valor'=>'VIRTUAL','etiqueta'=>'Virtual']]" /></div>
                @if(($casoImpacto['modalidad_recuperacion'] ?? 'POR_DEFINIR')==='VIRTUAL')
                    <div class="ga-campos mt-4">
                        <x-selector-institucional modelo="casoImpacto.medio_recuperacion" identificador="caso-medio-recuperacion" etiqueta="Medio para recuperar" :opciones="[['valor'=>'AULA_INSTITUCIONAL','etiqueta'=>'Aula virtual institucional'],['valor'=>'VIDEOLLAMADA','etiqueta'=>'Videollamada'],['valor'=>'OTRO','etiqueta'=>'Otro medio, explicar en el plan']]" />
                        <div><label for="caso-enlace-recuperacion" class="ui-label">Enlace del aula o reunión · opcional</label><input id="caso-enlace-recuperacion" type="url" wire:model="casoImpacto.enlace_recuperacion" class="ui-input" maxlength="2000" placeholder="https://…" /><x-input-error for="casoImpacto.enlace_recuperacion" /></div>
                        <div class="ga-campo-ancho"><label for="caso-plan-recuperacion" class="ui-label">Plan de recuperación virtual *</label><textarea id="caso-plan-recuperacion" wire:model="casoImpacto.plan_recuperacion" class="ui-input" required minlength="10" maxlength="1000" rows="3" placeholder="Explica las actividades, el acompañamiento docente y qué alternativa tendrán quienes no puedan conectarse…"></textarea><x-input-error for="casoImpacto.plan_recuperacion" /></div>
                    </div>
                    <p class="ui-muted text-xs mt-2">La modalidad virtual conserva los límites de horas y trimestre. Revisa conexión, dispositivos, materiales y participación; los docentes no pueden atender otra clase al mismo tiempo.</p>
                @endif
            @endif
            @if($casoImpacto['recuperacion']==='POR_CONFIRMAR')<div class="mt-4"><x-selector-institucional modelo="casoImpacto.dia_recuperacion" identificador="caso-dia-recuperacion" etiqueta="¿Qué día están considerando?" :opciones="[['valor'=>'POR_DEFINIR','etiqueta'=>'Aún por definir'],['valor'=>'SABADO','etiqueta'=>'Un sábado'],['valor'=>'ENTRE_SEMANA','etiqueta'=>'Entre semana']]" /><p class="ui-muted text-xs mt-2">Coordina con estudiantes y docentes. Lo recomendable es recuperar dentro de los siete días siguientes al caso y siempre antes del cierre de su trimestre.</p></div>@endif
            @if(in_array($casoImpacto['recuperacion'],['POR_CONFIRMAR','PROPUESTA'],true))<div class="mt-4"><label class="ui-label" for="caso-observacion-recuperacion">Observación para la gestión {{ $casoImpacto['recuperacion']==='POR_CONFIRMAR'?'*':'· opcional' }}</label><textarea id="caso-observacion-recuperacion" wire:model="casoImpacto.observacion_recuperacion" class="ui-input mt-2" rows="2" maxlength="1000" minlength="10" @required($casoImpacto['recuperacion']==='POR_CONFIRMAR') placeholder="Indica lo que falta coordinar, las horas pendientes o el motivo de la fecha propuesta…"></textarea><x-input-error for="casoImpacto.observacion_recuperacion" /></div>@endif
            @if($casoImpacto['recuperacion']==='PROPUESTA')<div class="ga-campos mt-4"><div class="ga-campo-ancho"><x-calendario-institucional modelo="casoImpacto.fecha_recuperacion" identificador="caso-fecha-recuperacion" etiqueta="Fecha propuesta" :minimo="$limitesRecuperacion['minimo']" :maximo="max($limitesRecuperacion['minimo'],$limitesRecuperacion['maximo'])" :requerido="true" /><button type="button" wire:click="sugerirSabadoRecuperacion" class="ui-btn ui-btn-secondary mt-2">Proponer el siguiente sábado</button></div><div><label for="caso-recuperacion-inicio" class="ui-label">Desde las *</label><input id="caso-recuperacion-inicio" x-ref="recuperacionInicio" x-init="$nextTick(()=>errorRecuperacion=validarFranjaRecuperacion($refs.recuperacionInicio.value,$refs.recuperacionFin.value,@js($limitesRecuperacion['hora_minima']),@js($limitesRecuperacion['hora_maxima'])))" x-on:input="errorRecuperacion=validarFranjaRecuperacion($refs.recuperacionInicio.value,$refs.recuperacionFin.value,@js($limitesRecuperacion['hora_minima']),@js($limitesRecuperacion['hora_maxima']))" type="time" wire:model="casoImpacto.hora_recuperacion_inicio" min="{{ $limitesRecuperacion['hora_minima'] }}" max="{{ $limitesRecuperacion['hora_maxima'] }}" required class="ui-input" /><x-input-error for="casoImpacto.hora_recuperacion_inicio" /></div><div><label for="caso-recuperacion-fin" class="ui-label">Hasta las *</label><input id="caso-recuperacion-fin" x-ref="recuperacionFin" x-on:input="errorRecuperacion=validarFranjaRecuperacion($refs.recuperacionInicio.value,$refs.recuperacionFin.value,@js($limitesRecuperacion['hora_minima']),@js($limitesRecuperacion['hora_maxima']))" :aria-invalid="!!errorRecuperacion" type="time" wire:model="casoImpacto.hora_recuperacion_fin" min="{{ $limitesRecuperacion['hora_minima'] }}" max="{{ $limitesRecuperacion['hora_maxima'] }}" required class="ui-input" /><x-input-error for="casoImpacto.hora_recuperacion_fin" /><p class="ui-error mt-2" x-text="errorRecuperacion" role="alert"></p></div></div><p class="ui-muted text-xs mt-2">Mínimo una hora; no puede superar el tiempo de clases afectado por grupo. Usa el horario escolar {{ $limitesRecuperacion['hora_minima'] ?? 'por confirmar' }}–{{ $limitesRecuperacion['hora_maxima'] ?? 'por confirmar' }} y conserva el mismo trimestre: {{ $limitesRecuperacion['trimestre'] ?? 'elige primero las fechas del caso' }}. @if(!$limitesRecuperacion['disponible']) No hay un rango disponible para esta selección; revisa fechas y grupos. @endif</p>@endif
        </div>@endif</section>
        <section class="ga-caso-seccion ga-campo-ancho"><h3 class="ui-title"><span>4</span> Motivo y respaldo</h3><label class="ui-label" for="academica-impacto-motivo">Cuéntanos qué ocurre *</label><textarea id="academica-impacto-motivo" wire:model="casoImpacto.motivo" required minlength="10" maxlength="1000" rows="3" class="ui-input mt-2" placeholder="Explica el motivo, la decisión que se está considerando y quiénes quedarían a cargo…"></textarea><x-input-error for="casoImpacto.motivo" />
            <x-plegable-institucional class="ga-caso-documento" icono="ph-file-pdf"><x-slot:titulo>Agregar respaldo opcional</x-slot:titulo><div class="ga-campos mt-4"><div><label class="ui-label" for="academica-impacto-documento">Nombre o número del comunicado</label><input id="academica-impacto-documento" wire:model="casoImpacto.documento" maxlength="250" class="ui-input" placeholder="Circular, resolución o comunicado" /><x-input-error for="casoImpacto.documento" /></div><div><label class="ui-label" for="caso-url-documento">Enlace al documento · opcional</label><input id="caso-url-documento" type="url" wire:model="casoImpacto.url_documento" maxlength="2000" class="ui-input" placeholder="https://…" /><x-input-error for="casoImpacto.url_documento" /></div><div class="ga-campo-ancho"><label for="caso-pdf" class="ui-label">Documento PDF · máximo 10 MB</label><input id="caso-pdf" x-ref="archivoPdf" type="file" accept=".pdf,application/pdf" x-on:change="elegirPdf($event)" class="ui-input mt-2" /><p class="ui-error mt-2" x-text="errorPdf" role="alert"></p><p class="ui-muted text-xs mt-2" x-show="pdf" x-text="pdf?.nombre"></p><div class="ga-acciones mt-2" x-show="pdf"><button type="button" class="ui-btn ui-btn-secondary" x-on:click="descargarPdf()">Descargar PDF</button><button type="button" class="ui-btn ui-btn-secondary" x-on:click="pdf=null;if($refs.archivoPdf)$refs.archivoPdf.value=''">Quitar del borrador</button></div><p class="ui-muted text-xs mt-2">El PDF acompaña el borrador guardado en este navegador. Su contenido requiere revisión; adjuntarlo no aprueba el caso.</p></div></div></x-plegable-institucional>
        </section>
        <footer class="ga-caso-pie ga-campo-ancho"><div class="ga-acciones">@if($casoImpacto['revision']==='SI')<button type="submit" class="ui-btn ui-btn-primary" :disabled="$wire.casoImpacto.recuperacion==='PROPUESTA' && !!errorRecuperacion" wire:loading.attr="disabled" wire:target="analizarImpacto"><i class="ph-duotone ph-intersect" aria-hidden="true" wire:loading.remove wire:target="analizarImpacto"></i><span class="ga-carga-boton" aria-hidden="true" wire:loading wire:target="analizarImpacto"></span><span wire:loading.remove wire:target="analizarImpacto">Revisar impacto</span><span wire:loading wire:target="analizarImpacto">Revisando clases y estudiantes…</span></button>@endif<button type="button" class="ui-btn ui-btn-secondary" wire:click="guardarBorrador" :disabled="!!errorPdf || leyendoPdf" wire:loading.attr="disabled">Guardar borrador</button><button type="button" class="ui-btn ui-btn-secondary" wire:click="descargarCaso" wire:loading.attr="disabled">Descargar propuesta</button></div><p class="ui-muted text-xs mt-3">El borrador se conserva en este navegador. La revisión y la descarga no suspenden clases ni cambian notas, asistencias o fechas de entrega.</p><p class="ui-muted text-xs mt-2" x-text="mensajeBorrador" role="status"></p></footer>
    <p class="ui-muted text-xs ga-campo-ancho" wire:loading.delay wire:target="analizarImpacto" role="status">Estamos revisando los horarios, las vigencias del alumnado y los vencimientos. Tus campos se conservan; espera a que termine la revisión.</p></fieldset></form>
    @else<div class="ga-nota-fuente mt-4"><i class="ph-duotone ph-lock-key" aria-hidden="true"></i><p>Esta gestión se conserva para consulta. Los análisis y las propuestas de cambios están disponibles únicamente en la gestión activa.</p></div>@endif
    @if($resultadoImpacto)<div class="ga-resultado-caso" x-show="resultadoVigente" wire:loading.remove wire:target="analizarImpacto" aria-live="polite">
        @foreach($resultadoImpacto['bloqueos'] ?? [] as $bloqueo)<div class="ga-aviso" data-nivel="error"><p>{{ $bloqueo }}</p></div>@endforeach
        @if($resultadoImpacto['impacto'] ?? null)@php($impacto=$resultadoImpacto['impacto'])
            <header><p class="ui-kicker">Consecuencias por revisar</p><h3 class="ui-title mt-1">{{ $efectosCaso[$impacto['efecto']] ?? 'Cambios previstos' }}</h3><p class="ui-muted text-sm mt-2">{{ $formatDate($resultadoImpacto['caso']['inicio']) }}@if($resultadoImpacto['caso']['fin']!==$resultadoImpacto['caso']['inicio']) — {{ $formatDate($resultadoImpacto['caso']['fin']) }}@endif · @if($resultadoImpacto['caso']['jornada']==='PARCIAL'){{ $resultadoImpacto['caso']['hora_inicio'] }}–{{ $resultadoImpacto['caso']['hora_fin'] }} · {{ $resultadoImpacto['caso']['inicio']===$resultadoImpacto['caso']['fin']?'Duración del caso':'Franja de cada día' }}: {{ $resultadoImpacto['caso']['duracion'] }} @else Toda la jornada @endif</p></header><div class="ga-cifras">@foreach(['sesiones'=>'Sesiones que coinciden','duracion'=>'Tiempo de clases acumulado','grupos'=>'Grupos afectados','materias'=>'Materias y especialidades','estudiantes'=>'Alumnado según vigencias','docentes'=>'Docentes involucrados','tareas'=>'Vencimientos por revisar','evaluaciones'=>'Evaluaciones incluidas'] as $campo=>$etiqueta)<div><strong>{{ $impacto[$campo] ?? '—' }}</strong><span>{{ $etiqueta }}</span></div>@endforeach</div>
            <p class="ui-muted text-sm mt-4">{{ $impacto['sesiones_suspendidas'] }} sesiones con interrupción propuesta · {{ $impacto['sesiones_virtuales'] }} sesiones con cambio a virtual.</p><p class="ui-muted text-xs mt-2">El tiempo suma las sesiones de todos los grupos afectados; varias pueden ocurrir a la misma hora. Son estimaciones del horario vigente, no asistencia real. Los vencimientos corresponden a las materias afectadas dentro del rango y pueden quedar fuera de las horas de suspensión.</p>
            @if($impacto['detalle'])<div class="ga-impacto-grupos">@foreach(collect($impacto['detalle'])->groupBy('grupo') as $grupo=>$materias)<x-plegable-institucional :abierto="count($impacto['cursos']) < 5" icono="ph-books"><x-slot:titulo><span>{{ $grupo }}</span><small>{{ $materias->sum('sesiones') }} sesiones · {{ $materias->count() }} materias</small></x-slot:titulo><div class="ga-impacto-materias">@foreach($materias as $materia)<article><div><strong>{{ $materia['materia'] }}</strong>@if(isset($materia['docente']))<p>{{ $materia['docente'] }} @if($materia['responsable'])<span class="ui-badge-info">Acompañante propuesto</span>@endif</p>@endif</div><span>{{ $materia['sesiones'] }} {{ $materia['sesiones']===1?'sesión':'sesiones' }} · {{ $materia['duracion'] }}</span></article>@endforeach</div></x-plegable-institucional>@endforeach</div>@endif
            @if($resultadoImpacto['responsable']['nombre'] ?? null)<section class="ga-responsable"><p class="ui-kicker">Acompañante propuesto</p><h4 class="ui-title mt-2">{{ $resultadoImpacto['responsable']['nombre'] }}</h4><p class="ui-muted text-sm mt-2">{{ $resultadoImpacto['responsable']['imparte_en_grupo']?'Imparte alguna de las clases afectadas.':'No coincide con las materias afectadas en estas horas.' }}</p>@if($resultadoImpacto['responsable']['cruces'])<h5 class="ui-title mt-3">Otras clases que necesitan cobertura</h5><div class="ga-impacto-materias">@foreach($resultadoImpacto['responsable']['cruces'] as $cruce)<article><div><strong>{{ $cruce['grupo'] }}</strong><p>{{ $cruce['materia'] }}</p></div><span>{{ $formatDate($cruce['fecha']) }} · {{ $cruce['horas'] }}</span></article>@endforeach</div><p class="ui-muted text-xs mt-2">{{ $resultadoImpacto['responsable']['cruces_total'] }} cruces en total; se muestran los primeros 12.</p>@endif</section>@endif
        @endif
        @foreach($resultadoImpacto['advertencias'] ?? [] as $advertencia)<div class="ga-aviso mt-3" data-nivel="warning"><p><i class="ph-duotone ph-info" aria-hidden="true"></i> {{ $advertencia }}</p></div>@endforeach
        @if($resultadoImpacto['recuperacion'] ?? null)<section class="ga-responsable"><p class="ui-kicker">Recuperación por revisar</p><h3 class="ui-title mt-2">{{ $resultadoImpacto['recuperacion']['fecha'] ? 'Propuesta para '.$formatDate($resultadoImpacto['recuperacion']['fecha']) : ($resultadoImpacto['recuperacion']['estado']==='NO'?'Sin reprogramación propuesta':'Fecha pendiente de definir') }}</h3><p class="ui-muted text-sm mt-2">{{ $resultadoImpacto['recuperacion']['mensaje'] }}</p>@if(in_array($resultadoImpacto['recuperacion']['estado'],['PROPUESTA','POR_CONFIRMAR'],true))<p class="ui-muted text-sm mt-2"><strong>Modalidad:</strong> {{ ['POR_DEFINIR'=>'Por confirmar','PRESENCIAL'=>'Presencial','VIRTUAL'=>'Virtual'][$resultadoImpacto['recuperacion']['modalidad'] ?? 'POR_DEFINIR'] }}</p>@if($resultadoImpacto['recuperacion']['plan'] ?? null)<p class="ui-muted text-sm mt-2"><strong>Plan de recuperación:</strong> {{ $resultadoImpacto['recuperacion']['plan'] }}</p>@endif
@endif
@if($resultadoImpacto['recuperacion']['observacion'])<p class="ui-muted text-sm mt-2"><strong>Observación propuesta:</strong> {{ $resultadoImpacto['recuperacion']['observacion'] }}</p>@endif
@foreach($resultadoImpacto['recuperacion']['avisos'] as $aviso)<p class="ui-muted text-sm mt-3">{{ $aviso }}</p>@endforeach<div class="ga-impacto-materias">@foreach($resultadoImpacto['recuperacion']['cruces'] as $cruce)<article><div><strong>{{ $cruce['grupo'] }} · {{ $cruce['materia'] }}</strong><p>{{ $cruce['docente'] }}</p></div><span>{{ $cruce['horas'] }}</span></article>@endforeach</div></section>@endif
    </div>@endif
</article>
