<section class="pa-estudio" x-data="{mostrarEstudio:false}" wire:poll.15s.keep-alive="actualizar">
    <div><p class="ui-kicker">Consulta al Ministerio</p><h4 class="ui-title font-bold mt-2">Investigar el calendario {{ $anio }}</h4><p class="ui-muted text-xs mt-2">Buscamos fechas publicadas para Educación Regular de este año. Solo se aplican al borrador cuando tú las eliges.</p></div>
    <div class="flex gap-2 flex-wrap mt-3"><button type="button" class="ui-btn ui-btn-primary" wire:click="investigar" x-on:click="mostrarEstudio=true" wire:loading.attr="disabled" @disabled(in_array($estudio['estado']??'', ['EN_COLA','INVESTIGANDO'],true))><i class="ph-duotone ph-magnifying-glass" aria-hidden="true"></i>Consultar fuentes oficiales</button><button type="button" class="ui-btn ui-btn-secondary" wire:click="avisarme" wire:loading.attr="disabled" @disabled($suscrito)>{{ $suscrito?'Aviso activado':'Avisarme cuando esté listo' }}</button></div>
    @if($suscrito)<p class="ui-muted text-xs mt-2">Te avisaremos aquí cuando haya fechas disponibles o cuando vuelvas a abrir Gestión académica.</p>@endif
    @if($estudio)<div class="pa-estudio-resultado mt-3" role="status"><strong class="ui-title text-sm">{{ ['EN_COLA'=>'Estudio pendiente','INVESTIGANDO'=>'Revisando fuentes','SIN_CONEXION'=>'Pendiente de conexión','SIN_PUBLICACION'=>'Pendiente de publicación','FUENTE_NO_DISPONIBLE'=>'La fuente no responde','REVISION_REQUERIDA'=>'Necesita revisión','NO_DISPONIBLE'=>'Estudio pendiente','RESULTADO'=>'Fechas encontradas'][$estudio['estado']]??'Estudio pendiente' }}</strong><p class="ui-muted text-xs mt-2">{{ $estudio['mensaje'] }}</p>
        @if(($estudio['estado']??'')==='RESULTADO')
        <dl class="pa-estudio-fechas"><div><dt>Inicio de clases</dt><dd>{{ \Carbon\Carbon::parse($estudio['resultado']['inicio'])->format('d/m/Y') }}</dd></div><div><dt>Cierre curricular</dt><dd>{{ \Carbon\Carbon::parse($estudio['resultado']['cierre'])->format('d/m/Y') }}</dd></div></dl>
        <a class="ga-texto-primary underline text-xs" href="{{ $estudio['resultado']['url'] }}" target="_blank" rel="noopener noreferrer">{{ $estudio['resultado']['documento'] }} · Página {{ implode(', ', $estudio['resultado']['paginas']) }}</a><p class="ui-muted text-xs mt-2">Consulta realizada: {{ \Carbon\Carbon::createFromTimestamp($estudio['consultado'])->timezone(config('app.timezone'))->format('d/m/Y H:i') }}. Revisa posibles modificaciones y disposiciones locales.</p><button type="button" class="ui-btn ui-btn-secondary mt-3" wire:click="aplicar" wire:loading.attr="disabled">Usar estas fechas en el borrador</button>
        @else<p class="ui-muted text-xs mt-2">El pendiente se conserva al cerrar esta ventana. No modificamos las fechas registradas.</p>@endif
    </div>@endif
    <div x-show="mostrarEstudio && ['EN_COLA','INVESTIGANDO'].includes($wire.estudio.estado)" x-cloak x-transition.opacity class="pa-estudio-overlay"><div class="ui-card pa-estudio-modal" role="status" aria-live="polite"><i class="ph-duotone ph-magnifying-glass pa-estudio-pulso" aria-hidden="true"></i><h4 class="ui-title font-bold mt-3">Estamos estudiando el calendario {{ $anio }}</h4><p class="ui-muted text-sm mt-3">Revisamos las publicaciones del Ministerio y comprobamos que las fechas correspondan a este año.</p><button type="button" class="ui-btn ui-btn-secondary mt-4" x-on:click="mostrarEstudio=false">Seguir trabajando</button></div></div>
    <div wire:loading.delay wire:target="investigar" class="ui-muted text-xs mt-3" role="status">Registrando tu solicitud…</div>
</section>
