<div x-show="modalNueva" x-cloak x-transition.opacity.duration.180ms class="fixed inset-0 z-50 ga-overlay ga-modal-entorno">
    <section x-show="modalNueva" x-ref="modalGestion" role="dialog" aria-modal="true" aria-labelledby="academica-nueva-titulo" tabindex="-1" x-on:keydown.tab="focoModalAcademico($event, $el)" class="ga-modal-nueva" x-data="{init(){this.$watch('modalNueva',abierta=>{if(abierta){this.paso='datos';this.detallesBloqueo=false;this.estructuraAbierta=false;this.motivoPropuesta='';this.anotacionEstructura='';this.ajustePeriodos=false;this.mensajePropuesta='';this.seleccionBase=['Cursos y paralelos','Asignaturas y especialidades'];}});}, paso:'datos', detallesBloqueo:false, estructuraAbierta:false, seleccionBase:['Cursos y paralelos','Asignaturas y especialidades'], ajustePeriodos:false, motivoPropuesta:'', anotacionEstructura:'', mensajePropuesta:'', fechaLegible(valor){return valor?valor.split('-').reverse().join('/'):'Por definir';}, meses:['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'], agregarPropuesta(){const texto='Propuesta para '+anio+': base '+@js($gestionActiva['anio']??'por definir')+' ('+this.seleccionBase.join(', ')+'). '+this.anotacionEstructura.trim()+(this.ajustePeriodos?' Ajuste de trimestres: '+this.motivoPropuesta.trim():''); if(this.ajustePeriodos && this.motivoPropuesta.trim().length<10){this.mensajePropuesta='Explica el ajuste con al menos 10 caracteres.';return;} if((descripcion+' '+texto).trim().length>500){this.mensajePropuesta='La descripción admite 500 caracteres. Acorta el motivo o la nota antes de añadirlo.';return;} descripcion=(descripcion+' '+texto).trim();this.mensajePropuesta='Propuesta añadida a la descripción. Puedes editarla en Datos.';}}">
        <header class="ga-modal-cabecera"><div class="ga-identidad"><span class="ga-emblema"><i class="ph-duotone ph-calendar-plus" aria-hidden="true"></i></span><div><p class="ui-kicker">Preparación del ciclo anual</p><h2 id="academica-nueva-titulo" class="ui-title">Nueva gestión académica</h2><p class="ui-muted">Define el ciclo, revisa las fuentes y decide cómo prepararlo.</p></div></div><button type="button" class="ui-btn ui-btn-secondary" wire:click="cerrarModal" aria-label="Cerrar nueva gestión"><i class="ph-duotone ph-x" aria-hidden="true"></i>Cerrar</button></header>
        <nav class="ga-modal-pasos" aria-label="Pasos para preparar una gestión">@foreach(['datos'=>['1','Datos del ciclo'],'calendario'=>['2','Fechas y fuentes'],'preparacion'=>['3','Base y trimestres']] as $clave=>[$numero,$titulo])<button type="button" x-on:click="paso='{{ $clave }}'" :aria-current="paso==='{{ $clave }}'?'step':null"><span>{{ $numero }}</span>{{ $titulo }}</button>@endforeach</nav>
        <form wire:submit="crearGestionAcademica" class="ga-modal-form">
            <div class="ga-modal-cuerpo">
                <section class="ga-bloqueo-plan" x-show="bloqueadoPorPlanificacionAnticipada" x-transition.opacity.duration.150ms aria-label="Ventana de planificación">
                    <div class="ga-bloqueo-icono"><i class="ph-duotone ph-lock-key" aria-hidden="true"></i></div><div><p class="ui-kicker">Preparación disponible desde noviembre</p><h3 class="ui-title">Puedes revisar la propuesta; el registro espera su etapa</h3><p class="ui-muted">La gestión <strong x-text="gestionActivaAnio"></strong> sigue en curso. La siguiente se prepara durante noviembre y diciembre.</p><div class="ga-ventana-plan"><span><i class="ph-duotone ph-map-pin" aria-hidden="true"></i><span x-text="meses[mesActual-1]+' · ahora'"></span></span><i class="ph-duotone ph-arrow-right" aria-hidden="true"></i><span><i class="ph-duotone ph-calendar-check" aria-hidden="true"></i>Noviembre y diciembre · planificación</span></div><button type="button" class="ui-link" x-on:click="detallesBloqueo=!detallesBloqueo" :aria-expanded="detallesBloqueo" aria-controls="academica-bloqueo-detalle">¿Cómo continúo?</button><p id="academica-bloqueo-detalle" x-show="detallesBloqueo" x-cloak x-transition.opacity class="ui-muted mt-2">Revisa las fechas y la base que te gustaría reutilizar. Cuando corresponda registrar el ciclo, comienza como Planificada y revisa el cierre anterior antes de activarlo. Esta ventana pertenece al flujo institucional.</p></div>
                </section>
                <div class="ga-modal-grilla">
                    <div class="ga-modal-trabajo">
                        <section x-show="paso==='datos'" x-transition.opacity.duration.150ms class="ga-form-seccion"><header><p class="ui-kicker">1 · Identificación</p><h3 class="ui-title">¿Qué ciclo vamos a preparar?</h3><p class="ui-muted">La vista previa se actualiza con lo que escribes.</p></header><div class="ga-campos">
                            <div><label for="nueva-gestion-anio" class="ui-label">Año de gestión *</label><input id="nueva-gestion-anio" type="number" x-model="anio" min="2020" max="2100" required class="ui-input" :aria-invalid="!anioValido || aniosRegistrados.includes(parseInt(anio))" /><p class="ui-error" x-show="!anioValido" x-cloak>El año debe estar entre 2020 y 2100.</p><p class="ui-error" x-show="aniosRegistrados.includes(parseInt(anio))" x-cloak>Ese año ya tiene una gestión registrada.</p><x-input-error for="form.anio" /></div>
                            <div><label for="nueva-gestion-nombre" class="ui-label">Nombre del ciclo *</label><input id="nueva-gestion-nombre" type="text" x-model="nombre" minlength="5" maxlength="150" required class="ui-input" /><p class="ui-error" x-show="nombre && !nombreValido" x-cloak>Escribe al menos 5 caracteres.</p><x-input-error for="form.nombre" /></div>
                            <div><label for="nueva-gestion-modalidad" class="ui-label">Modalidad *</label><input id="nueva-gestion-modalidad" type="text" x-model="modalidad" minlength="3" maxlength="150" required class="ui-input" /><x-input-error for="form.modalidad" /></div>
                            <x-selector-institucional enlace="estado" identificador="academica-estado-inicial" etiqueta="Estado inicial" :opciones="collect($estadosGestion)->map(fn($etiqueta,$valor)=>['valor'=>$valor,'etiqueta'=>$etiqueta])->values()->all()" />
                            <p class="ui-error ga-campo-ancho" x-show="bloqueadoPorGestionActivaDuplicada" x-cloak>Ya hay una gestión activa. Prepara la siguiente como Planificada.</p>
                            <div class="ga-campo-ancho"><label for="nueva-gestion-descripcion" class="ui-label">Descripción y motivos institucionales</label><textarea id="nueva-gestion-descripcion" x-model="descripcion" maxlength="500" rows="4" class="ui-input" placeholder="Explica el propósito del ciclo y cualquier cambio que deba quedar documentado."></textarea><div class="ga-ayuda-contador"><span>El motivo acompañará la descripción en la bitácora al registrar.</span><span x-text="(descripcion||'').length+'/500'"></span></div><x-input-error for="form.descripcion" /></div>
                        </div></section>
                        <section x-show="paso==='calendario'" x-cloak x-transition.opacity.duration.150ms class="ga-form-seccion"><header><p class="ui-kicker">2 · Calendario y respaldo</p><h3 class="ui-title">¿Cuándo comienzan y terminan las clases?</h3><p class="ui-muted">La publicación del Ministerio respalda el calendario. Los descansos y feriados se revisan aparte.</p></header><div class="ga-campos" wire:key="fechas-nueva-gestion-{{ $form['anio'] }}">
                            <x-calendario-institucional modelo="form.fecha_inicio" identificador="nueva-gestion-inicio" etiqueta="Inicio de clases" :minimo="((int)$form['anio']>=2020 && (int)$form['anio']<=2100 ? $form['anio'] : now()->year).'-01-01'" :maximo="((int)$form['anio']>=2020 && (int)$form['anio']<=2100 ? $form['anio'] : now()->year).'-12-31'" :requerido="true" />
                            <x-calendario-institucional modelo="form.fecha_fin" identificador="nueva-gestion-fin" etiqueta="Cierre curricular previsto" :minimo="((int)$form['anio']>=2020 && (int)$form['anio']<=2100 ? $form['anio'] : now()->year).'-01-01'" :maximo="((int)$form['anio']>=2020 && (int)$form['anio']<=2100 ? $form['anio'] : now()->year).'-12-31'" :requerido="true" />
                            <p class="ui-error ga-campo-ancho" x-show="fechaInicio && fechaFin && !fechaFinValida" x-cloak>El cierre debe ser posterior al inicio y pertenecer al año seleccionado.</p>
                        </div>
                        @include('livewire.admin.academica.fuentes-nueva-gestion')
                        <div class="ga-nota-fuente"><i class="ph-duotone ph-book-open" aria-hidden="true"></i><div><strong>Fuente de las fechas propuestas</strong><p>{{ $fuenteFechasAplicadas['fuente'] ?? ($fechasSugeridas['fuente'] ?? 'Confirma la normativa vigente.') }}</p>@if($fuenteFechasAplicadas['url'] ?? ($fechasSugeridas['url_fuente'] ?? null))<a class="ui-link" href="{{ $fuenteFechasAplicadas['url'] ?? $fechasSugeridas['url_fuente'] }}" target="_blank" rel="noopener noreferrer">Consultar documento oficial</a>@endif</div></div>
                        </section>
                        <section x-show="paso==='preparacion'" x-cloak x-transition.opacity.duration.150ms class="ga-form-seccion"><header><p class="ui-kicker">3 · Continuidad y adecuaciones</p><h3 class="ui-title">Una base conocida, adaptada al nuevo ciclo</h3><p class="ui-muted">Revisa el alcance antes de reutilizar la estructura o proponer cambios.</p></header>
                        @include('livewire.admin.academica.feriados-anuales')
                        <article class="ga-preparacion-card"><header><span class="ga-icono-suave"><i class="ph-duotone ph-tree-structure" aria-hidden="true"></i></span><div><h4 class="ui-title">Preparar como la gestión anterior</h4><p class="ui-muted">Base de consulta: {{ $gestionActiva['nombre'] ?? 'Sin gestión activa disponible' }}.</p></div></header><p class="ui-muted">La propuesta podrá conservar cursos y paralelos, asignaturas y especialidades, y la organización horaria que selecciones. Las asignaciones docentes y las fechas necesitan revisión para el nuevo año.</p><button type="button" class="ui-btn ui-btn-secondary" x-on:click="estructuraAbierta=!estructuraAbierta" :aria-expanded="estructuraAbierta" aria-controls="nueva-base-detalle"><i class="ph-duotone ph-sliders-horizontal" aria-hidden="true"></i>Personalizar la propuesta</button>
                        <div id="nueva-base-detalle" x-show="estructuraAbierta" x-cloak x-transition.opacity><div class="ga-opciones-base">@foreach(['Cursos y paralelos','Asignaturas y especialidades','Organización horaria'] as $opcion)<label><input type="checkbox" x-model="seleccionBase" value="{{ $opcion }}" /><span>{{ $opcion }}</span></label>@endforeach</div><label for="nueva-base-nota" class="ui-label">¿Qué conservarías o cambiarías?</label><textarea id="nueva-base-nota" x-model="anotacionEstructura" maxlength="250" rows="3" class="ui-input" placeholder="Por ejemplo: conservar los paralelos y revisar horarios por turno."></textarea></div>
                        <div class="ga-preview-base"><span><strong>{{ $gestionActiva['planes_asignatura'] ?? 0 }}</strong> planes de asignatura</span><span><strong>{{ $gestionActiva['planes_especialidad'] ?? 0 }}</strong> planes técnicos</span><span><strong>{{ $gestionActiva['horarios'] ?? 0 }}</strong> horarios registrados</span></div><p class="ga-limite-propuesta"><i class="ph-duotone ph-info" aria-hidden="true"></i>Esta selección documenta la propuesta. La copia todavía requiere una operación institucional validada. Inscripciones, notas, asistencia e historial se mantienen en su gestión de origen.</p></article>
                        <article class="ga-preparacion-card"><header><span class="ga-icono-suave"><i class="ph-duotone ph-calendar-check" aria-hidden="true"></i></span><div><h4 class="ui-title">Trimestres: qué se conserva y qué se prepararía</h4><p class="ui-muted">Una vista previa para explicar cada adecuación.</p></div></header>
                            <div class="ga-preview-periodos">@forelse($periodosSugeridos as $periodo)<div><span>{{ $periodo['orden'] }}</span><div><strong>{{ $periodo['nombre'] }}</strong><p>{{ $formatDate($periodo['fecha_inicio']) }} — {{ $formatDate($periodo['fecha_fin']) }}</p><small>{{ $periodo['dias_habiles_referencia'] }} días de referencia · propuesta</small>@php($periodoBase=collect($periodos)->firstWhere('orden',$periodo['orden']))@if($periodoBase)<p class="ga-periodo-base">Base {{ $gestionSeleccionada['anio']??'' }}: {{ $formatDate($periodoBase['fecha_inicio']) }} — {{ $formatDate($periodoBase['fecha_fin']) }}</p>@endif</div></div>@empty<p class="ui-muted">Selecciona un año válido para consultar la propuesta.</p>@endforelse</div>
                            <label class="ga-opcion-periodos"><input type="checkbox" x-model="crearPeriodos" :disabled="bloqueadoPorPlanificacionAnticipada || parseInt(anio)!==2026 || @js(count($periodos)>0)" /><span><strong>Crear los tres periodos base si el catálogo está vacío</strong><small>Se prepararían Primer, Segundo y Tercer trimestre. El registro existente conserva nombres y órdenes; esta opción no reemplaza periodos ni configura sus fechas.</small></span></label>
                            <p class="ga-limite-propuesta">{{ count($periodos) }} periodos en la gestión de consulta. Para modificar su configuración, revisa Trimestres con la norma y las fechas de ese año. La incorporación inicial y el registro de otra gestión son operaciones distintas.</p>
                            <label class="ga-opciones-base"><input type="checkbox" x-model="ajustePeriodos" /><span>Quiero explicar una adecuación a la propuesta</span></label><div x-show="ajustePeriodos" x-cloak x-transition.opacity><label for="nueva-periodos-motivo" class="ui-label">Motivo y disposición que respalda el cambio *</label><textarea id="nueva-periodos-motivo" x-model="motivoPropuesta" minlength="10" maxlength="250" rows="3" class="ui-input" placeholder="Explica qué cambiaría, por qué y qué documento debe revisarse."></textarea><p class="ui-muted text-xs mt-2">El motivo se añade a la descripción. Las fechas de los trimestres se validan y configuran en su apartado.</p></div>
                        </article><button type="button" class="ui-btn ui-btn-secondary" x-on:click="agregarPropuesta()">Añadir propuesta a la descripción</button><p class="ui-muted text-sm" x-show="mensajePropuesta" x-text="mensajePropuesta" aria-live="polite"></p>
                        </section>
                    </div>
                    <aside class="ga-preview-ciclo"><p class="ui-kicker">Tu ciclo en preparación</p><h3 class="ui-title" x-text="nombre || 'Nombre por definir'"></h3><span class="ui-badge-info" x-text="estado"></span><dl><div><dt>Año</dt><dd x-text="anio || 'Por definir'"></dd></div><div><dt>Modalidad</dt><dd x-text="modalidad || 'Por definir'"></dd></div><div><dt>Inicio de clases</dt><dd x-text="fechaLegible(fechaInicio)"></dd></div><div><dt>Cierre curricular</dt><dd x-text="fechaLegible(fechaFin)"></dd></div></dl><div class="ga-preview-duracion"><strong>200</strong><span>días efectivos de clases por planificar</span></div><div class="ga-preview-estado" :data-listo="puedeGuardarGestion"><i class="ph-duotone" :class="puedeGuardarGestion?'ph-check-circle':'ph-shield-check'" aria-hidden="true"></i><span x-text="estadoFormularioTexto"></span></div>
                        <x-plegable-institucional class="ga-revision-detalle" icono="ph-shield-check"><x-slot:titulo>Ver qué necesitamos revisar</x-slot:titulo><p class="ui-muted mt-2">{{ $analisisCreacion['mensaje'] ?? 'Completa los datos para revisar.' }}</p>@foreach(['bloqueos'=>'Debe corregirse','advertencias'=>'Revisar antes de guardar','sugerencias'=>'Orientación'] as $categoria=>$titulo)@if(!empty($analisisCreacion[$categoria]))<h4>{{ $titulo }}</h4><ul>@foreach($analisisCreacion[$categoria] as $aviso)<li>{{ $aviso }}</li>@endforeach</ul>@endif@endforeach</x-plegable-institucional><p class="ui-muted text-xs mt-3">La revisión protege tus datos y comprueba las condiciones antes de registrar.</p>
                    </aside>
                </div>
            </div>
            <footer class="ga-modal-pie"><div><p class="ui-title text-sm" x-text="puedeGuardarGestion?'Listo para revisión final':'La propuesta aún necesita revisión'"></p><p class="ui-muted text-xs">Registrar crea el ciclo. Reutilizar su estructura requiere la revisión indicada.</p></div><div><button type="button" class="ui-btn ui-btn-secondary" wire:click="cerrarModal">Cancelar</button><button type="submit" class="ui-btn ui-btn-primary" :disabled="!puedeGuardarGestion" wire:loading.attr="disabled" wire:target="crearGestionAcademica"><i class="ph-duotone ph-check" aria-hidden="true"></i><span wire:loading.remove wire:target="crearGestionAcademica">Registrar gestión</span><span wire:loading wire:target="crearGestionAcademica">Validando…</span></button></div></footer>
        </form>
    </section>
</div>
