<section class="ga-centro" wire:key="academica-centro-{{ $vista }}">
@if($vista === 'alertas')
    <article class="ui-card">
        <header><div><p class="ui-kicker">Revisión del expediente</p><h2 class="ui-title mt-1">Lo que necesita tu atención</h2><p class="ui-muted text-sm mt-2">Cada aviso explica su causa y te lleva al lugar donde puedes revisarlo.</p></div><span class="ui-badge-warning">{{ count($panelAcademico['alertas']) + count($avisosSesion) }} avisos</span></header>
        <div class="ga-cifras"><div><strong>{{ count($panelAcademico['anomalias']) }}</strong><span>Revisiones de consistencia y documentación</span></div><div><strong>{{ count($panelAcademico['alertas'])-count($panelAcademico['anomalias']) }}</strong><span>Revisiones de planificación y normativa</span></div><div><strong>{{ count($avisosSesion) }}</strong><span>Avisos de esta sesión</span></div></div>
        <p class="ui-muted text-xs">Una anomalía señala datos que necesitan revisión. Su causa debe confirmarse; no atribuye responsabilidad ni determina riesgo académico.</p>
        @php
            $avisosPorApartado=collect(array_merge($panelAcademico['alertas'],$avisosSesion))->groupBy('vista');
            $nombresApartados=['calendario'=>'Calendario','seguimiento'=>'Seguimiento','periodos'=>'Trimestres','inscripciones'=>'Inscripciones','general'=>'Resumen','gestiones'=>'Gestiones','alertas'=>'Revisión de casos'];
        @endphp
        @if($avisosPorApartado->isNotEmpty())
        <div class="ga-mapa-avisos" role="group" aria-label="Mapa de avisos por apartado"><div class="ga-mapa-centro"><i class="ph-duotone ph-intersect" aria-hidden="true"></i><strong>{{ $avisosPorApartado->sum(fn($casos)=>$casos->count()) }} avisos</strong><span>Ámbitos de revisión</span></div><div class="ga-mapa-ramas">@foreach($avisosPorApartado as $apartado=>$casos)<button type="button" wire:click="cambiarVista(@js($apartado))"><strong>{{ $casos->count() }}</strong><span>{{ $nombresApartados[$apartado]??'Revisar el caso' }}</span><i class="ph-duotone ph-arrow-right" aria-hidden="true"></i></button>@endforeach</div></div>
        @endif
        <div class="ga-avisos" aria-live="polite">
        @forelse(array_merge($panelAcademico['alertas'], $avisosSesion) as $aviso)
            <article class="ga-aviso" data-nivel="{{ $aviso['nivel'] }}"><i class="ph-duotone ph-warning-circle" aria-hidden="true"></i><div><h3 class="ui-title">{{ $aviso['titulo'] }}</h3><p>{{ $aviso['mensaje'] }}</p><button type="button" class="ui-btn ui-btn-secondary" wire:click="cambiarVista('{{ $aviso['vista'] }}')">Revisar {{ ['calendario'=>'calendario', 'periodos'=>'trimestres', 'inscripciones'=>'inscripciones'][$aviso['vista']] ?? 'el caso' }} <i class="ph-duotone ph-arrow-right" aria-hidden="true"></i></button></div></article>
        @empty
            <div class="ga-vacio"><i class="ph-duotone ph-check-circle" aria-hidden="true"></i><h3 class="ui-title">Sin avisos en las consultas disponibles</h3><p>Continúa revisando el expediente. Este resumen no sustituye la validación de cierre.</p></div>
        @endforelse
        </div>
        <p class="ui-muted text-xs mt-4">Los errores de acciones de esta pantalla permanecen visibles durante esta sesión. Los pendientes se calculan a partir de los registros actuales.</p>
    </article>
@elseif($vista === 'seguimiento')
    @include('livewire.admin.academica.trayectoria')
    <article class="ui-card"><header><div><p class="ui-kicker">Observaciones del calendario</p><h2 class="ui-title mt-1">Recuperaciones de esta gestión</h2><p class="ui-muted text-sm mt-2">{{ $panelAcademico['conteos']['recuperaciones'] ?? 0 }} recuperaciones confirmadas o finalizadas. Las propuestas pendientes conservan su estado y quedan fuera de este total; una fecha confirmada todavía puede estar por realizarse.</p></div></header><div class="ga-historial mt-3">@forelse($panelAcademico['recuperaciones'] ?? [] as $recuperacion)<article><header><h3 class="ui-title">{{ $recuperacion['nombre'] }}</h3><span class="ui-badge-info">{{ $recuperacion['estado'] }}</span></header><time>{{ $formatDate($recuperacion['inicio']) }} · {{ $recuperacion['hora_inicio'] ?: 'Horario por confirmar' }}@if($recuperacion['hora_fin'])–{{ $recuperacion['hora_fin'] }}@endif</time><p class="ui-muted text-sm mt-2">{{ $recuperacion['motivo'] ?: 'Observación pendiente.' }}</p></article>@empty<p class="ui-muted text-sm">Todavía no hay recuperaciones registradas en el calendario de esta gestión.</p>@endforelse</div></article>
    <article class="ui-card"><header><div><p class="ui-kicker">Continuidad del estudiante</p><h2 class="ui-title mt-1">Observaciones, retiros y novedades</h2><p class="ui-muted text-sm mt-2">Revisa los movimientos de esta gestión. La ficha del estudiante conserva su trayectoria completa.</p></div>@can('Estudiantes')<a class="ui-btn ui-btn-secondary" href="{{ route('admin.gestion-estudiantes') }}">Abrir estudiantes <i class="ph-duotone ph-arrow-right" aria-hidden="true"></i></a>@endcan</header>
        <div class="ga-filtros"><div><label for="academica-buscar-seguimiento" class="ui-label">Buscar en el seguimiento</label><input id="academica-buscar-seguimiento" class="ui-input mt-2" type="search" wire:model.live.debounce.400ms="busquedaSeguimiento" placeholder="Nombre, motivo u observación…" /></div><x-selector-institucional modelo="filtroSeguimiento" identificador="academica-tipo-movimiento" etiqueta="Tipo de movimiento" :opciones="array_merge([['valor'=>'','etiqueta'=>'Todos los movimientos']],collect($panelAcademico['movimientos'])->pluck('tipo')->unique()->map(fn($tipo)=>['valor'=>$tipo,'etiqueta'=>$tipo])->values()->all())" /></div>
        @php
            $movimientosVisibles = collect($panelAcademico['movimientos'])->filter(function(array $movimiento) use ($filtroSeguimiento, $busquedaSeguimiento) {
                return (!$filtroSeguimiento || $movimiento['tipo'] === $filtroSeguimiento) && (!$busquedaSeguimiento || str_contains(mb_strtolower($movimiento['nombre'].' '.$movimiento['motivo'].' '.$movimiento['observacion']), mb_strtolower(trim($busquedaSeguimiento))));
            });
        @endphp
        <p class="ui-muted text-xs">{{ $movimientosVisibles->count() }} movimientos en la selección</p><div class="ga-historial">
            @forelse($movimientosVisibles->take(60) as $movimiento)<article><header><div><h3 class="ui-title">{{ $movimiento['nombre'] }}</h3><p>{{ $movimiento['tipo'] }} · {{ $movimiento['estado'] }}</p></div><time>{{ $formatDate($movimiento['fecha']) }}</time></header><p class="mt-2"><strong>Motivo:</strong> {{ $movimiento['motivo'] ?: 'Pendiente de descripción.' }}</p>@if($movimiento['observacion'])<p class="mt-2">{{ $movimiento['observacion'] }}</p>@endif</article>@empty<div class="ga-vacio"><i class="ph-duotone ph-path" aria-hidden="true"></i><h3 class="ui-title">Sin movimientos en esta selección</h3><p>{{ $busquedaSeguimiento || $filtroSeguimiento?'Amplía los filtros para revisar otros casos.':'No hay observaciones, retiros ni novedades registrados para esta gestión.' }}</p></div>@endforelse
        </div>@if($movimientosVisibles->count()>60)<p class="ui-muted text-sm mt-4">Se muestran los 60 más recientes. Filtra por nombre o descarga el seguimiento completo.</p>@endif
    </article>
@elseif($vista === 'comparativas')
    @include('livewire.admin.academica.trayectoria')
    <article class="ui-card"><p class="ui-kicker">Contexto para planificar</p><h2 class="ui-title mt-1">Distribución y comparativas</h2><p class="ui-muted text-sm mt-2">Los gráficos usan inscripciones reales de la gestión seleccionada; incluyen sus diferentes estados.</p>
        @php
            $cursosAgrupados=collect($panelAcademico['cursos'])->groupBy('curso')->map(fn($grupos,$nombre)=>['nombre'=>$nombre,'cantidad'=>$grupos->sum('cantidad')])->values()->all();
            $paralelosVisibles=collect($panelAcademico['cursos'])->filter(fn($curso)=>$curso['curso']===$filtroCursoComparativa);
        @endphp
        <div class="ga-grilla ga-grilla-igual mt-5"><section><h3 class="ui-title">Distribución por curso</h3><p class="ui-muted text-xs mt-2 mb-3">El tamaño representa las inscripciones. Selecciona un curso para ver sus paralelos.</p><x-mosaico-institucional :datos="$cursosAgrupados" modelo="filtroCursoComparativa" campo-valor="cantidad" unidad="" unidad-accesible="inscripciones" descripcion-accion="Consultar los paralelos de este curso." mensaje-vacio="Todavía no hay inscripciones para representar." etiqueta="Inscripciones por curso" />
        @if($paralelosVisibles->isNotEmpty())<div class="ga-paralelos"><header><h3 class="ui-title">{{ $filtroCursoComparativa }} · Paralelos</h3><button type="button" class="ui-btn ui-btn-secondary" wire:click="$set('filtroCursoComparativa','')">Cerrar detalle</button></header><div class="ga-tabla-contenedor"><table class="ga-tabla"><thead><tr><th>Grupo</th><th>Inscripciones</th></tr></thead><tbody>@foreach($paralelosVisibles as $curso)<tr><td>{{ $curso['nombre'] }}</td><td>{{ $curso['cantidad'] }}</td></tr>@endforeach</tbody></table></div></div>@endif</section>
        <section><h3 class="ui-title">Composición de las inscripciones</h3>@php
            $colores=['var(--ui-primary)','var(--ui-info)','var(--ui-violet)','var(--ui-warning)','var(--ui-danger)'];$totalEstados=array_sum(array_column($panelAcademico['inscripciones'],'cantidad'));$paradas=[];$porcentaje=0;
            foreach($panelAcademico['inscripciones'] as $i=>$estado){$siguiente=$porcentaje+100*$estado['cantidad']/max(1,$totalEstados);$paradas[]=$colores[$i%count($colores)].' '.$porcentaje.'% '.$siguiente.'%';$porcentaje=$siguiente;}
        @endphp
            @if($totalEstados)<div class="ga-desglose"><div class="ga-anillo" role="img" aria-label="{{ collect($panelAcademico['inscripciones'])->map(fn($e)=>$e['nombre'].': '.$e['cantidad'])->implode(', ') }}" style="background:conic-gradient({{ implode(',',$paradas) }})"><div><strong>{{ $totalEstados }}</strong><small>Inscripciones</small></div></div><ul class="ga-leyenda">@foreach($panelAcademico['inscripciones'] as $i=>$estado)<li><span style="background:{{ $colores[$i%count($colores)] }}"></span>{{ $estado['nombre'] }} <strong>{{ $estado['cantidad'] }}</strong></li>@endforeach</ul></div>@else<p class="ui-muted text-sm mt-3">Sin datos para representar la composición.</p>@endif
            <h3 class="ui-title mt-6">Tipos de novedades</h3>@forelse($panelAcademico['novedades'] as $novedad)<p class="ui-muted text-sm mt-2">{{ $novedad['nombre'] }} · <strong>{{ $novedad['cantidad'] }}</strong></p>@empty<p class="ui-muted text-sm mt-2">Todavía no hay novedades registradas.</p>@endforelse
        </section></div>
    </article>
    <article class="ui-card"><header><div><p class="ui-kicker">Evolución histórica</p><h2 class="ui-title mt-1">Comparación entre gestiones</h2></div></header><x-comparativa-academica :datos="$panelAcademico['comparativas']" :anio="$gestionSeleccionada['anio']??null" /></article>
@elseif($vista === 'documentacion')
    <div class="ga-grilla ga-grilla-igual"><article class="ui-card"><p class="ui-kicker">Expediente a mano</p><h2 class="ui-title mt-1">Descargar datos de esta gestión</h2><p class="ui-muted text-sm mt-2">Obtén un CSV compatible con hojas de cálculo. Incluye los registros consultados y sus revisiones pendientes.</p><form wire:submit="descargarExpediente" class="ga-formulario"><x-selector-institucional modelo="tipoDescarga" identificador="academica-descarga" etiqueta="Contenido del archivo" :opciones="[['valor'=>'RESUMEN','etiqueta'=>'Resumen y distribución por cursos'],['valor'=>'CALENDARIO','etiqueta'=>'Calendario y disposiciones pendientes'],['valor'=>'SEGUIMIENTO','etiqueta'=>'Observaciones, retiros y novedades'],['valor'=>'COMPLETA','etiqueta'=>'Expediente de consulta completo']]" /><button type="submit" class="ui-btn ui-btn-primary" wire:loading.attr="disabled" wire:target="descargarExpediente" @disabled(!$gestionSeleccionada)><i class="ph-duotone ph-download-simple" aria-hidden="true"></i><span wire:loading.remove wire:target="descargarExpediente">Descargar CSV</span><span wire:loading wire:target="descargarExpediente">Preparando archivo…</span></button></form><p class="ui-muted text-xs mt-4">El expediente de consulta reúne resúmenes, calendario y movimientos. Los informes PDF y respaldos institucionales se gestionan en sus apartados.</p></article>
        <article class="ui-card"><p class="ui-kicker">Normativa y respaldo</p><h2 class="ui-title mt-1">Documentación de referencia</h2>@if((int)($gestionSeleccionada['anio']??0)===2026)<a class="ga-enlace mt-4" href="{{ \App\Support\Academico\PanelGestionAcademica::NORMA_2026 }}" target="_blank" rel="noopener noreferrer"><i class="ph-duotone ph-file-pdf" aria-hidden="true"></i><div><strong>RM 0001/2026 · Educación Regular</strong><span>Artículo 3: tres trimestres y 200 días efectivos de trabajo curricular.</span></div></a>@else<p class="ui-muted text-sm mt-4">Confirma la norma vigente de la gestión seleccionada.</p>@endif<button type="button" class="ui-btn ui-btn-secondary mt-4" wire:click="cambiarVista('calendario')">Ver fuentes de los eventos</button><button type="button" class="ui-btn ui-btn-secondary mt-4" wire:click="cambiarVista('reportes')">Consultar respaldos de gestión</button></article></div>
    <article class="ui-card"><h2 class="ui-title">Conectar con el flujo académico</h2><p class="ui-muted text-sm mt-2">Cada acceso conserva los permisos de su módulo. Los reportes institucionales ofrecen sus propios filtros y alcance.</p><div class="ga-enlaces">
        @foreach([['Estudiantes','admin.gestion-estudiantes','Estudiantes y trayectorias','Ficha completa e historial de cada estudiante','ph-student'],['Docentes','admin.gestion-docentes','Docentes','Fichas, horarios y carga académica','ph-chalkboard-teacher'],['Gestion_Academica','admin.calendario','Calendario institucional','Vista de eventos y tareas del calendario','ph-calendar-dots'],['Periodo_Evaluacion','admin.periodo-evaluacion','Periodos de evaluación','Configuración validada de los trimestres','ph-calendar-check'],['Reportes_Academicos','admin.reportes-academicos','Reportes académicos','Indicadores e informes con sus filtros','ph-chart-line'],['Reportes_Administrativos','admin.reportes-administrativos','Reportes administrativos','Documentación y resúmenes institucionales','ph-files']] as [$permiso,$ruta,$titulo,$detalle,$icono])
        @can($permiso)@if(\Illuminate\Support\Facades\Route::has($ruta))<a class="ga-enlace" href="{{ route($ruta, $ruta==='admin.calendario' ? ['gestion'=>$gestionSeleccionada['id']??null] : []) }}"><i class="ph-duotone {{ $icono }}" aria-hidden="true"></i><div><strong>{{ $titulo }}</strong><span>{{ $detalle }}</span></div></a>@endif@endcan
        @endforeach
    </div></article>
@endif
</section>
