<article class="ui-card" x-data="{ detalleTrayectoria:false }">
    <header><div><p class="ui-kicker">Trayectoria de los registros</p><h2 class="ui-title mt-1">Cómo se incorporaron las inscripciones</h2><p class="ui-muted text-sm mt-2">Evolución acumulada según las fechas registradas. Este gráfico describe incorporaciones, no rendimiento ni promoción.</p></div><button type="button" class="ui-btn ui-btn-secondary" x-on:click="detalleTrayectoria=!detalleTrayectoria" :aria-expanded="detalleTrayectoria" aria-controls="academica-fechas-inscripcion">Ver fechas</button></header>
    @php
        $puntos=collect($panelAcademico['trayectoria']); $maximo=max(1,$puntos->max('acumulado')??0);
        $primero=$puntos->first();$ultimo=$puntos->last();$coordenadas=[];
        $rango=$primero && $ultimo ? max(1,\Carbon\Carbon::parse($primero['fecha'])->diffInDays(\Carbon\Carbon::parse($ultimo['fecha']))) : 1;
        foreach($puntos as $punto){$x=count($puntos)===1?360:36+648*\Carbon\Carbon::parse($primero['fecha'])->diffInDays(\Carbon\Carbon::parse($punto['fecha']))/$rango;$y=190-155*$punto['acumulado']/$maximo;$coordenadas[]=['x'=>$x,'y'=>$y]+$punto;}
    @endphp
    @if($puntos->isNotEmpty())<div class="ga-trayectoria-grafico"><svg viewBox="0 0 720 230" role="img" aria-label="Inscripciones acumuladas: {{ $puntos->count() }} fechas; total {{ $ultimo['acumulado'] }}"><line x1="36" y1="190" x2="684" y2="190" class="ga-grafico-rejilla"/><line x1="36" y1="112" x2="684" y2="112" class="ga-grafico-rejilla"/><line x1="36" y1="35" x2="684" y2="35" class="ga-grafico-rejilla"/><text x="4" y="39" class="ga-grafico-texto">{{ $maximo }}</text><text x="4" y="194" class="ga-grafico-texto">0</text>@if(count($coordenadas)>1)<polyline points="{{ collect($coordenadas)->map(fn($p)=>$p['x'].','.$p['y'])->implode(' ') }}" class="ga-grafico-linea"/>@endif @foreach($coordenadas as $p)<circle cx="{{ $p['x'] }}" cy="{{ $p['y'] }}" r="5" class="ga-grafico-punto"><title>{{ $formatDate($p['fecha']) }} · {{ $p['inscripciones'] }} incorporaciones · {{ $p['acumulado'] }} acumuladas</title></circle>@endforeach<text x="36" y="218" class="ga-grafico-texto">{{ $formatDate($primero['fecha']) }}</text><text x="684" y="218" text-anchor="end" class="ga-grafico-texto">{{ $formatDate($ultimo['fecha']) }}</text></svg></div>@if($puntos->count()===1)<p class="ui-muted text-xs">Todas las inscripciones con fecha se concentran en un solo día registrado. Por eso se muestra un punto, sin inventar una tendencia.</p>@endif
        <div id="academica-fechas-inscripcion" x-show="detalleTrayectoria" x-cloak x-transition.opacity.duration.140ms class="ga-tabla-contenedor"><table class="ga-tabla"><thead><tr><th>Fecha registrada</th><th>Incorporaciones</th><th>Acumuladas</th></tr></thead><tbody>@foreach($puntos as $p)<tr><td>{{ $formatDate($p['fecha']) }}</td><td>{{ $p['inscripciones'] }}</td><td>{{ $p['acumulado'] }}</td></tr>@endforeach</tbody></table></div>
    @else<div class="ga-vacio"><i class="ph-duotone ph-chart-line" aria-hidden="true"></i><h3 class="ui-title">Faltan fechas para representar la evolución</h3><p>Las inscripciones se conservan en el resumen; confirma sus fechas de registro para interpretar su trayectoria.</p></div>@endif
</article>
