<button type="button" class="ui-btn ui-btn-secondary mt-3" x-on:click="$refs.vistaUniversidad.showModal()">Ver vista previa</button>
<template x-teleport="body">
    <dialog x-ref="vistaUniversidad" class="ga-preview-universidad" aria-labelledby="caso-vista-universidad-titulo" x-on:close="mostrarPagina=false">
        <header class="ga-modal-cabecera"><div><p class="ui-kicker">Revisión de la institución</p><h2 id="caso-vista-universidad-titulo" class="ui-title">{{ $revisionUniversidad['institucion'] ?: 'Página institucional por revisar' }}</h2></div><button type="button" class="ui-btn ui-btn-secondary" x-on:click="$refs.vistaUniversidad.close()" aria-label="Cerrar vista previa de universidad"><i class="ph-duotone ph-x" aria-hidden="true"></i>Cerrar</button></header>
        <div class="ga-modal-cuerpo">
            <span class="{{ $revisionUniversidad['verificada']?'ui-badge-success':'ui-badge-info' }}">{{ $revisionUniversidad['verificada']?'Página revisada':'Contenido por comprobar' }}</span>
            <p class="ui-muted text-sm mt-3">{{ $revisionUniversidad['mensaje'] }}</p>
            <p class="text-sm mt-3"><strong>Página institucional:</strong> <a class="ui-link" href="{{ $revisionUniversidad['url'] }}" target="_blank" rel="noopener noreferrer">{{ $revisionUniversidad['url'] }}</a></p>
            @if($revisionUniversidad['original']!==$revisionUniversidad['url'])<p class="ui-muted text-xs mt-2">El enlace de la carrera se agrupó bajo su universidad. Revisamos el portal institucional para mantener sus carreras en un mismo expediente.</p>@endif
            @if($revisionUniversidad['resumen'])<x-plegable-institucional class="ga-preparacion-card mt-4" icono="ph-file-text"><x-slot:titulo>Leer la descripción publicada en el portal</x-slot:titulo><p class="ui-muted text-sm">{{ $revisionUniversidad['resumen'] }}</p></x-plegable-institucional>@endif
            @if($revisionUniversidad['catalogo'])<section class="ga-preparacion-card mt-4"><h3 class="ui-title">Carreras presentes en el estudio de orientación</h3><p class="ui-muted text-xs">{{ $revisionUniversidad['catalogo']['sede'] }}. Estos registros no representan toda la oferta vigente.</p><div class="ga-carreras-tarjetas">@foreach($revisionUniversidad['catalogo']['carreras'] as $carrera)<x-carrera-orientacion :nombre="$carrera" :registrada="true" />@endforeach</div><x-plegable-institucional icono="ph-file-text"><x-slot:titulo>Ver sus fuentes oficiales</x-slot:titulo><div class="grid gap-2 mt-3">@foreach($revisionUniversidad['catalogo']['fuentes'] as $fuente)<a class="ui-link text-sm" href="{{ $fuente['url'] }}" target="_blank" rel="noopener noreferrer">{{ $fuente['nombre'] }}</a>@endforeach</div></x-plegable-institucional></section>@endif
            @if($revisionUniversidad['carreras'])<section class="ga-preparacion-card mt-4"><h3 class="ui-title">Enlaces de carreras encontrados en el portal</h3><p class="ui-muted text-xs">Quedan pendientes de comprobar. No se incorporan automáticamente a la orientación.</p><div class="ga-carreras-tarjetas">@foreach($revisionUniversidad['carreras'] as $carrera)<x-carrera-orientacion :nombre="$carrera['name']" :url="$carrera['url']" :institucion="$revisionUniversidad['institucion']" />@endforeach</div><p class="ui-muted text-xs mt-3">Preparar estudio abre la ficha con la carrera y su fuente. Completa los datos y revisa la propuesta; el Aporte incorpora la evidencia y sus fragmentos después de la aprobación y el procesamiento.</p></section>@elseif($revisionUniversidad['verificada'])<p class="ui-muted text-sm mt-4">El portal no mostró enlaces de carreras reconocibles en esta revisión. Esto no significa que la universidad no las ofrezca.</p>@endif
            <div class="ga-acciones mt-4"><button type="button" class="ui-btn ui-btn-secondary" x-on:click="mostrarPagina=!mostrarPagina" :aria-expanded="mostrarPagina">Ver página en esta ventana</button><a class="ui-btn ui-btn-secondary" href="{{ $revisionUniversidad['url'] }}" target="_blank" rel="noopener noreferrer">Abrir página institucional <i class="ph-duotone ph-arrow-square-out" aria-hidden="true"></i></a></div>
            <section x-show="mostrarPagina" x-cloak class="mt-4"><p class="ui-muted text-xs mb-3">Vista de consulta. Si la página no se muestra aquí, usa «Abrir página institucional».</p><iframe :src="mostrarPagina?@js($revisionUniversidad['url']):'about:blank'" title="Página institucional de la universidad · vista de consulta" sandbox="" referrerpolicy="no-referrer" loading="lazy" class="ga-iframe-universidad"></iframe></section>
        </div>
    </dialog>
</template>
